COMMERCE-5914
liferay-commerce/liferay-portal pull request #1024
Opened 2021-04-22 17:27 UTC by AfonsoHSantos

2021-04-22 17:29 UTC, AfonsoHSantos commented
https://issues.liferay.com/browse/COMMERCE-5914, cc @lorenzolapescara

2021-04-22 17:55 UTC, kristinonias commented
ci:test:sf

2021-04-22 17:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/5005/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-portal-source-format/builds/5005/jenkins-report.html">here</a>.</b></p>

2021-04-22 17:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9">03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/COMMERCE-5914">COMMERCE-5914</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/40d17e8ea186c72b729b21eae408229bd6d95b5a">40d17e8ea186c72b729b21eae408229bd6d95b5a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5005/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5005/jenkins-report.html">here</a>.</h5></details></html>

2021-04-22 18:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5005/">test-portal-source-format#5005</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5005/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1024">liferay-commerce#1024</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527860606">[master] ci:test:sf - AfonsoHSantos &gt; liferay-commerce - PR#1024 - 2021-04-22[10:55:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/395/">publish-testray-report#395</a><br/></div></div>

2021-04-26 17:37 UTC, pedro-michel commented
ci:test:sf

2021-04-26 17:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/5022/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-portal-source-format/builds/5022/jenkins-report.html">here</a>.</b></p>

2021-04-26 17:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c4c731285388d615b0631d9b2d7ead8b2555c486">c4c731285388d615b0631d9b2d7ead8b2555c486</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/COMMERCE-5914">COMMERCE-5914</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/a2a252067fb229c5dc2421682d235ecb0f93d57c">a2a252067fb229c5dc2421682d235ecb0f93d57c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5022/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5022/jenkins-report.html">here</a>.</h5></details></html>

2021-04-26 17:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5022/">test-portal-source-format#5022</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5022/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1024">liferay-commerce#1024</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528602189">[master] ci:test:sf - AfonsoHSantos &gt; liferay-commerce - PR#1024 - 2021-04-26[10:38:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/439/">publish-testray-report#439</a><br/></div></div>

2021-05-04 16:59 UTC, lorenzolapescara requested changes

2021-05-04 16:59 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceAccelerators.path
> +</tr>
Please move the locator to `CommerceFrontStore.path`.
```suggestion
<tr>
	<td>MINI_COMPARE_ITEM_CUSTOM_IMAGE</td>
	<td>//div[contains(@class,'mini-compare active')]//div[contains(@style,'${key_productName}')]</td>
	<td></td>
</tr>
```

2021-05-04 16:59 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase
> +			locator1 = "CommerceAccelerators#CHECK_ITEM_COMPARE");
As for the comment above, please update `CommerceAccelerators#CHECK_ITEM_COMPARE` locator name.

2021-05-04 16:59 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase
> +			locator1 = "CommerceAccelerators#CHECK_ITEM_COMPARE");
As for the comment above, please update `CommerceAccelerators#CHECK_ITEM_COMPARE` locator name.

2021-05-04 16:59 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase
> +			locator1 = "CommerceAccelerators#CHECK_ITEM_COMPARE");
As for the comment above, please update `CommerceAccelerators#CHECK_ITEM_COMPARE` locator name.

2021-05-04 16:59 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceAccelerators.path
> +</tr>
Since this locator is not being used anywhere on the test it can be removed from the PR.

2021-05-05 14:29 UTC, AfonsoHSantos commented
fixed @lorenzolapescara

2021-05-05 14:39 UTC, lorenzolapescara requested changes

2021-05-05 14:39 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase
> +		//	Navigator.openURL();
Please uncomment these lines.

2021-05-05 14:39 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase
> +		//}
Please uncomment these lines.

2021-05-05 15:49 UTC, lorenzolapescara approved these changes

2021-05-05 15:49 UTC, lorenzolapescara commented
ci:test:sf

2021-05-05 15:50 UTC, liferay-continuous-integration commented
Your pull request was not tested because you are not a member of the Liferay organization. Please make sure that you have been added and that your organization membership is set as Public. See https://help.github.com/articles/publicizing-or-hiding-organization-membership for more information.

2021-05-05 15:50 UTC, lorenzolapescara commented
ci:test:commerce-functional

2021-05-05 15:50 UTC, liferay-continuous-integration commented
Your pull request was not tested because you are not a member of the Liferay organization. Please make sure that you have been added and that your organization membership is set as Public. See https://help.github.com/articles/publicizing-or-hiding-organization-membership for more information.

2021-05-05 15:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/5832/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-portal-source-format/builds/5832/jenkins-report.html">here</a>.</b></p>

2021-05-05 15:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/9603/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9603/jenkins-report.html">here</a>.</b></p>

2021-05-05 15:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f1cebb0656a7d08b75e38c634a186cd4ce4202c2">f1cebb0656a7d08b75e38c634a186cd4ce4202c2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/COMMERCE-5914">COMMERCE-5914</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/60ff5ee075d98042b46d8f49da6ac9a305f1a899">60ff5ee075d98042b46d8f49da6ac9a305f1a899</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/5832/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/5832/jenkins-report.html">here</a>.</h5></details></html>

2021-05-05 15:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/5832/">test-portal-source-format#5832</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/5832/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1024">liferay-commerce#1024</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530521406">[master] ci:test:sf - AfonsoHSantos &gt; liferay-commerce - PR#1024 - 2021-05-05[08:50:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/879/">publish-testray-report#879</a><br/></div></div>

2021-05-05 18:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 1 out of 6 jobs passed in 2 hours 21 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1833">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1037401_9603</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f1cebb0656a7d08b75e38c634a186cd4ce4202c2">f1cebb0656a7d08b75e38c634a186cd4ce4202c2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/717b6c56cfbef0b06cbbf29c47304fe9bb2e1d65">717b6c56cfbef0b06cbbf29c47304fe9bb2e1d65</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1832">Acceptance Upstream DXP (master) #1832</a></p><details><summary><strong>ci:test:commerce-functional - 1 out of 6 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/9603/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9072/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/412703/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470616/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461178/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461179/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li></ul></details></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9603/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/412703/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></h5><div><h6>Job Results:</h6><p>7 Tests Passed.<br/>16 Tests Failed.</p></div><ol><li><div><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/412703//consoleText">AXIS_VARIABLE=10,label_exp=!master #412703</a><pre><code>deploy-extra-apps:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null179284326.properties

prepare-log4j-ext-xml:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/bundles/poshi
[stopwatch] [run.batch.test.action: 1:38.326 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1626: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1630: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13314: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2711: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/deploy/portal-commerce-license.xml to copy.
      [get] Getting: http://test-1-21/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/412703//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210505095548886.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210505095548886.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null187594609.properties</code></pre></div></li><li><div><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/412703//consoleText">AXIS_VARIABLE=11,label_exp=!master #412703</a><pre><code> [parallel] 2021-05-05 16:54:41.387 INFO  [main][SystemCheckOSGiCommands:126] Missing Component Scanner check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
     [echo] Unable to find X or Y.
[stopwatch] [run.batch.test.action: 5:38.002 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1626: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1630: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13403: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13761: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4298: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4379: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5808: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:6007: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:537: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/license.xml doesn't exist
      [get] Getting: http://test-1-21/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/412703//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210505095446896.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210505095446896.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null869615303.properties</code></pre></div></li><li><div><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/412703//consoleText">AXIS_VARIABLE=12,label_exp=!master #412703</a><pre><code>     [echo] 	at java.lang.ref.Reference.tryHandlePending(Reference.ja [...]

2021-05-05 18:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/9603/">test-portal-acceptance-pullrequest(master)#9603</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9603/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1024">liferay-commerce#1024</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530554299">[master] ci:test:commerce-functional - AfonsoHSantos &gt; liferay-commerce - PR#1024 - 2021-05-05[08:50:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/882/">publish-testray-report#882</a><br/></div></div>

2021-05-06 07:44 UTC, lorenzolapescara commented
ci:forward

2021-05-06 07:44 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-06 07:44 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-05-06 07:45 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-13.liferay.com/job/forward-pullrequest/194//consoleFull)

2021-05-06 07:45 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101454
[Console](https://test-1-13.liferay.com/job/forward-pullrequest/194//consoleFull)

2021-05-06 07:45 UTC, closed without merging