COMMERCE-6405 Commerce media resolver vulnerability issue
liferay-commerce/liferay-portal pull request #1161
Opened 2021-05-12 07:03 UTC by Commando18

Based on #1082 

Missing integration tests

2021-05-12 07:03 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-05-12 12:53 UTC, andrea-ale-sbarra commented on modules/apps/commerce/commerce-media-impl/src/main/java/com/liferay/commerce/media/internal/DefaultCommerceMediaResolver.java
>  		return getUrl(cpAttachmentFileEntryId, false, true);
accountId?

2021-05-12 16:11 UTC, Commando18 commented
@ivicac just FYI

2021-05-13 09:14 UTC, andrea-ale-sbarra commented
@ivicac and @marco-leo I'm not sure if we'd like to have a method in this resolver that return the bytes[] of the fileEntry, in this pull we moved actual download logic in the Servlet, what do you think?

2021-05-14 18:35 UTC, dsitu requested changes

2021-05-14 18:35 UTC, dsitu commented on modules/apps/commerce/commerce-lang/src/main/resources/content/Language.properties
> +cdn-url=Cdn Url
We should have them capitalized since they are abbreviations.

```suggestion
cdn-url=CDN URL
```

2021-05-18 14:58 UTC, andrea-ale-sbarra commented
@Commando18 we need to send this PR without CDN feature, we need to backport this bug without CDN

2021-05-18 14:58 UTC, closed without merging