COMMERCE-6731 - Make Commerce CheckoutStepHelper class as a osgi serv…
liferay-commerce/liferay-portal pull request #1321
Opened 2021-06-01 14:11 UTC by janbrychtadotcom

…ice.

2021-06-04 08:40 UTC, marco-leo commented
@janbrychtadotcom please rebase to fix the conflict

2021-06-04 14:18 UTC, riccardo-alberti requested changes
Can we also add integration tests? thnx

2021-06-07 07:15 UTC, janbrychtadotcom commented on modules/apps/commerce/commerce-checkout-api/src/main/java/com/liferay/commerce/checkout/helper/CommerceCheckoutStepHelper.java
> +
@riccardo-alberti, here are the reasons for having two arguments for this method ( specified exact commerceOrder) ActiveBillingAddressCommerceCheckoutStep

- getting CommerceOrder from HttpServletRequest differs from the place where you try to get it:
     -  case of Order steps: CommerceOrder commerceOrder =
				(CommerceOrder)httpServletRequest.getAttribute(
						CommerceCheckoutWebKeys.COMMERCE_ORDER);
     - case of Payment Servlet:
             CommerceOrder commerceOrder =
				_commercePaymentHttpHelper.getCommerceOrder(httpServletRequest);
           inside method:
                     long groupId = ParamUtil.getLong(httpServletRequest, "groupId");
		     String uuid = ParamUtil.getString(httpServletRequest, "uuid");
                 
- For the future changes ( in my case of Sintra where I need to change the implementation of this interface) it is absolutely clear what commerceOrder I can work with. I do not need to guess from what httpRequest params/attributes I can get commerceOrder

BTW. I also added commerceOrder as an argument into isActiveBillingAddressCommerceCheckoutStep to have these two methods consistent and again to be clear about the commerceOrder.

2021-06-07 10:36 UTC, janbrychtadotcom commented on modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/DefaultCommerceCheckoutStepHelper.java
done. I pushed new commit - checkout-web: source formatting

2021-06-07 17:13 UTC, janbrychtadotcom commented on modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/DefaultCommerceCheckoutStepHelper.java
I pushed new commit with integration tests

2021-06-09 16:39 UTC, riccardo-alberti commented
ci:test:sf

2021-06-09 16:40 UTC, riccardo-alberti commented
ci:test:relevant

2021-06-09 16:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/5548/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-source-format/builds/5548/jenkins-report.html">here</a>.</b></p>

2021-06-09 16:40 UTC, riccardo-alberti commented
@dsitu the SF is complaining about having HttpServletRequest in a api module but there are other examples where this is used. What should we do in this case? thnx

2021-06-09 16:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8464/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8464/jenkins-report.html">here</a>.</b></p>

2021-06-09 16:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a0de1166dd81ef9cfd22f8c3cae1066483049425">a0de1166dd81ef9cfd22f8c3cae1066483049425</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/janbrychtadotcom/liferay-portal/tree/commerceCheckoutStepHelper-api-service">commerceCheckoutStepHelper-api-service</a><br/>Branch GIT ID: <a href="https://github.com/janbrychtadotcom/liferay-portal/commit/aebd685a0b85ffb28c65eccafcb7bbc28bfe92f6">aebd685a0b85ffb28c65eccafcb7bbc28bfe92f6</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/5548/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5548/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Do not use type 'HttpServletRequest' in API method signature, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/java_api_signature_check.markdown: ./modules/apps/commerce/commerce-checkout-api/src/main/java/com/liferay/commerce/checkout/helper/CommerceCheckoutStepHelper.java (SourceCheck:JavaAPISignatureCheck)
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:469)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:312)
[stopwatch] [run.batch.test.action: 1:28.233 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-16/job/test-portal-source-format/5548//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210609094232182.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210609094232182.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2127214581.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null624621819
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 390ms
[junitreport] Deleting: /tmp/null624621819
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 06-09-2021 09:42:40:118 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</code></pre></details></html>

2021-06-09 16:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-source-format/5548/">test-portal-source-format#5548</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5548/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1321">liferay-commerce#1321</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1538874231">[master] ci:test:sf - janbrychtadotcom &gt; liferay-commerce - PR#1321 - 2021-06-09[09:40:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/1115/">publish-testray-report#1115</a><br/></div></div>

2021-06-09 17:35 UTC, dsitu commented
Hey @riccardo-alberti @janbrychtadotcom looking at this [documentation](https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/api_method_signatures.markdown), there are some exceptions. It might make sense to call `CommerceCheckoutStepHelper.java -> CommerceCheckoutStepHttpHelper.java`, similar to [this](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-wish-list-api/src/main/java/com/liferay/commerce/wish/list/util/CommerceWishListHttpHelper.java), otherwise as a last resort we would add a sf [suppression ](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/source-formatter-suppressions.xml).

2021-06-09 17:42 UTC, riccardo-alberti commented
@dsitu thanks! @janbrychtadotcom can you please make the suggested change? thx

2021-06-09 17:49 UTC, dsitu requested changes

2021-06-09 17:49 UTC, dsitu commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
> +			"Order does not have any addresses ( no shipping address, no " +
extra space
```suggestion
			"Order does not have any addresses (no shipping address, no " +
```

2021-06-09 17:49 UTC, dsitu commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
> +			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
Sort
```suggestion
		HttpServletRequest httpServletRequest = new MockHttpServletRequest();

		CommerceContext commerceContext = new TestCommerceContext(
			_commerceCurrency, _commerceChannel, _user, _group,
			_commerceAccount, null);

		httpServletRequest.setAttribute(
			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
```

2021-06-09 17:49 UTC, dsitu commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
> +			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
sort
```suggestion
		HttpServletRequest httpServletRequest = new MockHttpServletRequest();

		CommerceContext commerceContext = new TestCommerceContext(
			_commerceCurrency, _commerceChannel, _user, _group,
			_commerceAccount, null);

		httpServletRequest.setAttribute(
			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
```

2021-06-09 17:49 UTC, dsitu commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
> +			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
sort
```suggestion
		HttpServletRequest httpServletRequest = new MockHttpServletRequest();

		CommerceContext commerceContext = new TestCommerceContext(
			_commerceCurrency, _commerceChannel, _user, _group,
			_commerceAccount, null);

		httpServletRequest.setAttribute(
			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
```

2021-06-09 17:49 UTC, dsitu commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
> +			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
sort
```suggestion
		HttpServletRequest httpServletRequest = new MockHttpServletRequest();

		CommerceContext commerceContext = new TestCommerceContext(
			_commerceCurrency, _commerceChannel, _user, _group,
			_commerceAccount, null);

		httpServletRequest.setAttribute(
			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
```

2021-06-09 17:49 UTC, dsitu commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
> +			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
sort
```suggestion
		HttpServletRequest httpServletRequest = new MockHttpServletRequest();

		CommerceContext commerceContext = new TestCommerceContext(
			_commerceCurrency, _commerceChannel, _user, _group,
			_commerceAccount, null);

		httpServletRequest.setAttribute(
			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
```

2021-06-09 17:49 UTC, dsitu commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
> +			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
sort
```suggestion
		HttpServletRequest httpServletRequest = new MockHttpServletRequest();

		CommerceContext commerceContext = new TestCommerceContext(
			_commerceCurrency, _commerceChannel, _user, _group,
			_commerceAccount, null);

		httpServletRequest.setAttribute(
			CommerceWebKeys.COMMERCE_CONTEXT, commerceContext);
```

2021-06-09 17:49 UTC, dsitu commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
> +			RandomTestUtil.randomString(), //phoneNumber
remove comments when not necessary
```suggestion
			RandomTestUtil.randomString(),
			RandomTestUtil.randomString(),
			RandomTestUtil.randomString(),
			RandomTestUtil.randomString(),
			RandomTestUtil.randomString(),
			RandomTestUtil.randomString(),
			RandomTestUtil.randomString(),
			0,
			country.getCountryId(),
			RandomTestUtil.randomString(),
```

2021-06-09 18:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 10 out of 10 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 23 out of 24 jobs passed in 1 hour 55 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a0de1166dd81ef9cfd22f8c3cae1066483049425">a0de1166dd81ef9cfd22f8c3cae1066483049425</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a0de1166dd81ef9cfd22f8c3cae1066483049425">a0de1166dd81ef9cfd22f8c3cae1066483049425</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1967">Acceptance Upstream DXP (master) #1967</a></p><details><summary><strong>ci:test:stable - 10 out of 10 jobs PASSED</strong></summary><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423008/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/499085/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/436580/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423011/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/416228/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423010/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444302/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473809/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423009/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/499084/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 22 out of 24 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8464/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/499086/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464989/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/436578/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423008/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473810/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423012/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/389007/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/499085/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/436580/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/360206/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/436579/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423011/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/416228/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473808/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444303/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423010/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473807/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444302/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473809/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/332151/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423009/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423007/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/499084/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8464/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><s [...]

2021-06-09 18:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/8464/">test-portal-acceptance-pullrequest(master)#8464</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8464/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1321">liferay-commerce#1321</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1538944497">[master] ci:test:relevant - janbrychtadotcom &gt; liferay-commerce - PR#1321 - 2021-06-09[09:40:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/1119/">publish-testray-report#1119</a><br/></div></div>

2021-07-13 09:04 UTC, closed without merging