Commerce 5661 define diagram model
liferay-commerce/liferay-portal pull request #1472
Opened 2021-07-01 10:07 UTC by andrea-ale-sbarra

https://issues.liferay.com/browse/COMMERCE-5661

2021-07-01 10:58 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-01 17:40 UTC, dsitu requested changes

2021-07-01 17:40 UTC, dsitu commented on modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/service.xml
> +		<column name="positionY" type="double" />
sort these ids up
```suggestion
		<column name="CPInstanceUuid" type="String" />
		<column name="CProductId" type="long" />
		<column name="CPDefinitionId" type="long" />
		<column name="number" type="int" />
		<column name="positionX" type="double" />
		<column name="positionY" type="double" />
```

2021-07-02 15:49 UTC, andrea-ale-sbarra commented on modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/service.xml
> +		<column name="positionY" type="double" />
thanks @dsitu !

2021-07-02 17:06 UTC, dsitu approved these changes

2021-07-05 10:35 UTC, andrea-ale-sbarra commented on modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/service.xml
> +		<column name="CPInstanceUuid" type="String" />
use className classPK?

2021-07-05 10:36 UTC, andrea-ale-sbarra commented on modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/service.xml
> +		<column name="color" type="String" />
add type for diagram?

2021-07-06 09:00 UTC, andrea-ale-sbarra commented on modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/service.xml
> +		<column name="CPInstanceUuid" type="String" />
Add Flag that say if link is SKU or Diagram

Add product code for product that is not present at catalog level

2021-07-06 09:01 UTC, andrea-ale-sbarra commented on modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/service.xml
> +
miss quantity field

2021-07-06 14:20 UTC, andrea-ale-sbarra commented
ci:test:sf

2021-07-06 14:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-portal-source-format/4119/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-portal-source-format/builds/4119/jenkins-report.html">here</a>.</b></p>

2021-07-06 14:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/df92d437c1423ccd80e505d9ccf470a8450b9f69">df92d437c1423ccd80e505d9ccf470a8450b9f69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/COMMERCE-5661-define-diagram-model">COMMERCE-5661-define-diagram-model</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/04cf0805242d0aefb017ff80e4878ba86afab956">04cf0805242d0aefb017ff80e4878ba86afab956</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-20.liferay.com/job/test-portal-source-format/4119/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-20.liferay.com/userContent/jobs/test-portal-source-format/builds/4119/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 19 formatting issues:
     [java] 1: Added packageinfo for com.liferay.commerce.shop.by.diagram.exception, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_exports_check.markdown: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/bnd.bnd (SourceCheck:BNDExportsCheck)
     [java] 2: Added packageinfo for com.liferay.commerce.shop.by.diagram.model, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_exports_check.markdown: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/bnd.bnd (SourceCheck:BNDExportsCheck)
     [java] 3: Added packageinfo for com.liferay.commerce.shop.by.diagram.service, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_exports_check.markdown: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/bnd.bnd (SourceCheck:BNDExportsCheck)
     [java] 4: Added packageinfo for com.liferay.commerce.shop.by.diagram.service.persistence, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_exports_check.markdown: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/bnd.bnd (SourceCheck:BNDExportsCheck)
     [java] 5: Unneeded/incorrect Export-Package: com.liferay.commerce.shop.by.diagram.search, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_exports_check.markdown: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/bnd.bnd (SourceCheck:BNDExportsCheck)
     [java] 6: Incorrect order 'entity': 'CPDefinitionDiagramSetting' should come after 'CPDefinitionDiagramEntry': ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/service.xml (SourceCheck:XMLServiceFileCheck)
     [java] 7: Reference 'ExpandoRow' not needed for Entity 'CPDefinitionDiagramEntry': ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/service.xml (SourceCheck:XMLServiceReferenceCheck)</code></pre></details></html>

2021-07-06 14:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-20.liferay.com/job/test-portal-source-format/4119/">test-portal-source-format#4119</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-20.liferay.com/userContent/jobs/test-portal-source-format/builds/4119/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545232540">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-06[07:21:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-20.liferay.com/job/publish-testray-report/338/">publish-testray-report#338</a><br/></div></div>

2021-07-07 09:41 UTC, andrea-ale-sbarra commented
ci:test:sf

2021-07-07 09:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2399/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/2399/jenkins-report.html">here</a>.</b></p>

2021-07-07 09:44 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3f29f30710d0b777be99bb0824493977787cdff8">3f29f30710d0b777be99bb0824493977787cdff8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/COMMERCE-5661-define-diagram-model">COMMERCE-5661-define-diagram-model</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/e297ea8394e7c05d433707afba17de7b09244c26">e297ea8394e7c05d433707afba17de7b09244c26</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2399/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2399/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 7 formatting issues:
     [java] 1: Added packageinfo for com.liferay.commerce.shop.by.diagram.exception, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_exports_check.markdown: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/bnd.bnd (SourceCheck:BNDExportsCheck)
     [java] 2: Added packageinfo for com.liferay.commerce.shop.by.diagram.model, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_exports_check.markdown: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/bnd.bnd (SourceCheck:BNDExportsCheck)
     [java] 3: Added packageinfo for com.liferay.commerce.shop.by.diagram.service, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_exports_check.markdown: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/bnd.bnd (SourceCheck:BNDExportsCheck)
     [java] 4: Added packageinfo for com.liferay.commerce.shop.by.diagram.service.persistence, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_exports_check.markdown: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/bnd.bnd (SourceCheck:BNDExportsCheck)
     [java] 5: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/src/main/java/com/liferay/commerce/shop/by/diagram/exception/NoSuchCPDefinitionDiagramEntryException.java expected:&lt;...s reserved.
     [java]  *
     [java]  * Th[e contents of this file are subject to the terms of the Liferay Enterprise
     [java]  * Subscription License ("License"). You may not use this file except in
     [java]  * compliance with the License. You can obtain a copy of the License by
     [java]  * contacting Liferay, Inc. See the License for the specific language governing
     [java]  * permissions and limitations under the License, including but not limited to
     [java]  * distribution rights of the Software.
     [java]  *
     [java]  *
     [java]  *
     [java]  */
     [java] 
     [java] package com.liferay.commerce.shop.by.diagram.exception;
     [java] 
     [java] import com.liferay.portal.kernel.exception.NoSuchModelException;
     [java] </code></pre></details></html>

2021-07-07 09:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2399/">test-portal-source-format#2399</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2399/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545451775">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[02:41:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7234/">publish-testray-report#7234</a><br/></div></div>

2021-07-07 10:12 UTC, andrea-ale-sbarra commented
ci:test:sf

2021-07-07 10:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/3148/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-portal-source-format/builds/3148/jenkins-report.html">here</a>.</b></p>

2021-07-07 10:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3f29f30710d0b777be99bb0824493977787cdff8">3f29f30710d0b777be99bb0824493977787cdff8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/COMMERCE-5661-define-diagram-model">COMMERCE-5661-define-diagram-model</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/356f4c5cb3c2371488744eea28693cf408e8d6a7">356f4c5cb3c2371488744eea28693cf408e8d6a7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3148/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3148/jenkins-report.html">here</a>.</h5></details></html>

2021-07-07 10:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3148/">test-portal-source-format#3148</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3148/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545463887">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[03:13:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/1431/">publish-testray-report#1431</a><br/></div></div>

2021-07-07 10:25 UTC, andrea-ale-sbarra commented
ci:forward

2021-07-07 10:25 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-07-07 10:25 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2021-07-07 10:25 UTC, andrea-ale-sbarra commented
ci:stop

2021-07-07 10:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8413/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8413/jenkins-report.html">here</a>.</b></p>

2021-07-07 10:30 UTC, andrea-ale-sbarra commented
ci:test:stop

2021-07-07 10:30 UTC, andrea-ale-sbarra commented
ci:test:sf

2021-07-07 10:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/3149/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-portal-source-format/builds/3149/jenkins-report.html">here</a>.</b></p>

2021-07-07 10:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stop</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/5002/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5002/jenkins-report.html">here</a>.</b></p>

2021-07-07 10:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3f29f30710d0b777be99bb0824493977787cdff8">3f29f30710d0b777be99bb0824493977787cdff8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/COMMERCE-5661-define-diagram-model">COMMERCE-5661-define-diagram-model</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/aa63bee837bca898c625d4149bc1c3193ec34211">aa63bee837bca898c625d4149bc1c3193ec34211</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3149/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3149/jenkins-report.html">here</a>.</h5></details></html>

2021-07-07 10:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stop - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3f29f30710d0b777be99bb0824493977787cdff8">3f29f30710d0b777be99bb0824493977787cdff8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3f29f30710d0b777be99bb0824493977787cdff8">3f29f30710d0b777be99bb0824493977787cdff8</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2082">Acceptance Upstream DXP (master) #2082</a></p><details><summary><strong>ci:test:stop - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/5002/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5002/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/5002/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The CI test suite 'stop' is not a valid test suite.

List of available CI test suites:
* acceptance
* acceptance-functional
* acceptance-upstream
* accounts
* analytics-cloud
* auto-tagging
* backend
* backend-hypersonic
* blade
* blogs
* bulk-editing
* bundle
* calendar
* click-to-chat
* clustering
* commerce
* commerce-es7-remote
* commerce-functional
* content-page-review
* data-engine
* depot
* digital-signature
* dl-store
* documents
* drools
* dummy
* echo
* echo-acceptance
* echo-upgrade
* environments
* export-import
* forms
* forms-functional
* frontend
* gauntlet
* gauntlet-bucket
* gradle-plugins
* headless
* headless-acceptance
* jdk11
* jsf
* kaleo-forms
* knowledge-base
* ldap
* license
* license-cluster
* liferay-online
* lima
* lpkg
* message-boards
* mfa
* oauth2
* onedrive
* online-editing
* password-policies
* portal-release-upstream
* poshi
* poshi-gauntlet
* project-templates
* publications
* publications-environments
* questions-acceptance
* redirect
* relevant
* reports
* roles
* saml
* search
* search-remote
* search-remote-minimum
* security
* seo
* sf
* sharepoint
* sharing
* site-template
* smoke
* stable
* staging
* sybase
* system
* tango
* tango-acceptance
* tango-analytics-cloud
* tck
* translations
* upgrade
* upgrade-client
* upstream-functional
* users
* usm
* usm-upgrade
* vulcan-acceptance
* wiki
* workflow
* workflow-es7-remote
* workflow-metrics

</p><p>Comment 'ci:help' for details.</p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-07-07 10:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3149/">test-portal-source-format#3149</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3149/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545466638">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[03:30:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/1432/">publish-testray-report#1432</a><br/></div></div>

2021-07-07 10:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/5002/">test-portal-acceptance-pullrequest(master)#5002</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5002/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>stop<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545467591">[master] ci:test:stop - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[03:30:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/1433/">publish-testray-report#1433</a><br/></div></div>

2021-07-07 10:58 UTC, andrea-ale-sbarra commented
ci:test:sf

2021-07-07 10:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-source-format/6018/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-source-format/builds/6018/jenkins-report.html">here</a>.</b></p>

2021-07-07 11:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3f29f30710d0b777be99bb0824493977787cdff8">3f29f30710d0b777be99bb0824493977787cdff8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/COMMERCE-5661-define-diagram-model">COMMERCE-5661-define-diagram-model</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/3f03267451a3cb653757b81aead0a5791e3388be">3f03267451a3cb653757b81aead0a5791e3388be</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-source-format/6018/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/6018/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 4 formatting issues:
     [java] 1: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-api/src/main/java/com/liferay/commerce/shop/by/diagram/exception/NoSuchCPDefinitionDiagramPinException.java expected:&lt;...s reserved.
     [java]  *
     [java]  * Th[e contents of this file are subject to the terms of the Liferay Enterprise
     [java]  * Subscription License ("License"). You may not use this file except in
     [java]  * compliance with the License. You can obtain a copy of the License by
     [java]  * contacting Liferay, Inc. See the License for the specific language governing
     [java]  * permissions and limitations under the License, including but not limited to
     [java]  * distribution rights of the Software.
     [java]  *
     [java]  *
     [java]  *
     [java]  */
     [java] 
     [java] package com.liferay.commerce.shop.by.diagram.exception;
     [java] 
     [java] import com.liferay.portal.kernel.exception.NoSuchModelException;
     [java] 
     [java] /**
     [java]  * @author Andrea Sbarra
     [java]  */
     [java] public class NoSuchCPDefinitionDiagramPinException
     [java] 	extends NoSuchModelException \{
     [java] 
     [java] 	public NoSuchCPDefinitionDiagramPinException() \{
     [java] 	\}
     [java] 
     [java] 	public NoSuchCPDefinitionDiagramPinException(String msg) \{
     [java] 		super(msg);
     [java] 	\}
     [java] 
     [java] 	public NoSuchCPDefinitionDiagramPinException(
     [java] 		String msg, Throwable throwable) \{
     [java] ]
     [java] 		super(msg, throwa...&gt; but was:&lt;...s reserved.
     [java]  *
     [java]  * Th[is library is free software; you can redistribute it and/or modify it under
     [java]  * the terms of the GNU Lesser General Public License as published by the Free
     [java]  * Software Foundation; either version 2.1 of the License, or (at your option)
     [java]  * any later version.
     [java]  *
     [java]  * This library is distributed in the hope that it will be useful, but WITHOUT
     [java]  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
     [java]  * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
     [java]  * details.
     [java]  */
     [java] package com.liferay.commerce.shop.by.diagram.exception;
     [java] 
     [java] import com.liferay.portal.kernel.exception.NoSuchModelException;
     [java] 
     [java] /**</code></pre></details></html>

2021-07-07 11:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-23.liferay.com/job/test-portal-source-format/6018/">test-portal-source-format#6018</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/6018/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545483440">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[03:59:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-23.liferay.com/job/publish-testray-report/1026/">publish-testray-report#1026</a><br/></div></div>

2021-07-07 11:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 43 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3f29f30710d0b777be99bb0824493977787cdff8">3f29f30710d0b777be99bb0824493977787cdff8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3f29f30710d0b777be99bb0824493977787cdff8">3f29f30710d0b777be99bb0824493977787cdff8</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2082">Acceptance Upstream DXP (master) #2082</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8413/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8413/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8413/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :dxp:apps:commerce:commerce-shop-by-diagram:commerce-shop-by-diagram-service:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/service/impl/CPDefinitionDiagramEntryLocalServiceImpl.java:18: error: package com.liferay.portal.aop does not exist
     [exec] import com.liferay.portal.aop.AopService;
     [exec]                              ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/service/base/CPDefinitionDiagramEntryLocalServiceBaseImpl.java:23: error: package com.liferay.portal.aop does not exist
     [exec] import com.liferay.portal.aop.AopService;
     [exec]                              ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/service/base/CPDefinitionDiagramEntryLocalServiceBaseImpl.java:71: error: cannot find symbol
     [exec] 	implements AopService, CPDefinitionDiagramEntryLocalService,
     [exec] 	           ^
     [exec]   symbol: class AopService
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/service/impl/CPDefinitionDiagramEntryServiceImpl.java:18: error: package com.liferay.portal.aop does not exist
     [exec] import com.liferay.portal.aop.AopService;
     [exec]                              ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/service/base/CPDefinitionDiagramEntryServiceBaseImpl.java:22: error: package com.liferay.portal.aop does not exist
     [exec] import com.liferay.portal.aop.AopService;
     [exec]                              ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/service/base/CPDefinitionDiagramEntryServiceBaseImpl.java:52: error: cannot find symbol
     [exec] 	implements AopService, CPDefinitionDiagramEntryService,</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-07-07 11:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8413/">test-portal-acceptance-pullrequest(master)#8413</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8413/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545486083">[master] ci:test:relevant - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[03:27:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/1293/">publish-testray-report#1293</a><br/></div></div>

2021-07-07 12:46 UTC, andrea-ale-sbarra commented
ci:test:sf

2021-07-07 12:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4937/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4937/jenkins-report.html">here</a>.</b></p>

2021-07-07 12:51 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3f29f30710d0b777be99bb0824493977787cdff8">3f29f30710d0b777be99bb0824493977787cdff8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/COMMERCE-5661-define-diagram-model">COMMERCE-5661-define-diagram-model</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/477fd5b25b525912649aa022f8260540f7d2b1f9">477fd5b25b525912649aa022f8260540f7d2b1f9</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4937/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4937/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/model/impl/CPDefinitionDiagramPinImpl.java expected:&lt;...amPinBaseImpl \{
     [java] 
     [java] 	/*[*]
     [java] 	 * NOTE FOR DEVELO...&gt; but was:&lt;...amPinBaseImpl \{
     [java] 
     [java] 	/*[]
     [java] 	 * NOTE FOR DEVELO...&gt;
     [java] 2: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/service/impl/CPDefinitionDiagramPinLocalServiceImpl.java expected:&lt;...pl
     [java]  */
     [java] @Component(
     [java] 	[enabled = false,
     [java] 	property = "model.class.name=com.liferay.commerce.shop.by.diagram.model.CPDefinitionDiagramPin",
     [java] 	service = AopService.class
     [java] )
     [java] public class CPDefinitionDiagramPinLocalServiceImpl
     [java] 	extends CPDefinitionDiagramPinLocalServiceBaseImpl \{
     [java] 
     [java] 	/**
     [java] 	 * NOTE FOR DEVELOPERS:
     [java] 	 *
     [java] 	 * Never reference this class directly. Use &lt;code&gt;com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramPinLocalService&lt;/code&gt; via injection or a &lt;code&gt;org.osgi.util.tracker.ServiceTracker&lt;/code&gt; or use &lt;code&gt;com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramPinLocalServiceUtil&lt;/code&gt;.
     [java] 	 */
     [java] ]
     [java] \}&gt; but was:&lt;...pl
     [java]  */
     [java] @Component(
     [java] 	[property = "model.class.name=com.liferay.commerce.shop.by.diagram.model.CPDefinitionDiagramPin",
     [java] 	service = AopService.class
     [java] )
     [java] public class CPDefinitionDiagramPinLocalServiceImpl
     [java] 	extends CPDefinitionDiagramPinLocalServiceBaseImpl \{
     [java] 
     [java] 	/*
     [java] 	 * NOTE FOR DEVELOPERS:
     [java] 	 *
     [java] 	 * Never reference this class directly. Use &lt;code&gt;com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramPinLocalService&lt;/code&gt; via injection or a &lt;code&gt;org.osgi.util.tracker.ServiceTracker&lt;/code&gt; or use &lt;code&gt;com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramPinLocalServiceUtil&lt;/code&gt;.
     [java] 	 */]
     [java] \}&gt;
     [java] 3: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/service/impl/CPDefinitionDiagramPinServiceImpl.java expected:&lt;...pl</code></pre></details></html>

2021-07-07 12:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4937/">test-portal-source-format#4937</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4937/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545539749">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[05:47:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/1470/">publish-testray-report#1470</a><br/></div></div>

2021-07-07 16:22 UTC, andrea-ale-sbarra commented
ci:test:sf

2021-07-07 16:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2415/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/2415/jenkins-report.html">here</a>.</b></p>

2021-07-07 16:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9cf37c5ece5eea57ed6d91d868f90236caafaafa">9cf37c5ece5eea57ed6d91d868f90236caafaafa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/COMMERCE-5661-define-diagram-model">COMMERCE-5661-define-diagram-model</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/3b85579e4ec8d0f2a7fc6f04bc3ced5490ef6cd0">3b85579e4ec8d0f2a7fc6f04bc3ced5490ef6cd0</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2415/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2415/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 9 formatting issues:
     [java] 1: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/model/impl/CPDefinitionDiagramSettingImpl.java expected:&lt;...ttingBaseImpl \{
     [java] 
     [java] 	/*[*]
     [java] 	 * NOTE FOR DEVELO...&gt; but was:&lt;...ttingBaseImpl \{
     [java] 
     [java] 	/*[]
     [java] 	 * NOTE FOR DEVELO...&gt;
     [java] 2: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/model/impl/CPDefinitionDiagramEntryImpl.java expected:&lt;...EntryBaseImpl \{
     [java] 
     [java] 	/*[*]
     [java] 	 * NOTE FOR DEVELO...&gt; but was:&lt;...EntryBaseImpl \{
     [java] 
     [java] 	/*[]
     [java] 	 * NOTE FOR DEVELO...&gt;
     [java] 3: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/model/impl/CPDefinitionDiagramPinImpl.java expected:&lt;...amPinBaseImpl \{
     [java] 
     [java] 	/*[*]
     [java] 	 * NOTE FOR DEVELO...&gt; but was:&lt;...amPinBaseImpl \{
     [java] 
     [java] 	/*[]
     [java] 	 * NOTE FOR DEVELO...&gt;
     [java] 4: ./modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-service/src/main/java/com/liferay/commerce/shop/by/diagram/service/impl/CPDefinitionDiagramPinServiceImpl.java expected:&lt;...pl
     [java]  */
     [java] @Component(
     [java] 	[enabled = false,
     [java] 	property = \{
     [java] 		"json.web.service.context.name=commerce",
     [java] 		"json.web.service.context.path=CPDefinitionDiagramPin"
     [java] 	\},
     [java] 	service = AopService.class
     [java] )
     [java] public class CPDefinitionDiagramPinServiceImpl
     [java] 	extends CPDefinitionDiagramPinServiceBaseImpl \{
     [java] 
     [java] 	/**
     [java] 	 * NOTE FOR DEVELOPERS:
     [java] 	 *
     [java] 	 * Never reference this class directly. Always use &lt;code&gt;com.liferay.commerce.shop.by.diagram.service.CPDefinitionDiagramPinServiceUtil&lt;/code&gt; to access the cp definition diagram pin remote service.
     [java] 	 */
     [java] ]
     [java] \}&gt; but was:&lt;...pl
     [java]  */
     [java] @Component(
     [java] 	[property = \{
     [java] 		"json.web.service.context.name=commerce",
     [java] 		"json.web.service.context.path=CPDefinitionDiagramPin"
     [java] 	\},
     [java] 	service = AopService.class
     [java] )</code></pre></details></html>

2021-07-07 16:26 UTC, andrea-ale-sbarra commented
ci:test:sf

2021-07-07 16:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-source-format/6700/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-portal-source-format/builds/6700/jenkins-report.html">here</a>.</b></p>

2021-07-07 16:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2415/">test-portal-source-format#2415</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2415/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545576056">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[09:23:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7269/">publish-testray-report#7269</a><br/></div></div>

2021-07-07 16:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9cf37c5ece5eea57ed6d91d868f90236caafaafa">9cf37c5ece5eea57ed6d91d868f90236caafaafa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/COMMERCE-5661-define-diagram-model">COMMERCE-5661-define-diagram-model</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/a382686688ee697c842ca2dcc0b2ba4b8780114a">a382686688ee697c842ca2dcc0b2ba4b8780114a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6700/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6700/jenkins-report.html">here</a>.</h5></details></html>

2021-07-07 16:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6700/">test-portal-source-format#6700</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6700/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545576653">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[09:27:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-22.liferay.com/job/publish-testray-report/1173/">publish-testray-report#1173</a><br/></div></div>

2021-07-07 16:33 UTC, andrea-ale-sbarra commented
ci:forward

2021-07-07 16:33 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-07-07 16:33 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:sf`

2021-07-07 16:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/8257/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8257/jenkins-report.html">here</a>.</b></p>

2021-07-07 20:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 10 out of 10 jobs passed</h3><h3>:x: ci:test:relevant - 22 out of 24 jobs passed in 3 hours 56 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9cf37c5ece5eea57ed6d91d868f90236caafaafa">9cf37c5ece5eea57ed6d91d868f90236caafaafa</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9cf37c5ece5eea57ed6d91d868f90236caafaafa">9cf37c5ece5eea57ed6d91d868f90236caafaafa</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2083">Acceptance Upstream DXP (master) #2083</a></p><details><summary><strong>ci:test:stable - 10 out of 10 jobs PASSED</strong></summary><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/391139/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/501208/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/501210/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439242/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476214/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439241/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/424787/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/391141/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439240/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/501207/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 22 out of 24 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/8257/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/391142/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/501209/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/424785/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/391139/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439243/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/333999/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/501208/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/501210/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/389881/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476213/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439242/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/424786/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476214/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/391140/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/333998/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439241/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/391138/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/424787/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/391141/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476215/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439240/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/439239/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/501207/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8257/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test [...]

2021-07-07 20:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/8257/">test-portal-acceptance-pullrequest(master)#8257</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8257/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1472">liferay-commerce#1472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1545639470">[master] ci:test:relevant - andrea-ale-sbarra &gt; liferay-commerce - PR#1472 - 2021-07-07[09:39:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/1354/">publish-testray-report#1354</a><br/></div></div>

2021-07-08 08:12 UTC, Commando18 commented
I will manually forward it since the error is not related to our work.

2021-07-27 10:23 UTC, closed without merging