COMMERCE-6920 Always display normalized discount percentage.
liferay-commerce/liferay-portal pull request #1526
Opened 2021-07-16 17:53 UTC by brianikim

https://issues.liferay.com/browse/COMMERCE-6920

2021-07-16 17:53 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-16 17:53 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-16 17:53 UTC, brianikim commented
ci:test:relevant

2021-07-16 17:53 UTC, brianikim commented
ci:test:sf

2021-07-16 17:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2774/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/2774/jenkins-report.html">here</a>.</b></p>

2021-07-16 17:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39083469641949b1b563fd4965c5aec15ae72db6">39083469641949b1b563fd4965c5aec15ae72db6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brianikim/liferay-portal/tree/COMMERCE-6920">COMMERCE-6920</a><br/>Branch GIT ID: <a href="https://github.com/brianikim/liferay-portal/commit/01352e41bf439ee1e9d1d8b880da5b5bb003891f">01352e41bf439ee1e9d1d8b880da5b5bb003891f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2774/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2774/jenkins-report.html">here</a>.</h5></details></html>

2021-07-16 17:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3007/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3007/jenkins-report.html">here</a>.</b></p>

2021-07-16 17:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2774/">test-portal-source-format#2774</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2774/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1526">liferay-commerce#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1547721988">[master] ci:test:sf - brianikim &gt; liferay-commerce - PR#1526 - 2021-07-16[10:53:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8392/">publish-testray-report#8392</a><br/></div></div>

2021-07-16 19:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 10 out of 10 jobs passed</h3><h3>:x: ci:test:relevant - 22 out of 24 jobs passed in 1 hour 58 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2115">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1257401_3007</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39083469641949b1b563fd4965c5aec15ae72db6">39083469641949b1b563fd4965c5aec15ae72db6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8901fe306f4626e66de87953cb78b9108fedfba3">8901fe306f4626e66de87953cb78b9108fedfba3</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2114">Acceptance Upstream DXP (master) #2114</a></p><details><summary><strong>ci:test:stable - 10 out of 10 jobs PASSED</strong></summary><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363547/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476904/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21978/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473866/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/334517/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363548/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476907/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476905/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473865/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21976/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 22 out of 24 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3007/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21979/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476906/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331648/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363547/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363550/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473867/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/231977/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476904/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21978/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/390459/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473866/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331649/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/334517/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363549/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/341962/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363548/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476903/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476907/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476905/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/341963/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473865/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363546/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="ht [...]

2021-07-16 19:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3007/">test-portal-acceptance-pullrequest(master)#3007</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3007/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/1526">liferay-commerce#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1547750364">[master] ci:test:relevant - brianikim &gt; liferay-commerce - PR#1526 - 2021-07-16[10:53:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8408/">publish-testray-report#8408</a><br/></div></div>

2021-07-19 15:39 UTC, dsitu requested changes

2021-07-19 15:39 UTC, dsitu commented on modules/apps/commerce/commerce-order-content-web/src/main/resources/META-INF/resources/placed_orders/view_commerce_order_details.jsp
> +						CommerceDiscountValue shippingCommerceDiscountWithTaxValue = commerceOrderPrice.getShippingDiscountValueWithTaxAmount();
We should name this `shippingDiscountValueWithTaxAmount`.
```suggestion
						CommerceDiscountValue shippingDiscountValueWithTaxAmount = commerceOrderPrice.getShippingDiscountValueWithTaxAmount();
```

2021-07-19 15:39 UTC, dsitu commented on modules/apps/commerce/commerce-order-content-web/src/main/resources/META-INF/resources/placed_orders/view_commerce_order_details.jsp
> +						<dd class="text-right"><%= HtmlUtil.escape(commerceOrderContentDisplayContext.getLocalizedPercentage(shippingCommerceDiscountWithTaxValue.getDiscountPercentage(), locale)) %></dd>
```suggestion
						<dd class="text-right"><%= HtmlUtil.escape(commerceOrderContentDisplayContext.getLocalizedPercentage(shippingDiscountValueWithTaxAmount.getDiscountPercentage(), locale)) %></dd>
```

2021-07-23 15:21 UTC, brianikim commented
hey @dsitu , forgot to update you. The change you requested has been implemented.

2021-07-23 15:24 UTC, dsitu approved these changes

2021-08-31 11:23 UTC, igorbeslic commented
ci:help

2021-08-31 11:23 UTC, liferay-continuous-integration commented
## Available CI commands:
#### ci:close
&nbsp;&nbsp;&nbsp;&nbsp;Close the pull request.
#### ci:forward
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request  and forward the pullrequest to `brianchandotcom` if the required test suites pass.
#### ci:merge[:force]
&nbsp;&nbsp;&nbsp;&nbsp;Merge in the changes from the subrepo. All tests must pass before this command will successfully run. Optionally use the force flag to bypass failed tests.
#### ci:reevaluate:[buildID]
&nbsp;&nbsp;&nbsp;&nbsp;Reevaluate the pull request result from a generated build ID.
#### ci:reopen
&nbsp;&nbsp;&nbsp;&nbsp;Reopen the pull request.
#### ci:stop[:suite]
&nbsp;&nbsp;&nbsp;&nbsp;Stop all currrently running tests. Optionally specify the name of the test suite.
#### ci:test[:suite][:SHA|nocompile|norebase]
&nbsp;&nbsp;&nbsp;&nbsp;Test the pull request.Optionally specify the name of the test suite and/or optionally specify the upstream SHA to test against or use "nocompile" to test with a prebuilt bundle or use "norebase" to test without rebasing.

&nbsp;&nbsp;&nbsp;&nbsp;List of available test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance** - Test acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-functional** - Test acceptance functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**acceptance-upstream** - Test acceptance upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**account** - Test Account tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud** - Test Analytics Cloud tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**analytics-cloud-quarantine** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**auto-tagging** - Test Auto Tagging tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend** - Test backend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**backend-hypersonic** - Test backend tests on Hypersonic.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blade** - Test Blade samples tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**blogs** - Test Blogs tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bulk-editing** - Test Bulk Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**bundle** - Saves a compiled tomcat bundle.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**calendar** - Test Calendar tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**click-to-chat** - Test Click to Chat tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**clustering** - Test clustering tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce** - Test only Commerce tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-es7-remote** - Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**commerce-functional** - Test only Commerce functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**content-page-review** - Test Content Page Review (comments) tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**data-engine** - Test Data Engine functional tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**depot** - Test Depot tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**digital-signature** - Test Digital Signature tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dl-store** - Test Document Library Store tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**document** - Test Document and Media tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**drools** - Test Drools tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**dummy** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo** - Test all Echo (WCM) team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-acceptance** - Test Echo (WCM) team acceptance tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**echo-upgrade** - Test Echo (WCM) team upgrade tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**environments** - Test environment acceptance functional tests on all available environment stacks.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**export-import** - Test exportimport tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms** - Test forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**forms-functional** - Test only functional forms tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**frontend** - Test frontend tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet** - Test upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gauntlet-bucket** - Test a subset of upstream tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**gradle-plugins** - Test Gradle Plugins tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless** - Test headless team tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**headless-acceptance** - Test headless team acceptance tests considering Headless and Rest Builder.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jdk11** - Test acceptance, smoke, and upgrade functional tests against JDK11.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**jsf** - Test Liferay Faces tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**kaleo-forms** - Test Kaleo Forms admin tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**knowledge-base** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**ldap** - Test LDAP tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license** - Compile a release bundle and execute tests for licensing.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**license-cluster** - Compile a release bundle and execute tests for cluster licensing on 32GB slaves.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**liferay-online** - Compile a release bundle and execute tests with liferay online properties.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lima** - Test Lima tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**lpkg** - Test LPKG tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**message-boards** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**mfa** - Test Multi Factor Authentication tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**oauth2** - Test OAuth 2 tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**object** - Test Object tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**onedrive** - Test OneDrive tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**online-editing** - Test Online Editing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**password-policies** - Test Password Policies tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**portal-release-upstream** - Run full release tests against a release bundle compiled from head.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**poshi** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**poshi-gauntlet** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**project-templates** - Test project-templates tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**publications** - Test publications tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**publications-environments** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**questions-acceptance** - Test headless team acceptance tests considering Questions.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**redirect** - Test Redirection tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant** - Test relevant changes only.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**reports** - Test Reports tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**roles** - Test Roles tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**saml** - Test SAML tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search** - Test search tests with the Elasticsearch 7 search engine.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search-remote** - Test only search tests with the latest compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**search-remote-minimum** - Test search tests with the minimum compatible remote Elasticsearch 7 version.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**security** - Test security tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**seo** - Test SEO tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf** - Test source formatter.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sharepoint** - Test Sharepoint 2010 tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sharing** - Test Asset Sharing tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**site-template** - Test Site Template tests.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**smoke** - Run smoke test with all available configurations in PortalSmoke.testcase
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable** - No description is available.
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**staging** - Test Staging [...]

2022-03-31 00:47 UTC, brianikim commented
https://github.com/liferay-commerce/liferay-portal/pull/2483

2022-03-31 00:47 UTC, closed without merging