COMMERCE-4763 Document breaking changes introduced by COMMERCE-4762
liferay-commerce/liferay-portal pull request #166
Opened 2020-09-10 09:33 UTC by riccardo-alberti

2020-09-10 09:34 UTC, riccardo-alberti commented
ci:test:sf

2020-09-10 09:34 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-09-10 09:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-source-format/4775/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-source-format/builds/4775/jenkins-report.html">here</a>.</b></p>

2020-09-10 09:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1c8dc14a5fceda724a941159b418c46386af1650">1c8dc14a5fceda724a941159b418c46386af1650</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/COMMERCE-4763">COMMERCE-4763</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/468e3e22ca2d5e2eeacd1aeedc2baf0a7c63b91c">468e3e22ca2d5e2eeacd1aeedc2baf0a7c63b91c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-source-format/4775/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/4775/jenkins-report.html">here</a>.</h5></details></html>

2020-09-10 09:40 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-23.liferay.com/job/test-portal-source-format/4775/">test-portal-source-format#4775</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/4775/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/166">liferay-commerce#166</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/38849.aspx">master - riccardo-alberti > liferay-commerce - PR#166 - 2020-09-10[02:34:31]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-20.liferay.com/job/publish-spira-report/4037/">publish-spira-report#4037</a><br />

2020-09-10 16:20 UTC, dsitu requested changes

2020-09-10 16:20 UTC, dsitu commented on modules/apps/commerce/BREAKING_CHANGES.markdown
> +- **Date:** 2020-Aug-10
```suggestion
- **Date:** 2020-Sep-10
```

2020-09-10 17:24 UTC, corbinmurakami requested changes
Thanks. Reviewed and made some comments. Also made a comment on the Jira issue: https://issues.liferay.com/browse/COMMERCE-4763?focusedCommentId=2264215&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2264215

2020-09-10 17:24 UTC, corbinmurakami commented on modules/apps/commerce/BREAKING_CHANGES.markdown
> +The prefix commerce_ has been added to the commerce destinations defined in
We should make it a little clearer that commerce_ is the prefix, either by formatting it as `commerce_` or containing it within quotes, i.e. "commerce_"

We should follow whatever pattern is already established by the Portal breaking changes doc.

2020-09-10 17:24 UTC, corbinmurakami commented on modules/apps/commerce/BREAKING_CHANGES.markdown
> +Update any explicit reference to commerce destinations with the new names.
Is "commerce" referencing the Commerce product/code? If so, it should be a capital C in Commerce because it is a proper noun.

2020-09-10 17:24 UTC, corbinmurakami commented on modules/apps/commerce/BREAKING_CHANGES.markdown
> +This change was introduced to follow Liferay naming pattern.
```suggestion
This change was introduced to follow the Liferay naming pattern.
```

2020-09-11 15:45 UTC, riccardo-alberti commented
ci:test:sf

2020-09-11 15:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/4028/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-portal-source-format/builds/4028/jenkins-report.html">here</a>.</b></p>

2020-09-11 15:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/18ff9e7c715d8e6ec2315b44af6b986f39185764">18ff9e7c715d8e6ec2315b44af6b986f39185764</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/COMMERCE-4763">COMMERCE-4763</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/6fa9dd3ef2592a329f817fc6f4810018faff4cd0">6fa9dd3ef2592a329f817fc6f4810018faff4cd0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/4028/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/4028/jenkins-report.html">here</a>.</h5></details></html>

2020-09-11 16:00 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-17.liferay.com/job/test-portal-source-format/4028/">test-portal-source-format#4028</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/4028/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/166">liferay-commerce#166</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/39602.aspx">master - riccardo-alberti > liferay-commerce - PR#166 - 2020-09-11[08:46:27]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/4691/">publish-spira-report#4691</a><br />

2020-09-11 17:04 UTC, dsitu approved these changes

2020-09-11 21:33 UTC, dsitu commented
Closing sent directly here https://github.com/brianchandotcom/liferay-portal/pull/94162.

2020-09-11 21:33 UTC, closed without merging