COMMERCE-6055 REPLACEMENT
liferay-commerce/liferay-portal pull request #2134
Opened 2022-01-10 20:37 UTC by garofalog

2022-01-10 20:37 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-01-10 20:37 UTC, garofalog commented
ci:test:sf

2022-01-10 20:37 UTC, garofalog commented
ci:test:relevant

2022-01-10 20:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/628/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/628/jenkins-report.html">here</a>.</b></p>

2022-01-10 20:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/1254/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1254/jenkins-report.html">here</a>.</b></p>

2022-01-10 20:39 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/60e93e9f3580106ef82418e09e5677b842cf77d3">60e93e9f3580106ef82418e09e5677b842cf77d3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/garofalog/liferay-portal/tree/COMMERCE-6055">COMMERCE-6055</a><br/>Branch GIT ID: <a href="https://github.com/garofalog/liferay-portal/commit/e0daa96d27e981d72cf400dd3e751b18767a205b">e0daa96d27e981d72cf400dd3e751b18767a205b</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1254/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1254/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 6 formatting issues:
     [java] 1: ',' is not followed by whitespace., see https://checkstyle.sourceforge.io/config_whitespace.html#WhitespaceAfter: ./modules/apps/commerce/commerce-product-subscription-type-web/src/main/resources/META-INF/resources/monthly/view.jsp 104 (Checkstyle:WhitespaceAfterCheck)
     [java] 2: ',' is not followed by whitespace., see https://checkstyle.sourceforge.io/config_whitespace.html#WhitespaceAfter: ./modules/apps/commerce/commerce-product-subscription-type-web/src/main/resources/META-INF/resources/yearly/view.jsp 132 (Checkstyle:WhitespaceAfterCheck)
     [java] 3: ./modules/apps/commerce/commerce-product-subscription-type-web/src/main/resources/META-INF/resources/weekly/view.jsp expected:&lt;...herwise&gt;
     [java] &lt;/c:choose&gt;[]&gt; but was:&lt;...herwise&gt;
     [java] &lt;/c:choose&gt;[
     [java] ]&gt;
     [java] 4: ./modules/apps/commerce/commerce-product-subscription-type-web/src/main/resources/META-INF/resources/yearly/view.jsp expected:&lt;...modeExactdayOfYear",[ ]CPSubscriptionTypeCo...&gt; but was:&lt;...modeExactdayOfYear",[]CPSubscriptionTypeCo...&gt;
     [java] 5: ./modules/apps/commerce/commerce-product-subscription-type-web/src/main/resources/META-INF/resources/monthly/view.jsp expected:&lt;...aui:input&gt;
     [java]     &lt;/div&gt;
     [java] [  &lt;/c:otherwise&gt;
     [java] &lt;/c:choose&gt;
     [java] 
     [java] &lt;liferay-frontend:component
     [java]   context='&lt;%=
     [java]     HashMapBuilder.&lt;String, Object&gt;put(
     [java]       "modeExactDayOfMonth", ]CPSubscriptionTypeCo...&gt; but was:&lt;...aui:input&gt;
     [java]     &lt;/div&gt;
     [java] [
     [java]   &lt;/c:otherwise&gt;
     [java] &lt;/c:choose&gt;
     [java] 
     [java] &lt;liferay-frontend:component
     [java]   context='&lt;%=
     [java]     HashMapBuilder.&lt;String, Object&gt;put(
     [java]       "modeExactDayOfMonth",]CPSubscriptionTypeCo...&gt;
     [java] 6: ./modules/apps/commerce/commerce-product-subscription-type-web/src/main/resources/META-INF/resources/init.jsp expected:&lt;..."liferay-theme" %&gt;
     [java] 
     [java] [&lt;%@ page import="com.liferay.commerce.product.subscription.type.web.internal.constants.CPSubscriptionTypeConstants" %&gt;&lt;%@
     [java] page import="com.liferay.commerce.product.subscription.type.web.internal.display.context.MonthlyCPSubscriptionTypeDisplayContext" %&gt;&lt;%@
     [java] page import="com.liferay.commerce.product.subscription.type.web.internal.display.context.WeeklyCPSubscriptionTypeDisplayContext" %&gt;&lt;%@</code></pre></details></html>

2022-01-10 20:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1254/">test-portal-source-format#1254</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1254/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2134">liferay-commerce#2134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1598238433">[master] ci:test:sf - garofalog &gt; liferay-commerce - PR#2134 - 2022-01-10[12:37:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/4062/">publish-testray-report#4062</a><br/></div></div>

2022-01-10 22:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 11 out of 11 jobs passed</h3><h3>:x: ci:test:relevant - 23 out of 27 jobs passed in 1 hour 43 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2789">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1347401_628</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/60e93e9f3580106ef82418e09e5677b842cf77d3">60e93e9f3580106ef82418e09e5677b842cf77d3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3d2a74598c120e8d3b5055ea8a220c70bb1e38ac">3d2a74598c120e8d3b5055ea8a220c70bb1e38ac</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2787">Acceptance Upstream DXP (master) #2787</a></p><details><summary><strong>ci:test:stable - 11 out of 11 jobs PASSED</strong></summary><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23459/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470331/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/474119/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26055/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23461/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23462/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470332/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13558/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11671/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23460/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/480084/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 27 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/628/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25083/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23799/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22113/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22110/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22108/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/27000/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26271/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23459/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26999/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470331/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/474119/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23464/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26055/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23461/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13557/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11674/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23462/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16853/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23791/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470332/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13558/">test-portal-acceptance-pullrequest-batch(mast [...]

2022-01-10 22:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/628/">test-portal-acceptance-pullrequest(master)#628</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/628/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2134">liferay-commerce#2134</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1598259865">[master] ci:test:relevant - garofalog &gt; liferay-commerce - PR#2134 - 2022-01-10[12:37:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/1991/">publish-testray-report#1991</a><br/></div></div>

2022-01-13 11:06 UTC, FabioDiegoMastrorilli requested changes

2022-01-13 11:06 UTC, FabioDiegoMastrorilli commented on modules/apps/commerce/commerce-product-subscription-type-web/src/main/resources/META-INF/resources/js/yearly/view.js
> +	function changeYearlyDeliveryCPSubscriptionTypeSettingsMode() {
Moving a function here will make it uncallable from the outside (have a look at its closure).

Also, the function should be invoked via event listener after removing:
`onChange='<%= "event.preventDefault(); changeYearlyDeliveryCPSubscriptionTypeSettingsMode();"`

2022-01-13 11:06 UTC, FabioDiegoMastrorilli commented on modules/apps/commerce/commerce-product-subscription-type-web/src/main/resources/META-INF/resources/js/montly/view.js
> +	function changeYearlyDeliveryCPSubscriptionTypeSettingsMode() {
Moving a function here will make it uncallable from the outside (have a look at its closure).

Also, the function should be invoked via event listener after removing:
`onChange='<%= "event.preventDefault(); changeYearlyDeliveryCPSubscriptionTypeSettingsMode();" %>`

2022-01-13 11:06 UTC, FabioDiegoMastrorilli commented
@garofalog please after testing also run `sf`

2023-02-02 14:08 UTC, closed without merging