COMMERCE-8885 info_box refactoring
liferay-commerce/liferay-portal pull request #2604
Opened 2022-05-04 13:29 UTC by garofalog

2022-05-04 13:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-05-06 13:24 UTC, alessiorendina commented on modules/apps/commerce/commerce-frontend-taglib/src/main/resources/META-INF/resources/info_box/page.jsp
> +			"actionLabelValidator", Validator.isNotNull(actionLabel)
You can remove it and validate the actionLabel directly into the component.

2022-05-06 13:25 UTC, alessiorendina commented on modules/apps/commerce/commerce-frontend-taglib/src/main/resources/META-INF/resources/info_box/page.jsp
> +			"actionTargetIdValidator", Validator.isNotNull(actionTargetId)
Same here, you can validate it in the component.

2022-05-06 13:28 UTC, alessiorendina commented on modules/apps/commerce/commerce-frontend-taglib/src/main/resources/META-INF/resources/js/info_box/page.js
> +	if (link && actionLabelValidator && actionTargetIdValidator) {
Create a const to store the result of this if statement.

2022-05-06 13:29 UTC, alessiorendina requested changes
@garofalog Please take a look at the comments, thanks!

2022-05-20 08:19 UTC, giuliogarofalo commented
resolved in [this](https://github.com/liferay-commerce/liferay-portal/pull/2592) pr. this will be closed

2022-05-20 08:21 UTC, garofalog commented
resolved in [this](https://github.com/liferay-commerce/liferay-portal/pull/2592) pr. this pr will be closed then.

2022-05-20 08:22 UTC, closed without merging