Commerce 9047
liferay-commerce/liferay-portal pull request #2736
Opened 2022-06-01 21:57 UTC by MahmoudAzzam

2022-06-01 21:58 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-06-01 21:58 UTC, MahmoudAzzam commented
ci:test:relevant

2022-06-01 21:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3042/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3042/jenkins-report.html">here</a>.</b></p>

2022-06-01 22:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/723/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/723/jenkins-report.html">here</a>.</b></p>

2022-06-01 22:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/723/">test-portal-source-format#723</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/723/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2736">liferay-commerce#2736</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1866694142">[master] ci:test:sf - MahmoudAzzam &gt; liferay-commerce - PR#2736 - 2022-06-01[14:58:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/2335/">publish-testray-report#2335</a><br/></div></div>

2022-06-01 22:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4ed8b4214767add7dcc9f517cd176127530a4081">4ed8b4214767add7dcc9f517cd176127530a4081</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/936b6f597175536b830b73a17b27ce6687f76f88">936b6f597175536b830b73a17b27ce6687f76f88</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3346">Acceptance Upstream DXP (master) #3346</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3042/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3042/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3042/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] &gt; Task :apps:commerce:commerce-initializer-util:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java:494: error: method buildCPInstances in interface CPInstanceLocalService cannot be applied to given types;
     [exec]         _cpInstanceLocalService.buildCPInstances(
     [exec]                                ^
     [exec]   required: long,long,ServiceContext
     [exec]   found: long,ServiceContext
     [exec]   reason: actual and formal argument lists differ in length
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java:713: error: incompatible types: boolean cannot be converted to long
     [exec]           cpDefinitionId, cpOption.getCPOptionId(), importOptionValue,
     [exec]                                                     ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java:748: error: no suitable method found for addCPDefinitionOptionValueRel(long,CPOptionValue,ServiceContext)
     [exec]     return _cpDefinitionOptionValueRelLocalService.
     [exec]                                                   ^
     [exec]     method CPDefinitionOptionValueRelLocalService.addCPDefinitionOptionValueRel(CPDefinitionOptionValueRel) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method CPDefinitionOptionValueRelLocalService.addCPDefinitionOptionValueRel(long,long,CPOptionValue,ServiceContext) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method CPDefinitionOptionValueRelLocalService.addCPDefinitionOptionValueRel(long,long,Map&lt;Locale,String&gt;,double,String,ServiceContext) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java:786: error: no suitable method found for addCPDefinitionSpecificationOptionValue(long,long,long,Map&lt;Locale,String&gt;,double,ServiceContext)
     [exec]     return _cpDefinitionSpecificationOptionValueLocalService.</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-06-01 22:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3042/">test-portal-acceptance-pullrequest(master)#3042</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3042/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2736">liferay-commerce#2736</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1866696520">[master] ci:test:relevant - MahmoudAzzam &gt; liferay-commerce - PR#2736 - 2022-06-01[14:58:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8059/">publish-testray-report#8059</a><br/></div></div>

2022-06-02 08:22 UTC, andrea-ale-sbarra requested changes
1. Avoid direct method call, use service reference. I know this is something you didn't do, but if you find those mistakes please fix them
2. Don't change remote service signature
3. Pass userId to local service with method getUserId()

2022-06-02 08:22 UTC, andrea-ale-sbarra commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionLinkLocalServiceImpl.java
>  		return addCPDefinitionLinkByCProductId(
use service reference don't call method directly

2022-06-23 10:50 UTC, riccardo-alberti commented
@andrea-ale-sbarra is this PR still needed? If not please close

2022-06-24 12:53 UTC, andrea-ale-sbarra commented
I'm closing this because the ticket was removed from the sprint. Once it come back we can review this PR as it is linked to the ticket

2022-06-24 12:53 UTC, closed without merging