Automate test for COMMERCE-7915
liferay-commerce/liferay-portal pull request #2841
Opened 2022-06-28 14:11 UTC by 22LucaGiannotta22

2022-06-28 14:32 UTC, lorenzolapescara requested changes

2022-06-28 14:32 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceDiscounts.testcase
> +			Click(locator1 = "Button#PLUS");
Try to use `CommerceAcceleratorsInitializers.addPortlet()` instead of this and see if it works. Thanks!

2022-07-01 12:40 UTC, lorenzolapescara approved these changes

2022-07-01 12:47 UTC, lorenzolapescara commented
ci:forward

2022-07-01 13:17 UTC, victoroscuro commented
ci:stop

2022-07-01 13:18 UTC, victoroscuro commented
ci:forward

2022-07-01 13:18 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-07-01 13:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1943/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1943/jenkins-report.html">here</a>.</b></p>

2022-07-01 13:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/31e4a20dc53eb12ac4fd6af76734d508bdd4d461">31e4a20dc53eb12ac4fd6af76734d508bdd4d461</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/22LucaGiannotta22/liferay-portal/tree/COMMERCE-7915">COMMERCE-7915</a><br/>Branch GIT ID: <a href="https://github.com/22LucaGiannotta22/liferay-portal/commit/dd20414ddb4504bf2770145e0d58379ffdfd9d18">dd20414ddb4504bf2770145e0d58379ffdfd9d18</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1437/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1437/jenkins-report.html">here</a>.</h5></details></html>

2022-07-01 13:22 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/test-portal-source-format/1437//consoleFull)

2022-07-01 13:22 UTC, closed without merging

2022-07-01 13:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1437/">test-portal-source-format#1437</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1437/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2841">liferay-commerce#2841</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1894441982">[master] ci:test:sf - 22LucaGiannotta22 &gt; liferay-commerce - PR#2841 - 2022-07-01[06:18:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/4524/">publish-testray-report#4524</a><br/></div></div>

2022-07-01 13:32 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/119748

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1943//consoleFull)

2022-07-01 14:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1943/">test-portal-acceptance-pullrequest(master)#1943</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1943/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2841">liferay-commerce#2841</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1894477378">[master] ci:test:relevant - 22LucaGiannotta22 &gt; liferay-commerce - PR#2841 - 2022-07-01[06:18:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/4527/">publish-testray-report#4527</a><br/></div></div>