COMMERCE-9583 Expose ChannelID lookup in Commerce delivery API
liferay-commerce/liferay-portal pull request #2900
Opened 2022-07-20 07:27 UTC by CrescenzoRegaLF

https://issues.liferay.com/browse/COMMERCE-9583

2022-07-20 07:27 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-20 07:28 UTC, CrescenzoRegaLF commented
ci:test:sf

2022-07-20 07:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/1749/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1749/jenkins-report.html">here</a>.</b></p>

2022-07-20 07:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2b6af22d5ab7595d8eb09194c29fcabdbe743459">2b6af22d5ab7595d8eb09194c29fcabdbe743459</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CrescenzoRegaLF/liferay-portal/tree/COMMERCE-9583">COMMERCE-9583</a><br/>Branch GIT ID: <a href="https://github.com/CrescenzoRegaLF/liferay-portal/commit/485781cadc7ddc9ea2b2f06d244925308c7565c9">485781cadc7ddc9ea2b2f06d244925308c7565c9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1749/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1749/jenkins-report.html">here</a>.</h5></details></html>

2022-07-20 07:33 UTC, CrescenzoRegaLF commented
ci:test:relevant

2022-07-20 07:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1749/">test-portal-source-format#1749</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1749/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2900">liferay-commerce#2900</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1911825502">[master] ci:test:sf - CrescenzoRegaLF &gt; liferay-commerce - PR#2900 - 2022-07-20[00:28:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/5568/">publish-testray-report#5568</a><br/></div></div>

2022-07-20 07:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3563/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3563/jenkins-report.html">here</a>.</b></p>

2022-07-20 09:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3563/">test-portal-acceptance-pullrequest(master)#3563</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3563/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2900">liferay-commerce#2900</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1911899521">[master] ci:test:relevant - CrescenzoRegaLF &gt; liferay-commerce - PR#2900 - 2022-07-20[00:34:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/8456/">publish-testray-report#8456</a><br/></div></div>

2022-07-20 14:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/22411abd9875742b0d5eeb0c54ea8f94c0741166">22411abd9875742b0d5eeb0c54ea8f94c0741166</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CrescenzoRegaLF/liferay-portal/tree/COMMERCE-9583">COMMERCE-9583</a><br/>Branch GIT ID: <a href="https://github.com/CrescenzoRegaLF/liferay-portal/commit/fb3dd0e8b23b08ba1b2e56aecfe22bb2289d2a28">fb3dd0e8b23b08ba1b2e56aecfe22bb2289d2a28</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1755/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1755/jenkins-report.html">here</a>.</h5></details></html>

2022-07-20 14:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1755/">test-portal-source-format#1755</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1755/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2900">liferay-commerce#2900</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1912328382">[master] ci:test:sf - CrescenzoRegaLF &gt; liferay-commerce - PR#2900 - 2022-07-20[07:06:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/5588/">publish-testray-report#5588</a><br/></div></div>

2022-07-20 14:11 UTC, CrescenzoRegaLF commented
ci:test:relevant

2022-07-20 15:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/4273/">test-portal-acceptance-pullrequest(master)#4273</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4273/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/2900">liferay-commerce#2900</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1912385238">[master] ci:test:relevant - CrescenzoRegaLF &gt; liferay-commerce - PR#2900 - 2022-07-20[07:11:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/11540/">publish-testray-report#11540</a><br/></div></div>

2022-07-25 16:18 UTC, luca-pellizzon requested changes
One description to fix and commits to sort better.
Regarding permissions, we are so relying on VIEW permission assigned at the model level right?
cc @andrea-ale-sbarra

2022-07-25 16:18 UTC, luca-pellizzon commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-delivery-catalog-impl/rest-openapi.yaml
> +            summary: "Gets a list of channel."
should be "channels" plural

2022-07-26 08:53 UTC, andrea-ale-sbarra commented
> One description to fix and commits to sort better. Regarding permissions, we are so relying on VIEW permission assigned at the model level right? cc @andrea-ale-sbarra

@luca-pellizzon we should, that's what we decided during the grooming

2022-07-27 15:20 UTC, andrea-ale-sbarra commented
resend here https://github.com/liferay-commerce/liferay-portal/pull/2920

2022-07-27 15:20 UTC, closed without merging