COMMERCE-10560
liferay-commerce/liferay-portal pull request #3309
Opened 2023-01-12 16:47 UTC by Brunno0liveira

2023-01-12 16:47 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-01-12 16:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/5893/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5893/jenkins-report.html">here</a>.</b></p>

2023-01-12 16:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/30e6ce42fe80240841eb075d9c66b7f39f8b0511">30e6ce42fe80240841eb075d9c66b7f39f8b0511</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-10560">COMMERCE-10560</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/88160fe56b4ea4b105a7e9e66ecbd7656d61b844">88160fe56b4ea4b105a7e9e66ecbd7656d61b844</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5893/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5893/jenkins-report.html">here</a>.</h5></details></html>

2023-01-12 16:56 UTC, Brunno0liveira commented
ci:test:commerce

2023-01-12 16:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5893/">test-portal-source-format#5893</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5893/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2159439990">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-12[08:49:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/2901/">publish-testray-report#2901</a><br/></div></div>

2023-01-12 17:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7858/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7858/jenkins-report.html">here</a>.</b></p>

2023-01-12 20:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce - 192 out of 201 jobs passed in 2 hours 54 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4183">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1327401_7858</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/30e6ce42fe80240841eb075d9c66b7f39f8b0511">30e6ce42fe80240841eb075d9c66b7f39f8b0511</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/045dfcd7cf0f5630008e30b11e4694570adea96a">045dfcd7cf0f5630008e30b11e4694570adea96a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2157933222">EE Development Acceptance (master) - 4182 - 2023-01-11[05:11:22]</a></p><details><summary><strong>ci:test:commerce - 192 out of 201 jobs PASSED</strong></summary><div><h4>9 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7858/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/351698/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/397762/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372103/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/368759/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379145/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394478/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340437/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372104/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418351/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/177256/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379139/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/397758/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340433/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394474/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379140/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/368754/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/329223/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/177261/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418356/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/121777/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/329224/"><strike>functional-tomcat90-mysql57-jdk8/0/20</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/386055/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151248/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/226597/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/152469/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/397759/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372100/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/368755/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379141/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394475/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340434/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/394476/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/340435/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/397760/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372101/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379148/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/368762/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/177259/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/418354/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372107/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/397766/"><strike>functional-tomcat90-mysql57-jdk8/1/15</strike></a></li><li><a href="https://test-1- [...]

2023-01-12 20:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7858/">test-portal-acceptance-pullrequest(master)#7858</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7858/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2159828127">[master] ci:test:commerce - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-12[09:18:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/19537/">publish-testray-report#19537</a><br/></div></div>

2023-01-16 12:51 UTC, Brunno0liveira commented
ci:test:sf

2023-01-16 12:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/3640/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3640/jenkins-report.html">here</a>.</b></p>

2023-01-16 12:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/923f924efd027680f0669216761d55546f07a9b0">923f924efd027680f0669216761d55546f07a9b0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-10560">COMMERCE-10560</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/eb0c081a4d6a00fb2c3305a5dfd8815c24955f32">eb0c081a4d6a00fb2c3305a5dfd8815c24955f32</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3640/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3640/jenkins-report.html">here</a>.</h5></details></html>

2023-01-16 12:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3640/">test-portal-source-format#3640</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3640/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2162699267">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-16[04:51:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/12749/">publish-testray-report#12749</a><br/></div></div>

2023-01-16 12:58 UTC, Brunno0liveira commented
ci:test:commerce

2023-01-16 13:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/5751/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5751/jenkins-report.html">here</a>.</b></p>

2023-01-17 11:07 UTC, lorenzolapescara requested changes
@Brunno0liveira test descriptions and names are missing the details about the Allow Back Order configuration. Can you add the details to the description and try to change the test names to be compliant with the back order configuration? Thanks

2023-01-17 11:07 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +		task ("Then product remains available to be added to the cart and buyer user can place a second order") {
```suggestion
		task ("Then the product can still be added to the cart and buyer user can place a second order") {
```

2023-01-17 14:53 UTC, Brunno0liveira commented
ci:test:sf

2023-01-17 14:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/6619/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6619/jenkins-report.html">here</a>.</b></p>

2023-01-17 14:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7b11a1fa4186195fe52164a783d3f87bca7fa98b">7b11a1fa4186195fe52164a783d3f87bca7fa98b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-10560">COMMERCE-10560</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/6ace207c067220f30a7a7bc06a98952ee35a9e54">6ace207c067220f30a7a7bc06a98952ee35a9e54</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6619/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6619/jenkins-report.html">here</a>.</h5></details></html>

2023-01-17 15:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6619/">test-portal-source-format#6619</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6619/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2163897406">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-17[06:54:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/3117/">publish-testray-report#3117</a><br/></div></div>

2023-01-17 15:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/2345/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2345/jenkins-report.html">here</a>.</b></p>

2023-01-17 17:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/2345/">test-portal-acceptance-pullrequest(master)#2345</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2345/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2163980166">[master] ci:test:commerce - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-17[07:16:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/5579/">publish-testray-report#5579</a><br/></div></div>

2023-01-17 17:53 UTC, Brunno0liveira commented
ci:test:sf

2023-01-17 17:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/4525/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4525/jenkins-report.html">here</a>.</b></p>

2023-01-17 18:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7b11a1fa4186195fe52164a783d3f87bca7fa98b">7b11a1fa4186195fe52164a783d3f87bca7fa98b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-10560">COMMERCE-10560</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/2ae7d136d476b66bf7944b4fba4ac0eb04f98da5">2ae7d136d476b66bf7944b4fba4ac0eb04f98da5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4525/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4525/jenkins-report.html">here</a>.</h5></details></html>

2023-01-17 18:00 UTC, Brunno0liveira commented
ci:test:commerce

2023-01-17 18:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/5788/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5788/jenkins-report.html">here</a>.</b></p>

2023-01-17 18:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4525/">test-portal-source-format#4525</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4525/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2164118383">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-17[09:55:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/17023/">publish-testray-report#17023</a><br/></div></div>

2023-01-17 21:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce - 103 out of 141 jobs passed in 3 hours 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7b11a1fa4186195fe52164a783d3f87bca7fa98b">7b11a1fa4186195fe52164a783d3f87bca7fa98b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7b11a1fa4186195fe52164a783d3f87bca7fa98b">7b11a1fa4186195fe52164a783d3f87bca7fa98b</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2163548052">EE Development Acceptance (master) - 4194 - 2023-01-16[17:39:37]</a></p><details><summary><strong>ci:test:commerce - 103 out of 141 jobs PASSED</strong></summary><div><h4>38 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/5788/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356620/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/346901/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376730/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403166/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319191/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383856/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/182059/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/182060/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/346902/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/423696/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/423692/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/346898/"><strike>functional-tomcat90-mysql57-jdk8/0/11</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/399457/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356618/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/344481/"><strike>functional-tomcat90-mysql57-jdk8/0/14</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373511/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/344488/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372496/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319197/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389339/"><strike>functional-tomcat90-mysql57-jdk8/0/19</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/150396/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/154076/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/138791/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140309/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/146711/"><strike>functional-tomcat90-mysql57-jdk8/0/24</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/399458/"><strike>functional-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/346899/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373512/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383854/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356619/"><strike>functional-tomcat90-mysql57-jdk8/1/4</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/182057/"><strike>functional-tomcat90-mysql57-jdk8/1/5</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373514/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373513/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376729/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403164/"><strike>functional-tomcat90-mysql57-jdk8/1/9</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/182063/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/344487/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383860/"><strike>functional-tomcat90-mysql57-jdk8/1/12</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372495/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373521/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319196/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389337/"><strike>functional-tomcat90-mysql57-jdk8/1/16</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/399460/"><strike>functional-t [...]

2023-01-17 21:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/5788/">test-portal-acceptance-pullrequest(master)#5788</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5788/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2164254068">[master] ci:test:commerce - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-17[10:00:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/12826/">publish-testray-report#12826</a><br/></div></div>

2023-01-19 12:53 UTC, Brunno0liveira commented
ci:test:commerce

2023-01-19 14:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/5580/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5580/jenkins-report.html">here</a>.</b></p>

2023-01-19 16:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce - 130 out of 141 jobs passed in 1 hour 48 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4200">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1287401_5580</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0005f7933515c08392cecc6c7dd75d523d8a4bb6">0005f7933515c08392cecc6c7dd75d523d8a4bb6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/748079b6a4522d5ae29ee905d5f5d9984f82a56b">748079b6a4522d5ae29ee905d5f5d9984f82a56b</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2166313109">EE Development Acceptance (master) - 4199 - 2023-01-18[20:13:53]</a></p><details><summary><strong>ci:test:commerce - 130 out of 141 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/5580/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/427200/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137490/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379694/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379696/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376647/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379695/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376646/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379697/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185432/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137491/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137479/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137480/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137481/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137482/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137483/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137484/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347467/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402912/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347468/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151413/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/406812/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322150/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402915/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151414/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/406813/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137487/"><strike>functional-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137477/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137488/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185424/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185423/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185422/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376642/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185425/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/427195/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376710/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376654/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347465/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322144/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374167/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379702/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/359963/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-38.liferay.com/job [...]

2023-01-19 16:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/5580/">test-portal-acceptance-pullrequest(master)#5580</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5580/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2166483310">[master] ci:test:commerce - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-19[06:20:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/13339/">publish-testray-report#13339</a><br/></div></div>

2023-01-19 16:31 UTC, lorenzolapescara requested changes
@Brunno0liveira please check this comments and look for similar errors in the test descriptions and names. Thanks

2023-01-19 16:31 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10560. Allowed quantities can be added to cart when order is higher than stock quantity when back orders are enable"
```suggestion
	@description = "This is a test for COMMERCE-10560. Allowed quantities can be added to the cart when order quantity is higher than the stock quantity and back order is enabled"
```

2023-01-19 16:31 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CanAddToCartAllowedQuantitiesWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrdersAreEnable {
```suggestion
	test CanAddToCartAllowedQuantitiesWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrderIsEnabled {
```

2023-01-19 17:31 UTC, Brunno0liveira commented
ci:test:sf

2023-01-19 17:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0005f7933515c08392cecc6c7dd75d523d8a4bb6">0005f7933515c08392cecc6c7dd75d523d8a4bb6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-10560">COMMERCE-10560</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/a1fadce30a71e339cb22aa62e14c1826b633c20b">a1fadce30a71e339cb22aa62e14c1826b633c20b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4560/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4560/jenkins-report.html">here</a>.</h5></details></html>

2023-01-19 17:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/4560/">test-portal-source-format#4560</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/4560/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2166542685">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-19[09:31:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/17156/">publish-testray-report#17156</a><br/></div></div>

2023-01-19 17:43 UTC, Brunno0liveira commented
ci:test:commerce

2023-01-19 17:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7959/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7959/jenkins-report.html">here</a>.</b></p>

2023-01-19 20:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce - 133 out of 141 jobs passed in 2 hours 17 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0005f7933515c08392cecc6c7dd75d523d8a4bb6">0005f7933515c08392cecc6c7dd75d523d8a4bb6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0005f7933515c08392cecc6c7dd75d523d8a4bb6">0005f7933515c08392cecc6c7dd75d523d8a4bb6</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2166487250">EE Development Acceptance (master) - 4200 - 2023-01-19[05:07:56]</a></p><details><summary><strong>ci:test:commerce - 133 out of 141 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7959/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347986/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/407408/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403298/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334563/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380179/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/152866/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/155451/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/392376/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387724/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403299/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387713/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387714/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387715/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/154331/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347979/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387716/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350641/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130462/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/132145/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/141587/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/322670/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151430/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374484/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/234000/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/153757/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/154332/"><strike>functional-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347981/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387719/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347982/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140015/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387718/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403296/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387720/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347983/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380176/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/392379/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233998/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/155453/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140019/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137421/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137422/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/360543/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/139652/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387725/"><strike>functional-tomcat90-mysql57-jdk8/1/18</strike></a></li><li><a href=" [...]

2023-01-19 20:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/7959/">test-portal-acceptance-pullrequest(master)#7959</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7959/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2166696819">[master] ci:test:commerce - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-19[09:46:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/19759/">publish-testray-report#19759</a><br/></div></div>

2023-01-20 10:47 UTC, lorenzolapescara requested changes

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10542. Maximum quantity can be added to the cart when order quantity is lower than stock quantity and back orders is enabled"
```suggestion
	@description = "This is a test for COMMERCE-10542. Maximum quantity can be added to the cart when order quantity is lower than stock quantity and back order is enabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CanAddToCartMaximumProductQuantityWhenOrderItemQuantityIsLowerThanStockQuantityAndBackOrdersIsEnable {
```suggestion
	test CanAddToCartMaximumQuantityWhenOrderItemQuantityIsLowerThanStockQuantityAndBackOrderIsEnabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10503. Minimum quantity can be added to the cart when order quantity is higher then the stock quantity and back orders is enabled"
```suggestion
	@description = "This is a test for COMMERCE-10503. Minimum quantity can be added to the cart when order quantity is higher than the stock quantity and back order is enabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CanAddToCartMinimumProductQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrdersIsEnable {
```suggestion
	test CanAddToCartMinimumQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrderIsEnabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10503. Minimum quantity can be added to the cart when order quantity is lower than the stock quantity and back orders is enabled"
```suggestion
	@description = "This is a test for COMMERCE-10503. Minimum quantity can be added to the cart when order quantity is lower than the stock quantity and back order is enabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CanAddToCartMinimumProductQuantityWhenOrderItemQuantityIsLowerThanStockQuantityAndBackOrdersIsEnable {
```suggestion
	test CanAddToCartMinimumQuantityWhenOrderItemQuantityIsLowerThanStockQuantityAndBackOrderIsEnabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10559. Multiple quantity can be added to the cart when order quantity is higher than the stock quantity and back orders is enabled"
```suggestion
	@description = "This is a test for COMMERCE-10559. Multiple quantities can be added to the cart when order quantity is higher than the stock quantity and back order is enabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CanAddToCartMultipleProductQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrdersIsEnable {
```suggestion
	test CanAddToCartMultipleQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrderIsEnabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10559. Multiple quantity can be added to the cart when order quantity is lower than the stock quantity and back orders is enabled"
```suggestion
	@description = "This is a test for COMMERCE-10559. Multiple quantities can be added to the cart when order quantity is lower than the stock quantity and back order is enabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CanAddToCartMultipleProductQuantityWhenOrderItemQuantityIsLowerThanStockQuantityAndBackOrdersIsEnable {
```suggestion
	test  #CanAddToCartMultipleQuantityWhenOrderItemQuantityIsLowerThanStockQuantityAndBackOrderIsEnabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10560. Allowed quantities can be added to the cart until there's stock quantity and back orders is unabled"
```suggestion
	@description = "This is a test for COMMERCE-10560. Allowed quantities can be added to the cart until there's stock quantity and back order is disabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CannotAddToCartAllowedQuantitiesWhenStockQuantityIsLessAndBackOrdersIsUnable {
```suggestion
	test CannotAddToCartAllowedQuantitiesWhenStockQuantityIsLessAndBackOrdersIsUnable {
```
```suggestion
	test CannotAddToCartAllowedQuantitiesWhenStockQuantityIsLessAndBackOrderIsDisabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10542. Maximum quantity cannot be added to the cart when order quantity is higher than the stock quantity and back orders is unabled"
```suggestion
	@description = "This is a test for COMMERCE-10542. Maximum quantity cannot be added to the cart when order quantity is higher than the stock quantity and back order is disabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CannotAddToCartMaximumProductQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrdersIsUnable {
```suggestion
	test CannotAddToCartMaximumQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrderIsDisabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10542. Maximum quantity can be added to the cart until there's stock quantity and back orders is unabled"
```suggestion
	@description = "This is a test for COMMERCE-10542. Maximum quantity can be added to the cart until there's stock quantity and back order is disabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CannotAddToCartMaximumProductQuantityWhenStockQuantityIsLessAndBackOrdersIsUnable {
```suggestion
	test CannotAddToCartMaximumQuantityWhenStockQuantityIsLessAndBackOrderIsDisabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10503. Minimum quantity cannot be added to the cart when order quantity is higher then the stock quantity and back orders is unabled"
```suggestion
	@description = "This is a test for COMMERCE-10503. Minimum quantity cannot be added to the cart when order quantity is higher then the stock quantity and back order is disabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CannotAddToCartMinimumProductQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrdersIsUnable {
```suggestion
	test CannotAddToCartMinimumQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrderIsDisabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10503. Minimum quantity can be added to the cart until there's stock quantity and back orders is unabled"
```suggestion
	@description = "This is a test for COMMERCE-10503. Minimum quantity can be added to the cart until there's stock quantity and back order is disabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CannotAddToCartMinimumProductQuantityWhenStockQuantityIsLessAndBackOrdersIsUnable {
```suggestion
	test CannotAddToCartMinimumQuantityWhenStockQuantityIsLessAndBackOrderIsDisabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10559. Multiple quantity cannot be added to the cart when order quantity is higher than the stock quantity and back orders is unable"
```suggestion
	@description = "This is a test for COMMERCE-10559. Multiple quantities cannot be added to the cart when order quantity is higher than the stock quantity and back order is disabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CannotAddToCartMultipleProductQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrdersIsUnable {
```suggestion
	test CannotAddToCartMultipleQuantityWhenOrderItemQuantityIsHigherThanStockQuantityAndBackOrderIsDisabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10559. Multiple quantity can be added to the cart until there's stock quantity and back orders is unabled"
```suggestion
	@description = "This is a test for COMMERCE-10559. Multiple quantities can be added to the cart until there's stock quantity and back order is disabled"
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	test CannotAddToCartMultipleProductQuantityWhenStockQuantityIsLessAndBackOrdersIsUnable {
```suggestion
	test CannotAddToCartMultipleQuantityWhenStockQuantityIsLessAndBackOrderIsDisabled {
```

2023-01-20 10:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductConfigurations.testcase
> +	@description = "This is a test for COMMERCE-10491. The product can be added to the cart until there's stock quantity and back orders is unabled"
```suggestion
	@description = "This is a test for COMMERCE-10491. The product can be added to the cart until there's stock quantity and back order is disabled"
```

2023-01-20 14:47 UTC, Brunno0liveira commented
ci:test:sf

2023-01-20 14:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/1298/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1298/jenkins-report.html">here</a>.</b></p>

2023-01-20 14:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/347d0d9e32ce975c2f9ac0cc6070b73ebb1a50c2">347d0d9e32ce975c2f9ac0cc6070b73ebb1a50c2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-10560">COMMERCE-10560</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/b5e8a592853a6d4c0d597b9e19692688c8005f02">b5e8a592853a6d4c0d597b9e19692688c8005f02</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1298/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1298/jenkins-report.html">here</a>.</h5></details></html>

2023-01-20 14:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1298/">test-portal-source-format#1298</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1298/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2167818513">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-20[06:47:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/3618/">publish-testray-report#3618</a><br/></div></div>

2023-01-20 15:10 UTC, Brunno0liveira commented
ci:test:sf

2023-01-20 15:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/5748/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5748/jenkins-report.html">here</a>.</b></p>

2023-01-20 15:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/347d0d9e32ce975c2f9ac0cc6070b73ebb1a50c2">347d0d9e32ce975c2f9ac0cc6070b73ebb1a50c2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-10560">COMMERCE-10560</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/307e2245b20d200635e734259f725a0663d19688">307e2245b20d200635e734259f725a0663d19688</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5748/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5748/jenkins-report.html">here</a>.</h5></details></html>

2023-01-20 15:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5748/">test-portal-source-format#5748</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5748/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2167868149">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-20[07:11:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/3121/">publish-testray-report#3121</a><br/></div></div>

2023-01-20 16:55 UTC, Brunno0liveira commented
ci:test:sf

2023-01-20 16:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/4875/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4875/jenkins-report.html">here</a>.</b></p>

2023-01-20 16:58 UTC, lorenzolapescara approved these changes

2023-01-20 16:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/347d0d9e32ce975c2f9ac0cc6070b73ebb1a50c2">347d0d9e32ce975c2f9ac0cc6070b73ebb1a50c2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-10560">COMMERCE-10560</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/9860b96181396fa4d9b8e02cd25433c0c7df186a">9860b96181396fa4d9b8e02cd25433c0c7df186a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4875/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4875/jenkins-report.html">here</a>.</h5></details></html>

2023-01-20 17:00 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-01-20 17:00 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2023-01-20 17:01 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-35.liferay.com/job/forward-pullrequest/354//consoleFull)

2023-01-20 17:01 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/129061
[Console](https://test-1-35.liferay.com/job/forward-pullrequest/354//consoleFull)

2023-01-20 17:01 UTC, closed without merging

2023-01-20 17:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/4875/">test-portal-source-format#4875</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4875/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3309">liferay-commerce#3309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2168016400">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3309 - 2023-01-20[08:55:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/18685/">publish-testray-report#18685</a><br/></div></div>