COMMERCE-11068
liferay-commerce/liferay-portal pull request #3574
Opened 2023-03-28 13:50 UTC by Brunno0liveira

2023-03-28 13:51 UTC, Brunno0liveira commented
ci:test:sf

2023-03-28 13:51 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-28 13:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/1730/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1730/jenkins-report.html">here</a>.</b></p>

2023-03-28 14:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/1730/">test-portal-source-format#1730</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1730/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2248640266">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-03-28[06:51:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/7106/">publish-testray-report#7106</a><br/></div></div>

2023-03-28 14:32 UTC, Brunno0liveira commented
ci:test:sf

2023-03-28 14:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/2256/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2256/jenkins-report.html">here</a>.</b></p>

2023-03-28 14:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69049f4216818f70a89fcfd5e7ab189673d9b763">69049f4216818f70a89fcfd5e7ab189673d9b763</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-11068">COMMERCE-11068</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/e75392538d5216f968b506a1ba733a7fe3ee0f54">e75392538d5216f968b506a1ba733a7fe3ee0f54</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2256/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2256/jenkins-report.html">here</a>.</h5></details></html>

2023-03-28 14:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2256/">test-portal-source-format#2256</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2256/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2248699963">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-03-28[07:32:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/8991/">publish-testray-report#8991</a><br/></div></div>

2023-03-28 15:26 UTC, Brunno0liveira commented
ci:test:commerce-functional

2023-03-28 17:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 136 out of 140 jobs passed in 2 hours 22 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4417">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1267401_8463</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8804f1e7f8b1a387b7408d416ae5d54d8808c551">8804f1e7f8b1a387b7408d416ae5d54d8808c551</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d79e68689c95b6ab53e625e49759386b549d8365">d79e68689c95b6ab53e625e49759386b549d8365</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2248034661">EE Development Acceptance (master) - 4416 - 2023-03-27[16:44:51]</a></p><details><summary><strong>ci:test:commerce-functional - 136 out of 140 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/8463/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/546716/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/451320/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31517/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/181628/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/173591/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453225/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/174558/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/445224/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453226/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/191509/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/174556/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43134/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/417825/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/151059/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453219/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/182346/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/523404/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/546724/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/496815/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/417842/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/496820/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/523409/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/496822/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/173596/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/422037/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/188121/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190121/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/471515/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/314452/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/422022/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/417826/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190122/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/193626/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43138/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/523393/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/185108/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/182351/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/188125/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453231/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/447375/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43147/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-30.liferay.com/jo [...]

2023-03-28 17:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/8463/">test-portal-acceptance-pullrequest(master)#8463</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8463/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2248969038">[master] ci:test:commerce-functional - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-03-28[08:26:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/19818/">publish-testray-report#19818</a><br/></div></div>

2023-03-29 09:25 UTC, lorenzolapescara requested changes

2023-03-29 09:25 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceAccelerators.testcase
> +	test CanChangeThemeToMiniumTheme {
```suggestion
	test CanApplyMiniumThemeToSite {
```

2023-03-29 15:23 UTC, Brunno0liveira commented
ci:test:sf

2023-03-29 15:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/4183/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4183/jenkins-report.html">here</a>.</b></p>

2023-03-29 15:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d2dd7c5a39b6c58c8557e9aa7917d7da7b712e0d">d2dd7c5a39b6c58c8557e9aa7917d7da7b712e0d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-11068">COMMERCE-11068</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/e36385582985c7f8c3d1754c93617901338a476e">e36385582985c7f8c3d1754c93617901338a476e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4183/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4183/jenkins-report.html">here</a>.</h5></details></html>

2023-03-29 15:28 UTC, Brunno0liveira commented
ci:test:commerce-functional

2023-03-29 15:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4183/">test-portal-source-format#4183</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4183/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2250412677">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-03-29[08:23:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/15698/">publish-testray-report#15698</a><br/></div></div>

2023-03-29 18:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6135/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6135/jenkins-report.html">here</a>.</b></p>

2023-03-29 22:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 135 out of 140 jobs passed in 4 hours 27 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d2dd7c5a39b6c58c8557e9aa7917d7da7b712e0d">d2dd7c5a39b6c58c8557e9aa7917d7da7b712e0d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d2dd7c5a39b6c58c8557e9aa7917d7da7b712e0d">d2dd7c5a39b6c58c8557e9aa7917d7da7b712e0d</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2250643354">EE Development Acceptance (master) - 4422 - 2023-03-29[08:36:50]</a></p><details><summary><strong>ci:test:commerce-functional - 135 out of 140 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6135/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303564/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46352/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/189028/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186159/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526721/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/180680/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46353/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303566/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526722/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448387/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/168114/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/168115/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/168116/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/168117/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/550215/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/550216/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456516/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/181452/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420770/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/317531/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454375/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/194948/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303574/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420771/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448393/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/550219/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/550218/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/550222/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/181153/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/550220/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/181152/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/512231/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/550224/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/550223/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/168120/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456515/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420769/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303572/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/448391/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/464382/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/181157/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/500100/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/175592/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/526724/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a href="https://tes [...]

2023-03-29 23:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/6135/">test-portal-acceptance-pullrequest(master)#6135</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6135/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2250772475">[master] ci:test:commerce-functional - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-03-29[11:32:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/14358/">publish-testray-report#14358</a><br/></div></div>

2023-03-30 08:22 UTC, lorenzolapescara approved these changes

2023-03-30 08:26 UTC, lorenzolapescara commented
@Brunno0liveira the new test is failing, please check it, thanks!

2023-03-31 07:30 UTC, victoroscuro commented
@Brunno0liveira can you please check the test that is failing?

2023-03-31 14:15 UTC, Brunno0liveira commented
ci:test:sf

2023-03-31 14:19 UTC, Brunno0liveira commented
> @Brunno0liveira can you please check the test that is failing?

The test was updated, waiting for review

2023-03-31 14:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/3999/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3999/jenkins-report.html">here</a>.</b></p>

2023-03-31 14:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/633/">test-portal-source-format#633</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/633/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2253826106">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-03-31[07:16:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/1955/">publish-testray-report#1955</a><br/></div></div>

2023-03-31 16:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 130 out of 143 jobs passed in 1 hour 41 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4427">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1397401_3999</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/eeb112e46093f89e02046cb3bc5fa6dece29a594">eeb112e46093f89e02046cb3bc5fa6dece29a594</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/38a95f4cd1935c57e8a7fae672576d9d9a5b163e">38a95f4cd1935c57e8a7fae672576d9d9a5b163e</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2253392023">EE Development Acceptance (master) - 4426 - 2023-03-30[20:40:42]</a></p><details><summary><strong>ci:test:commerce-functional - 130 out of 143 jobs PASSED</strong></summary><div><h4>13 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/3999/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454004/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/428763/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/475749/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452475/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/424463/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/457893/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/321436/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/475750/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/516040/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/460634/"><strike>functional-tomcat90-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50799/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/424459/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452471/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/504129/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/428760/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/475746/"><strike>functional-tomcat90-mysql57-jdk8/0/15</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/554741/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/475753/"><strike>functional-tomcat90-mysql57-jdk8/0/17</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/428767/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/516046/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50807/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/475754/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/516047/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38558/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/457898/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38550/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/321434/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/504130/"><strike>functional-tomcat90-mysql57-jdk8/1/2</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452472/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307949/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/457890/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/457891/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/321435/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50801/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/475747/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/468360/"><strike>functional-tomcat90-mysql57-jdk8/1/10</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/531099/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/475752/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/554740/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/428766/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/516045/">funct [...]

2023-03-31 16:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/3999/">test-portal-acceptance-pullrequest(master)#3999</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3999/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2253960955">[master] ci:test:commerce-functional - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-03-31[07:20:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/8837/">publish-testray-report#8837</a><br/></div></div>

2023-04-03 07:29 UTC, lorenzolapescara commented
`CanApplyMiniumThemeToSite` is still failing. We need to investigate what's happening here

2023-04-03 16:19 UTC, Brunno0liveira commented
ci:test:sf

2023-04-03 16:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8ac53d398fd24e827769ffb1b41868aeaab72e2c">8ac53d398fd24e827769ffb1b41868aeaab72e2c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-11068">COMMERCE-11068</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/7d973b7028289ba054284528ff09945954a8fca3">7d973b7028289ba054284528ff09945954a8fca3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5573/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5573/jenkins-report.html">here</a>.</h5></details></html>

2023-04-03 16:28 UTC, Brunno0liveira commented
ci:test:commerce-functional

2023-04-03 16:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5573/">test-portal-source-format#5573</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5573/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2256138961">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-04-03[09:21:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/3768/">publish-testray-report#3768</a><br/></div></div>

2023-04-03 18:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 133 out of 141 jobs passed in 1 hour 47 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8ac53d398fd24e827769ffb1b41868aeaab72e2c">8ac53d398fd24e827769ffb1b41868aeaab72e2c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8ac53d398fd24e827769ffb1b41868aeaab72e2c">8ac53d398fd24e827769ffb1b41868aeaab72e2c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2256017752">EE Development Acceptance (master) - 4431 - 2023-04-03[04:36:22]</a></p><details><summary><strong>ci:test:commerce-functional - 133 out of 141 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/4027/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506141/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459549/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/426247/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/197018/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/184980/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/170235/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462433/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455932/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/533255/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/533254/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462427/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309573/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/506135/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462428/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/470432/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309574/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53040/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477303/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455936/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190983/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/187846/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/323444/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53041/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455937/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/183204/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459545/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/470433/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459546/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/426244/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462425/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309575/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/426245/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/557022/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462430/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309576/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/517875/"><strike>functional-tomcat90-mysql57-jdk8/1/10</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/323441/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53039/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455935/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477302/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/430688/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40591/">functional-tomcat90-mysql57-jdk8/1/16</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/174145/">functional-tomcat90-mysql57-jdk8/1/17</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/177326/">functional-tomcat90-mysql57-jdk8/1/18</a></li><li><a  [...]

2023-04-03 18:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/4027/">test-portal-acceptance-pullrequest(master)#4027</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4027/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2256236176">[master] ci:test:commerce-functional - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-04-03[09:29:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/8890/">publish-testray-report#8890</a><br/></div></div>

2023-04-04 12:50 UTC, Brunno0liveira commented
ci:test:sf

2023-04-04 12:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/6400/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6400/jenkins-report.html">here</a>.</b></p>

2023-04-04 12:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c98d93dc5097b2a702723f607edf951c2d4dd560">c98d93dc5097b2a702723f607edf951c2d4dd560</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-11068">COMMERCE-11068</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/79c2998f8a4f31e03722f5f9edd73b0c4911703f">79c2998f8a4f31e03722f5f9edd73b0c4911703f</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6400/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6400/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-impl/src/portal.properties expected:&lt;...ER4__NUMBER5__NUMBER[]6__NUMBER3_
     [java]     #
     [java]   ...&gt; but was:&lt;...ER4__NUMBER5__NUMBER[2__NUMBER8_
     [java]     #
     [java]     feature.flag.LPS-164528=false
     [java] 
     [java]     #
     [java]     # Env: LIFERAY_FEATURE_PERIOD_FLAG_PERIOD__UPPERCASEL__UPPERCASEP__UPPERCASES__MINUS__NUMBER1__NUMBER6__NUMBER4__NUMBER5__NUMBER]6__NUMBER3_
     [java]     #
     [java]   ...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:456)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 2:48.087 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-6/job/test-portal-source-format/6400//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230404055227526.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230404055227526.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1798616559.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2055260253
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 245ms
[junitreport] Deleting: /tmp/null2055260253
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2023-04-04 13:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6400/">test-portal-source-format#6400</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6400/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2257269853">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-04-04[05:51:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/3899/">publish-testray-report#3899</a><br/></div></div>

2023-04-04 13:04 UTC, Brunno0liveira commented
ci:test:sf

2023-04-04 13:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5922/">test-portal-source-format#5922</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5922/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3574">liferay-commerce#3574</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2257269971">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#3574 - 2023-04-04[06:05:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/21514/">publish-testray-report#21514</a><br/></div></div>

2023-04-04 13:22 UTC, closed without merging