COMMERCE-9979 check if it is an empty list
liferay-commerce/liferay-portal pull request #3787
Opened 2023-05-19 09:31 UTC by jaydawu

https://issues.liferay.com/browse/COMMERCE-9979
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3029
Since the fix already [exists](https://github.com/liferay-commerce/liferay-portal/pull/3029/commits/01eaabb54b3339d56ca33b11c4ab26f5cec79168) on master, we just send a functional test to cover this scene, thanks.

2023-05-19 09:31 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-05-19 09:31 UTC, jaydawu commented
ci:test:sf

2023-05-19 09:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5210/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5210/jenkins-report.html">here</a>.</b></p>

2023-05-19 09:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b21f637c6157f87c482aabd4dc2efe8ed4ae0b9d">b21f637c6157f87c482aabd4dc2efe8ed4ae0b9d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaydawu/liferay-portal/tree/COMMERCE-9979">COMMERCE-9979</a><br/>Branch GIT ID: <a href="https://github.com/jaydawu/liferay-portal/commit/8c54d46acecb4146cf5f3b67b1b45aad617d3a73">8c54d46acecb4146cf5f3b67b1b45aad617d3a73</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5210/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5210/jenkins-report.html">here</a>.</h5></details></html>

2023-05-19 09:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/9306/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9306/jenkins-report.html">here</a>.</b></p>

2023-05-19 09:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5210/">test-portal-source-format#5210</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5210/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3787">liferay-commerce#3787</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2310367563">[master] ci:test:sf - jaydawu &gt; liferay-commerce - PR#3787 - 2023-05-19[02:31:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/19455/">publish-testray-report#19455</a><br/></div></div>

2023-05-19 12:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/9306/">test-portal-acceptance-pullrequest(master)#9306</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9306/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3787">liferay-commerce#3787</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2310800998">[master] ci:test:commerce-functional - jaydawu &gt; liferay-commerce - PR#3787 - 2023-05-19[02:37:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/21542/">publish-testray-report#21542</a><br/></div></div>

2023-05-22 09:12 UTC, lorenzolapescara requested changes

2023-05-22 09:12 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommercePaymentMethodsPermissions.testcase
> +	test CanOperationsManagerEditTheSelectedPaymentMethodOfAPlacedOrderWithoutItems {
```suggestion
	test CanOperationsManagerEditEmptyPlacedOrderSelectedPaymentMethod {
```

2023-05-22 09:34 UTC, jaydawu commented
ci:test:sf

2023-05-22 09:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2317/">test-portal-source-format#2317</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2317/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/3787">liferay-commerce#3787</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2314898290">[master] ci:test:sf - jaydawu &gt; liferay-commerce - PR#3787 - 2023-05-22[02:35:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/9316/">publish-testray-report#9316</a><br/></div></div>

2023-05-22 09:46 UTC, jaydawu commented
ci:forward

2023-05-22 09:46 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-22 09:46 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-05-22 09:47 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-9.liferay.com/job/forward-pullrequest/362//consoleFull)

2023-05-22 09:48 UTC, closed without merging