COMMERCE-12393
liferay-commerce/liferay-portal pull request #4278
Opened 2023-10-02 13:45 UTC by Brunno0liveira

2023-10-02 13:45 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-02 13:45 UTC, Brunno0liveira commented
ci:test:sf

2023-10-02 13:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/8322/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8322/jenkins-report.html">here</a>.</b></p>

2023-10-02 13:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fa65eaa1d9c6063a8463909c47b97a73ea16c071">fa65eaa1d9c6063a8463909c47b97a73ea16c071</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-12393">COMMERCE-12393</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/f080e4f35959f0ee4129793356d7e91559c23ed4">f080e4f35959f0ee4129793356d7e91559c23ed4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8322/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8322/jenkins-report.html">here</a>.</h5></details></html>

2023-10-02 13:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8322/">test-portal-source-format#8322</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8322/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4278">liferay-commerce#4278</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2434580162">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#4278 - 2023-10-02[06:45:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/31618/">publish-testray-report#31618</a><br/></div></div>

2023-10-02 14:08 UTC, 22LucaGiannotta22 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceUnitsOfMeasure.testcase
> +	@description = "COMMERCE-12393. As a buyer I can view the UOMs sorted by priority."
@description = "COMMERCE-12393. As a buyer I can view the UOMs sorted by priority on the UOM selector from the product details page

2023-10-02 14:11 UTC, 22LucaGiannotta22 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceUnitsOfMeasure.testcase
> +	@description = "COMMERCE-12393. As a buyer I can view the UOMs sorted by priority."
@description = "COMMERCE-12393. As a buyer I can view the UOMs sorted by priority on the UOM selector from the product details page."

2023-10-02 15:38 UTC, Brunno0liveira commented
ci:test:sf

2023-10-02 15:40 UTC, Brunno0liveira commented
ci:test:commerce-functional

2023-10-02 15:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/2315/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2315/jenkins-report.html">here</a>.</b></p>

2023-10-02 15:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7437/">test-portal-source-format#7437</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7437/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4278">liferay-commerce#4278</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2434638140">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#4278 - 2023-10-02[08:39:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27779/">publish-testray-report#27779</a><br/></div></div>

2023-10-02 18:32 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 190 out of 196 jobs passed in 2 hours 48 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/53">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1327401_2315</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a93daf3fd852d2730ebe63a3c5ecf9ad49078593">a93daf3fd852d2730ebe63a3c5ecf9ad49078593</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5478700ed9489d8b83f571e14550dbb9d38b4cf2">5478700ed9489d8b83f571e14550dbb9d38b4cf2</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2434377318">EE Development Acceptance (master) - 52 - 2023-10-01[16:38:59]</a></p><details><summary><strong>ci:test:commerce-functional - 190 out of 196 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/2315/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731836/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731835/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313000/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/769434/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/693908/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/661857/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/769433/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/872830/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/747620/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/625689/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281795/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/747618/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/289537/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760415/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/296404/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/271550/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372057/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/760418/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/671646/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792961/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/273982/"><strike>functional-tomcat90-mysql57-jdk8/0/20</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372059/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372060/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372061/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/605460/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/605457/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/279785/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/716723/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357057/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/372054/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/298442/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/625688/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/272955/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/256915/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239708/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/747622/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/872832/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792960/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357059/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/605459/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/706627/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href= [...]

2023-10-02 18:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/2315/">test-portal-acceptance-pullrequest(master)#2315</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2315/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4278">liferay-commerce#4278</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2434709869">[master] ci:test:commerce-functional - Brunno0liveira &gt; liferay-commerce - PR#4278 - 2023-10-02[08:44:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27787/">publish-testray-report#27787</a><br/></div></div>

2023-10-03 10:21 UTC, pietrobocale requested changes
The review is done. Please take a look at the comments.

Thanks!

2023-10-03 10:21 UTC, pietrobocale commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceUnitsOfMeasure.testcase
> +					uomName = ${uomName});
- The highest priority UOM should be pre-selected(UOM2). I noticed that we are just checking with an AssertElementPresent and an Idex, but we don't verify the content of what is written. At that moment, you should be able to use the AssertSelectedLabel with this path here: CommerceFrontStore#FS_PRODUCT_UOM_SELECT

2023-10-03 10:21 UTC, pietrobocale commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceUnitsOfMeasure.testcase
> +				productSKU = "MIN93015");
We are not checking the quantity in the product details

2023-10-03 13:30 UTC, Brunno0liveira commented
ci:test:sf

2023-10-03 13:30 UTC, Brunno0liveira commented
ci:test:commerce-functional

2023-10-03 13:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6475/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6475/jenkins-report.html">here</a>.</b></p>

2023-10-03 13:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3105/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3105/jenkins-report.html">here</a>.</b></p>

2023-10-03 13:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/104f1f8d1ce8a5f7b68c8450605119af7ba3d328">104f1f8d1ce8a5f7b68c8450605119af7ba3d328</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-12393">COMMERCE-12393</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/4d951bed4a958c94e764c41fc5bd911abf7be795">4d951bed4a958c94e764c41fc5bd911abf7be795</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3105/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3105/jenkins-report.html">here</a>.</h5></details></html>

2023-10-03 13:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3105/">test-portal-source-format#3105</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3105/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4278">liferay-commerce#4278</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2435604451">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#4278 - 2023-10-03[06:30:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/12010/">publish-testray-report#12010</a><br/></div></div>

2023-10-03 16:13 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 191 out of 196 jobs passed in 2 hours 42 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/56">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1407401_6475</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/104f1f8d1ce8a5f7b68c8450605119af7ba3d328">104f1f8d1ce8a5f7b68c8450605119af7ba3d328</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cadd291d82bb2ab8d3a35381c47d97162eb97a91">cadd291d82bb2ab8d3a35381c47d97162eb97a91</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2435631399">EE Development Acceptance (master) - 55 - 2023-10-03[04:38:57]</a></p><details><summary><strong>ci:test:commerce-functional - 191 out of 196 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6475/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/874439/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358739/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/606884/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/794467/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/275799/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/270497/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274349/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/749190/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/761828/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/695188/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358737/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/761827/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/627300/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/770899/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/874437/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/749188/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280201/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/296829/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/627306/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358742/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/695190/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/299093/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373722/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/290277/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/290278/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/732918/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358738/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/627301/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/265984/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313579/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/299091/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/627302/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/732919/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/794466/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/278827/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/273298/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/240048/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/695189/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/874440/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/770902/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/290276/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-38. [...]

2023-10-03 16:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/6475/">test-portal-acceptance-pullrequest(master)#6475</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6475/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4278">liferay-commerce#4278</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2435658794">[master] ci:test:commerce-functional - Brunno0liveira &gt; liferay-commerce - PR#4278 - 2023-10-03[06:30:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/12022/">publish-testray-report#12022</a><br/></div></div>

2023-10-03 20:37 UTC, Brunno0liveira commented
ci:test:sf

2023-10-03 20:39 UTC, Brunno0liveira commented
ci:test:commerce-functional

2023-10-03 20:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7303/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7303/jenkins-report.html">here</a>.</b></p>

2023-10-03 20:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1990a27636d2e02a09d53d32fa1e8ef7717f35ea">1990a27636d2e02a09d53d32fa1e8ef7717f35ea</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Brunno0liveira/liferay-portal/tree/COMMERCE-12393">COMMERCE-12393</a><br/>Branch GIT ID: <a href="https://github.com/Brunno0liveira/liferay-portal/commit/54e323ade896c8a859a83e43c6c1f65677f9bddf">54e323ade896c8a859a83e43c6c1f65677f9bddf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7303/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7303/jenkins-report.html">here</a>.</h5></details></html>

2023-10-03 20:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7303/">test-portal-source-format#7303</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7303/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4278">liferay-commerce#4278</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2435807766">[master] ci:test:sf - Brunno0liveira &gt; liferay-commerce - PR#4278 - 2023-10-03[13:37:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/3668/">publish-testray-report#3668</a><br/></div></div>

2023-10-03 21:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/8001/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8001/jenkins-report.html">here</a>.</b></p>

2023-10-03 23:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 190 out of 196 jobs passed in 2 hours 3 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/57">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1307401_8001</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1990a27636d2e02a09d53d32fa1e8ef7717f35ea">1990a27636d2e02a09d53d32fa1e8ef7717f35ea</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/104f1f8d1ce8a5f7b68c8450605119af7ba3d328">104f1f8d1ce8a5f7b68c8450605119af7ba3d328</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2435759162">EE Development Acceptance (master) - 56 - 2023-10-03[08:40:24]</a></p><details><summary><strong>ci:test:commerce-functional - 190 out of 196 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/8001/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795370/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762648/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771763/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/273531/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313922/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/359700/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/875391/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/875392/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374658/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/718664/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795366/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628279/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795367/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/359697/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247045/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795368/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663942/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663943/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762650/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762651/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/276037/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/750084/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280491/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708539/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/282249/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/750082/"><strike>functional-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628280/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762647/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771762/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/628281/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/359698/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/278730/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280489/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/359699/">functional-tomcat90-mysql57-jdk8/1/8</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/795369/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/272264/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663939/">functional-tomcat90-mysql57-jdk8/1/11</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274579/">functional-tomcat90-mysql57-jdk8/1/12</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/247047/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/272263/">functional-tomcat90-mysql57-jdk8/1/14</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/663940/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href=" [...]

2023-10-03 23:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/8001/">test-portal-acceptance-pullrequest(master)#8001</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8001/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4278">liferay-commerce#4278</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2435963797">[master] ci:test:commerce-functional - Brunno0liveira &gt; liferay-commerce - PR#4278 - 2023-10-03[14:25:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/19295/">publish-testray-report#19295</a><br/></div></div>

2023-10-04 15:20 UTC, pietrobocale commented
Review Passed

Thanks!

2023-10-04 15:20 UTC, pietrobocale approved these changes

2023-10-04 15:22 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-10-04 15:22 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-10-04 15:23 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-36.liferay.com/job/forward-pullrequest/410//consoleFull)

2023-10-04 15:25 UTC, closed without merging

2023-10-04 15:25 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/141756
[Console](https://test-1-36.liferay.com/job/forward-pullrequest/410//consoleFull)