COMMERCE-12676 Add automation CannotAddToCartOptionWhenStockIsZeroAndBackOrderIsDisabled
liferay-commerce/liferay-portal pull request #4376
Opened 2023-10-27 06:12 UTC by jaydawu

https://liferay.atlassian.net/browse/COMMERCE-12678

2023-10-27 06:12 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-27 06:12 UTC, jaydawu commented
ci:test:sf

2023-10-27 06:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/6336/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/6336/jenkins-report.html">here</a>.</b></p>

2023-10-27 06:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/259e93090188cbf1a0ddca3d8d63a4b2d116212e">259e93090188cbf1a0ddca3d8d63a4b2d116212e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaydawu/liferay-portal/tree/COMMERCE-12676">COMMERCE-12676</a><br/>Branch GIT ID: <a href="https://github.com/jaydawu/liferay-portal/commit/3210a36ab167c72b11c1c04b2f0cc4b2ac979548">3210a36ab167c72b11c1c04b2f0cc4b2ac979548</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/6336/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/6336/jenkins-report.html">here</a>.</h5></details></html>

2023-10-27 06:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-source-format/6336/">test-portal-source-format#6336</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/6336/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4376">liferay-commerce#4376</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447701498">[master] ci:test:sf - jaydawu &gt; liferay-commerce - PR#4376 - 2023-10-26[23:13:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/4604/">publish-testray-report#4604</a><br/></div></div>

2023-10-27 11:02 UTC, lorenzolapescara requested changes

2023-10-27 11:02 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductDetails.testcase
> +		}
Can you use JSON macros instead? Thanks!

2023-10-30 18:03 UTC, lorenzolapescara commented
Manually forwarded.

2023-10-30 18:06 UTC, lorenzolapescara commented
ci:close

2023-10-30 18:06 UTC, closed without merging