COMMERCE-10079 Edit a product with options from Order Details page
liferay-commerce/liferay-portal pull request #4422
Opened 2023-11-07 14:49 UTC by 22LucaGiannotta22

https://liferay.atlassian.net/browse/COMMERCE-10079

Resent from #4377

2023-11-07 14:50 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-11-07 14:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/7533/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7533/jenkins-report.html">here</a>.</b></p>

2023-11-07 14:55 UTC, 22LucaGiannotta22 commented
ci:test:sf

2023-11-07 14:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fd0fb0a24b0b7f51f540a472e6ca61ebe7bde0ef">fd0fb0a24b0b7f51f540a472e6ca61ebe7bde0ef</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/22LucaGiannotta22/liferay-portal/tree/COMMERCE-10079">COMMERCE-10079</a><br/>Branch GIT ID: <a href="https://github.com/22LucaGiannotta22/liferay-portal/commit/ca46dcfa8d0e72a2facb2ba8dbba388468a59c22">ca46dcfa8d0e72a2facb2ba8dbba388468a59c22</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7533/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7533/jenkins-report.html">here</a>.</h5></details></html>

2023-11-07 15:36 UTC, baharturk requested changes
Please take a look at my comments. Thanks!

2023-11-07 15:36 UTC, baharturk commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceSKUs.macro
> +	@summary = "Default summary"
Can you update the summary by writing a description of what the macro is doing?

2023-11-07 15:36 UTC, baharturk commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceSKUs.macro
> +	macro editSkuName(skuERC = null) {
I guess you need to pass **productSku** instead of **skuERC**

2023-11-07 15:36 UTC, baharturk commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/FrontStore.macro
> +	macro editMiniCartItemOptionProduct(date = null, boolean = null, multipleSelectionValuesChecked = null, cartItemOptionName = null, multipleSelectionValuesNotChecked = null, numeric = null, cartItemO
The product option is being edited, right? We may name the macro like this:
**editMiniCartItemProductOption**

2023-11-07 15:36 UTC, baharturk commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/FrontStore.macro
> +	macro gotoEditMiniCartItemOptionProduct(cartItemSku = null) {
The product option is being targeted, right? We may name the macro like this:
gotoEditMiniCartItemProductOption

2023-11-07 15:36 UTC, baharturk commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/FrontStore.macro
> +	macro viewMiniCartEditOptionProduct(date = null, multipleSelectionValuesChecked = null, cartItemPromoPriceValue = null, cartItemPriceAsConfiguredValue = null, numeric = null, cartItemPriceValue = nu
The product option is being targeted, right? We may name the macro like this:
**viewMiniCartEditProductOption**

2023-11-07 15:36 UTC, baharturk commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/FrontStore.macro
>  	@summary = "Default summary"
You may also update the summary of these macros.

2023-11-07 15:36 UTC, baharturk commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceMiniCartEditBundledProducts.testcase
> +			FrontStore.gotoEditMiniCartItemOptionProduct(cartItemSku = "BLUE");
Please update macro names also here according to the changes that you make.

2023-11-07 16:06 UTC, baharturk requested changes

2023-11-07 16:06 UTC, baharturk commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommercePendingOrdersEditProductOptions.testcase
> +	test CanBuyerEditOnThePendingOrder {
CanBuyerEditProductOptionsOnThePendingOrder

2023-11-08 08:14 UTC, 22LucaGiannotta22 commented
ci:close

2023-11-08 08:14 UTC, closed without merging