COMMERCE-12431 OrgChart View/Edit Panel - Account + Automation
liferay-commerce/liferay-portal pull request #4441
Opened 2023-11-13 17:55 UTC by baharturk

Story: https://liferay.atlassian.net/browse/COMMERCE-12431

Test Plan: https://liferay.atlassian.net/browse/COMMERCE-12822

sent from: #4402

2023-11-13 17:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-11-13 17:56 UTC, baharturk commented
ci:test:sf

2023-11-13 18:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2141/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2141/jenkins-report.html">here</a>.</b></p>

2023-11-13 18:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cc7034192fede4a5dee2cad027c7a650e87456fe">cc7034192fede4a5dee2cad027c7a650e87456fe</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/baharturk/liferay-portal/tree/COMMERCE-12712-3">COMMERCE-12712-3</a><br/>Branch GIT ID: <a href="https://github.com/baharturk/liferay-portal/commit/1e389bf72aa09ebc8ee32e7d8152b70f800df0fd">1e389bf72aa09ebc8ee32e7d8152b70f800df0fd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2141/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2141/jenkins-report.html">here</a>.</h5></details></html>

2023-11-13 18:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2141/">test-portal-source-format#2141</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2141/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4441">liferay-commerce#4441</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2457823713">[master] ci:test:sf - baharturk &gt; liferay-commerce - PR#4441 - 2023-11-13[09:57:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8452/">publish-testray-report#8452</a><br/></div></div>

2023-11-14 14:34 UTC, lorenzolapescara requested changes

2023-11-14 14:34 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceWidget.macro
> +	macro searchAndGoToWidgetEntry(entryName = null) {
Be more specific in the macro name as it is focused on the Organization Management widget

2023-11-14 14:34 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceWidget.macro
> +		if (isSet(newAccountImage)) {
```suggestion
		if (isSet(accountImage)) {
```

2023-11-14 14:34 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceWidget.macro
> +		if (isSet(newAccountTaxID)) {
```suggestion
		if (isSet(accountTaxID)) {
```

2023-11-14 14:34 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceWidget.macro
> +		if (isSet(newAccountERC)) {
```suggestion
		if (isSet(accountERC)) {
```

2023-11-14 14:34 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceWidget.macro
> +		if (isSet(newAccountDescription)) {
```suggestion
		if (isSet(accountDescription)) {
```

2023-11-14 14:34 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceWidget.macro
> +				key_nodeName = ${currentAccountName},
```suggestion
				key_nodeName = ${accountName},
```

2023-11-14 14:34 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceOrganizationManagementWidget.testcase
> +	test CanUserEditAccountsDetailsFromOrganizationManagementChart {
```suggestion
	test CanUserEditAccountDetailsFromOrganizationManagementChart {
```

2023-11-14 14:34 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceOrganizationManagementWidget.testcase
> +				accountID = ${accountID},
these lines can be removed.

2023-11-14 14:34 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceOrganizationManagementWidget.testcase
> +				accountID = ${accountID},
these lines can be removed

2023-11-14 17:27 UTC, baharturk commented
ci:test:commerce-functional

2023-11-14 18:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/9684/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9684/jenkins-report.html">here</a>.</b></p>

2023-11-14 18:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fd1f94ff16d16aaf67c202b267cd325580c14048">fd1f94ff16d16aaf67c202b267cd325580c14048</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cc7034192fede4a5dee2cad027c7a650e87456fe">cc7034192fede4a5dee2cad027c7a650e87456fe</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2458019307">EE Development Acceptance (master) - 147 - 2023-11-13[12:40:33]</a></p><details><summary><strong>ci:test:commerce-functional - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/9684/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9684/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/9684/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/4441">baharturk/COMMERCE-12712-3</a></strong><pre>Unable to rebase master-temp-1699987645368 to master
Rebasing (1/13)
Rebasing (2/13)
Rebasing (3/13)
Rebasing (4/13)
Rebasing (5/13)
Rebasing (6/13)
Rebasing (7/13)
Rebasing (8/13)
Rebasing (9/13)
Rebasing (10/13)
error: could not apply 726bfdda98ec2... COMMERCE-12431 Autogenerated Code (buildLang)
Resolve all conflicts manually, mark them as resolved with
"git add/rm &lt;conflicted_files&gt;", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 726bfdda98ec2... COMMERCE-12431 Autogenerated Code (buildLang)</pre></p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-11-15 08:55 UTC, smottal commented
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/4451

2023-11-15 08:55 UTC, closed without merging