COMMERCE-4977 Create new Admin Shipment API
liferay-commerce/liferay-portal pull request #464
Opened 2020-12-22 15:52 UTC by riccardo-alberti

2020-12-22 15:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-12-22 15:52 UTC, riccardo-alberti commented
ci:test:sf

2020-12-22 15:53 UTC, riccardo-alberti commented
ci:test:relevant

2020-12-22 15:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/8719/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8719/jenkins-report.html">here</a>.</b></p>

2020-12-22 15:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/4886/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-portal-source-format/builds/4886/jenkins-report.html">here</a>.</b></p>

2020-12-22 16:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5964c801595c9ea44298d03a8b3edd52ccda9456">5964c801595c9ea44298d03a8b3edd52ccda9456</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/0045c28638a677aedc5411635e341681023a2800">0045c28638a677aedc5411635e341681023a2800</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/4886/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/4886/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-test/build.gradle expected:&lt;...tionCompile group: "[com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.10.3"
     [java] 	testIntegrationCompile group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.10.3"
     [java] 	testIntegrationCompile group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.10.3"
     [java] 	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
     [java] 	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.test", version: "default"
     [java] 	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.test.integration", version: "default"
     [java] 	testIntegrationCompile group: "commons-beanutils", name: "commons-beanutils", version: "1.9.4"
     [java] 	testIntegrationCompile group: "commons-lang", name: "commons-lang", version: "2.6"
     [java] 	testIntegrationCompile group: "javax.validation", name: "validation-api", version: "2.0.1.Final"
     [java] 	testIntegrationCompile group: "javax.ws.rs", name: "javax.ws.rs-api", version: "2.1"
     [java] 	testIntegrationCompile group: "junit", name: "junit", version: "4.13.1"
     [java] 	testIntegrationCompile project(":apps:asset:asset-test-util")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-account-api")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-account-test-util")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-api")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-currency-api")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-currency-test-util")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-discount-api")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-inventory-api")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-payment-api")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-payment-test-util")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-price-list-api")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-pricing-api")
     [java] 	testIntegrationCompile project(":apps:commerce:commerce-product-api")</code></pre></details></html>

2020-12-22 16:18 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-18.liferay.com/job/test-portal-source-format/4886/">test-portal-source-format#4886</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/4886/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/73688.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2020-12-22[07:53:10]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/16943/">publish-spira-report#16943</a><br />

2020-12-22 18:00 UTC, riccardo-alberti commented
ci:test:sf

2020-12-22 18:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-source-format/5309/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-source-format/builds/5309/jenkins-report.html">here</a>.</b></p>

2020-12-22 18:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5964c801595c9ea44298d03a8b3edd52ccda9456">5964c801595c9ea44298d03a8b3edd52ccda9456</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/fce8dd8f822f522affdf039fdea12d5ecc06ce15">fce8dd8f822f522affdf039fdea12d5ecc06ce15</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-source-format/5309/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/5309/jenkins-report.html">here</a>.</h5></details></html>

2020-12-22 18:14 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-23.liferay.com/job/test-portal-source-format/5309/">test-portal-source-format#5309</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/5309/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/73727.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2020-12-22[10:00:40]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/9948/">publish-spira-report#9948</a><br />

2020-12-22 18:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 7 out of 9 jobs passed</h3><h3>:x: ci:test:relevant - 20 out of 23 jobs passed in 2 hours 52 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/198c693cbd9cee7b50baa9b5843e2bec9323327a">198c693cbd9cee7b50baa9b5843e2bec9323327a</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/15218ef33680a1fe233ea812e8d097cfcb0feb42">15218ef33680a1fe233ea812e8d097cfcb0feb42</a></p><details><summary><strong>ci:test:stable - 7 out of 9 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430023/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448048/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448047/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7296/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482338/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460791/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/449939/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/420553/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/449941/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 20 out of 23 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/8719/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430023/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448048/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>20 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430025/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430024/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448047/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/459734/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/454997/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7296/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482338/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448050/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482337/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430022/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/472856/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460791/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/449940/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/324297/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/449939/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448049/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/420553/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372233/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448046/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/449941/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8719/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430023/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-7.liferay.com/job/test-portal [...]

2020-12-22 19:01 UTC, riccardo-alberti commented
ci:test:relevant

2020-12-22 19:05 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/8719/">test-portal-acceptance-pullrequest(master)#8719</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8719/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/73759.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2020-12-22[07:53:18]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/10607/">publish-spira-report#10607</a><br />

2020-12-22 19:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/3700/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3700/jenkins-report.html">here</a>.</b></p>

2020-12-22 20:18 UTC, dsitu requested changes

2020-12-22 20:18 UTC, dsitu commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-impl/src/main/java/com/liferay/headless/commerce/admin/shipment/internal/resource/v1_0/ShipmentResourceImpl.java
> +	public Shipment postShipmentDeliver(Long shipmentId) throws Exception {
```suggestion
	public Shipment postShipmentStatusDelivered(Long shipmentId) throws Exception {
```

2020-12-22 20:18 UTC, dsitu commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-impl/src/main/java/com/liferay/headless/commerce/admin/shipment/internal/resource/v1_0/ShipmentResourceImpl.java
> +	public Shipment postShipmentFinishProcessing(Long shipmentId)
```suggestion
	public Shipment postShipmentStatusFinishedProcessing(Long shipmentId)
```

2020-12-22 20:18 UTC, dsitu commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-impl/src/main/java/com/liferay/headless/commerce/admin/shipment/internal/resource/v1_0/ShipmentResourceImpl.java
> +	public Shipment postShipmentShip(Long shipmentId) throws Exception {
```suggestion
	public Shipment postShipmentStatusShipped(Long shipmentId) throws Exception {
```

2020-12-22 22:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 8 out of 9 jobs passed</h3><h3>:x: ci:test:relevant - 21 out of 23 jobs passed in 3 hours 24 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b6d6d3abf020d32a2071b2e575bf86f48bd2cc8c">b6d6d3abf020d32a2071b2e575bf86f48bd2cc8c</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/15218ef33680a1fe233ea812e8d097cfcb0feb42">15218ef33680a1fe233ea812e8d097cfcb0feb42</a></p><details><summary><strong>ci:test:stable - 8 out of 9 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448069/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>8 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482365/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/374259/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448068/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/420574/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/374255/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482369/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482366/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/374257/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 23 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/3700/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448069/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/314874/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/374258/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482365/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482370/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/410692/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/374259/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448068/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/344757/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/429072/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482368/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482363/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/420574/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/374256/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/314873/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/374255/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482367/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482369/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/429073/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482366/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482364/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/374257/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3700/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448069/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!mast [...]

2020-12-22 23:16 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/3700/">test-portal-acceptance-pullrequest(master)#3700</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3700/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/73831.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2020-12-22[11:31:29]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/10616/">publish-spira-report#10616</a><br />

2020-12-23 11:11 UTC, riccardo-alberti commented
ci:test:sf

2020-12-23 11:11 UTC, riccardo-alberti commented
ci:test:relevant

2020-12-23 11:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/2937/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-portal-source-format/builds/2937/jenkins-report.html">here</a>.</b></p>

2020-12-23 11:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/5126/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5126/jenkins-report.html">here</a>.</b></p>

2020-12-23 11:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5964c801595c9ea44298d03a8b3edd52ccda9456">5964c801595c9ea44298d03a8b3edd52ccda9456</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/5d936ebe8757866e3db0798f04e393096239296a">5d936ebe8757866e3db0798f04e393096239296a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/2937/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/2937/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Truncated message :
     [java] ./modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-impl/rest-openapi.yaml expected:&lt;...pments/\{shipmentId\}/[items:
     [java]         get:
     [java]             operationId: getShipmentItemsPage
     [java]             parameters:
     [java]                 - in: path
     [java]                   explode: false
     [java]                   name: shipmentId
     [java]                   required: true
     [java]                   schema:
     [java]                       description:
     [java]                           The shipment resource Id
     [java]                       example: 30130
     [java]                       format: int64
     [java]                       minimum: 0
     [java]                       type: integer
     [java]                   style: simple
     [java]                 - in: query
     [java]                   name: page
     [java]                   required: false
     [java]                   schema:
     [java]                       type: integer
     [java]                 - in: query
     [java]                   name: pageSize
     [java]                   required: false
     [java]                   schema:
     [java]                       type: integer
     [java]             responses:
     [java]                 200:
     [java]                     content:
     [java]                         application/json:
     [java]                             schema:
     [java]                                 items:
     [java]                                     \$ref: "#/components/schemas/ShipmentItem"
     [java]                                 type: array
     [java]                         application/xml:
     [java]                             schema:
     [java]                                 items:
     [java]                                     \$ref: "#/components/schemas/ShipmentItem"
     [java]                                 type: array
     [java]                     description:
     [java]                         Successful operation
     [java]                 400:
     [java]                     description:
     [java]                         Invalid input
     [java]                 401:
     [java]                     content:
     [java]                         application/json:
     [java]                             schema:</code></pre></details></html>

2020-12-23 11:20 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/test-portal-source-format/2937/">test-portal-source-format#2937</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/2937/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/74014.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2020-12-23[03:11:58]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/10647/">publish-spira-report#10647</a><br />

2020-12-23 11:34 UTC, riccardo-alberti commented
ci:test:sf

2020-12-23 11:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/4892/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-portal-source-format/builds/4892/jenkins-report.html">here</a>.</b></p>

2020-12-23 11:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b265d851edce5207d5da8198f1f01d96554e8499">b265d851edce5207d5da8198f1f01d96554e8499</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/38974ce1deccebd3029d5f055059f8e972c40778">38974ce1deccebd3029d5f055059f8e972c40778</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/4892/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/4892/jenkins-report.html">here</a>.</h5></details></html>

2020-12-23 11:46 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-18.liferay.com/job/test-portal-source-format/4892/">test-portal-source-format#4892</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/4892/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/74020.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2020-12-23[03:34:20]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-20.liferay.com/job/publish-spira-report/9054/">publish-spira-report#9054</a><br />

2020-12-23 14:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 8 out of 9 jobs passed</h3><h3>:x: ci:test:relevant - 21 out of 23 jobs passed in 3 hours 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b265d851edce5207d5da8198f1f01d96554e8499">b265d851edce5207d5da8198f1f01d96554e8499</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/15218ef33680a1fe233ea812e8d097cfcb0feb42">15218ef33680a1fe233ea812e8d097cfcb0feb42</a></p><details><summary><strong>ci:test:stable - 8 out of 9 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455077/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>8 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/429097/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/421467/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/399957/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460893/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/420648/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/459481/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/459480/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/314968/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 23 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/5126/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455077/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/420649/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/482421/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/429097/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448184/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212122/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/421467/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/399957/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/420650/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/212121/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460892/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/472931/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460893/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/399956/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/429098/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/420648/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455076/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/459481/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/314969/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/459480/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/472930/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/314968/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5126/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455077/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!mas [...]

2020-12-23 14:27 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/5126/">test-portal-acceptance-pullrequest(master)#5126</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5126/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/74061.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2020-12-23[03:12:09]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/10001/">publish-spira-report#10001</a><br />

2021-01-11 08:40 UTC, riccardo-alberti commented
ci:test:relevant

2021-01-11 08:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/5022/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5022/jenkins-report.html">here</a>.</b></p>

2021-01-11 11:27 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 7 out of 9 jobs passed</h3><h3>:x: ci:test:relevant - 20 out of 23 jobs passed in 2 hours 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f0d8da3d86724c398c4c31f4eee40287fb1f066">7f0d8da3d86724c398c4c31f4eee40287fb1f066</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/15218ef33680a1fe233ea812e8d097cfcb0feb42">15218ef33680a1fe233ea812e8d097cfcb0feb42</a></p><details><summary><strong>ci:test:stable - 7 out of 9 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460949/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460339/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/375349/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/345791/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450944/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460948/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460946/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460945/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461578/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 20 out of 23 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/5022/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460949/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460339/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>20 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/400914/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450943/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/375349/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319368/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461579/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/345791/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450944/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/375352/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/422199/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461577/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319369/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460948/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/345789/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/213265/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460946/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/213264/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/375351/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460945/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/316019/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461578/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5022/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460949/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-4.liferay.com/job/test-portal [...]

2021-01-11 11:47 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/5022/">test-portal-acceptance-pullrequest(master)#5022</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5022/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/77938.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2021-01-11[00:40:32]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/publish-spira-report/12804/">publish-spira-report#12804</a><br />

2021-01-11 12:01 UTC, riccardo-alberti commented
ci:test:relevant

2021-01-11 12:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/8147/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8147/jenkins-report.html">here</a>.</b></p>

2021-01-11 14:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 23 out of 23 jobs passed in 2 hours 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f0d8da3d86724c398c4c31f4eee40287fb1f066">7f0d8da3d86724c398c4c31f4eee40287fb1f066</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/15218ef33680a1fe233ea812e8d097cfcb0feb42">15218ef33680a1fe233ea812e8d097cfcb0feb42</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460359/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460977/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455957/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430943/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458957/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450976/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458959/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450785/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450787/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 23 jobs PASSED</strong></summary><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/8147/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460361/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460360/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460359/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430942/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458960/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460977/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455957/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460362/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458958/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450786/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/449227/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430943/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460976/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450788/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458957/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460358/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450976/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458959/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450789/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450785/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450784/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450787/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8147/jenkins-report.html">here</a>.</h5></details></html>

2021-01-11 15:11 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/8147/">test-portal-acceptance-pullrequest(master)#8147</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8147/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/78010.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2021-01-11[04:01:47]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/10727/">publish-spira-report#10727</a><br />

2021-02-08 09:15 UTC, riccardo-alberti commented
ci:test:sf

2021-02-08 09:15 UTC, riccardo-alberti commented
ci:test:relevant

2021-02-08 09:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/2591/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-source-format/builds/2591/jenkins-report.html">here</a>.</b></p>

2021-02-08 09:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/7699/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7699/jenkins-report.html">here</a>.</b></p>

2021-02-08 09:18 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/19d993d6e3c0dd6865924bf23f75992f52fc355e">19d993d6e3c0dd6865924bf23f75992f52fc355e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/7b442038eeaf6264757171598ad71ebe1862481a">7b442038eeaf6264757171598ad71ebe1862481a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2591/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2591/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-test/src/testIntegration/java/com/liferay/headless/commerce/admin/shipment/resource/v1_0/test/ShippingAddressResourceTest.java expected:&lt;...	\}
     [java] 
     [java] 	private static [final ]BeanUtilsBean _beanU...&gt; but was:&lt;...	\}
     [java] 
     [java] 	private static []BeanUtilsBean _beanU...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:445)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 1:22.840 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-15/job/test-portal-source-format/2591//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210208011806812.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210208011806812.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null160940365.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null398691995
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 195ms
[junitreport] Deleting: /tmp/null398691995
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 02-08-2021 01:18:12:275 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] </code></pre></details></html>

2021-02-08 09:20 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2591/">test-portal-source-format#2591</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2591/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/88132.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2021-02-08[01:15:24]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/15370/">publish-spira-report#15370</a><br />

2021-02-08 09:28 UTC, riccardo-alberti commented
ci:test:sf

2021-02-08 09:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/4906/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-source-format/builds/4906/jenkins-report.html">here</a>.</b></p>

2021-02-08 09:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/19d993d6e3c0dd6865924bf23f75992f52fc355e">19d993d6e3c0dd6865924bf23f75992f52fc355e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/d38b964b971b559ee2c94e5604b02e299f79326b">d38b964b971b559ee2c94e5604b02e299f79326b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4906/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4906/jenkins-report.html">here</a>.</h5></details></html>

2021-02-08 09:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/19d993d6e3c0dd6865924bf23f75992f52fc355e">19d993d6e3c0dd6865924bf23f75992f52fc355e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/19d993d6e3c0dd6865924bf23f75992f52fc355e">19d993d6e3c0dd6865924bf23f75992f52fc355e</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1524">Acceptance Upstream DXP (master) #1524</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/7699/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7699/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/7699/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:commerce:commerce-service:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-frontend-js:deploy
     [exec] Files of project ':apps:commerce:commerce-frontend-js' deployed to /opt/dev/projects/github/liferay-portal/bundles/osgi/modules
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-frontend-js:deployDependencies NO-SOURCE
     [exec] &gt; Task :apps:commerce:commerce-frontend-js:deployConfigs NO-SOURCE
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
     [exec] &gt; Task :apps:commerce:commerce-frontend-impl:jar
     [exec] &gt; Task :apps:commerce:commerce-frontend-impl:autoUpdateXml SKIPPED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-product-service:compileJava
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] Gradle build finished at 2021-02-08 09:36:15.576.
     [exec] 1504 actionable tasks: 1446 executed, 58 up-to-date
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-service:compileJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-service:compileJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:208)
     [exec] 	at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:263)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-02-08 09:48 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-impl/src/main/java/com/liferay/headless/commerce/admin/shipment/internal/resource/v1_0/ShipmentItemResourceImpl.java
> +			GetterUtil.get(
is it allowed to change warehouse ?

2021-02-08 09:55 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-impl/src/main/java/com/liferay/headless/commerce/admin/shipment/internal/util/v1_0/ShippingAddressUtil.java
> +	public static CommerceShipment upsertShippingAddress(
there is no insert method in this upsert

2021-02-08 10:12 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/7699/">test-portal-acceptance-pullrequest(master)#7699</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7699/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/88144.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2021-02-08[01:15:29]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/publish-spira-report/15159/">publish-spira-report#15159</a><br />

2021-02-08 10:15 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4906/">test-portal-source-format#4906</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4906/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/88147.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2021-02-08[01:28:58]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/15374/">publish-spira-report#15374</a><br />

2021-02-09 13:06 UTC, riccardo-alberti commented
ci:test:sf

2021-02-09 13:06 UTC, riccardo-alberti commented
ci:test:relevant

2021-02-09 13:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/3751/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-portal-source-format/builds/3751/jenkins-report.html">here</a>.</b></p>

2021-02-09 13:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/7347/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7347/jenkins-report.html">here</a>.</b></p>

2021-02-09 13:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/67e57d147b6b7f13bb101be79d43bd0a95148ab1">67e57d147b6b7f13bb101be79d43bd0a95148ab1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/b2f96670f4d20b65304764da02cf8053a9b544b4">b2f96670f4d20b65304764da02cf8053a9b544b4</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/3751/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/3751/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-test/build.gradle expected:&lt;...nd", version: "2.10.[5.1]"
     [java] 	testIntegrationCo...&gt; but was:&lt;...nd", version: "2.10.[3]"
     [java] 	testIntegrationCo...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:445)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 1:20.152 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-7/job/test-portal-source-format/3751//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210209050931471.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210209050931471.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1536121410.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null824172522
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 224ms
[junitreport] Deleting: /tmp/null824172522
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 02-09-2021 05:09:36:540 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] 
     [echo] Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)</code></pre></details></html>

2021-02-09 13:24 UTC, riccardo-alberti commented
ci:test:sf

2021-02-09 13:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 18 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1531">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1232004_7347</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/67e57d147b6b7f13bb101be79d43bd0a95148ab1">67e57d147b6b7f13bb101be79d43bd0a95148ab1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4318e2f9eb91ca3c0c74c377855994dac9dc8d80">4318e2f9eb91ca3c0c74c377855994dac9dc8d80</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1530">Acceptance Upstream DXP (master) #1530</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/7347/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7347/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/7347/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:commerce:commerce-service:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-product-taglib:jar
     [exec] &gt; Task :apps:commerce:commerce-product-taglib:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceRegionServiceImpl.java:65: error: cannot find symbol
     [exec] 		PortalPermissionUtil.check(
     [exec] 		^
     [exec]   symbol:   variable PortalPermissionUtil
     [exec]   location: class CommerceRegionServiceImpl
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
     [exec] 
     [exec] &gt; Task :apps:staging:staging-taglib:compileJSP
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-product-service:compileJava
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] Gradle build finished at 2021-02-09 13:23:45.490.
     [exec] 1434 actionable tasks: 1376 executed, 58 up-to-date
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-service:compileJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-service:compileJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:208)</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-02-09 13:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/4190/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-portal-source-format/builds/4190/jenkins-report.html">here</a>.</b></p>

2021-02-09 13:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/67e57d147b6b7f13bb101be79d43bd0a95148ab1">67e57d147b6b7f13bb101be79d43bd0a95148ab1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/b2f96670f4d20b65304764da02cf8053a9b544b4">b2f96670f4d20b65304764da02cf8053a9b544b4</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/4190/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/4190/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-test/build.gradle expected:&lt;...nd", version: "2.10.[5.1]"
     [java] 	testIntegrationCo...&gt; but was:&lt;...nd", version: "2.10.[3]"
     [java] 	testIntegrationCo...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:445)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 3:51.446 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-4/job/test-portal-source-format/4190//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210209052934870.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210209052934870.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null494835439.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null429338775
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 219ms
[junitreport] Deleting: /tmp/null429338775
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 02-09-2021 05:29:40:347 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] 
     [echo] Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)</code></pre></details></html>

2021-02-09 13:41 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/test-portal-source-format/4190/">test-portal-source-format#4190</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/4190/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/88833.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2021-02-09[05:24:31]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/19177/">publish-spira-report#19177</a><br />

2021-02-09 13:44 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/test-portal-source-format/4190/">test-portal-source-format#4190</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/4190/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/88833.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2021-02-09[05:24:31]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/19178/">publish-spira-report#19178</a><br />

2021-02-09 15:47 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-7.liferay.com/job/test-portal-source-format/3751/">test-portal-source-format#3751</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/3751/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/88909.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#464 - 2021-02-09[05:06:57]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/15490/">publish-spira-report#15490</a><br />

2021-02-09 16:36 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/7347/">test-portal-acceptance-pullrequest(master)#7347</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7347/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/88929.aspx">master - riccardo-alberti > liferay-commerce - PR#464 - 2021-02-09[05:07:05]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/publish-spira-report/15304/">publish-spira-report#15304</a><br />

2021-02-13 11:17 UTC, riccardo-alberti commented
ci:test:sf

2021-02-13 11:17 UTC, riccardo-alberti commented
ci:test:relevant

2021-02-13 11:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4279/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4279/jenkins-report.html">here</a>.</b></p>

2021-02-13 11:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/7377/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7377/jenkins-report.html">here</a>.</b></p>

2021-02-13 11:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7985dd55f78d0b4e4960d1b8b07158787e32d29f">7985dd55f78d0b4e4960d1b8b07158787e32d29f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/0c368e849324d03b18b77b288a2b1465ef38cae6">0c368e849324d03b18b77b288a2b1465ef38cae6</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4279/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4279/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-test/build.gradle expected:&lt;...nd", version: "2.10.[5.1]"
     [java] 	testIntegrationCo...&gt; but was:&lt;...nd", version: "2.10.[3]"
     [java] 	testIntegrationCo...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:445)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 1:23.455 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-8/job/test-portal-source-format/4279//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210213031952169.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210213031952169.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null579351648.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null518710677
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 236ms
[junitreport] Deleting: /tmp/null518710677
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 02-13-2021 03:19:57:025 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] 
     [echo] Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)</code></pre></details></html>

2021-02-13 11:22 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4279/">test-portal-source-format#4279</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4279/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/90851.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#464 - 2021-02-13[03:17:27]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/publish-spira-report/15630/">publish-spira-report#15630</a><br />

2021-02-13 11:23 UTC, riccardo-alberti commented
ci:test:sf

2021-02-13 11:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4280/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4280/jenkins-report.html">here</a>.</b></p>

2021-02-13 11:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7985dd55f78d0b4e4960d1b8b07158787e32d29f">7985dd55f78d0b4e4960d1b8b07158787e32d29f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/44f1d2231fc31a838b4a984d37d61f0d18241577">44f1d2231fc31a838b4a984d37d61f0d18241577</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4280/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4280/jenkins-report.html">here</a>.</h5></details></html>

2021-02-13 11:29 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4280/">test-portal-source-format#4280</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4280/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/90852.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#464 - 2021-02-13[03:23:52]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-20.liferay.com/job/publish-spira-report/11559/">publish-spira-report#11559</a><br />

2021-02-13 13:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 8 out of 9 jobs passed</h3><h3>:x: ci:test:relevant - 21 out of 23 jobs passed in 2 hours 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7985dd55f78d0b4e4960d1b8b07158787e32d29f">7985dd55f78d0b4e4960d1b8b07158787e32d29f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7985dd55f78d0b4e4960d1b8b07158787e32d29f">7985dd55f78d0b4e4960d1b8b07158787e32d29f</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1549">Acceptance Upstream DXP (master) #1549</a></p><details><summary><strong>ci:test:stable - 8 out of 9 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328459/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>8 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/434096/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319245/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/425433/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328460/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319244/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414476/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414474/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/462476/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 23 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/7377/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328459/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217074/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/425432/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/434096/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/404541/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/462477/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319245/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/425433/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464909/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414475/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/349291/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/349292/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328460/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217073/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/434097/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319244/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464908/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414476/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/404542/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414474/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217072/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/462476/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7377/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328459/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-ba [...]

2021-02-13 13:43 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/7377/">test-portal-acceptance-pullrequest(master)#7377</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7377/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/90857.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#464 - 2021-02-13[03:17:35]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/15802/">publish-spira-report#15802</a><br />

2021-02-13 13:50 UTC, riccardo-alberti commented
ci:test:relevant

2021-02-13 13:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest(master)/7878/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7878/jenkins-report.html">here</a>.</b></p>

2021-02-13 14:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7985dd55f78d0b4e4960d1b8b07158787e32d29f">7985dd55f78d0b4e4960d1b8b07158787e32d29f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7985dd55f78d0b4e4960d1b8b07158787e32d29f">7985dd55f78d0b4e4960d1b8b07158787e32d29f</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1549">Acceptance Upstream DXP (master) #1549</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7878/jenkins-report.html">here</a>.</h5></details></html>

2021-02-13 14:38 UTC, riccardo-alberti commented
ci:test:relevant

2021-02-13 14:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7583/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7583/jenkins-report.html">here</a>.</b></p>

2021-02-13 16:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 23 out of 23 jobs passed in 2 hours 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7985dd55f78d0b4e4960d1b8b07158787e32d29f">7985dd55f78d0b4e4960d1b8b07158787e32d29f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7985dd55f78d0b4e4960d1b8b07158787e32d29f">7985dd55f78d0b4e4960d1b8b07158787e32d29f</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1549">Acceptance Upstream DXP (master) #1549</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464913/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/487814/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464917/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458959/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217085/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414488/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/379010/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319254/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217086/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 23 jobs PASSED</strong></summary><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7583/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319257/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464915/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464913/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319256/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/379009/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/487814/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464917/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328470/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/379011/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319255/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217087/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458959/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464914/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464916/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217085/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/487813/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414488/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/379010/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319258/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/319254/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/487812/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217086/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7583/jenkins-report.html">here</a>.</h5></details></html>

2021-02-13 16:51 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7583/">test-portal-acceptance-pullrequest(master)#7583</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7583/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/90885.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#464 - 2021-02-13[06:38:25]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/13841/">publish-spira-report#13841</a><br />

2021-02-16 08:30 UTC, riccardo-alberti commented
ci:foward

2021-02-16 17:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-02-16 17:07 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`

2021-02-16 17:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/2747/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-portal-source-format/builds/2747/jenkins-report.html">here</a>.</b></p>

2021-02-16 17:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1cb9c4712f1b534ab0c278cb2abfbaa8ea0921e1">1cb9c4712f1b534ab0c278cb2abfbaa8ea0921e1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/PR-383">PR-383</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/82f2ba156dffbcdc6975b426cce7c1c469c19ffa">82f2ba156dffbcdc6975b426cce7c1c469c19ffa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/2747/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/2747/jenkins-report.html">here</a>.</h5></details></html>

2021-02-16 17:11 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pullrequest to `brianchandotcom`.

2021-02-16 17:11 UTC, closed without merging

2021-02-16 18:02 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/test-portal-source-format/2747/">test-portal-source-format#2747</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/2747/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/464">liferay-commerce#464</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/91557.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#464 - 2021-02-16[09:07:49]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/13944/">publish-spira-report#13944</a><br />