LPD-13526 new option type select date
liferay-commerce/liferay-portal pull request #4814
Opened 2024-03-27 16:14 UTC by andrea-ale-sbarra

https://liferay.atlassian.net/browse/LPD-13526

resend of https://github.com/liferay-commerce/liferay-portal/pull/4643

2024-03-27 16:14 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-03-27 16:15 UTC, andrea-ale-sbarra commented
ci:test:sf

2024-03-27 16:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/3743/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3743/jenkins-report.html">here</a>.</b></p>

2024-03-27 16:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b0a65b966c0bb09611defbe0eb3bb89caf8969d6">b0a65b966c0bb09611defbe0eb3bb89caf8969d6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/LPD-13526-as">LPD-13526-as</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/929fafc30986ffdd7981a9a3f677ee4c04bfa872">929fafc30986ffdd7981a9a3f677ee4c04bfa872</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3743/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3743/jenkins-report.html">here</a>.</h5><pre>     [exec]   72:5  error  Expected object keys to be in natural ascending order. 'day' should be before 'month'.  sort-keys
     [exec]   89:4  error  Expected blank line before this statement.  padding-line-between-statements
     [exec] 
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/edit_cp_option_and_value.js
     [exec]   63:5  error  Expected object keys to be in natural ascending order. 'month' should be before 'year'.  sort-keys
     [exec]   64:5  error  Expected object keys to be in natural ascending order. 'day' should be before 'month'.  sort-keys
     [exec]   81:4  error  Expected blank line before this statement.  padding-line-between-statements
     [exec] 
     [exec] ��� 7 problems (7 errors, 0 warnings)
     [exec]   3 errors and 0 warnings potentially fixable with the `--fix` option.
     [exec] 
     [exec] 2 of 3 jobs failed
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-03-27 16:21:29.165.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-03-27 16:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3743/">test-portal-source-format#3743</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3743/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4814">liferay-commerce#4814</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2555569186">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#4814 - 2024-03-27[09:15:59]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2555569186<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/24918/">publish-testray-report#24918</a><br/></div></div>

2024-03-28 14:26 UTC, andrea-ale-sbarra commented
ci:test:sf

2024-03-28 14:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/7111/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/7111/jenkins-report.html">here</a>.</b></p>

2024-03-28 14:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/30a66cf65b7407cfeafd34716d826bfb166f97cc">30a66cf65b7407cfeafd34716d826bfb166f97cc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/LPD-13526-as">LPD-13526-as</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/e8d19afe714a62cc08694a155711a3e9db6a9244">e8d19afe714a62cc08694a155711a3e9db6a9244</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/7111/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/7111/jenkins-report.html">here</a>.</h5></details></html>

2024-03-28 15:39 UTC, smottal requested changes

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_cp_definition_option_value_rel.jspf
> +			optionValueSelectDateObj.setTime(slugify.default(timeInput.value));
remove empty line

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_cp_definition_option_value_rel.jspf
> +			optionValueSelectDateObj.setDurationType(durationTypeInput.value);
remove empty line

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_cp_definition_option_value_rel.jspf
> +					month: 'long',
numeric

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-options-web/src/main/java/com/liferay/commerce/product/options/web/internal/display/context/CPOptionDisplayContext.java
> +		if (cpOptionSelectDate) {
inline please

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-options-web/src/main/java/com/liferay/commerce/product/options/web/internal/display/context/CPOptionValueDisplayContext.java
> +		if (splits.length > 8) {
buy space

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-options-web/src/main/java/com/liferay/commerce/product/options/web/internal/portlet/action/AddCPOptionValueMVCRenderCommand.java
> +			CPOption cpOption = _cpOptionService.fetchCPOption(cpOptionId);
why fetch and not get?

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-options-web/src/main/java/com/liferay/commerce/product/options/web/internal/portlet/action/EditCPOptionValueMVCActionCommand.java
> +			String timeZone = ParamUtil.getString(actionRequest, "timezone");
timezone or timeZone?

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/add_cp_option_value.js
> +
no empty line

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/add_cp_option_value.js
> +	const labelInput = form.querySelector( '#'+namespace+'optionValueSelectDateLabel' );
sort these

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/add_cp_option_value.js
> +			optionValueSelectDateObj.setDurationType(durationTypeInput.value);
no empty line

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/edit_cp_option_and_value.js
> +	const labelInput = form.querySelector( '#'+namespace+'optionValueSelectDateLabel' );
sort

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionOptionValueRelLocalServiceImpl.java
> +		if (splits.length > 8) {
buy space

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-delivery-catalog-impl/src/main/java/com/liferay/headless/commerce/delivery/catalog/internal/dto/v1_0/converter/ProductOptionValueDTOConverter.java
> +								StringPool.CLOSE_PARENTHESIS, StringPool.SPACE,
check if comma needed

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-test/src/testIntegration/java/com/liferay/commerce/product/service/test/CPDefinitionOptionValueRelLocalServiceTest.java
> +		_addCPDefinitionWitOptionValue("2024-03-18-16-45-1-xyz-europe-paris");
right format with only the wrong field

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-test/src/testIntegration/java/com/liferay/commerce/product/service/test/CPDefinitionOptionValueRelLocalServiceTest.java
> +			CPConstants.PRODUCT_OPTION_SELECT_DATE_KEY, false);
valuate if pass the type of field as parameter

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-test/src/testIntegration/java/com/liferay/commerce/product/service/test/CPOptionValueLocalServiceTest.java
> +		_addCPOptionWitCPOptionValue("2024-03-aa-16-45-1-hours-europe-paris");
right format with only the wrong field

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-test/src/testIntegration/java/com/liferay/commerce/product/service/test/CPOptionValueLocalServiceTest.java
> +		_addCPOptionWitCPOptionValue("2024-03-18-16-45-1-xyz-europe-paris");
right format with only the wrong field

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-test/src/testIntegration/java/com/liferay/commerce/product/service/test/CPOptionValueLocalServiceTest.java
> +		_addCPOptionWitCPOptionValue("2024-03-18-16:45-1-hours-europe-paris");
right format with only the wrong field

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-test/src/testIntegration/java/com/liferay/commerce/product/service/test/CPOptionValueLocalServiceTest.java
> +		CPOption cpOption = CPTestUtil.addCPOption(
valuate if the type can be passed as parameter

2024-03-28 15:39 UTC, smottal commented on modules/apps/commerce/commerce-product-test/src/testIntegration/java/com/liferay/commerce/product/service/test/CPOptionValueLocalServiceTest.java
> +	private static User _user;
why static?

2024-03-29 13:43 UTC, alessiorendina requested changes
Hey @andrea-ale-sbarra in addition to @smottal requested changes, I also added some  comments. Please make sure to check them out, thank you!

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/option/DateCommerceOptionTypeImpl.java
> +	public static final String KEY = CPConstants.PRODUCT_OPTION_DATE_KEY;
You can directly use the constant instead of initializing a new one

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/option/NumericCommerceOptionTypeImpl.java
> +	public static final String KEY = CPConstants.PRODUCT_OPTION_NUMERIC_KEY;
You can directly use the constant instead of initializing a new one

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/option/RadioCommerceOptionTypeImpl.java
> +	public static final String KEY = CPConstants.PRODUCT_OPTION_RADIO_KEY;
You can directly use the constant instead of initializing a new one

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/option/SelectCommerceOptionTypeImpl.java
> +	public static final String KEY = CPConstants.PRODUCT_OPTION_SELECT_KEY;
You can directly use the constant instead of initializing a new one

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/option/SelectDateCommerceOptionTypeImpl.java
> +	public static final String KEY = CPConstants.PRODUCT_OPTION_SELECT_DATE_KEY;
You can directly use the constant instead of initializing a new one

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/option/TextCommerceOptionTypeImpl.java
> +	public static final String KEY = CPConstants.PRODUCT_OPTION_TEXT_KEY;
You can directly use the constant instead of initializing a new one

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-api/src/main/java/com/liferay/commerce/product/constants/CPConstants.java
> +		"select", "select_date", "radio"
You can use the constants here

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-api/src/main/java/com/liferay/commerce/product/constants/CPConstants.java
>  		"checkbox", "checkbox_multiple", "radio", "select", "select_date"
You can use the constants here

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-api/src/main/java/com/liferay/commerce/product/constants/CPConstants.java
>  		{"select", "radio"};
You can use the constants here

2024-03-29 13:43 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/display/context/CPDefinitionOptionValueRelDisplayContext.java
> +		if (cpDefinitionOptionRelSelectDate) {
You should be able to directly return

```
Objects.equals(
			SelectDateCommerceOptionTypeImpl.KEY,
			cpDefinitionOptionRel.getCommerceOptionTypeKey());
```

2024-03-29 15:35 UTC, andrea-ale-sbarra commented
ci:test:sf

2024-04-02 10:47 UTC, andrea-ale-sbarra commented
ci:test:sf

2024-04-02 10:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7602/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7602/jenkins-report.html">here</a>.</b></p>

2024-04-02 10:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d6e26f225c136ed7f27560b2e600be32d2100b8b">d6e26f225c136ed7f27560b2e600be32d2100b8b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/LPD-13526-as">LPD-13526-as</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/a4e7fdd5bb35bb4241d8718007c70deec8c449f8">a4e7fdd5bb35bb4241d8718007c70deec8c449f8</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7602/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7602/jenkins-report.html">here</a>.</h5><pre>     [exec] warning Resolution field "webpack@5.89.0" is incompatible with requested version "webpack@5.76.0"
     [exec] success Already up-to-date.
     [exec] Done in 1.86s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/add_cp_option_value.js: BAD
     [exec] apps/commerce/commerce-product-options-web/src/main/resources/META-INF/resources/js/edit_cp_option_and_value.js: BAD
     [exec] Prettier checked 7 files, 2 files have problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-04-02 10:55:27.794.
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2024-04-02-03-55-03.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-04-02 10:58 UTC, andrea-ale-sbarra commented
ci:test:sf

2024-04-02 11:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/7073/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7073/jenkins-report.html">here</a>.</b></p>

2024-04-02 11:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7602/">test-portal-source-format#7602</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7602/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4814">liferay-commerce#4814</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2557636634">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#4814 - 2024-04-02[03:49:43]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2557636634<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/3964/">publish-testray-report#3964</a><br/></div></div>

2024-04-02 11:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d6e26f225c136ed7f27560b2e600be32d2100b8b">d6e26f225c136ed7f27560b2e600be32d2100b8b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/LPD-13526-as">LPD-13526-as</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/1f184b9e4bcb2bab8fb769574ee5d3b58f01e47a">1f184b9e4bcb2bab8fb769574ee5d3b58f01e47a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7073/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7073/jenkins-report.html">here</a>.</h5></details></html>

2024-04-02 11:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7073/">test-portal-source-format#7073</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7073/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4814">liferay-commerce#4814</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2557636674">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#4814 - 2024-04-02[03:59:24]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2557636674<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/4681/">publish-testray-report#4681</a><br/></div></div>

2024-04-02 12:13 UTC, andrea-ale-sbarra commented
ci:test:relevant

2024-04-02 14:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/5659/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5659/jenkins-report.html">here</a>.</b></p>

2024-04-02 18:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 34 out of 34 jobs passed</h3><h3>:x: ci:test:relevant - 372 out of 412 jobs passed in 4 hours 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b1d9bc8ed395c607d366b2efb0c53d6a75586237">b1d9bc8ed395c607d366b2efb0c53d6a75586237</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d6e26f225c136ed7f27560b2e600be32d2100b8b">d6e26f225c136ed7f27560b2e600be32d2100b8b</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2557831736">EE Development Acceptance (master) - 467 - 2024-04-02[04:39:02]</a></p><details><summary><strong>ci:test:stable - 34 out of 34 jobs PASSED</strong></summary><details><summary><strong>34 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 372 out of 412 jobs PASSED</strong></summary><div><h4>40 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/5659/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326142/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358623/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354941/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381366/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/847946/"><strike>functional-smoke-tomcat90-hypersonic20-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387113/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/310417/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354943/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/864510/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383567/">functional-smoke-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/566277/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354481/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/360698/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/854145/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/310418/">functional-tomcat90-mysql57-chrome100-jdk8/1/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/413731/">functional-tomcat90-mysql57-chrome100-jdk8/1/1</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381364/">functional-tomcat90-mysql57-chrome100-jdk8/1/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/566289/">functional-tomcat90-mysql57-chrome100-jdk8/1/3</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374534/">functional-tomcat90-mysql57-chrome100-jdk8/1/4</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354950/">functional-tomcat90-mysql57-chrome100-jdk8/1/5</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383561/">functional-tomcat90-mysql57-chrome100-jdk8/1/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/410438/">functional-tomcat90-mysql57-chrome100-jdk8/1/7</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354901/">functional-tomcat90-mysql57-chrome100-jdk8/1/8</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358629/">functional-tomcat90-mysql57-chrome100-jdk8/1/9</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354895/">functional-tomcat90-mysql57-chrome100-jdk8/1/10</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374529/">functional-tomcat90-mysql57-chrome100-jdk8/1/11</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358624/">functional-tomcat90-mysql57-chrome100-jdk8/1/12</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354476/">functional-tomcat90-mysql57-chrome100-jdk8/1/13</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383556/">functional-tomcat90-mysql57-chrome100-jdk8/1/14</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374530/">functional-tomcat90-mysql57-chrome100-jdk8/1/15</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358625/">functional-tomcat90-mysql57-chrome100-jdk8/1/16</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354896/">functional-tomcat90-mysql57-chrome100-jdk8/1/17</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/354477/">functional-tomcat90-mysql57-chrome100-jdk8/1/18</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357472/">functional-tomcat90-mysql57-chrome100-jdk8/1/19</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/413725/">functional-tomcat90-mysql57-chrome100-jdk8/1/20</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/310413/">functional-tomcat90-mysql57-chrome100-jdk8 [...]

2024-04-02 18:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/5659/">test-portal-acceptance-pullrequest(master)#5659</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5659/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4814">liferay-commerce#4814</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2557860293">[master] ci:test:relevant - andrea-ale-sbarra &gt; liferay-commerce - PR#4814 - 2024-04-02[07:15:59]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2557860293<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/12362/">publish-testray-report#12362</a><br/></div></div>

2024-04-03 09:02 UTC, andrea-ale-sbarra commented
ci:test:sf

2024-04-03 09:02 UTC, andrea-ale-sbarra commented
ci:test:relevant

2024-04-03 09:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/4876/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4876/jenkins-report.html">here</a>.</b></p>

2024-04-03 09:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/4876/">test-portal-source-format#4876</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4876/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4814">liferay-commerce#4814</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2558104873">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#4814 - 2024-04-03[02:04:30]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2558104873<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/19000/">publish-testray-report#19000</a><br/></div></div>

2024-04-03 12:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5488/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5488/jenkins-report.html">here</a>.</b></p>

2024-04-03 15:44 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 82 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ddc4622fcc071bf96902e2101d368ad3549e65c9">ddc4622fcc071bf96902e2101d368ad3549e65c9</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5488/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5488/jenkins-report.html">here</a>.</b></p>

2024-04-03 15:49 UTC, andrea-ale-sbarra commented
ci:test:relevant

2024-04-03 15:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5488/">test-portal-acceptance-pullrequest(master)#5488</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5488/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4814">liferay-commerce#4814</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2558203648">[master] ci:test:relevant - andrea-ale-sbarra &gt; liferay-commerce - PR#4814 - 2024-04-03[05:10:06]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2558203648<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/12060/">publish-testray-report#12060</a><br/></div></div>

2024-04-03 15:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6464195a5db935c082cd8ffa77c9a7b72acec278">6464195a5db935c082cd8ffa77c9a7b72acec278</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/LPD-13526-as">LPD-13526-as</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/0a9f6d5c41d1d21e510a25cb394dfa750be3bd40">0a9f6d5c41d1d21e510a25cb394dfa750be3bd40</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7563/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7563/jenkins-report.html">here</a>.</h5></details></html>

2024-04-03 15:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7563/">test-portal-source-format#7563</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7563/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/4814">liferay-commerce#4814</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2558208385">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#4814 - 2024-04-03[08:49:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2558208385<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4817/">publish-testray-report#4817</a><br/></div></div>

2024-04-04 16:08 UTC, andrea-ale-sbarra commented
sent here https://github.com/liferay-commerce/liferay-portal/pull/4837

2024-04-04 16:08 UTC, closed without merging