LPD-13526 new option type
liferay-commerce/liferay-portal pull request #4833
Opened 2024-04-04 05:12 UTC by bryceosterhaus

2024-04-04 05:12 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-04-04 07:23 UTC, andrea-ale-sbarra commented
cool, I'll send this to Brian, thank you!

2024-04-04 08:57 UTC, andrea-ale-sbarra requested changes
moreover I found there is some more js in the jsp file:

<img width="1676" alt="Screenshot 2024-04-04 at 10 44 28" src="https://github.com/liferay-commerce/liferay-portal/assets/580733/3d168ec7-f219-49d0-9552-347ab7cd59ae">

2024-04-04 08:57 UTC, andrea-ale-sbarra commented on modules/apps/commerce/commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_cp_definition_option_value_rel.jspf
> +	<liferay-frontend:components
ehy @bryceosterhaus I was testing this PR locally and I found some issues that make us think it's safer for everybody to merge your changes after our PRs.
See:
I found this issue with this change of yours:

<img width="1239" alt="Screenshot 2024-04-04 at 10 40 40" src="https://github.com/liferay-commerce/liferay-portal/assets/580733/4cea9562-9ab3-401b-9b83-a337b52bfcbe">

this I think should be 
```suggestion
<liferay-frontend:component
```
and even with the suggested change I found this issue:

<img width="1676" alt="Screenshot 2024-04-04 at 10 44 00" src="https://github.com/liferay-commerce/liferay-portal/assets/580733/40c9c244-2a9f-41c3-b973-8a99bcfd56bc">

this is not working and we have no bandwidth to fix this issues too.

2024-04-04 10:11 UTC, andrea-ale-sbarra commented
see here for fixes https://github.com/liferay-commerce/liferay-portal/pull/4834

2024-04-05 05:53 UTC, bryceosterhaus commented
@andrea-ale-sbarra if my changes are causing issues for you, you can just drop my commit. I will fix it in my PR after your changes are merged.

2024-05-22 15:20 UTC, closed without merging