LPD-28159 - Refactor of poshi test Account#AccountGroupsAreDisplayedInAccountDetailsPage
liferay-commerce/liferay-portal pull request #5023
Opened 2024-06-10 13:21 UTC by brbalazs

https://liferay.atlassian.net/browse/LPD-28159

2024-06-10 13:21 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-06-10 13:21 UTC, brbalazs commented
ci:test:sf

2024-06-10 13:22 UTC, brbalazs commented
ci:test:stop

2024-06-10 13:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3472/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3472/jenkins-report.html">here</a>.</b></p>

2024-06-10 13:27 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/14288b1f8b2c29bbadcc79b3086a1aefd0f2269a">14288b1f8b2c29bbadcc79b3086a1aefd0f2269a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brbalazs/liferay-portal/tree/LPD-28159">LPD-28159</a><br/>Branch GIT ID: <a href="https://github.com/brbalazs/liferay-portal/commit/d12d2570e3896b4e6498bc28913a327e1f48da8f">d12d2570e3896b4e6498bc28913a327e1f48da8f</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3472/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3472/jenkins-report.html">here</a>.</h5><pre>     [exec] 
     [exec] added 2648 packages, and audited 2649 packages in 12s
     [exec] 
     [exec] 210 packages are looking for funding
     [exec]   run `npm fund` for details
     [exec] 
     [exec] 95 vulnerabilities (4 low, 38 moderate, 28 high, 25 critical)
     [exec] 
     [exec] To address issues that do not require attention, run:
     [exec]   npm audit fix
     [exec] 
     [exec] To address all issues (including breaking changes), run:
     [exec]   npm audit fix --force
     [exec] 
     [exec] Run `npm audit` for details.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] 
     [exec] &gt; @liferay/playwright@1.0.0 checkFormat
     [exec] &gt; tsc &amp;&amp; liferay-npm-scripts lint &amp;&amp; liferay-npm-scripts format:check
     [exec] 
     [exec] 
     [exec] tests/account-admin-web/accountGroups.spec.ts: BAD
     [exec] Prettier checked 546 files, 1 file has problems
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-06-10 13:26:37.188.
     [exec] 3 actionable tasks: 3 executed
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/modules/test/playwright/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-06-10 13:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3472/">test-portal-source-format#3472</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3472/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5023">liferay-commerce#5023</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/13739573">[master] ci:test:sf - brbalazs &gt; liferay-commerce - PR#5023 - 2024-06-10[06:22:10]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>13739573<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/13771/">publish-testray-report#13771</a><br/></div></div>

2024-06-10 14:01 UTC, brbalazs commented
ci:test:sf

2024-06-10 14:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/14288b1f8b2c29bbadcc79b3086a1aefd0f2269a">14288b1f8b2c29bbadcc79b3086a1aefd0f2269a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brbalazs/liferay-portal/tree/LPD-28159">LPD-28159</a><br/>Branch GIT ID: <a href="https://github.com/brbalazs/liferay-portal/commit/0d11e8a2e43d7d333d6911d8b08037b0b6c4d8bd">0d11e8a2e43d7d333d6911d8b08037b0b6c4d8bd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8654/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8654/jenkins-report.html">here</a>.</h5></details></html>

2024-06-10 14:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8654/">test-portal-source-format#8654</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8654/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5023">liferay-commerce#5023</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/13769353">[master] ci:test:sf - brbalazs &gt; liferay-commerce - PR#5023 - 2024-06-10[07:02:25]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>13769353<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/32709/">publish-testray-report#32709</a><br/></div></div>

2024-06-11 11:29 UTC, brbalazs commented
ci:test:playwright

2024-06-11 11:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/9587/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9587/jenkins-report.html">here</a>.</b></p>

2024-06-11 13:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/9587/">test-portal-acceptance-pullrequest(master)#9587</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9587/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5023">liferay-commerce#5023</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/14622620">[master] ci:test:playwright - brbalazs &gt; liferay-commerce - PR#5023 - 2024-06-11[04:29:46]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>14622620<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/21177/">publish-testray-report#21177</a><br/></div></div>

2024-06-11 15:39 UTC, smottal requested changes

2024-06-11 15:39 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accountGroups.spec.ts
> +
no empty line

2024-06-11 15:39 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accountGroups.spec.ts
> +
no empty line

2024-06-11 15:39 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accountGroups.spec.ts
> +		page.getByText(accountGroup1.name, {exact: true})
can you add a dynamic locator (so a function - we have already example) in the page and in the test call it passing the name? I don't like to have the locators (so the .getBy***) in the tests - and you can call the same dynamic locator three times with the three different account groups

2024-06-11 15:39 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accountGroups.spec.ts
> +	await apiHelpers.headlessAdminUser.assignAccountToAccountGroup(
because you have to touch the test can you move this after the creation? 
so create1 + data push1 + assign1 / create2 + data push2 + assign2 ...

2024-06-11 15:40 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accountGroups.spec.ts
> +	await apiHelpers.headlessAdminUser.assignAccountToAccountGroup(
@brbalazs is fine, just very little things

2024-06-12 08:26 UTC, brbalazs commented
ci:test:sf

2024-06-12 08:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/6329/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6329/jenkins-report.html">here</a>.</b></p>

2024-06-12 08:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0028e9ea6a713f318f9eef73ecdd2473c93e2f20">0028e9ea6a713f318f9eef73ecdd2473c93e2f20</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brbalazs/liferay-portal/tree/LPD-28159">LPD-28159</a><br/>Branch GIT ID: <a href="https://github.com/brbalazs/liferay-portal/commit/6901a90d3345510b2096a86cea4e82fe7d3ce944">6901a90d3345510b2096a86cea4e82fe7d3ce944</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/6329/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/6329/jenkins-report.html">here</a>.</h5><pre>     [exec] 
     [exec] added 2648 packages, and audited 2649 packages in 21s
     [exec] 
     [exec] 210 packages are looking for funding
     [exec]   run `npm fund` for details
     [exec] 
     [exec] 109 vulnerabilities (2 low, 32 moderate, 50 high, 25 critical)
     [exec] 
     [exec] To address issues that do not require attention, run:
     [exec]   npm audit fix
     [exec] 
     [exec] To address all issues (including breaking changes), run:
     [exec]   npm audit fix --force
     [exec] 
     [exec] Run `npm audit` for details.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] 
     [exec] &gt; @liferay/playwright@1.0.0 checkFormat
     [exec] &gt; tsc &amp;&amp; liferay-npm-scripts lint &amp;&amp; liferay-npm-scripts format:check
     [exec] 
     [exec] 
     [exec] tests/account-admin-web/accountGroups.spec.ts: BAD
     [exec] Prettier checked 550 files, 1 file has problems
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-06-12 08:35:26.741.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/modules/test/playwright/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-06-12 08:40 UTC, brbalazs commented
ci:test:sf

2024-06-12 08:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0028e9ea6a713f318f9eef73ecdd2473c93e2f20">0028e9ea6a713f318f9eef73ecdd2473c93e2f20</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brbalazs/liferay-portal/tree/LPD-28159">LPD-28159</a><br/>Branch GIT ID: <a href="https://github.com/brbalazs/liferay-portal/commit/973805b8f04d6a24871bfe9a94abecc1b25a1006">973805b8f04d6a24871bfe9a94abecc1b25a1006</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7799/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7799/jenkins-report.html">here</a>.</h5></details></html>

2024-06-12 08:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7799/">test-portal-source-format#7799</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7799/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5023">liferay-commerce#5023</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/15608666">[master] ci:test:sf - brbalazs &gt; liferay-commerce - PR#5023 - 2024-06-12[01:40:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>15608666<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4166/">publish-testray-report#4166</a><br/></div></div>

2024-06-12 12:13 UTC, smottal requested changes

2024-06-12 12:13 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accountGroups.spec.ts
> +
no, this should not go here: it should go inside the accountsPage but as a "dynamic locator". Have a look to `modules/test/playwright/pages/account-admin-web/EditAccountContactAddressPage.ts` for the addressDisplay

2024-06-12 14:13 UTC, smottal approved these changes

2024-06-12 14:14 UTC, brbalazs commented
ci:test:sf

2024-06-12 14:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/5505/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5505/jenkins-report.html">here</a>.</b></p>

2024-06-12 14:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0028e9ea6a713f318f9eef73ecdd2473c93e2f20">0028e9ea6a713f318f9eef73ecdd2473c93e2f20</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brbalazs/liferay-portal/tree/LPD-28159">LPD-28159</a><br/>Branch GIT ID: <a href="https://github.com/brbalazs/liferay-portal/commit/2dfd2410a8b5a5e0c80c346df574a15c380d7333">2dfd2410a8b5a5e0c80c346df574a15c380d7333</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5505/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5505/jenkins-report.html">here</a>.</h5></details></html>

2024-06-12 14:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5505/">test-portal-source-format#5505</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5505/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5023">liferay-commerce#5023</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/15758929">[master] ci:test:sf - brbalazs &gt; liferay-commerce - PR#5023 - 2024-06-12[07:14:18]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>15758929<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/20979/">publish-testray-report#20979</a><br/></div></div>

2024-06-14 08:07 UTC, smottal commented
ci:forward

2024-06-14 08:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-06-14 08:07 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-06-14 08:13 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-6.liferay.com/job/forward-pullrequest/577//consoleFull)

2024-06-14 08:13 UTC, closed without merging

2024-06-14 08:13 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/151390
[Console](https://test-1-6.liferay.com/job/forward-pullrequest/577//consoleFull)