LPD-28161 - Refactor Account#CanViewRoleAndOrganizationsPrintedAsScript as a playwright test
liferay-commerce/liferay-portal pull request #5038
Opened 2024-06-12 13:48 UTC by matyaswollner

https://liferay.atlassian.net/browse/LPD-28161

2024-06-12 13:48 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-06-12 14:05 UTC, matyaswollner commented
ci:test:sf

2024-06-12 14:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5710/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5710/jenkins-report.html">here</a>.</b></p>

2024-06-12 14:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0028e9ea6a713f318f9eef73ecdd2473c93e2f20">0028e9ea6a713f318f9eef73ecdd2473c93e2f20</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-28161">LPD-28161</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/2a31e05704f43dda8a1c71bd25c078e906b78049">2a31e05704f43dda8a1c71bd25c078e906b78049</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5710/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5710/jenkins-report.html">here</a>.</h5><pre>     [exec] added 2648 packages, and audited 2649 packages in 16s
     [exec] 
     [exec] 210 packages are looking for funding
     [exec]   run `npm fund` for details
     [exec] 
     [exec] 109 vulnerabilities (2 low, 32 moderate, 50 high, 25 critical)
     [exec] 
     [exec] To address issues that do not require attention, run:
     [exec]   npm audit fix
     [exec] 
     [exec] To address all issues (including breaking changes), run:
     [exec]   npm audit fix --force
     [exec] 
     [exec] Run `npm audit` for details.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] 
     [exec] &gt; @liferay/playwright@1.0.0 checkFormat
     [exec] &gt; tsc &amp;&amp; liferay-npm-scripts lint &amp;&amp; liferay-npm-scripts format:check
     [exec] 
     [exec] 
     [exec] fixtures/accountsPagesTest.ts: BAD
     [exec] Prettier checked 552 files, 1 file has problems
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-06-12 14:12:08.988.
     [exec] 
     [exec] 3 actionable tasks: 3 executed
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/modules/test/playwright/build/reports/profile/profile-2024-06-12-07-11-03.html
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/modules/test/playwright/build/node/bin/node'' finished with non-zero exit value 1A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] 
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-06-12 14:29 UTC, smottal requested changes

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/helpers/HeadlessAdminUserApiHelper.ts
> +				(accountRoleIds ? `?accountRoleIds=${accountRoleIds}` : ''),
`${this.apiHelpers.baseUrl}${this.basePath}/accounts/${accountId}/user-accounts/by-email-address${(accountRoleIds ? `?accountRoleIds=${accountRoleIds}` : '')}`

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/fixtures/accountsPagesTest.ts
> +		await use( new AccountRolesPage(page));
please remove the empty space

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/fixtures/accountsPagesTest.ts
> +		await use( new AccountUsersPage(page));
please remove the empty space

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/pages/account-admin-web/AccountUsersPage.ts
> +	tableLocator: Locator,
probably not used anymore. In case please delete this

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +test('LPD-28161 Can view role and organizations printed as script', async ({
please rename the description like this "Can view role and organization name escaped"

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +	const organizationName = 'My org1<script>confirm("compromised")</script>';
please move this where used

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +		+organization.id,
please change + with Number()

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +	await expect(
please add an empty line before this

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +	await (await accountsPage.accountsTableRowLink(account.name)).click();
please add a new line before this

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +	await expect(await accountRolesPage.roleName(roleName)).toBeVisible();
please add a new line before this

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +	await editAccountPage.usersLink.click();
please add a new line before this

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +	await expect(await accountUsersPage.roleName(roleName)).toBeVisible();
please add a new line before this

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +	const user1 = await apiHelpers.headlessAdminUser.postUserAccount();
please remove the 1 because it's the only one

2024-06-12 14:29 UTC, smottal commented on modules/test/playwright/tests/account-admin-web/accounts.spec.ts
> +	const accountId = account.id;
please don't store in a dedicated variable but inline in the two points

2024-06-13 14:12 UTC, matyaswollner commented
ci:test:sf

2024-06-13 14:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/703bbd3a58ab98edd9606e673057636930dce5bd">703bbd3a58ab98edd9606e673057636930dce5bd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-28161">LPD-28161</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/90dad579b5a572c6710ac0f0a68f1304c9113e35">90dad579b5a572c6710ac0f0a68f1304c9113e35</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5540/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5540/jenkins-report.html">here</a>.</h5></details></html>

2024-06-13 14:22 UTC, smottal commented
ci:test:playwright:nocompile

2024-06-13 14:22 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2024-06-13 14:58 UTC, smottal approved these changes

2024-06-13 15:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5886/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5886/jenkins-report.html">here</a>.</b></p>

2024-06-13 16:32 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 30 out of 35 jobs passed in 1 hour 30 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0028e9ea6a713f318f9eef73ecdd2473c93e2f20">0028e9ea6a713f318f9eef73ecdd2473c93e2f20</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0028e9ea6a713f318f9eef73ecdd2473c93e2f20">0028e9ea6a713f318f9eef73ecdd2473c93e2f20</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/15390890">EE Development Acceptance (master) - 594 - 2024-06-11[12:39:19]</a></p><details><summary><strong>ci:test:playwright - 30 out of 35 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5886/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965304/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907123/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023343/">playwright-js-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010731/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130228/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660464/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130129/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/893137/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130226/"><strike>playwright-js-tomcat90-mysql57-jdk8/7/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/916922/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965305/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010732/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894158/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010733/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023344/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/912878/"><strike>playwright-js-tomcat90-mysql57-jdk8/14/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894159/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130230/">playwright-js-tomcat90-mysql57-jdk8/16/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907124/">playwright-js-tomcat90-mysql57-jdk8/17/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894155/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130225/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010729/">playwright-js-tomcat90-mysql57-jdk8/20/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660463/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894156/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130227/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/916923/"><strike>playwright-js-tomcat90-mysql57-jdk8/24/0</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965306/"><strike>playwright-js-tomcat90-mysql57-jdk8/25/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130128/">playwright-js-tomcat90-mysql57-jdk8/26/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/912877/">playwright-js-tomcat90-mysql57-jdk8/27/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1010730/">playwright-js-tomcat90-mysql57-jdk8/28/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/894157/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660465/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/916925/">playwright-js-tomcat90-mysql57-jdk8/31/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1130229/">playwright-js-tomcat90-mysql57-jdk8/32/0</a></li></ul></li></ul></div><details><summary><strong>30 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5886/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965306//consoleText">playwright-js-tomcat90-mysql57-jdk8/25/0</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-06/test-1-35/test-portal-acceptance-pullrequest(master)/5886/playwright-js-tomcat90-mysql57-jdk8/25/0/playwright-report/index.html">Playwright Report</a><ol><li><details><summary><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965306/testReport/headless-builder-web_schemas.spec/ts">headless-builder-web/schemas.spec.ts</a></summary><div><ol><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/965306//testReport/headless-builder-web_schemas.spec/ts/check_related_objects_enablement_with_feature_flag">check related objects enablement with feature flag</a></li></ol></div></details></li></ol></div></li></ol><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/jo [...]

2024-06-13 17:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5886/">test-portal-acceptance-pullrequest(master)#5886</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5886/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5038">liferay-commerce#5038</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/16856880">[master] ci:test:playwright - matyaswollner &gt; liferay-commerce - PR#5038 - 2024-06-13[08:01:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>16856880<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/12992/">publish-testray-report#12992</a><br/></div></div>

2024-06-14 07:14 UTC, smottal commented
ci:forward

2024-06-14 07:14 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-06-14 07:14 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-06-14 07:14 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1320//consoleFull)

2024-06-14 07:15 UTC, closed without merging

2024-06-14 07:15 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/151383
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1320//consoleFull)