LPD-28891 Key is not automatically generated when writing new Specifications label
liferay-commerce/liferay-portal pull request #5068
Opened 2024-06-20 08:34 UTC by monaco-fabio

https://liferay.atlassian.net/browse/LPD-28891

2024-06-20 08:34 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-06-20 08:42 UTC, andrea-ale-sbarra approved these changes
LGTM.
thank you!
Remeber to add the entities created to the dataguard

2024-06-20 10:22 UTC, monaco-fabio commented
ci:test:sf

2024-06-20 10:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/8670/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8670/jenkins-report.html">here</a>.</b></p>

2024-06-20 10:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9f66856ed9d25029d096b0efcd5927358e8c0000">9f66856ed9d25029d096b0efcd5927358e8c0000</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-28891">LPD-28891</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/babdf98bcfd039f95d70e360912747f6bf8e0c88">babdf98bcfd039f95d70e360912747f6bf8e0c88</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8670/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8670/jenkins-report.html">here</a>.</h5></details></html>

2024-06-20 10:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8670/">test-portal-source-format#8670</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8670/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5068">liferay-commerce#5068</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/22123915">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5068 - 2024-06-20[03:23:11]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>22123915<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/32817/">publish-testray-report#32817</a><br/></div></div>

2024-06-20 21:01 UTC, andrea-ale-sbarra requested changes

2024-06-20 21:01 UTC, andrea-ale-sbarra commented on modules/test/playwright/tests/commerce/commerce-product-options-web/commerceProductSpecifications.spec.ts
> +		});
this is a little to much, can you check the specification and option category names before put those into the dataguard?

2024-07-04 08:27 UTC, monaco-fabio commented
I'm closing this PR. Resent here: #5110

2024-07-04 08:27 UTC, closed without merging