LPD-28683 When clicking on order item without visibility the user is not redirected to the catalog page
liferay-commerce/liferay-portal pull request #5081
Opened 2024-06-25 17:59 UTC by monaco-fabio

https://liferay.atlassian.net/browse/LPD-28683

2024-06-25 17:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-06-25 17:59 UTC, monaco-fabio commented
ci:test:sf

2024-06-25 18:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3274/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3274/jenkins-report.html">here</a>.</b></p>

2024-06-25 18:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4053233efc7665eaa07fc901fcf1c39d89e2721e">4053233efc7665eaa07fc901fcf1c39d89e2721e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-28683">LPD-28683</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/827fb21ef4a017c384bdb2e57d47733e507646c2">827fb21ef4a017c384bdb2e57d47733e507646c2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3274/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3274/jenkins-report.html">here</a>.</h5><pre>     [exec] warning Resolution field "webpack@5.89.0" is incompatible with requested version "webpack@5.76.0"
     [exec] success Already up-to-date.
     [exec] Done in 1.09s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts format --check
     [exec] 🛫 Running preflight...
     [exec] 📜 Validating tsconfig files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc in groups of 12 projects
     [exec] ℹ️ Going to check 0 modified projects
     [exec] 📝 Running format...
     [exec] ℹ️ Only running against files changed between 'master' and 'master-temp-1719338428171' branches. Use flag '--all' to run against all files.
     [exec] 📝 Formatting 6 files
     [exec] Error: Format checked 6 files
     [exec] 1 file has problems
     [exec] 
     [exec]     at format (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/format.mjs:304:9)
     [exec]     at async main (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/index.mjs:22:2)
     [exec] 
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-06-25 18:03:51.949.
     [exec] 
     [exec] 3 actionable tasks: 2 executed, 1 up-to-dateFAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] 
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin. Run with '-Ddevelocity.deprecation.captureOrigin=true' to see where the deprecated functionality is being used. For assistance with migration, see https://gradle.com/help/gradle-plugin-develocity-migration.org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec] - The deprecated "gradleEnterprise.buildScan.tag" API has been replaced by "develocity.buildScan.tag"</pre></details></html>

2024-06-25 18:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3274/">test-portal-source-format#3274</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3274/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5081">liferay-commerce#5081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/25800485">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5081 - 2024-06-25[10:59:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>25800485<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/13686/">publish-testray-report#13686</a><br/></div></div>

2024-06-25 18:14 UTC, monaco-fabio commented
ci:test:sf

2024-06-25 18:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/6063/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6063/jenkins-report.html">here</a>.</b></p>

2024-06-25 18:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4053233efc7665eaa07fc901fcf1c39d89e2721e">4053233efc7665eaa07fc901fcf1c39d89e2721e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-28683">LPD-28683</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/1b6b716e4a095525cec597f01df5f036ea41620c">1b6b716e4a095525cec597f01df5f036ea41620c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/6063/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6063/jenkins-report.html">here</a>.</h5></details></html>

2024-06-25 18:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/6063/">test-portal-source-format#6063</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6063/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5081">liferay-commerce#5081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/25821920">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5081 - 2024-06-25[11:17:59]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>25821920<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/3899/">publish-testray-report#3899</a><br/></div></div>

2024-07-02 09:41 UTC, alessiorendina requested changes
@monaco-fabio please check my comments, thank you!

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerce-order-content-web/pendingOrdersPage.ts
> +		);
No need to have the error message here.

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerce-order-content-web/pendingOrdersPage.ts
> +		this.clickOnProductSku = (sku) => page.getByRole('link', {name: sku});
It is not an action, it should be `skuLink`

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerce-theme-minium/commerceThemeMiniumPage.ts
> +		this.miniumLogo = page.getByRole('link', {name: 'Go to Minium'});
It is a link, so it should be called `goToMiniumLink`

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceMiniCartPage.ts
> +		this.viewOrderDetails = page.getByRole('button', {
It is a button, so it should be `viewDetailsButton`

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceMiniCartPage.ts
> +	async goToPeningOrder(sku: string) {
Fix typo `goToPeningOrder` -> `goToPendingOrder`

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceMiniCartPage.ts
> +	}
It seems that this method does another thing

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/users-admin-web/EditUserPage.ts
> +		this.frameSelectSite = async (siteName: string) => {
It is a link, so it should be `selectSiteLink`

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/users-admin-web/EditUserPage.ts
> +		this.saveMemberSiteButton = page.getByRole('button', {name: 'Save'});
This is not specific for the member site, so it should be `saveButton`

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/users-admin-web/EditUserPage.ts
> +		this.selectMembershipSite = page.getByLabel('Select Sites');
It is too generic, can we locate it better?

2024-07-02 09:41 UTC, alessiorendina commented on modules/test/playwright/pages/users-admin-web/EditUserPage.ts
> +	async assignUserToSite(site: string) {
`selectUserMembershipSite`

2024-07-05 13:58 UTC, monaco-fabio commented
ci:test:sf

2024-07-10 13:45 UTC, alessiorendina requested changes
@monaco-fabio please check my comments, thanks!

2024-07-10 13:45 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerce-order-content-web/pendingOrdersPage.ts
> +	readonly clickOnProductSkuLink: (sku: string) => Locator;
skuLink

2024-07-10 13:45 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerce-order-content-web/pendingOrdersPage.ts
> +	readonly showErrorMessage: Locator;
This needs to be removed

2024-07-10 13:45 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerce-order-content-web/pendingOrdersPage.ts
> +	readonly closeErrorMessage: Locator;
errorMessageCloseButton

2024-07-10 13:45 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceMiniCartPage.ts
> +	readonly viewOrderDetailsButton: Locator;
viewDetailsButton

2024-07-10 13:45 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceMiniCartPage.ts
> +			name: 'View Details',
Add `exact: true`

2024-07-10 13:45 UTC, alessiorendina commented on modules/test/playwright/pages/users-admin-web/EditUserPage.ts
> +	readonly membershipSiteSelectButton: Locator;
Check the other PR

2024-07-10 13:45 UTC, alessiorendina commented on modules/test/playwright/tests/commerce/commerce-order-content-web/pendingOrder.spec.ts
> +	await commerceLayoutsPage.cleanupSiteInitializerData(apiHelpers, site.name);
Let's move this after site creation or in a finally block

2024-07-10 13:45 UTC, alessiorendina commented on modules/test/playwright/tests/commerce/commerce-order-content-web/pendingOrder.spec.ts
> +
Remove empty line

2024-07-10 15:07 UTC, monaco-fabio commented
ci:test:sf

2024-07-10 15:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/9773/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9773/jenkins-report.html">here</a>.</b></p>

2024-07-10 15:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8e8d9db0ebbc47efb450bcc3d2d3b54e18518f9a">8e8d9db0ebbc47efb450bcc3d2d3b54e18518f9a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-28683">LPD-28683</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/6fcc6666bb1f6d1cd5244421bf456d0f92585513">6fcc6666bb1f6d1cd5244421bf456d0f92585513</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9773/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9773/jenkins-report.html">here</a>.</h5></details></html>

2024-07-10 15:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9773/">test-portal-source-format#9773</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9773/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5081">liferay-commerce#5081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/34996060">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5081 - 2024-07-10[08:07:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>34996060<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37485/">publish-testray-report#37485</a><br/></div></div>

2024-07-10 15:21 UTC, alessiorendina requested changes
@monaco-fabio please check my comments, thank you!

2024-07-10 15:21 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerce-order-content-web/pendingOrdersPage.ts
> +	readonly errorMessageCloseButton: Locator;
Sort alphabetically

2024-07-10 15:21 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerce-theme-minium/commerceThemeMiniumPage.ts
>  		this.myProfileItemMenu = page.getByRole('link', {name: 'My Profile'});
Sort alphabetically, remove empty line

2024-07-10 15:21 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceMiniCartPage.ts
Sort alphabetically

2024-07-12 15:57 UTC, monaco-fabio commented
ci:test:sf

2024-07-12 15:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2876/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2876/jenkins-report.html">here</a>.</b></p>

2024-07-12 16:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/18186553726902f517a0c480cc90c839c485a5d1">18186553726902f517a0c480cc90c839c485a5d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-28683">LPD-28683</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/f8f75b7e745469525554b6d13857c31bc9ab9b78">f8f75b7e745469525554b6d13857c31bc9ab9b78</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2876/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2876/jenkins-report.html">here</a>.</h5></details></html>

2024-07-12 16:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2876/">test-portal-source-format#2876</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2876/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5081">liferay-commerce#5081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/36601722">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5081 - 2024-07-12[08:57:13]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>36601722<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/11679/">publish-testray-report#11679</a><br/></div></div>

2024-07-12 16:20 UTC, monaco-fabio commented
ci:test:playwright:nocompile

2024-07-12 16:21 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2024-07-12 16:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6496/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6496/jenkins-report.html">here</a>.</b></p>

2024-07-12 17:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 42 out of 54 jobs passed in 1 hour 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/18186553726902f517a0c480cc90c839c485a5d1">18186553726902f517a0c480cc90c839c485a5d1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/18186553726902f517a0c480cc90c839c485a5d1">18186553726902f517a0c480cc90c839c485a5d1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/36297944">EE Development Acceptance (master) - 668 - 2024-07-11[16:38:21]</a></p><details><summary><strong>ci:test:playwright - 42 out of 54 jobs PASSED</strong></summary><div><h4>12 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6496/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/409054/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/960394/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155370/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151934/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/932843/"><strike>playwright-js-tomcat90-mysql57-jdk8/3/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/935842/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/871349/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1043127/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989751/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910888/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032510/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910887/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/938301/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/932844/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402727/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/447737/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/409055/"><strike>playwright-js-tomcat90-mysql57-jdk8/15/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151936/"><strike>playwright-js-tomcat90-mysql57-jdk8/16/0</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/351711/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/938298/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342761/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/938299/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/409053/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/450608/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/989750/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/938300/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155371/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/685640/"><strike>playwright-js-tomcat90-mysql57-jdk8/26/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/632498/"><strike>playwright-js-tomcat90-mysql57-jdk8/27/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155373/">playwright-js-tomcat90-mysql57-jdk8/28/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/450609/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/911476/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1043128/">playwright-js-tomcat90-mysql57-jdk8/31/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032512/"><strike>playwright-js-tomcat90-mysql57-jdk8/32/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/685641/">playwright-js-tomcat90-mysql57-jdk8/33/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/935841/">playwright-js-tomcat90-mysql57-jdk8/34/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/932845/">playwright-js-tomcat90-mysql57-jdk8/35/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1043130/">playwright-js-tomcat90-mysql57-jdk8/36/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151935/">playwright-js-tomcat90-mysql57-jdk8/37/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358463/">playwright-js-tomcat90-mysql57-jdk8/38/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358462/">playwright-js-tomcat90-mysql57-jdk8/39/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/685639/">playwright-js-tomcat90-mysql57-jdk8/40/0</a></li><li><a hr [...]

2024-07-12 17:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/6496/">test-portal-acceptance-pullrequest(master)#6496</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6496/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5081">liferay-commerce#5081</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/36726172">[master] ci:test:playwright - monaco-fabio &gt; liferay-commerce - PR#5081 - 2024-07-12[09:21:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>36726172<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/24634/">publish-testray-report#24634</a><br/></div></div>

2024-07-15 07:53 UTC, alessiorendina requested changes
@monaco-fabio please check my comment and make sure the order is deleted as well. Thank you!

2024-07-15 07:53 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerce-theme-minium/commerceThemeMiniumPage.ts
> +	readonly goToMiniumLink: Locator;
Sort alphabetically

2024-07-15 08:54 UTC, monaco-fabio commented
ci:test:sf

2024-07-15 09:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/5538/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5538/jenkins-report.html">here</a>.</b></p>

2024-07-15 09:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7ad7570343ecae9b7ca0930e20480b25a2328956">7ad7570343ecae9b7ca0930e20480b25a2328956</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-28683">LPD-28683</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/b9b9c2f63f1d6620e085fc11eb0b1cffa2389b90">b9b9c2f63f1d6620e085fc11eb0b1cffa2389b90</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/5538/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5538/jenkins-report.html">here</a>.</h5></details></html>

2024-07-15 09:08 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-07-15 09:08 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-07-15 09:10 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-10.liferay.com/job/forward-pullrequest/678//consoleFull)

2024-07-15 09:10 UTC, closed without merging

2024-07-15 09:10 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/152333
[Console](https://test-1-10.liferay.com/job/forward-pullrequest/678//consoleFull)