LPD-21633
liferay-commerce/liferay-portal pull request #5086
Opened 2024-06-26 09:17 UTC by andrea-ale-sbarra

https://liferay.atlassian.net/browse/LPD-21633

2024-06-26 09:17 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-06-26 09:52 UTC, andrea-ale-sbarra commented
ci:test:sf

2024-06-26 09:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5594/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5594/jenkins-report.html">here</a>.</b></p>

2024-06-26 09:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/54e58a5e8594909dd69271bb7ee9c2bbb95f2f83">54e58a5e8594909dd69271bb7ee9c2bbb95f2f83</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/LPD-21633">LPD-21633</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/d7ab089e175e2fd12601b7521657f0cee0a5cb72">d7ab089e175e2fd12601b7521657f0cee0a5cb72</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5594/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5594/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Create a new variable for the left hand side operand of the '&gt;' operator for better readability: ./modules/apps/commerce/commerce-order-web/src/main/java/com/liferay/commerce/order/web/internal/display/context/CommerceReturnEditDisplayContext.java 385 (Checkstyle:OperatorOperandCheck)
     [java] 2: Create a new variable for the left hand side operand of the '&gt;' operator for better readability: ./modules/apps/commerce/commerce-order-web/src/main/java/com/liferay/commerce/order/web/internal/display/context/CommerceReturnEditDisplayContext.java 409 (Checkstyle:OperatorOperandCheck)
     [java] 3: Create a new variable for the left hand side operand of the '&gt;' operator for better readability: ./modules/apps/commerce/commerce-order-web/src/main/java/com/liferay/commerce/order/web/internal/display/context/CommerceReturnEditDisplayContext.java 411 (Checkstyle:OperatorOperandCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:469)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 2:37.053 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:641: Java returned: 1
      [get] Getting: http://test-1-29/job/test-portal-source-format/5594//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240626025716341.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240626025716341.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1132203973.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null372508480</pre></details></html>

2024-06-26 10:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5594/">test-portal-source-format#5594</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5594/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5086">liferay-commerce#5086</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/26470417">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#5086 - 2024-06-26[02:53:01]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>26470417<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/22102/">publish-testray-report#22102</a><br/></div></div>

2024-06-26 14:52 UTC, alessiorendina requested changes
@andrea-ale-sbarra Overall it looks good to me, just a small change. Thank you!

2024-06-26 14:52 UTC, alessiorendina commented on modules/apps/commerce/commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/display/context/CommerceReturnContentDisplayContext.java
> +			StringUtil.equals(commerceReturn.getReturnStatus(), "completed")) {
Can you use constants for the return status?

2024-06-26 14:52 UTC, alessiorendina commented on modules/apps/commerce/commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/display/context/CommerceReturnContentDisplayContext.java
> +		else if (StringUtil.equals(commerceReturn.getReturnStatus(), "draft")) {
Same here

2024-06-28 13:21 UTC, andrea-ale-sbarra commented
resent here https://github.com/liferay-commerce/liferay-portal/pull/5100

2024-06-28 13:21 UTC, closed without merging