LPD-26643 Address autoselect during checkout not working for account defaults and reorder
liferay-commerce/liferay-portal pull request #5114
Opened 2024-07-03 16:36 UTC by monaco-fabio

https://liferay.atlassian.net/browse/LPD-26643

2024-07-03 16:36 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-07-03 16:36 UTC, monaco-fabio commented
ci:test:sf

2024-07-03 16:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3300/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3300/jenkins-report.html">here</a>.</b></p>

2024-07-03 16:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f62a37a67ce8215e92cf7c8f365461932669206a">f62a37a67ce8215e92cf7c8f365461932669206a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-26643">LPD-26643</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/c207dc55c051df807d1caef4a2c042806921d78e">c207dc55c051df807d1caef4a2c042806921d78e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3300/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3300/jenkins-report.html">here</a>.</h5><pre>     [exec] warning nohoist config is ignored in "@liferay/amd-loader" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
     [exec] [4/4] Building fresh packages...
     [exec] Done in 6.39s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts format --check
     [exec] 🛫 Running preflight...
     [exec] 📜 Generating tsconfig files...
     [exec] 🕵️ Checking modified typescript files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] ℹ️ Going to check 0 modified projects
     [exec] 📝 Running format...
     [exec] ℹ️ Only running against files changed between 'master' and 'master-temp-1720024680755' branches. Use flag '--all' to run against all files.
     [exec] 📝 Formatting 8 files
     [exec] Error: Format checked 8 files
     [exec] 6 files have problems
     [exec] 
     [exec]     at format (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/format.mjs:304:9)
     [exec]     at async main (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/index.mjs:27:2)
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-07-03 16:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3300/">test-portal-source-format#3300</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3300/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5114">liferay-commerce#5114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/30175901">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5114 - 2024-07-03[09:37:30]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>30175901<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/13776/">publish-testray-report#13776</a><br/></div></div>

2024-07-03 16:51 UTC, monaco-fabio commented
ci:test:sf

2024-07-03 16:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/8076/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8076/jenkins-report.html">here</a>.</b></p>

2024-07-03 16:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f62a37a67ce8215e92cf7c8f365461932669206a">f62a37a67ce8215e92cf7c8f365461932669206a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-26643">LPD-26643</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/40b5f32748c8c4c4a2a2610e29cd8ef244828e86">40b5f32748c8c4c4a2a2610e29cd8ef244828e86</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/8076/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8076/jenkins-report.html">here</a>.</h5></details></html>

2024-07-03 17:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/8076/">test-portal-source-format#8076</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8076/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5114">liferay-commerce#5114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/30190607">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5114 - 2024-07-03[09:52:08]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>30190607<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/31844/">publish-testray-report#31844</a><br/></div></div>

2024-07-04 08:10 UTC, alessiorendina requested changes
@monaco-fabio please check my comments, thank you!

2024-07-04 08:10 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceAdminOrderDetailsPage.ts
> +		this.checkoutButton = page.getByRole('button', {name: 'Checkout'});
Add `exact: true` property

2024-07-04 08:10 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceAdminOrderDetailsPage.ts
> +		this.reorderButton = page.getByRole('button', {name: 'Reorder'});
Same here

2024-07-04 08:10 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceAdminOrderDetailsPage.ts
> +	async redordeProduct() {
Please fix typo here

2024-07-04 08:10 UTC, alessiorendina commented on modules/test/playwright/tests/commerce/commerce-order-content-web/placedOrder.spec.ts
> +test('LPD-26643 Address autoselect during checkout not working for account defaults and reorder', async ({
Describe what the test does instead

2024-07-04 09:12 UTC, monaco-fabio commented
ci:test:sf

2024-07-04 09:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7895/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7895/jenkins-report.html">here</a>.</b></p>

2024-07-04 09:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9165ef78ad0b808aff504d2456c3a74bdf84af4">d9165ef78ad0b808aff504d2456c3a74bdf84af4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-26643">LPD-26643</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/d637fad4f2d6ecd5e87aef3f3ff956bfcd4e3a02">d637fad4f2d6ecd5e87aef3f3ff956bfcd4e3a02</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7895/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7895/jenkins-report.html">here</a>.</h5></details></html>

2024-07-04 09:27 UTC, monaco-fabio commented
ci:test:relevant

2024-07-04 09:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7895/">test-portal-source-format#7895</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7895/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5114">liferay-commerce#5114</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/30996191">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5114 - 2024-07-04[02:16:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>30996191<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4264/">publish-testray-report#4264</a><br/></div></div>

2024-07-04 12:45 UTC, monaco-fabio commented
ci:test:relevant

2024-07-04 13:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17328/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17328/jenkins-report.html">here</a>.</b></p>

2024-07-05 09:14 UTC, monaco-fabio commented
ci:stop

2024-07-05 09:17 UTC, closed without merging

2024-07-05 09:33 UTC, monaco-fabio commented
#5119