LPD-29997 Refactor test GlobalSearchSearchProductsBySpecificationValues to playwright
liferay-commerce/liferay-portal pull request #5124
Opened 2024-07-08 22:58 UTC by dsitu

https://liferay.atlassian.net/browse/LPD-29997

2024-07-08 22:58 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-07-08 23:00 UTC, dsitu commented
ci:test:sf

2024-07-08 23:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5863/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5863/jenkins-report.html">here</a>.</b></p>

2024-07-08 23:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e9043735ac47973d0bf9f597c61b1ca756be33a7">e9043735ac47973d0bf9f597c61b1ca756be33a7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-29997">LPD-29997</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/0508c5e9d094318a2ae06617595d36873280f866">0508c5e9d094318a2ae06617595d36873280f866</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5863/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5863/jenkins-report.html">here</a>.</h5></details></html>

2024-07-08 23:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5863/">test-portal-source-format#5863</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5863/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/33522846">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-08[16:01:00]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>33522846<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/22907/">publish-testray-report#22907</a><br/></div></div>

2024-07-08 23:08 UTC, dsitu commented
ci:test:relevant

2024-07-08 23:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/10681/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10681/jenkins-report.html">here</a>.</b></p>

2024-07-08 23:09 UTC, dsitu commented
ci:test:playwright

2024-07-08 23:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5693/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5693/jenkins-report.html">here</a>.</b></p>

2024-07-08 23:52 UTC, dsitu commented
@riccardo-alberti I just saw this PR:https://github.com/liferay-commerce/liferay-portal/pull/5069, I can apply `await apiHelpers.commerceMiniumApiHelper.loadCleanUpData(site);` to this code when the other PR is merged

2024-07-09 00:26 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 39 out of 54 jobs passed in 1 hour 15 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/657">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1257401_5693</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e9043735ac47973d0bf9f597c61b1ca756be33a7">e9043735ac47973d0bf9f597c61b1ca756be33a7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0f0b8c4cf99ee49a04626026b0f28656778ba994">0f0b8c4cf99ee49a04626026b0f28656778ba994</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/33522039">EE Development Acceptance (master) - 656 - 2024-07-08[12:38:27]</a></p><details><summary><strong>ci:test:playwright - 39 out of 54 jobs PASSED</strong></summary><div><h4>15 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5693/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/997090/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929183/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/682456/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/997089/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/997091/"><strike>playwright-js-tomcat90-mysql57-jdk8/3/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907391/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870402/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986311/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986310/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870405/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/997088/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/682454/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/932353/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049269/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629033/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/932355/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986314/"><strike>playwright-js-tomcat90-mysql57-jdk8/15/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907392/"><strike>playwright-js-tomcat90-mysql57-jdk8/16/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/997092/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907390/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929184/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/682455/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151628/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/957016/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/932354/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/932356/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049268/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629032/"><strike>playwright-js-tomcat90-mysql57-jdk8/26/0</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039503/"><strike>playwright-js-tomcat90-mysql57-jdk8/27/0</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986313/"><strike>playwright-js-tomcat90-mysql57-jdk8/28/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151631/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/957017/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151629/">playwright-js-tomcat90-mysql57-jdk8/31/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049271/"><strike>playwright-js-tomcat90-mysql57-jdk8/32/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/957015/"><strike>playwright-js-tomcat90-mysql57-jdk8/33/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907394/">playwright-js-tomcat90-mysql57-jdk8/34/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039504/">playwright-js-tomcat90-mysql57-jdk8/35/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929186/">playwright-js-tomcat90-mysql57-jdk8/36/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629031/">playwright-js-tomcat90-mysql57-jdk8/37/0</a></li><li [...]

2024-07-09 00:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/5693/">test-portal-acceptance-pullrequest(master)#5693</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5693/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/33603186">[master] ci:test:playwright - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-08[16:10:07]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>33603186<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/11616/">publish-testray-report#11616</a><br/></div></div>

2024-07-09 08:13 UTC, riccardo-alberti requested changes

2024-07-09 08:13 UTC, riccardo-alberti commented on modules/test/playwright/tests/commerce/commerce-theme-minium/commerceSearch.spec.ts
> +
Use the const {channel, site} = await miniumSetUp(apiHelpers); to create minium. It will take care of deleting the data afterward.

2024-07-10 15:45 UTC, dsitu commented
ci:test:sf

2024-07-10 15:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5772/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5772/jenkins-report.html">here</a>.</b></p>

2024-07-10 15:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8e8d9db0ebbc47efb450bcc3d2d3b54e18518f9a">8e8d9db0ebbc47efb450bcc3d2d3b54e18518f9a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-29997">LPD-29997</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/fb739a925315592f0b41d89d72f6e744c29f2d84">fb739a925315592f0b41d89d72f6e744c29f2d84</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5772/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5772/jenkins-report.html">here</a>.</h5></details></html>

2024-07-10 15:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5772/">test-portal-source-format#5772</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5772/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/35000675">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-10[08:45:47]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>35000675<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/22540/">publish-testray-report#22540</a><br/></div></div>

2024-07-10 22:28 UTC, dsitu commented
ci:test:sf

2024-07-10 22:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7913/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7913/jenkins-report.html">here</a>.</b></p>

2024-07-10 22:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/00d0f1b87c4a266004528a8c08446d8e87282545">00d0f1b87c4a266004528a8c08446d8e87282545</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-29997">LPD-29997</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/5bd55a3a520e4a5f3a27c0f2230d98d7df376504">5bd55a3a520e4a5f3a27c0f2230d98d7df376504</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7913/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7913/jenkins-report.html">here</a>.</h5></details></html>

2024-07-10 22:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9627/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9627/jenkins-report.html">here</a>.</b></p>

2024-07-10 22:58 UTC, dsitu commented
ci:stop

2024-07-10 22:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 0 out of 1 jobs passed in 16 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/00d0f1b87c4a266004528a8c08446d8e87282545">00d0f1b87c4a266004528a8c08446d8e87282545</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8e8d9db0ebbc47efb450bcc3d2d3b54e18518f9a">8e8d9db0ebbc47efb450bcc3d2d3b54e18518f9a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/35191084">EE Development Acceptance (master) - 665 - 2024-07-10[08:38:35]</a></p><details><summary><strong>ci:test:playwright - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9627/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9627/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9627/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-07-10 23:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7913/">test-portal-source-format#7913</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7913/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/35431636">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-10[15:30:59]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>35431636<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4282/">publish-testray-report#4282</a><br/></div></div>

2024-07-10 23:02 UTC, dsitu commented
ci:test:playwright

2024-07-10 23:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17398/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17398/jenkins-report.html">here</a>.</b></p>

2024-07-10 23:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9627/">test-portal-acceptance-pullrequest(master)#9627</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9627/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/35433660">[master] ci:test:playwright - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-10[15:42:46]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>35433660<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/22972/">publish-testray-report#22972</a><br/></div></div>

2024-07-11 00:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 43 out of 54 jobs passed in 1 hour 18 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/667">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_17398</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/00d0f1b87c4a266004528a8c08446d8e87282545">00d0f1b87c4a266004528a8c08446d8e87282545</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bff0c1e8fe73e39700b0bee506af3ebb5e15dda2">bff0c1e8fe73e39700b0bee506af3ebb5e15dda2</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/35444101">EE Development Acceptance (master) - 666 - 2024-07-10[12:38:22]</a></p><details><summary><strong>ci:test:playwright - 43 out of 54 jobs PASSED</strong></summary><div><h4>11 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17398/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/909389/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988360/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1051115/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/931101/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1150572/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1041501/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1041504/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1051112/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988358/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630993/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958825/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153666/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934302/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1150570/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/999255/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1051113/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153669/"><strike>playwright-js-tomcat90-mysql57-jdk8/15/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/931102/"><strike>playwright-js-tomcat90-mysql57-jdk8/16/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1150573/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958824/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958828/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1150571/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1051111/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1041503/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988359/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988362/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958826/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934308/"><strike>playwright-js-tomcat90-mysql57-jdk8/26/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153665/"><strike>playwright-js-tomcat90-mysql57-jdk8/27/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/909390/"><strike>playwright-js-tomcat90-mysql57-jdk8/28/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630994/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988363/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/934306/">playwright-js-tomcat90-mysql57-jdk8/31/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958830/">playwright-js-tomcat90-mysql57-jdk8/32/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630992/">playwright-js-tomcat90-mysql57-jdk8/33/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/909391/">playwright-js-tomcat90-mysql57-jdk8/34/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1041502/">playwright-js-tomcat90-mysql57-jdk8/35/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630995/">playwright-js-tomcat90-mysql57-jdk8/36/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988361/">playwright-js-tomcat90-mysql57-jdk8/37/0</a></li><li><a href="https://test-1-32.liferay.com/jo [...]

2024-07-11 00:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17398/">test-portal-acceptance-pullrequest(master)#17398</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17398/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/35519857">[master] ci:test:playwright - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-10[16:02:25]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>35519857<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37503/">publish-testray-report#37503</a><br/></div></div>

2024-07-11 07:33 UTC, riccardo-alberti approved these changes

2024-07-11 22:08 UTC, dsitu commented
ci:test:sf

2024-07-11 22:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/5472/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5472/jenkins-report.html">here</a>.</b></p>

2024-07-11 22:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/18186553726902f517a0c480cc90c839c485a5d1">18186553726902f517a0c480cc90c839c485a5d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-29997">LPD-29997</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/026e9561e120e54c9a798448bf03ba516d38c3c2">026e9561e120e54c9a798448bf03ba516d38c3c2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5472/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5472/jenkins-report.html">here</a>.</h5><pre>     [exec] [4/4] Building fresh packages...
     [exec] Done in 5.62s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts format --check
     [exec] 🛫 Running preflight...
     [exec] 📜 Generating tsconfig files...
     [exec] 📜 Validating tsconfig files...
     [exec] 🕵️ Checking modified typescript files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] ℹ️ Going to check 0 modified projects
     [exec] 📝 Running format...
     [exec] 📝 Formatting 2 files
     [exec] /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/commerce/commerce-theme-minium/commerceSearch.spec.ts
     [exec]   27:2  error  'page' is defined but never used. Allowed unused args must match /^_|^this\$/u.  @typescript-eslint/no-unused-vars
     [exec] 
     [exec] ✖ 1 problem (1 error, 0 warnings)
     [exec] Error: Format checked 2 files
     [exec] 1 file has problems
     [exec] 
     [exec]     at format (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/format.mjs:328:9)
     [exec]     at async main (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/index.mjs:27:2)
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-07-11 22:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5472/">test-portal-source-format#5472</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5472/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/36199322">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-11[15:08:31]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>36199322<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/21592/">publish-testray-report#21592</a><br/></div></div>

2024-07-11 22:17 UTC, dsitu commented
ci:test:sf

2024-07-11 22:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/9794/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9794/jenkins-report.html">here</a>.</b></p>

2024-07-11 22:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/18186553726902f517a0c480cc90c839c485a5d1">18186553726902f517a0c480cc90c839c485a5d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-29997">LPD-29997</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/9c39398296b3175e4c4fddbb7bddf0c5b1d64849">9c39398296b3175e4c4fddbb7bddf0c5b1d64849</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9794/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9794/jenkins-report.html">here</a>.</h5><pre>     [exec] [4/4] Building fresh packages...
     [exec] Done in 6.36s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts format --check
     [exec] 🛫 Running preflight...
     [exec] 📜 Generating tsconfig files...
     [exec] 📜 Validating tsconfig files...
     [exec] 🕵️ Checking modified typescript files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] ℹ️ Going to check 0 modified projects
     [exec] 📝 Running format...
     [exec] 📝 Formatting 2 files
     [exec] /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/commerce/commerce-theme-minium/commerceSearch.spec.ts
     [exec]   27:2  error  'page' is defined but never used. Allowed unused args must match /^_|^this\$/u.  @typescript-eslint/no-unused-vars
     [exec] 
     [exec] ✖ 1 problem (1 error, 0 warnings)
     [exec] Error: Format checked 2 files
     [exec] 1 file has problems
     [exec] 
     [exec]     at format (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/format.mjs:328:9)
     [exec]     at async main (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/index.mjs:27:2)
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-07-11 22:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9794/">test-portal-source-format#9794</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9794/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/36200314">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-11[15:17:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>36200314<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37540/">publish-testray-report#37540</a><br/></div></div>

2024-07-11 22:24 UTC, dsitu commented
ci:test:sf

2024-07-11 22:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/9795/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9795/jenkins-report.html">here</a>.</b></p>

2024-07-11 22:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/18186553726902f517a0c480cc90c839c485a5d1">18186553726902f517a0c480cc90c839c485a5d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-29997">LPD-29997</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/b6d6bea63cc1e4b9849ec4770b8fdd5a7d580a5f">b6d6bea63cc1e4b9849ec4770b8fdd5a7d580a5f</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9795/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9795/jenkins-report.html">here</a>.</h5><pre>     [exec] warning "workspace-aggregator-8e992980-1a97-4d95-b6c8-6036622bf38b &gt; @liferay/frontend-js-dependencies-web &gt; graphiql &gt; codemirror-graphql &gt; graphql-language-service &gt; graphql-config &gt; @graphql-tools/url-loader &gt; subscriptions-transport-ws@0.11.0" has incorrect peer dependency "graphql@^15.7.2 || ^16.0.0".
     [exec] warning nohoist config is ignored in "@liferay/amd-loader" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
     [exec] [4/4] Building fresh packages...
     [exec] Done in 6.32s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts format --check
     [exec] 🛫 Running preflight...
     [exec] 📜 Generating tsconfig files...
     [exec] 📜 Validating tsconfig files...
     [exec] 🕵️ Checking modified typescript files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] ℹ️ Going to check 0 modified projects
     [exec] 📝 Running format...
     [exec] 📝 Formatting 2 files
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-07-11 22:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9795/">test-portal-source-format#9795</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9795/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/36200354">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-11[15:24:49]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>36200354<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37541/">publish-testray-report#37541</a><br/></div></div>

2024-07-11 23:13 UTC, dsitu commented
ci:test:sf

2024-07-11 23:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/9796/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9796/jenkins-report.html">here</a>.</b></p>

2024-07-11 23:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/18186553726902f517a0c480cc90c839c485a5d1">18186553726902f517a0c480cc90c839c485a5d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-29997">LPD-29997</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/c490fb85ee48388ba9554f7b1a7b6abc18a5b542">c490fb85ee48388ba9554f7b1a7b6abc18a5b542</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9796/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9796/jenkins-report.html">here</a>.</h5></details></html>

2024-07-11 23:21 UTC, dsitu commented
ci:forward

2024-07-11 23:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-07-11 23:21 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-07-11 23:22 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/forward-pullrequest/1635//consoleFull)

2024-07-11 23:22 UTC, closed without merging

2024-07-11 23:22 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/152276
[Console](https://test-1-32.liferay.com/job/forward-pullrequest/1635//consoleFull)

2024-07-11 23:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9796/">test-portal-source-format#9796</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9796/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5124">liferay-commerce#5124</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/36240106">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5124 - 2024-07-11[16:14:01]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>36240106<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37545/">publish-testray-report#37545</a><br/></div></div>