LPD-30466 Refactor poshi test
liferay-commerce/liferay-portal pull request #5126
Opened 2024-07-09 08:08 UTC by monaco-fabio

https://liferay.atlassian.net/browse/LPD-30466

2024-07-09 08:09 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-07-09 08:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f9c10926adea06bd31f72995c0ca031c9afd95ee">f9c10926adea06bd31f72995c0ca031c9afd95ee</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-30466">LPD-30466</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/849058a99956a0d6f8f97796bc1dc47d3a27cb99">849058a99956a0d6f8f97796bc1dc47d3a27cb99</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5760/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5760/jenkins-report.html">here</a>.</h5></details></html>

2024-07-09 08:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5760/">test-portal-source-format#5760</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5760/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/33707725">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-09[01:09:29]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>33707725<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/22516/">publish-testray-report#22516</a><br/></div></div>

2024-07-09 08:27 UTC, smottal requested changes

2024-07-09 08:27 UTC, smottal commented on modules/test/playwright/tests/commerce/commerceChannelDefaults.spec.ts
> +	});
move this before the creation of the role because you use this value only there

2024-07-09 08:27 UTC, smottal commented on modules/test/playwright/tests/commerce/commerceChannelDefaults.spec.ts
> +
I think this is not needed because the postChannel already add it (please verify)

2024-07-09 08:27 UTC, smottal commented on modules/test/playwright/tests/commerce/commerceChannelDefaults.spec.ts
> +		await applicationsMenuPage.goToCommerceChannels();
please use the CommerceAdminChannelDetailsPage to reach the page (with the goto function)

2024-07-09 08:27 UTC, smottal commented on modules/test/playwright/tests/commerce/commerceChannelDefaults.spec.ts
> +		await expect(page.getByText(channel.name)).toBeVisible();
we should try to have the locators only inside the pages so for this please create a locator in the CommerceAdminChannelDetailsPage and in the test use it

2024-07-09 08:27 UTC, smottal commented on modules/test/playwright/tests/commerce/commerceChannelDefaults.spec.ts
> +		).toHaveCount(0);
same here, please create a locator in the CommerceAdminChannelDetailsPage

2024-07-09 08:27 UTC, smottal commented on modules/test/playwright/pages/product-navigation-applications-menu/ApplicationsMenuPage.ts
> -		await expect(this.applicationsMenuTabButton).toBeVisible();
why this? because I think. this is used by everyone...

2024-07-09 10:21 UTC, smottal requested changes

2024-07-09 10:21 UTC, smottal commented on modules/test/playwright/pages/commerce/commerceAdminChannelDetailsPage.ts
> +	readonly channelNameLink: (channelName: string ) => Promise<Locator>;
this returns a Locator, not a Promise<Locator>

2024-07-09 10:21 UTC, smottal commented on modules/test/playwright/pages/commerce/commerceAdminChannelDetailsPage.ts
> +	readonly checkChannelName: (channelName: string ) => Promise<Locator>;
same here

2024-07-09 10:21 UTC, smottal commented on modules/test/playwright/pages/commerce/commerceAdminChannelDetailsPage.ts
> +		};
you don't need the async because you're not returning a promise but directly the locator

2024-07-09 10:21 UTC, smottal commented on modules/test/playwright/pages/commerce/commerceAdminChannelDetailsPage.ts
> +	async goto(checkTabVisibility = true) {
I don't know if in this way is also optional (because otherwise you have to change ALL the other tests)

2024-07-09 10:21 UTC, smottal commented on modules/test/playwright/pages/product-navigation-applications-menu/ApplicationsMenuPage.ts
> +	async goto(checkTabVisibility = true) {
same here, I don't know if you have to specify the parameter as optional (with the ?)

2024-07-09 10:21 UTC, smottal commented on modules/test/playwright/pages/product-navigation-applications-menu/ApplicationsMenuPage.ts
> +	async goToCommerceChannels(checkTabVisibility = true) {
same here

2024-07-09 10:21 UTC, smottal commented on modules/test/playwright/pages/product-navigation-applications-menu/ApplicationsMenuPage.ts
> +	async goToCommercePanel(checkTabVisibility = true) {
and here...

2024-07-09 12:16 UTC, smottal approved these changes

2024-07-09 12:16 UTC, smottal commented
ci:test:sf

2024-07-09 12:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/6991/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6991/jenkins-report.html">here</a>.</b></p>

2024-07-09 12:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b91e483ef366e4ce089775eac4cb589235422f92">b91e483ef366e4ce089775eac4cb589235422f92</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-30466">LPD-30466</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/6be4164be05cdc197931010a27ed36af802700c3">6be4164be05cdc197931010a27ed36af802700c3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6991/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6991/jenkins-report.html">here</a>.</h5></details></html>

2024-07-09 12:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6991/">test-portal-source-format#6991</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6991/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/33805416">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-09[05:17:01]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>33805416<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/26712/">publish-testray-report#26712</a><br/></div></div>

2024-07-09 12:25 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2024-07-09 12:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12227/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12227/jenkins-report.html">here</a>.</b></p>

2024-07-09 15:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12227/">test-portal-acceptance-pullrequest(master)#12227</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12227/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/33872568">[master] ci:test:playwright - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-09[05:25:33]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>33872568<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/26714/">publish-testray-report#26714</a><br/></div></div>

2024-07-10 14:08 UTC, monaco-fabio commented
ci:test:sf

2024-07-10 14:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5769/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5769/jenkins-report.html">here</a>.</b></p>

2024-07-10 14:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c2c388b266596711595aece101f87434fc344c63">c2c388b266596711595aece101f87434fc344c63</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-30466">LPD-30466</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/8cf9a055566201ebe1b0da33b1875a98219113ea">8cf9a055566201ebe1b0da33b1875a98219113ea</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5769/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5769/jenkins-report.html">here</a>.</h5></details></html>

2024-07-10 14:23 UTC, monaco-fabio commented
ci:test:playwright:nocompile

2024-07-10 14:23 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2024-07-10 14:35 UTC, smottal approved these changes

2024-07-10 15:50 UTC, monaco-fabio commented
ci:stop

2024-07-10 15:52 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 42 out of 54 jobs passed in 1 hour 15 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/664">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1287401_9766</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/51cb4cbf6fee235d75454f628053730080f9f9ed">51cb4cbf6fee235d75454f628053730080f9f9ed</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f449080142ea3cac3e0ebf3c6725fde51dd939fc">f449080142ea3cac3e0ebf3c6725fde51dd939fc</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/34809357">EE Development Acceptance (master) - 663 - 2024-07-10[00:39:05]</a></p><details><summary><strong>ci:test:playwright - 42 out of 54 jobs PASSED</strong></summary><div><h4>12 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/9766/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/930641/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/936502/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030838/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998754/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/933839/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630545/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1150152/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910085/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987847/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630547/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153170/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153173/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/908902/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958396/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1030836/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1150150/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/930643/"><strike>playwright-js-tomcat90-mysql57-jdk8/15/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998755/"><strike>playwright-js-tomcat90-mysql57-jdk8/16/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/933841/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1050641/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987849/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/908901/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958395/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/958397/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/936500/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998757/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/936501/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910087/"><strike>playwright-js-tomcat90-mysql57-jdk8/26/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153172/"><strike>playwright-js-tomcat90-mysql57-jdk8/27/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/936504/"><strike>playwright-js-tomcat90-mysql57-jdk8/28/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153175/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/933840/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/987848/">playwright-js-tomcat90-mysql57-jdk8/31/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1150153/"><strike>playwright-js-tomcat90-mysql57-jdk8/32/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/630546/">playwright-js-tomcat90-mysql57-jdk8/33/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910088/">playwright-js-tomcat90-mysql57-jdk8/34/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/908900/">playwright-js-tomcat90-mysql57-jdk8/35/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153176/">playwright-js-tomcat90-mysql57-jdk8/36/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/910086/">playwright-js-tomcat90-mysql57-jdk8/37/0</a></li><li><a href="https://test-1-38.lif [...]

2024-07-10 15:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/9766/">test-portal-acceptance-pullrequest(master)#9766</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9766/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/35003771">[master] ci:test:playwright - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-10[07:35:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>35003771<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/21570/">publish-testray-report#21570</a><br/></div></div>

2024-07-15 09:37 UTC, monaco-fabio commented
ci:test:sf

2024-07-15 09:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7923/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7923/jenkins-report.html">here</a>.</b></p>

2024-07-15 09:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7ad7570343ecae9b7ca0930e20480b25a2328956">7ad7570343ecae9b7ca0930e20480b25a2328956</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-30466">LPD-30466</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/5b2decfb0fc02db13f0f6c7caa81da026cd58d3f">5b2decfb0fc02db13f0f6c7caa81da026cd58d3f</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7923/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7923/jenkins-report.html">here</a>.</h5><pre>     [exec] [4/4] Building fresh packages...
     [exec] Done in 10.37s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts format --check
     [exec] ���� Running preflight...
     [exec] ���� Generating tsconfig files...
     [exec] ���� Validating tsconfig files...
     [exec] ������� Checking modified typescript files...
     [exec] ������ A total of 8 CPUs were detected: launching tsc using 8 workers
     [exec] ������ Going to check 0 modified projects
     [exec] ���� Running format...
     [exec] ���� Formatting 4 files
     [exec] Error: Format checked 4 files
     [exec] 2 files have problems
     [exec] 
     [exec]     at format (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/format.mjs:328:9)
     [exec]     at async main (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/index.mjs:27:2)
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-07-15 09:47:28.021.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-07-15 09:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/6996/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6996/jenkins-report.html">here</a>.</b></p>

2024-07-15 09:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7923/">test-portal-source-format#7923</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7923/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/37663893">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-15[02:38:31]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>37663893<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4292/">publish-testray-report#4292</a><br/></div></div>

2024-07-15 09:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7ad7570343ecae9b7ca0930e20480b25a2328956">7ad7570343ecae9b7ca0930e20480b25a2328956</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-30466">LPD-30466</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/b6033d996d18d668191bad0363395a11e766ea7a">b6033d996d18d668191bad0363395a11e766ea7a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6996/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6996/jenkins-report.html">here</a>.</h5></details></html>

2024-07-15 09:58 UTC, monaco-fabio commented
ci:test:playwright:nocompile

2024-07-15 09:58 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2024-07-15 09:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5992/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5992/jenkins-report.html">here</a>.</b></p>

2024-07-15 10:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6996/">test-portal-source-format#6996</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6996/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/37663901">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-15[02:51:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>37663901<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/26746/">publish-testray-report#26746</a><br/></div></div>

2024-07-15 10:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7ad7570343ecae9b7ca0930e20480b25a2328956">7ad7570343ecae9b7ca0930e20480b25a2328956</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7ad7570343ecae9b7ca0930e20480b25a2328956">7ad7570343ecae9b7ca0930e20480b25a2328956</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/37579247">EE Development Acceptance (master) - 672 - 2024-07-14[12:38:05]</a></p><details><summary><strong>ci:test:playwright - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5992/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5992/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5992/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-07-15 10:02 UTC, monaco-fabio commented
ci:test:playwright:nocompile

2024-07-15 10:02 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2024-07-15 10:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5993/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5993/jenkins-report.html">here</a>.</b></p>

2024-07-15 10:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5992/">test-portal-acceptance-pullrequest(master)#5992</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5992/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/37665712">[master] ci:test:playwright - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-15[02:58:30]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>37665712<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/13200/">publish-testray-report#13200</a><br/></div></div>

2024-07-15 11:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 39 out of 54 jobs passed in 1 hour 15 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7ad7570343ecae9b7ca0930e20480b25a2328956">7ad7570343ecae9b7ca0930e20480b25a2328956</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7ad7570343ecae9b7ca0930e20480b25a2328956">7ad7570343ecae9b7ca0930e20480b25a2328956</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/37579247">EE Development Acceptance (master) - 672 - 2024-07-14[12:38:05]</a></p><details><summary><strong>ci:test:playwright - 39 out of 54 jobs PASSED</strong></summary><div><h4>15 Failed Jobs:</h4><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5993/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/911721/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/686561/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961247/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033214/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/939027/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053622/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/911722/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/872213/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033206/"><strike>playwright-js-tomcat90-mysql57-jdk8/7/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/933660/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033208/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/686562/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/872217/"><strike>playwright-js-tomcat90-mysql57-jdk8/11/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/911720/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033218/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/933659/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/421683/"><strike>playwright-js-tomcat90-mysql57-jdk8/15/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/686563/"><strike>playwright-js-tomcat90-mysql57-jdk8/16/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1156284/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033204/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961245/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/872216/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033209/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/686564/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033211/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1043964/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/872212/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/633323/"><strike>playwright-js-tomcat90-mysql57-jdk8/26/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/686560/"><strike>playwright-js-tomcat90-mysql57-jdk8/27/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053626/"><strike>playwright-js-tomcat90-mysql57-jdk8/28/0</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1043965/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053627/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053623/">playwright-js-tomcat90-mysql57-jdk8/31/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/686565/"><strike>playwright-js-tomcat90-mysql57-jdk8/32/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033215/">playwright-js-tomcat90-mysql57-jdk8/33/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1152695/">playwright-js-tomcat90-mysql57-jdk8/34/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053624/">playwright-js-tomcat90-mysql57-jdk8/35/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/633324/">playwright-js-tomcat90-mysql57-jdk8/36/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/872215/">playwright-js-tomcat90-mysql57-jdk8/37/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1043966/">playwright-js-tomcat90-mysql57-jdk8/38/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033216/">playwright-js-tomcat90-mysql57-jdk8/39/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1033207/">playwrig [...]

2024-07-15 11:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5993/">test-portal-acceptance-pullrequest(master)#5993</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5993/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/37678926">[master] ci:test:playwright - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-15[03:02:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>37678926<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/13206/">publish-testray-report#13206</a><br/></div></div>

2024-07-15 12:31 UTC, alessiorendina reviewed
@monaco-fabio please check my comments, thank you!

2024-07-15 12:31 UTC, alessiorendina commented on modules/test/playwright/pages/commerce/commerceAdminChannelDetailsPage.ts
> +			page.getByText(channelName);
We don't need this in the page, let's move it in the test

2024-07-15 12:31 UTC, alessiorendina commented on modules/test/playwright/tests/commerce/commerceAdminChannelDetails.spec.ts
> +
Remove empty line

2024-07-15 12:31 UTC, alessiorendina commented on modules/test/playwright/tests/commerce/commerceAdminChannelDetails.spec.ts
> +	});
Can we sort alphabetically by resourceName?

2024-07-15 13:02 UTC, monaco-fabio commented
ci:test:sf

2024-07-15 13:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/8730/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8730/jenkins-report.html">here</a>.</b></p>

2024-07-15 13:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7ad7570343ecae9b7ca0930e20480b25a2328956">7ad7570343ecae9b7ca0930e20480b25a2328956</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-30466">LPD-30466</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/6762a36eac198ec158fefa712ebde20641e58eca">6762a36eac198ec158fefa712ebde20641e58eca</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8730/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8730/jenkins-report.html">here</a>.</h5></details></html>

2024-07-15 13:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8730/">test-portal-source-format#8730</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8730/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/37692607">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-15[06:03:00]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>37692607<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/33024/">publish-testray-report#33024</a><br/></div></div>

2024-07-15 13:14 UTC, alessiorendina requested changes
@monaco-fabio please check my comment, thanks!

2024-07-15 13:14 UTC, alessiorendina commented on modules/test/playwright/tests/commerce/commerceAdminChannelDetails.spec.ts
> +			},
dot should be before underscore

2024-07-15 13:18 UTC, monaco-fabio commented
ci:test:sf

2024-07-15 15:31 UTC, monaco-fabio commented
ci:test:sf

2024-07-15 15:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5908/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5908/jenkins-report.html">here</a>.</b></p>

2024-07-15 15:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f70e314f67dca8dbc899bff1669d39637e7c0e5a">f70e314f67dca8dbc899bff1669d39637e7c0e5a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-30466">LPD-30466</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/756e7124fb15a4bd0a68f53c1b66fdc07244bce5">756e7124fb15a4bd0a68f53c1b66fdc07244bce5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5908/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5908/jenkins-report.html">here</a>.</h5></details></html>

2024-07-15 15:37 UTC, alessiorendina commented
ci:forward

2024-07-15 15:37 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-07-15 15:37 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-07-15 15:38 UTC, closed without merging

2024-07-15 15:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5908/">test-portal-source-format#5908</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5908/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5126">liferay-commerce#5126</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/37844214">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5126 - 2024-07-15[08:31:45]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>37844214<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/23034/">publish-testray-report#23034</a><br/></div></div>