LPD-30589 - Rewrite Localfile.Organizations#AddOrganizationTeam as a Playwright test
liferay-commerce/liferay-portal pull request #5127
Opened 2024-07-09 08:12 UTC by matyaswollner

https://liferay.atlassian.net/browse/LPD-30589

2024-07-09 08:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-07-09 08:13 UTC, matyaswollner commented
ci:test:sf

2024-07-09 08:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5868/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5868/jenkins-report.html">here</a>.</b></p>

2024-07-09 08:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f9c10926adea06bd31f72995c0ca031c9afd95ee">f9c10926adea06bd31f72995c0ca031c9afd95ee</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-30589">LPD-30589</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/e762294e710f29d10f7624ec88a66c02d6b1a048">e762294e710f29d10f7624ec88a66c02d6b1a048</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5868/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5868/jenkins-report.html">here</a>.</h5></details></html>

2024-07-09 08:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5868/">test-portal-source-format#5868</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5868/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5127">liferay-commerce#5127</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/33707734">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5127 - 2024-07-09[01:13:18]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>33707734<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/22915/">publish-testray-report#22915</a><br/></div></div>

2024-07-09 08:47 UTC, smottal requested changes

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/tests/users-admin-web/usersAndOrganizations.spec.ts
> +	// await editOrganizationPage.manageSiteLink.click();
remove this comment

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/tests/users-admin-web/usersAndOrganizations.spec.ts
> +	// await applicationsMenuPage.goToSite(organization.name);
remove this

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/fixtures/usersAndOrganizationsPagesTest.ts
> +	},
do we need this inside this fixture? why we cannot use its original fixture to retrieve it in the test?

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/pages/product-navigation-control-menu-web/ProductMenuPage.ts
> +		this.peopleButton = page.getByRole('menuitem', {name: 'People'});
is it used?

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/pages/product-navigation-control-menu-web/ProductMenuPage.ts
> +		this.teamsButton = page.getByRole('menuitem', {name: 'Teams'});
is it used?

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/pages/users-admin-web/EditOrganizationPage.ts
> +		await this.organizationSiteSaveButton.click();
can you please remove this and move the instruction directly in the test? I think we will not using this so much in the future

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/pages/users-admin-web/TeamsPage.ts
> +	readonly nameInput: Locator;
this should go before (sort them)

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/pages/users-admin-web/TeamsPage.ts
> +		this.nameInput = page.getByPlaceholder('Name');
same here

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/pages/users-admin-web/TeamsPage.ts
> +		return teamName;
same here, please remove the function from there and put the logic in the test

2024-07-09 08:47 UTC, smottal commented on modules/test/playwright/tests/users-admin-web/usersAndOrganizations.spec.ts
> +	await usersAndOrganizationsPage.goToOrganizations();
do we need to go to the page here (before the creation of the data) or we can create everything and then move in the page?

2024-07-09 09:37 UTC, matyaswollner commented
ci:test:sf

2024-07-09 10:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/5539/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5539/jenkins-report.html">here</a>.</b></p>

2024-07-09 10:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/105f946f10df429c9d38e8ae6ca74f9ed067e434">105f946f10df429c9d38e8ae6ca74f9ed067e434</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-30589">LPD-30589</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/9189a7a127bc0bb9c40297446422cc429555adcb">9189a7a127bc0bb9c40297446422cc429555adcb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5539/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5539/jenkins-report.html">here</a>.</h5></details></html>

2024-07-09 10:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5539/">test-portal-source-format#5539</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5539/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5127">liferay-commerce#5127</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/33766897">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5127 - 2024-07-09[03:09:26]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>33766897<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/5888/">publish-testray-report#5888</a><br/></div></div>

2024-07-09 10:23 UTC, smottal approved these changes

2024-07-09 10:23 UTC, smottal commented
ci:test:playwright:nocompile

2024-07-09 10:23 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2024-07-09 14:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 41 out of 54 jobs passed in 2 hours 7 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/656">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1317401_11073</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0f0b8c4cf99ee49a04626026b0f28656778ba994">0f0b8c4cf99ee49a04626026b0f28656778ba994</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f9c10926adea06bd31f72995c0ca031c9afd95ee">f9c10926adea06bd31f72995c0ca031c9afd95ee</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/33768431">EE Development Acceptance (master) - 658 - 2024-07-09[00:38:37]</a></p><details><summary><strong>ci:test:playwright - 41 out of 54 jobs PASSED</strong></summary><div><h4>13 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11073/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/682748/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039693/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029798/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/682747/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449352/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/935417/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420054/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151864/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/935416/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/420053/"><strike>playwright-js-tomcat90-mysql57-jdk8/8/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629203/">playwright-js-tomcat90-mysql57-jdk8/9/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870663/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357282/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/935418/">playwright-js-tomcat90-mysql57-jdk8/12/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907636/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/957279/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/909202/"><strike>playwright-js-tomcat90-mysql57-jdk8/15/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151865/"><strike>playwright-js-tomcat90-mysql57-jdk8/16/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029799/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039692/">playwright-js-tomcat90-mysql57-jdk8/18/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907635/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1029797/"><strike>playwright-js-tomcat90-mysql57-jdk8/20/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870660/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/997309/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929404/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629205/"><strike>playwright-js-tomcat90-mysql57-jdk8/24/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049484/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/935419/"><strike>playwright-js-tomcat90-mysql57-jdk8/26/0</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151863/"><strike>playwright-js-tomcat90-mysql57-jdk8/27/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/932547/">playwright-js-tomcat90-mysql57-jdk8/28/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/929405/">playwright-js-tomcat90-mysql57-jdk8/29/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629206/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907634/">playwright-js-tomcat90-mysql57-jdk8/31/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/682749/"><strike>playwright-js-tomcat90-mysql57-jdk8/32/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/629204/">playwright-js-tomcat90-mysql57-jdk8/33/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039695/">playwright-js-tomcat90-mysql57-jdk8/34/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357281/">playwright-js-tomcat90-mysql57-jdk8/35/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/997308/">playwright-js-tomcat90-mysql57-jdk8/36/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/932546/">playwright-js-tomcat90-mysql57-jdk8/37/0</a></li><li><a href="https://test-1-6.liferay. [...]

2024-07-09 14:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11073/">test-portal-acceptance-pullrequest(master)#11073</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11073/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5127">liferay-commerce#5127</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/33852571">[master] ci:test:playwright - matyaswollner &gt; liferay-commerce - PR#5127 - 2024-07-09[05:16:47]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>33852571<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/25500/">publish-testray-report#25500</a><br/></div></div>

2024-07-11 06:38 UTC, smottal commented
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/5140 for conflicts

2024-07-11 06:38 UTC, closed without merging