LPD-31020 - Rewrite Localfile.Organizations#AssignUser as a Playwright test
liferay-commerce/liferay-portal pull request #5132
Opened 2024-07-09 13:44 UTC by matyaswollner

https://liferay.atlassian.net/browse/LPD-31020

2024-07-09 13:44 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-07-09 13:45 UTC, matyaswollner commented
ci:test:sf

2024-07-09 13:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5764/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5764/jenkins-report.html">here</a>.</b></p>

2024-07-09 13:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b91e483ef366e4ce089775eac4cb589235422f92">b91e483ef366e4ce089775eac4cb589235422f92</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-31020">LPD-31020</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/43c735ed19fb72aeae584d2ab6038f5a9b8d1e74">43c735ed19fb72aeae584d2ab6038f5a9b8d1e74</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5764/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5764/jenkins-report.html">here</a>.</h5></details></html>

2024-07-09 13:55 UTC, smottal requested changes

2024-07-09 13:55 UTC, smottal commented on modules/test/playwright/tests/users-admin-web/usersAndOrganizations.spec.ts
> +	});
I think we need to test this using UI and not API because probably the test is exactly to test the UI process

2024-07-09 15:07 UTC, matyaswollner commented
ci:test:sf

2024-07-23 09:44 UTC, matyaswollner commented
ci:test:sf

2024-07-23 09:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/9857/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9857/jenkins-report.html">here</a>.</b></p>

2024-07-23 09:49 UTC, matyaswollner commented
ci:test:playwright:nocompile

2024-07-23 09:51 UTC, liferay-continuous-integration commented
No valid prebuilt bundle is available.

2024-07-23 09:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9857/">test-portal-source-format#9857</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9857/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5132">liferay-commerce#5132</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/43434400">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5132 - 2024-07-23[02:44:34]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>43434400<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37760/">publish-testray-report#37760</a><br/></div></div>

2024-07-23 09:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9746/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9746/jenkins-report.html">here</a>.</b></p>

2024-07-23 09:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f168e4467c133b80b1388c39d5c7a35d4c7c5cb">6f168e4467c133b80b1388c39d5c7a35d4c7c5cb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3cfaa75bea1a335c229db6495ccafe5159969c69">3cfaa75bea1a335c229db6495ccafe5159969c69</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/42703939">EE Development Acceptance (master) - 692 - 2024-07-21[16:38:41]</a></p><details><summary><strong>ci:test:playwright - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9746/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9746/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9746/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-07-23 10:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9746/">test-portal-acceptance-pullrequest(master)#9746</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9746/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5132">liferay-commerce#5132</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/43438936">[master] ci:test:playwright - matyaswollner &gt; liferay-commerce - PR#5132 - 2024-07-23[02:51:59]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>43438936<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/23235/">publish-testray-report#23235</a><br/></div></div>

2024-07-23 14:25 UTC, matyaswollner commented
ci:test:sf

2024-07-23 14:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5981/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5981/jenkins-report.html">here</a>.</b></p>

2024-07-23 14:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f168e4467c133b80b1388c39d5c7a35d4c7c5cb">6f168e4467c133b80b1388c39d5c7a35d4c7c5cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-31020">LPD-31020</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/fe6c7f300e766561e4c7620426167d3ac1ecc1ac">fe6c7f300e766561e4c7620426167d3ac1ecc1ac</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5981/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5981/jenkins-report.html">here</a>.</h5></details></html>

2024-07-23 14:31 UTC, matyaswollner commented
ci:test:playwright:nocompile

2024-07-23 14:33 UTC, liferay-continuous-integration commented
No valid prebuilt bundle is available.

2024-07-23 14:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17525/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17525/jenkins-report.html">here</a>.</b></p>

2024-07-23 14:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5981/">test-portal-source-format#5981</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5981/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5132">liferay-commerce#5132</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/43454306">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5132 - 2024-07-23[07:25:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>43454306<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/23270/">publish-testray-report#23270</a><br/></div></div>

2024-07-23 14:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f168e4467c133b80b1388c39d5c7a35d4c7c5cb">6f168e4467c133b80b1388c39d5c7a35d4c7c5cb</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3cfaa75bea1a335c229db6495ccafe5159969c69">3cfaa75bea1a335c229db6495ccafe5159969c69</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/42703939">EE Development Acceptance (master) - 692 - 2024-07-21[16:38:41]</a></p><details><summary><strong>ci:test:playwright - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17525/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17525/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17525/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-07-23 14:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17525/">test-portal-acceptance-pullrequest(master)#17525</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17525/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5132">liferay-commerce#5132</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/43454345">[master] ci:test:playwright - matyaswollner &gt; liferay-commerce - PR#5132 - 2024-07-23[07:33:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>43454345<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37772/">publish-testray-report#37772</a><br/></div></div>

2024-07-24 07:29 UTC, matyaswollner commented
ci:test:playwright

2024-07-24 07:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9781/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9781/jenkins-report.html">here</a>.</b></p>

2024-07-24 08:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 41 out of 56 jobs passed in 1 hour 24 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/694">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1307401_9781</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/356fd6e9f8eeacd2cd071cb754afc9c6447b2a1f">356fd6e9f8eeacd2cd071cb754afc9c6447b2a1f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3cfaa75bea1a335c229db6495ccafe5159969c69">3cfaa75bea1a335c229db6495ccafe5159969c69</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/42703939">EE Development Acceptance (master) - 692 - 2024-07-21[16:38:41]</a></p><details><summary><strong>ci:test:playwright - 41 out of 56 jobs PASSED</strong></summary><div><h4>15 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9781/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1009232/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694302/"><strike>playwright-js-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/641260/"><strike>playwright-js-tomcat90-mysql57-jdk8/1/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1060771/">playwright-js-tomcat90-mysql57-jdk8/2/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1009233/">playwright-js-tomcat90-mysql57-jdk8/3/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1163763/">playwright-js-tomcat90-mysql57-jdk8/4/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1159382/">playwright-js-tomcat90-mysql57-jdk8/5/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1163764/">playwright-js-tomcat90-mysql57-jdk8/6/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694299/">playwright-js-tomcat90-mysql57-jdk8/7/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998049/">playwright-js-tomcat90-mysql57-jdk8/8/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1163761/"><strike>playwright-js-tomcat90-mysql57-jdk8/9/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039132/">playwright-js-tomcat90-mysql57-jdk8/10/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941388/">playwright-js-tomcat90-mysql57-jdk8/11/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943985/"><strike>playwright-js-tomcat90-mysql57-jdk8/12/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941389/">playwright-js-tomcat90-mysql57-jdk8/13/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1163765/">playwright-js-tomcat90-mysql57-jdk8/14/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1159383/">playwright-js-tomcat90-mysql57-jdk8/15/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/641258/"><strike>playwright-js-tomcat90-mysql57-jdk8/16/0</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998050/"><strike>playwright-js-tomcat90-mysql57-jdk8/17/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694298/"><strike>playwright-js-tomcat90-mysql57-jdk8/18/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1009231/">playwright-js-tomcat90-mysql57-jdk8/19/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/641259/">playwright-js-tomcat90-mysql57-jdk8/20/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998045/">playwright-js-tomcat90-mysql57-jdk8/21/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694304/">playwright-js-tomcat90-mysql57-jdk8/22/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694300/">playwright-js-tomcat90-mysql57-jdk8/23/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/943987/">playwright-js-tomcat90-mysql57-jdk8/24/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998047/">playwright-js-tomcat90-mysql57-jdk8/25/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1163766/">playwright-js-tomcat90-mysql57-jdk8/26/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694301/"><strike>playwright-js-tomcat90-mysql57-jdk8/27/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941386/"><strike>playwright-js-tomcat90-mysql57-jdk8/28/0</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1159381/"><strike>playwright-js-tomcat90-mysql57-jdk8/29/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/878687/">playwright-js-tomcat90-mysql57-jdk8/30/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941384/">playwright-js-tomcat90-mysql57-jdk8/31/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/878688/">playwright-js-tomcat90-mysql57-jdk8/32/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/694303/"><strike>playwright-js-tomcat90-mysql57-jdk8/33/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1009234/"><strike>playwright-js-tomcat90-mysql57-jdk8/34/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945577/">playwright-js-tomcat90-mysql57-jdk8/35/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/919153/">playwright-js-tomcat90-mysql57-jdk8/36/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/878685/">playwright-js-tomcat90-mysql57-jdk8/37/0</a></ [...]

2024-07-24 08:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/9781/">test-portal-acceptance-pullrequest(master)#9781</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9781/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5132">liferay-commerce#5132</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/44215061">[master] ci:test:playwright - matyaswollner &gt; liferay-commerce - PR#5132 - 2024-07-24[00:30:05]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>44215061<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/23301/">publish-testray-report#23301</a><br/></div></div>

2024-07-29 09:51 UTC, matyaswollner commented
ci:test:sf

2024-07-29 09:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3360/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3360/jenkins-report.html">here</a>.</b></p>

2024-07-29 09:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c16e65131bb9e8393356423a33f6b57c5d833d86">c16e65131bb9e8393356423a33f6b57c5d833d86</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-31020">LPD-31020</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/a58faf9cc4997c8f91e2e7d4fa7634bfc2d6cec3">a58faf9cc4997c8f91e2e7d4fa7634bfc2d6cec3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3360/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3360/jenkins-report.html">here</a>.</h5></details></html>

2024-07-29 09:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3360/">test-portal-source-format#3360</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3360/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5132">liferay-commerce#5132</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/46443028">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5132 - 2024-07-29[02:51:45]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>46443028<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/13979/">publish-testray-report#13979</a><br/></div></div>

2024-07-29 10:35 UTC, smottal approved these changes

2024-07-29 10:35 UTC, smottal commented
ci:forward

2024-07-29 10:35 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-07-29 10:35 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-07-29 10:36 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1398//consoleFull)

2024-07-29 10:36 UTC, closed without merging

2024-07-29 10:36 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/152741
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1398//consoleFull)