LPD-33466 adapt code
liferay-commerce/liferay-portal pull request #5257
Opened 2024-08-13 10:40 UTC by andrea-ale-sbarra

https://liferay.atlassian.net/browse/LPD-33466

2024-08-13 10:40 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-08-13 16:32 UTC, smottal requested changes
There are breaking changes in the service layer but no breaking change message

2024-08-14 16:34 UTC, riccardo-alberti requested changes
@andrea-ale-sbarra @smottal avoid major versions because this has to go in a hotfix

2024-08-16 10:16 UTC, smottal commented
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/5274

2024-08-16 10:16 UTC, closed without merging