LPD-34378 - Add ERC to email aderesses
liferay-commerce/liferay-portal pull request #5375
Opened 2024-09-13 14:53 UTC by matyaswollner

https://liferay.atlassian.net/browse/LPD-34378

2024-09-13 14:53 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-09-16 12:50 UTC, smottal requested changes

2024-09-16 12:50 UTC, smottal commented on portal-impl/src/com/liferay/portal/service/impl/EmailAddressLocalServiceImpl.java
> +
Please move this at the beginning of the method

2024-09-16 12:50 UTC, smottal commented on portal-impl/src/com/liferay/portlet/usersadmin/util/UsersAdminUtil.java
> +					null, className, classPK, address, listTypeId, primary,
probably we have to get the erc from the emailAddress no?

2024-09-16 12:50 UTC, smottal commented on portal-impl/src/com/liferay/portlet/usersadmin/util/UsersAdminUtil.java
> +					null, emailAddressId, address, listTypeId, primary);
same here

2024-09-16 12:50 UTC, smottal commented on portal-impl/src/com/liferay/portal/upgrade/v7_4_x/UpgradeEmailAddressExternalReferenceCode.java
> +public class UpgradeEmailAddressExternalReferenceCode extends BaseExternalReferenceCodeUpgradeProcess {
Wrong name: let's call it EmailAddressExternalReferenceCodeUpgradeProcess.java

2024-09-16 14:17 UTC, matyaswollner commented
ci:test:sf

2024-09-16 14:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6489/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6489/jenkins-report.html">here</a>.</b></p>

2024-09-16 14:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-34378">LPD-34378</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/03de9390471ea3b4b704b724a05f0ed634cc317d">03de9390471ea3b4b704b724a05f0ed634cc317d</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6489/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6489/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-impl/src/com/liferay/portal/upgrade/v7_4_x/EmailAddressExternalReferenceCodeUpgradeProcess.java expected:&lt;...lAddressId"\}\};
     [java]   \}
     [java] 
     [java] \}[]&gt; but was:&lt;...lAddressId"\}\};
     [java]   \}
     [java] 
     [java] \}[
     [java] ]&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:473)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 1:44.902 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-28/job/test-portal-source-format/6489//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240916072113649.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240916072113649.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null745111988.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null602702762
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 166ms
[junitreport] Deleting: /tmp/null602702762
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 09-16-2024 07:21:16:183 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2024-09-16 14:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6489/">test-portal-source-format#6489</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6489/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5375">liferay-commerce#5375</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/12989036">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5375 - 2024-09-16[07:18:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>12989036<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/24244/">publish-testray-report#24244</a><br/></div></div>

2024-09-16 14:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/3687/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3687/jenkins-report.html">here</a>.</b></p>

2024-09-16 14:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-34378">LPD-34378</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/2e44dd9100ceed1742155731a44dd30789b542a1">2e44dd9100ceed1742155731a44dd30789b542a1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3687/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3687/jenkins-report.html">here</a>.</h5></details></html>

2024-09-16 14:33 UTC, smottal commented
ci:test:relevant

2024-09-16 14:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3687/">test-portal-source-format#3687</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3687/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5375">liferay-commerce#5375</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/12991299">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5375 - 2024-09-16[07:27:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>12991299<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/25090/">publish-testray-report#25090</a><br/></div></div>

2024-09-16 14:45 UTC, liferay-continuous-integration commented
ci:test:upgrade

Invoking upgrade test suite because an upgrade file has been modified.

2024-09-16 14:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 14 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/12668577">EE Development Acceptance (master) - 830 - 2024-09-14[16:38:16]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4995/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4995/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4995/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>compile:
     [copy] Copying 58 files to /opt/dev/projects/github/liferay-portal/portal-test/classes
     [copy] Copied 87 empty directories to 9 empty directories under /opt/dev/projects/github/liferay-portal/portal-test/classes
    [javac] Compiling 130 source files to /opt/dev/projects/github/liferay-portal/portal-test/classes
 [parallel] /opt/dev/projects/github/liferay-portal/portal-test/src/com/liferay/portal/kernel/test/util/OrganizationTestUtil.java:83: error: no suitable method found for addEmailAddress(long,String,long,String,long,boolean,ServiceContext)
 [parallel]     return EmailAddressLocalServiceUtil.addEmailAddress(
 [parallel]                                        ^
 [parallel]     method EmailAddressLocalServiceUtil.addEmailAddress(EmailAddress) is not applicable
 [parallel]       (actual and formal argument lists differ in length)
 [parallel]     method EmailAddressLocalServiceUtil.addEmailAddress(String,long,String,long,String,long,boolean,ServiceContext) is not applicable
 [parallel]       (actual and formal argument lists differ in length)
 [parallel] Note: Some input files use or override a deprecated API.
 [parallel] Note: Recompile with -Xlint:deprecation for details.
 [parallel] Note: Some input files use unchecked or unsafe operations.
 [parallel] Note: Recompile with -Xlint:unchecked for details.
 [parallel] 1 error
[beanshell] 4840 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 54 minutes.
[beanshell]     https://api.github.com/repos/liferay-commerce/liferay-portal/issues/5375/comments?per_page=100&amp;page=1
[beanshell] File propagator ID: 12-0 - Copying from source test-1-32-5.lax.liferay.com:/tmp/-917731238/build-database.json
[beanshell] Executing commands: ssh -o ConnectTimeout=15 -o NumberOfPasswordPrompts=0 test-1-32 'mkdir -p /opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest\(master\)/builds/4995/ ; rsync -Iqs test-1-32-5.lax.liferay.com:/tmp/-917731238/build-database.json /opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest\(master\)/builds/4995/build-database.json ; ls -al /opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest\(master\)/builds/4995'
[beanshell] File propagator ID: 12-0 - Finished copying from source.
[beanshell] File propagator ID: 12-0 - File propagation starting with 1 threads.
[beanshell] File propagator ID: 12-0 - File propagation completed in 2 ms.</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-09-16 14:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>upgrade</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10298/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10298/jenkins-report.html">here</a>.</b></p>

2024-09-16 14:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:upgrade - 0 out of 1 jobs passed in 12 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/12668577">EE Development Acceptance (master) - 830 - 2024-09-14[16:38:16]</a></p><details><summary><strong>ci:test:upgrade - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10298/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10298/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10298/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>compile:
     [copy] Copying 58 files to /opt/dev/projects/github/liferay-portal/portal-test/classes
     [copy] Copied 87 empty directories to 9 empty directories under /opt/dev/projects/github/liferay-portal/portal-test/classes
    [javac] Compiling 130 source files to /opt/dev/projects/github/liferay-portal/portal-test/classes
 [parallel] /opt/dev/projects/github/liferay-portal/portal-test/src/com/liferay/portal/kernel/test/util/OrganizationTestUtil.java:83: error: no suitable method found for addEmailAddress(long,String,long,String,long,boolean,ServiceContext)
 [parallel]     return EmailAddressLocalServiceUtil.addEmailAddress(
 [parallel]                                        ^
 [parallel]     method EmailAddressLocalServiceUtil.addEmailAddress(EmailAddress) is not applicable
 [parallel]       (actual and formal argument lists differ in length)
 [parallel]     method EmailAddressLocalServiceUtil.addEmailAddress(String,long,String,long,String,long,boolean,ServiceContext) is not applicable
 [parallel]       (actual and formal argument lists differ in length)
 [parallel] Note: Some input files use or override a deprecated API.
 [parallel] Note: Recompile with -Xlint:deprecation for details.
 [parallel] Note: Some input files use unchecked or unsafe operations.
 [parallel] Note: Recompile with -Xlint:unchecked for details.
 [parallel] 1 error
[beanshell] 4431 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 44 minutes.
[beanshell]     https://api.github.com/repos/liferay-commerce/liferay-portal/issues/5375/comments?per_page=100&amp;page=1
[beanshell] File propagator ID: 12-0 - Copying from source test-1-29-61.lax.liferay.com:/tmp/-1334866389/build-database.json
[beanshell] Executing commands: ssh -o ConnectTimeout=15 -o NumberOfPasswordPrompts=0 test-1-29 'mkdir -p /opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest\(master\)/builds/10298/ ; rsync -Iqs test-1-29-61.lax.liferay.com:/tmp/-1334866389/build-database.json /opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest\(master\)/builds/10298/build-database.json ; ls -al /opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest\(master\)/builds/10298'
[beanshell] Executing commands: git push -f git@github-dev.cluster-5.lax.liferay.com:liferay/liferay-portal-ee.git master-temp-1726498168018:cache-liferay-d9c623c28b91555b7ed3b45e210c832ea4c233bd-liferay-d9c623c28b91555b7ed3b45e210c832ea4c233bd-LOCK
     [echo] Generating Jenkins report.</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-09-16 14:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4995/">test-portal-acceptance-pullrequest(master)#4995</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4995/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5375">liferay-commerce#5375</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/13000289">[master] ci:test:relevant - matyaswollner &gt; liferay-commerce - PR#5375 - 2024-09-16[07:33:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>13000289<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/33883/">publish-testray-report#33883</a><br/></div></div>

2024-09-16 14:58 UTC, matyaswollner commented
ci:test:sf

2024-09-16 15:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6493/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6493/jenkins-report.html">here</a>.</b></p>

2024-09-16 15:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-34378">LPD-34378</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/6662a9626241c998ae6daa74ff570faba00771be">6662a9626241c998ae6daa74ff570faba00771be</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6493/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6493/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-test/src/com/liferay/portal/kernel/test/util/OrganizationTestUtil.java expected:&lt;...til.addEmailAddress([
     [java]       null, ]organization.getUser...&gt; but was:&lt;...til.addEmailAddress([null,
     [java]       ]organization.getUser...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:473)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 1:48.143 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-28/job/test-portal-source-format/6493//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240916080203347.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240916080203347.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1375553149.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null870571857
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 158ms
[junitreport] Deleting: /tmp/null870571857
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 09-16-2024 08:02:05:890 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2024-09-16 15:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6493/">test-portal-source-format#6493</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6493/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5375">liferay-commerce#5375</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/13032353">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5375 - 2024-09-16[07:58:54]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>13032353<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/24248/">publish-testray-report#24248</a><br/></div></div>

2024-09-16 15:08 UTC, matyaswollner commented
ci:test:sf

2024-09-16 15:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6494/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6494/jenkins-report.html">here</a>.</b></p>

2024-09-16 15:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-34378">LPD-34378</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/7c67a00c967db0273b9d5b5979f3c6378679a10a">7c67a00c967db0273b9d5b5979f3c6378679a10a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6494/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6494/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-test/src/com/liferay/portal/kernel/test/util/OrganizationTestUtil.java expected:&lt;...ization.getUserId(),[ organization.getModelClassName(),
     [java]       organization.getOrganizationId(), "[REDACTED]",
     [java]       _getListTypeId(
     [java]         organization.getCompanyId(),
     [java]         ListTypeConstants.ORGANIZATION_EMAIL_ADDRESS),
     [java]       false, ]new ServiceContext()...&gt; but was:&lt;...ization.getUserId(),[
     [java]       organization.getModelClassName(), organization.getOrganizationId(),
     [java]       "[REDACTED]", _getListTypeId(
     [java]         organization.getCompanyId(),
     [java]         ListTypeConstants.ORGANIZATION_EMAIL_ADDRESS), false,
     [java]         ]new ServiceContext()...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:473)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 1:41.966 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-28/job/test-portal-source-format/6494//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240916081128194.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240916081128194.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null684756756.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1620724456
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 147ms
[junitreport] Deleting: /tmp/null1620724456</pre></details></html>

2024-09-16 15:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6494/">test-portal-source-format#6494</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6494/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5375">liferay-commerce#5375</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/13089787">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5375 - 2024-09-16[08:08:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>13089787<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/24249/">publish-testray-report#24249</a><br/></div></div>

2024-09-16 15:18 UTC, matyaswollner commented
ci:test:sf

2024-09-16 15:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6495/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6495/jenkins-report.html">here</a>.</b></p>

2024-09-16 15:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-34378">LPD-34378</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/d5e851b200391973314208f5134845a6ca732fa0">d5e851b200391973314208f5134845a6ca732fa0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6495/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6495/jenkins-report.html">here</a>.</h5></details></html>

2024-09-16 15:24 UTC, matyaswollner commented
ci:test:relevant

2024-09-16 15:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11076/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11076/jenkins-report.html">here</a>.</b></p>

2024-09-16 15:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6495/">test-portal-source-format#6495</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6495/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5375">liferay-commerce#5375</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/13153932">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5375 - 2024-09-16[08:19:01]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>13153932<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/24251/">publish-testray-report#24251</a><br/></div></div>

2024-09-16 15:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 34 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/12668577">EE Development Acceptance (master) - 830 - 2024-09-14[16:38:16]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11076/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11076/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11076/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] &gt; Task :apps:users-admin:users-admin-impl:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:translation:translation-translator-google-cloud:compileJava
     [exec] 
     [exec] &gt; Task :apps:trash:trash-web:packageRunBuild
     [exec] yarn run v1.13.0
     [exec] warning package.json: No license field
     [exec] \$ node-scripts build
     [exec] ⌛ Esbuild for main took: 0.103 s
 [parallel] Executing commands: git push -f git@github-dev.cluster-2.lax.liferay.com:liferay/liferay-portal.git master-temp-1726500585993:cache-liferay-d9c623c28b91555b7ed3b45e210c832ea4c233bd-matyaswollner-d5e851b200391973314208f5134845a6ca732fa0-LOCK
     [exec] ⌛ Legacy build (liferay-npm-scripts) took: 1.602 s
     [exec] 
     [exec] Using pre-existing NODE_ENV: "production"
     [exec] Received 0
     [exec] Done in 3.28s.
     [exec] 
     [exec] &gt; Task :apps:user-groups-admin:user-groups-admin-web:packageRunBuild
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts build
     [exec] ⌛ Esbuild for main took: 0.062 s
     [exec] DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
     [exec] 
     [exec] Recommendation: math.div(\$numerator, \$denominator) or calc(\$numerator / \$denominator)
     [exec] 
     [exec] More info and automated migrator: https://sass-lang.com/d/slash-div
     [exec] 
     [exec]    ╷
     [exec] 13 │         \$numerator / \$denominator
     [exec]    │         ^^^^^^^^^^^^^^^^^^^^^^^^^
     [exec]    ╵
     [exec]     ../../../node_modules/@clayui/css/src/scss/functions/_polyfills.scss 13:3           clay-div()
     [exec]     ../../../node_modules/@clayui/css/src/scss/functions/_global-functions.scss 904:15  clay-svg-url()
     [exec]     ../../../node_modules/@clayui/css/src/scss/functions/_global-functions.scss 969:10  clay-icon()
     [exec]     ../../../node_modules/@clayui/css/src/scss/atlas/variables/_forms.scss 247:28       @import
     [exec]     ../../../node_modules/@clayui/css/src/scss/atlas/_variables.scss 14:9               @import
     [exec]     atlas-variables.scss 9:9                                                            @import
     [exec]     src/main/resources/META-INF/resources/css/main.scss 1:9                             root stylesheet
     [exec] 
     [exec] ⌛ Sass for /opt/dev/projects/github/liferay-portal/modules/apps/user-groups-admin/user-groups-admin-web/src/main/resources/META-INF/resources/css/main.scss took: 0.392 s</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-09-16 16:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11076/">test-portal-acceptance-pullrequest(master)#11076</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11076/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5375">liferay-commerce#5375</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/13199103">[master] ci:test:relevant - matyaswollner &gt; liferay-commerce - PR#5375 - 2024-09-16[08:24:31]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>13199103<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/24254/">publish-testray-report#24254</a><br/></div></div>

2024-09-17 11:18 UTC, matyaswollner commented
ci:test:sf

2024-09-17 11:23 UTC, matyaswollner commented
ci:test:sf

2024-09-17 12:08 UTC, smottal commented
ci:test:sf

2024-09-17 13:27 UTC, closed without merging