LPD-38670 - Catalog Page loads slowly if there are too many accounts created
liferay-commerce/liferay-portal pull request #5472
Opened 2024-10-08 14:10 UTC by victorcdp

2024-10-08 14:11 UTC, victorcdp commented
ci:test:sf

2024-10-08 14:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/3749/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3749/jenkins-report.html">here</a>.</b></p>

2024-10-08 14:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/47340f5c4ce30fd201060e63c1931071ade08b51">47340f5c4ce30fd201060e63c1931071ade08b51</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorcdp/liferay-portal/tree/LPD-38670">LPD-38670</a><br/>Branch GIT ID: <a href="https://github.com/victorcdp/liferay-portal/commit/b450e2b7fe4715dd96561ffbbb5dad78cb0271cd">b450e2b7fe4715dd96561ffbbb5dad78cb0271cd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3749/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3749/jenkins-report.html">here</a>.</h5></details></html>

2024-10-08 14:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3749/">test-portal-source-format#3749</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3749/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5472">liferay-commerce#5472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/35206870">[master] ci:test:sf - victorcdp &gt; liferay-commerce - PR#5472 - 2024-10-08[07:12:15]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>35206870<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/25331/">publish-testray-report#25331</a><br/></div></div>

2024-10-08 14:31 UTC, smottal commented
Hey @victorcdp , could you please check if this https://liferay.atlassian.net/browse/LPD-36191 is the same problem and check the solution we did last time?

2024-10-08 21:39 UTC, victorcdp commented
Hey @smottal, they are different issues, unfortunately that solution doesn't work in this case

2024-10-11 07:40 UTC, smottal requested changes

2024-10-11 07:40 UTC, smottal commented on modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/util/CommerceAccountHelperImpl.java
I don't get how this change could improve the performance because now we are calling `getAccountEntries` that does
```
		return accountEntryPersistence.findByC_S(
			companyId, status, start, end, orderByComparator);
```

with your changes we will do a first select to retrieve the distinct of the ids of the accounts of a company
```
Set<Serializable> accountEntryIds = new HashSet<>(
			dslQuery(
				DSLQueryFactoryUtil.selectDistinct(
					AccountEntryTable.INSTANCE.accountEntryId
				).from(
					AccountEntryTable.INSTANCE
				).where(
					AccountEntryTable.INSTANCE.companyId.eq(companyId)
				).orderBy(
					AccountEntryTable.INSTANCE, orderByComparator
				).limit(
					start, end
				)));
```
followed by another select to get all the accounts with the id discovered by the previous one
```
Map<Serializable, AccountEntry> accountEntriesMap =
			accountEntryPersistence.fetchByPrimaryKeys(accountEntryIds);
```

...and for sure we are loosing the check on the status APPROVED like we are doing now

2024-10-14 20:38 UTC, victorcdp commented on modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/util/CommerceAccountHelperImpl.java
Hey @smottal, To be honest I don't know exactly why it's faster this way, but I tested it and it indeed works, the page loading time goes from ~40s to ~7s (with 11k accounts). I followed the same logic from the [getUserAccountEntries](https://github.com/liferay/liferay-portal/blob/822628ceb40d1a42169c5aeb2b1ca9e3842f61ed/modules/apps/account/account-service/src/main/java/com/liferay/account/service/impl/AccountEntryLocalServiceImpl.java#L538-L547) method, you can see that it was optimized [this](https://github.com/shuyangzhou/liferay-portal/pull/10578/commits/e3c8fe0b65b9fa34f0784108f2d4867bea9a61fb#diff-62e94c461ef85630be2ebfe9297ef44c048c321380c1185538dabaabf4addeb0R456-R468) way in the past by Pei-Jung.

As for the status check, the getUserAccountEntries uses the STATUS_ANY by default when fetching the accounts, so I thought a check for APPROVED wasn't really needed

2024-10-15 20:30 UTC, smottal commented on modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/util/CommerceAccountHelperImpl.java
@victorcdp 
for the status: before we were calling _accountEntryLocalService.getAccountEntries( asking only for WorkflowConstants.STATUS_APPROVED accounts), but now we are retrieving all of them because in the new dslQuery there is nothing related to the status

2024-10-15 20:34 UTC, smottal commented on modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/util/CommerceAccountHelperImpl.java
can be that the performance are better because we are not filtering by the status?

2024-10-16 02:36 UTC, victorcdp commented on modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/util/CommerceAccountHelperImpl.java
I've tested it with and without the filter, there is no change in performance, If you want I can update the PR and put the filter back

2024-10-18 08:29 UTC, smottal requested changes

2024-10-25 07:59 UTC, smottal commented
@victorcdp could you please create a test for the new method in the service layer?

2024-10-29 13:13 UTC, smottal requested changes

2024-10-29 13:13 UTC, smottal commented on modules/apps/account/account-test/src/testIntegration/java/com/liferay/account/service/test/AccountEntryLocalServiceTest.java
> +		Company company1 = CompanyTestUtil.addCompany();
can we avoid adding a new company? it's a very heavy (performance) task

2024-10-29 20:38 UTC, smottal commented
ci:test:sf

2024-10-29 20:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/6850/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6850/jenkins-report.html">here</a>.</b></p>

2024-10-29 20:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/242af868ceddfead4d65906b44cd7d4e7ce668a2">242af868ceddfead4d65906b44cd7d4e7ce668a2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorcdp/liferay-portal/tree/LPD-38670">LPD-38670</a><br/>Branch GIT ID: <a href="https://github.com/victorcdp/liferay-portal/commit/505cf4a0bb57078e313d0363e01042a53ec48693">505cf4a0bb57078e313d0363e01042a53ec48693</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6850/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6850/jenkins-report.html">here</a>.</h5></details></html>

2024-10-29 20:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6850/">test-portal-source-format#6850</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6850/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5472">liferay-commerce#5472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/55397949">[master] ci:test:sf - victorcdp &gt; liferay-commerce - PR#5472 - 2024-10-29[13:39:14]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>55397949<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/26804/">publish-testray-report#26804</a><br/></div></div>

2024-10-29 22:31 UTC, smottal commented
ci:forward

2024-10-29 22:31 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-29 22:31 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2024-10-29 22:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/6191/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6191/jenkins-report.html">here</a>.</b></p>

2024-10-30 08:00 UTC, smottal commented
ci:stop

2024-10-30 08:02 UTC, smottal commented
ci:test:relevant

2024-10-30 14:29 UTC, smottal commented
ci:test:relevant

2024-10-30 14:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12936/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12936/jenkins-report.html">here</a>.</b></p>

2024-10-30 16:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 42 out of 46 jobs passed in 1 hour 32 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0da72bb641af8b8be5d33d54f919c08ed3dd440b">0da72bb641af8b8be5d33d54f919c08ed3dd440b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d0b52765d46d39352692ddccd7138acdd8e06866">d0b52765d46d39352692ddccd7138acdd8e06866</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/55915318">EE Development Acceptance (master) - 963 - 2024-10-29[22:01:57]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 42 out of 46 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12936/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077727/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/951350/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1018447/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034625/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1243190/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015286/">js-unit/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1018434/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971108/">modules-compile/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012564/">modules-compile/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1224660/">modules-compile/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708837/">modules-compile/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012561/">modules-compile/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034624/">modules-compile/0/5</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/774404/">modules-compile/0/6</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968437/">modules-compile/0/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/951349/">modules-compile/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1224659/">modules-compile/0/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971106/">modules-compile/0/10</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/774406/">modules-compile/0/11</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131971/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034623/">modules-integration-mysql57/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015352/"><strike>modules-integration-mysql57/0/1</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/774403/">modules-integration-mysql57/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1243188/">modules-integration-mysql57/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708836/">modules-integration-mysql57/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971107/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077740/">modules-integration-mysql57/0/6</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1224717/"><strike>modules-integration-mysql57/0/7</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077741/">modules-integration-mysql57/0/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015296/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/774405/">modules-integration-mysql57/0/10</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1224716/"><strike>modules-integration-mysql57/0/11</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012562/">modules-integration-mysql57/0/12</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/951351/">modules-integration-mysql57/0/13</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1243189/">modules-integration-mysql57/0/14</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131970/">modules-integration-mysql57/0/15</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077742/">modules-integration-mysql57/0/16</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968439/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077728/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012563/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015298/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968436/">playwright-js-tomcat90-mysql57/0/ [...]

2024-10-30 16:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12936/">test-portal-acceptance-pullrequest(master)#12936</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12936/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5472">liferay-commerce#5472</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/56226217">[master] ci:test:relevant - victorcdp &gt; liferay-commerce - PR#5472 - 2024-10-30[07:29:43]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>56226217<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28272/">publish-testray-report#28272</a><br/></div></div>

2024-10-30 16:57 UTC, smottal commented
ci:forward:force

2024-10-30 16:59 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-30 16:59 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-10-30 17:00 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-33.liferay.com/job/forward-pullrequest/806//consoleFull)

2024-10-30 17:00 UTC, closed without merging

2024-10-30 17:00 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/155714
[Console](https://test-1-33.liferay.com/job/forward-pullrequest/806//consoleFull)