LPD-33676 LPD-33493 LPD-32234 LPD-32223 LPD-33831 LPD-32237 LPD-33783
liferay-commerce/liferay-portal pull request #5474
Opened 2024-10-09 02:11 UTC by gianmarcobrunialti

https://liferay.atlassian.net/browse/LPD-33676
https://liferay.atlassian.net/browse/LPD-33493
https://liferay.atlassian.net/browse/LPD-32234
https://liferay.atlassian.net/browse/LPD-32223
https://liferay.atlassian.net/browse/LPD-33831
https://liferay.atlassian.net/browse/LPD-32237
https://liferay.atlassian.net/browse/LPD-33783

Early PR, will split later. Currently at site init, fragment renderers with endorsing a configuration don't load up, but also field mappings are lost (native functionality).

Will investigate on fragment configurations, as they do load-up correctly if replaced by hand in the page.

2024-10-09 02:11 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-09 02:12 UTC, gianmarcobrunialti commented
ci:test:sf

2024-10-09 02:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6648/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6648/jenkins-report.html">here</a>.</b></p>

2024-10-09 02:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/80bc82dfb5df762c0b9d1f4ddee1bf97edeada8c">80bc82dfb5df762c0b9d1f4ddee1bf97edeada8c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/gianmarcobrunialti/liferay-portal/tree/LPD-34676-op">LPD-34676-op</a><br/>Branch GIT ID: <a href="https://github.com/gianmarcobrunialti/liferay-portal/commit/34f99b19673f322cf5857b497945309a6de83726">34f99b19673f322cf5857b497945309a6de83726</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6648/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6648/jenkins-report.html">here</a>.</h5></details></html>

2024-10-09 02:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6648/">test-portal-source-format#6648</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6648/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5474">liferay-commerce#5474</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/35970235">[master] ci:test:sf - gianmarcobrunialti &gt; liferay-commerce - PR#5474 - 2024-10-08[19:12:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>35970235<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/24781/">publish-testray-report#24781</a><br/></div></div>

2024-10-09 17:19 UTC, andrea-ale-sbarra requested changes
Overall looks good, just few changes.

Thank you!

2024-10-10 12:36 UTC, gianmarcobrunialti commented
Split in referenced PR's

2024-10-10 12:36 UTC, closed without merging