LPD-39452 - permissions on default roles revert when a hotfix is installed/the portal is updated
liferay-commerce/liferay-portal pull request #5515
Opened 2024-10-17 06:20 UTC by wanderlast

Hi @andrea-ale-sbarra,

https://liferay.atlassian.net/browse/LPD-39452, tied to LPP.

This is related to an issue where when the portal is upgraded or a hotfix is installed the permissions for default roles (e.g. Account Manager or Account Administrator) within the portal will revert to their default values. The cause is due to the fact that the portalInstanceRegistered method will run after an upgrade/update and therefore the permissions for these roles are being force reloaded. I've removed that specific attribute from being set here to prevent this from occurring.

I checked the reproduction steps for [LPD-3470](https://liferay.atlassian.net/browse/LPD-3470) (which is the original source of the attribute being added) locally and still didn't reproduce them with this fix deployed, so I do not believe this has caused a reversion in this behavior. Tests are also included.

As a note, I know this issue is technically related to Roles, but the issue/fix is in the CommerceServicePortalInstanceLifecycleListener and is related to code you worked on so I thought you would be the best person to take a look at it. Thanks!

2024-10-17 06:20 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-17 06:20 UTC, wanderlast commented
ci:test:sf

2024-10-17 06:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/5837/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5837/jenkins-report.html">here</a>.</b></p>

2024-10-17 06:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c5ede076937e208feae3b423e5e5b54883a68bce">c5ede076937e208feae3b423e5e5b54883a68bce</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/wanderlast/liferay-portal/tree/LPD-39452">LPD-39452</a><br/>Branch GIT ID: <a href="https://github.com/wanderlast/liferay-portal/commit/7a86d3592ac2f75bbf4365ec8e4276011cdc2509">7a86d3592ac2f75bbf4365ec8e4276011cdc2509</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/5837/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5837/jenkins-report.html">here</a>.</h5></details></html>

2024-10-17 06:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/5837/">test-portal-source-format#5837</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5837/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5515">liferay-commerce#5515</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/44225834">[master] ci:test:sf - wanderlast &gt; liferay-commerce - PR#5515 - 2024-10-16[23:20:44]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>44225834<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/6587/">publish-testray-report#6587</a><br/></div></div>

2024-10-23 07:05 UTC, smottal requested changes

2024-10-23 07:05 UTC, smottal commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/internal/instance/lifecycle/test/CommerceServicePortalInstanceLifecycleListenerTest.java
Because the creation of a company is a very "heavy" task I think it's better to create a single test that:
1) creates a new company
2) verifies if the  role is there
3) removes the permission
4) runs the listener
5) verifies that the role is still missing
6) deletes the company

2024-10-24 06:49 UTC, wanderlast commented
ci:test:sf

2024-10-24 06:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/7542/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7542/jenkins-report.html">here</a>.</b></p>

2024-10-24 06:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ff9815fa7c6e0c17a7e10fd9f56ff6e4d93af28a">ff9815fa7c6e0c17a7e10fd9f56ff6e4d93af28a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/wanderlast/liferay-portal/tree/LPD-39452">LPD-39452</a><br/>Branch GIT ID: <a href="https://github.com/wanderlast/liferay-portal/commit/dd8a0abeb871a9e03bf0b76ffcb2dd94b9d67e5e">dd8a0abeb871a9e03bf0b76ffcb2dd94b9d67e5e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7542/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7542/jenkins-report.html">here</a>.</h5></details></html>

2024-10-24 06:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7542/">test-portal-source-format#7542</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7542/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5515">liferay-commerce#5515</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/50554401">[master] ci:test:sf - wanderlast &gt; liferay-commerce - PR#5515 - 2024-10-23[23:50:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>50554401<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/5283/">publish-testray-report#5283</a><br/></div></div>

2024-10-24 09:28 UTC, smottal requested changes

2024-10-24 09:28 UTC, smottal commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/internal/instance/lifecycle/test/CommerceServicePortalInstanceLifecycleListenerTest.java
> +	private Company _company;
we don't need to have this global anymore

2024-10-24 09:28 UTC, smottal commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/internal/instance/lifecycle/test/CommerceServicePortalInstanceLifecycleListenerTest.java
> +	private ResourcePermission _resourcePermission;
we don't need to have this global anymore

2024-10-24 09:28 UTC, smottal commented on modules/apps/commerce/commerce-test/src/testIntegration/java/com/liferay/commerce/internal/instance/lifecycle/test/CommerceServicePortalInstanceLifecycleListenerTest.java
> +	private Role _role;
we don't need to have this global anymore

2024-10-25 04:51 UTC, wanderlast commented
ci:test:sf

2024-10-25 05:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/7303/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7303/jenkins-report.html">here</a>.</b></p>

2024-10-25 05:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1dbaed3be11b249c7cfd3dc514db825793b235ee">1dbaed3be11b249c7cfd3dc514db825793b235ee</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/wanderlast/liferay-portal/tree/LPD-39452">LPD-39452</a><br/>Branch GIT ID: <a href="https://github.com/wanderlast/liferay-portal/commit/e98c5d989076664eb52e71a20e17bf0ec0f86395">e98c5d989076664eb52e71a20e17bf0ec0f86395</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7303/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7303/jenkins-report.html">here</a>.</h5></details></html>

2024-10-25 05:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7303/">test-portal-source-format#7303</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7303/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5515">liferay-commerce#5515</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/51752065">[master] ci:test:sf - wanderlast &gt; liferay-commerce - PR#5515 - 2024-10-24[22:07:39]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>51752065<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/5245/">publish-testray-report#5245</a><br/></div></div>

2024-10-25 07:04 UTC, smottal approved these changes

2024-10-25 07:04 UTC, smottal commented
ci:test:relevant

2024-10-25 07:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12893/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12893/jenkins-report.html">here</a>.</b></p>

2024-10-25 09:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 101 out of 105 jobs passed in 2 hours 22 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/950">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_12893</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1dbaed3be11b249c7cfd3dc514db825793b235ee">1dbaed3be11b249c7cfd3dc514db825793b235ee</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5b6dca6081d3beb4ffc8f366a84452df78153d50">5b6dca6081d3beb4ffc8f366a84452df78153d50</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/51708710">EE Development Acceptance (master) - 949 - 2024-10-24[16:41:45]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 101 out of 105 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12893/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454773/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1009318/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012375/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454784/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/440584/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/480468/">js-unit/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/454774/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966377/">modules-compile/0/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/432182/">modules-compile/0/1</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377559/">modules-compile/0/2</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1074864/">modules-compile/0/3</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966376/">modules-compile/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/948620/">modules-compile/0/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1058044/">modules-compile/0/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032228/">modules-compile/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015418/">modules-compile/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1222023/">modules-compile/0/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1124112/">modules-compile/0/10</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/440583/">modules-compile/0/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/706253/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1239830/">modules-integration-mysql57/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1222025/">modules-integration-mysql57/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1129616/">modules-integration-mysql57/0/2</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1112201/">modules-integration-mysql57/0/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771323/">modules-integration-mysql57/0/4</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1222026/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1129617/">modules-integration-mysql57/0/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/706252/">modules-integration-mysql57/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1124113/">modules-integration-mysql57/0/8</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1239831/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/706251/">modules-integration-mysql57/0/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1112199/">modules-integration-mysql57/0/11</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1058045/">modules-integration-mysql57/0/12</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1222021/">modules-integration-mysql57/0/13</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1112198/">modules-integration-mysql57/0/14</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1222024/">modules-integration-mysql57/0/15</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/771322/">modules-integration-mysql57/0/16</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012373/">modules-integration-mysql57/0/17</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1112200/">modules-integration-mysql57/0/18</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1129615/">modules-integration-mysql57/0/19</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(maste [...]

2024-10-25 09:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12893/">test-portal-acceptance-pullrequest(master)#12893</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12893/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5515">liferay-commerce#5515</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/52013232">[master] ci:test:relevant - wanderlast &gt; liferay-commerce - PR#5515 - 2024-10-25[00:04:31]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>52013232<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28187/">publish-testray-report#28187</a><br/></div></div>

2024-10-28 07:43 UTC, smottal commented
ci:forward:force

2024-10-28 07:43 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-28 07:43 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-10-28 07:43 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-39.liferay.com/job/forward-pullrequest/1494//consoleFull)

2024-10-28 07:45 UTC, closed without merging

2024-10-28 07:45 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/155619
[Console](https://test-1-39.liferay.com/job/forward-pullrequest/1494//consoleFull)