LPD-39598 Fix poshi test
liferay-commerce/liferay-portal pull request #5531
Opened 2024-10-21 14:20 UTC by monaco-fabio

https://liferay.atlassian.net/browse/LPD-39598

2024-10-21 14:20 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-21 14:20 UTC, monaco-fabio commented
ci:test:sf

2024-10-21 14:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7376/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7376/jenkins-report.html">here</a>.</b></p>

2024-10-21 14:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/50b16974319ad31afc71a85d3c827c182ad636cc">50b16974319ad31afc71a85d3c827c182ad636cc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-39598">LPD-39598</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/1c58ee8896e5d0b4d7eb1394f991ac557188ec75">1c58ee8896e5d0b4d7eb1394f991ac557188ec75</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7376/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7376/jenkins-report.html">here</a>.</h5></details></html>

2024-10-21 14:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7376/">test-portal-source-format#7376</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7376/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5531">liferay-commerce#5531</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/47931703">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5531 - 2024-10-21[07:20:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>47931703<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28098/">publish-testray-report#28098</a><br/></div></div>

2024-10-24 15:06 UTC, monaco-fabio commented
ci:test:sf

2024-10-24 15:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/6284/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6284/jenkins-report.html">here</a>.</b></p>

2024-10-24 15:11 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6b2fbb841c388e3186d36d9261dbca0caed88998">6b2fbb841c388e3186d36d9261dbca0caed88998</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-39598">LPD-39598</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/ec76402564047f1eba48f67c35fca459dbe5d365">ec76402564047f1eba48f67c35fca459dbe5d365</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/6284/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6284/jenkins-report.html">here</a>.</h5><pre>     [java] Caused by: java.lang.RuntimeException: Unable to format ./modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceUnitsOfMeasure.testcase
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:718)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.access\$000(BaseSourceProcessor.java:69)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:101)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor\$1.call(BaseSourceProcessor.java:97)
     [java]   ... 4 more
     [java] Caused by: com.liferay.poshi.core.script.UnbalancedCodeException: Unmatched opening boundary at:
     [java] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceUnitsOfMeasure.testcase:2
     [java]   at com.liferay.poshi.core.script.PoshiScriptParserUtil.isBalancedPoshiScript(PoshiScriptParserUtil.java:238)
     [java]   at com.liferay.poshi.core.elements.PoshiNodeFactory.newPoshiNode(PoshiNodeFactory.java:100)
     [java]   at com.liferay.source.formatter.processor.PoshiSourceProcessor.parse(PoshiSourceProcessor.java:103)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:309)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor.format(BaseSourceProcessor.java:268)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._format(BaseSourceProcessor.java:601)
     [java]   at com.liferay.source.formatter.processor.BaseSourceProcessor._performTask(BaseSourceProcessor.java:703)
     [java]   ... 7 more
[stopwatch] [run.batch.test.action: 2:46.105 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-7/job/test-portal-source-format/6284//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20241024081114384.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20241024081114384.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.</pre></details></html>

2024-10-24 15:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/6284/">test-portal-source-format#6284</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6284/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5531">liferay-commerce#5531</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/50750776">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5531 - 2024-10-24[08:06:25]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>50750776<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/4125/">publish-testray-report#4125</a><br/></div></div>

2024-10-24 16:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/7302/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7302/jenkins-report.html">here</a>.</b></p>

2024-10-24 16:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/682c54a9f50c5448a06cd562456c0efa6e2198b7">682c54a9f50c5448a06cd562456c0efa6e2198b7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-39598">LPD-39598</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/925822edc07b63ef16b565247abb8adf74efc9f2">925822edc07b63ef16b565247abb8adf74efc9f2</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7302/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7302/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
     [java] SLF4J: Defaulting to no-operation (NOP) logger implementation
     [java] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceUnitsOfMeasure.testcase expected:&lt;...2.00");
     [java]       \}
     [java]     \}
     [java]   \}
     [java] [
     [java] ]\}&gt; but was:&lt;...2.00");
     [java]       \}
     [java]     \}
     [java]   \}
     [java] []\}&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:473)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 3:00.569 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-8/job/test-portal-source-format/7302//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20241024093733326.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20241024093733326.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null944400046.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1407189158
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 193ms
[junitreport] Deleting: /tmp/null1407189158
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2024-10-24 17:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7302/">test-portal-source-format#7302</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7302/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5531">liferay-commerce#5531</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/50847501">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5531 - 2024-10-24[09:32:15]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>50847501<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/5243/">publish-testray-report#5243</a><br/></div></div>

2024-10-25 08:06 UTC, monaco-fabio commented
ci:test:sf

2024-10-25 08:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3112/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3112/jenkins-report.html">here</a>.</b></p>

2024-10-25 08:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3112/">test-portal-source-format#3112</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3112/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5531">liferay-commerce#5531</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/51962081">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5531 - 2024-10-25[01:10:30]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>51962081<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/12756/">publish-testray-report#12756</a><br/></div></div>

2024-10-29 11:56 UTC, monaco-fabio commented
ci:test:sf

2024-10-29 11:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/8347/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8347/jenkins-report.html">here</a>.</b></p>

2024-10-29 12:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cb5de877e640621412771e788397eed6d63fa549">cb5de877e640621412771e788397eed6d63fa549</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-39598">LPD-39598</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/bebb8e9d3f0a73c36e9674b29b7d5dd070230bd7">bebb8e9d3f0a73c36e9674b29b7d5dd070230bd7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/8347/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8347/jenkins-report.html">here</a>.</h5></details></html>

2024-10-29 12:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/8347/">test-portal-source-format#8347</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8347/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5531">liferay-commerce#5531</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/54774725">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5531 - 2024-10-29[04:56:47]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>54774725<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/32845/">publish-testray-report#32845</a><br/></div></div>

2024-10-29 12:04 UTC, monaco-fabio commented
ci:test:playwright:nocompile

2024-10-29 12:04 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2024-10-29 12:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/14112/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/14112/jenkins-report.html">here</a>.</b></p>

2024-10-29 14:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 82 out of 103 jobs passed in 2 hours 31 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f6188570e4c3abad574c7b2ff681357efec5d4f3">f6188570e4c3abad574c7b2ff681357efec5d4f3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f6188570e4c3abad574c7b2ff681357efec5d4f3">f6188570e4c3abad574c7b2ff681357efec5d4f3</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/54696820">EE Development Acceptance (master) - 958 - 2024-10-29[00:44:16]</a></p><details><summary><strong>ci:test:playwright - 82 out of 103 jobs PASSED</strong></summary><div><h4>21 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/14112/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077112/">playwright-compile/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1017755/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485014/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485015/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034110/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1114646/"><strike>playwright-js-tomcat90-mysql57/4/0</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455958/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1224056/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1114651/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/967960/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/374740/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131457/"><strike>playwright-js-tomcat90-mysql57/10/0</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439113/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242487/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/950780/">playwright-js-tomcat90-mysql57/13/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034105/"><strike>playwright-js-tomcat90-mysql57/14/0</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011862/">playwright-js-tomcat90-mysql57/15/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242485/"><strike>playwright-js-tomcat90-mysql57/16/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/773879/">playwright-js-tomcat90-mysql57/17/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077110/">playwright-js-tomcat90-mysql57/18/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034108/">playwright-js-tomcat90-mysql57/19/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1126601/">playwright-js-tomcat90-mysql57/20/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077107/">playwright-js-tomcat90-mysql57/21/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/967961/">playwright-js-tomcat90-mysql57/22/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242484/">playwright-js-tomcat90-mysql57/23/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242488/">playwright-js-tomcat90-mysql57/24/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439108/">playwright-js-tomcat90-mysql57/25/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077111/"><strike>playwright-js-tomcat90-mysql57/26/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1017756/">playwright-js-tomcat90-mysql57/27/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/481692/">playwright-js-tomcat90-mysql57/28/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439107/"><strike>playwright-js-tomcat90-mysql57/29/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/950777/">playwright-js-tomcat90-mysql57/30/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034109/">playwright-js-tomcat90-mysql57/31/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441661/">playwright-js-tomcat90-mysql57/32/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/950775/">playwright-js-tomcat90-mysql57/33/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387641/">playwright-js-tomcat90-mysql57/34/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077114/">playwright-js-tomcat90-mysql57/35/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1224058/">playwright-js-tomcat90-mysql57/36/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1114647/">playwright-js-tomcat90-mysql57/37/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/481691/">playwright-js-tomcat90-mysql57/38/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242486/">playwright-js-tomcat90-mysql57/39/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/967959/"><strike>playwright-js-tomcat90-mysql57/40/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1131458/">playwright-js-tomcat90-mysql57/41/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034107 [...]

2024-10-29 14:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/14112/">test-portal-acceptance-pullrequest(master)#14112</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/14112/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5531">liferay-commerce#5531</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/54911110">[master] ci:test:playwright - monaco-fabio &gt; liferay-commerce - PR#5531 - 2024-10-29[05:05:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>54911110<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/32849/">publish-testray-report#32849</a><br/></div></div>

2024-10-30 08:50 UTC, andrea-ale-sbarra requested changes

2024-10-30 08:50 UTC, andrea-ale-sbarra commented on modules/test/playwright/tests/commerce/commerce-product-content-web/productDetails.spec.ts
> +	);
move these lines at the beginning of the test, the idea is to use variables close to where you declared it, if you create a catalog and the catalog is used after the account creation you are breaking the logical chain..

2024-10-30 16:21 UTC, monaco-fabio commented
ci:test:sf

2024-10-30 16:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3929/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3929/jenkins-report.html">here</a>.</b></p>

2024-10-30 16:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bc425dc709b850edaeaa392147145955720664a6">bc425dc709b850edaeaa392147145955720664a6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-39598">LPD-39598</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/60fbf6937ac64f24d61c7082c32441068beb2954">60fbf6937ac64f24d61c7082c32441068beb2954</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3929/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3929/jenkins-report.html">here</a>.</h5></details></html>

2024-10-30 16:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3929/">test-portal-source-format#3929</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3929/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5531">liferay-commerce#5531</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/56231076">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5531 - 2024-10-30[09:31:35]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>56231076<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/15387/">publish-testray-report#15387</a><br/></div></div>

2024-10-30 16:40 UTC, monaco-fabio commented
ci:test:playwright:nocompile

2024-10-30 16:40 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2024-10-30 17:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11595/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11595/jenkins-report.html">here</a>.</b></p>

2024-10-30 20:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 82 out of 103 jobs passed in 3 hours 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bc425dc709b850edaeaa392147145955720664a6">bc425dc709b850edaeaa392147145955720664a6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bc425dc709b850edaeaa392147145955720664a6">bc425dc709b850edaeaa392147145955720664a6</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/56324958">EE Development Acceptance (master) - 964 - 2024-10-30[08:41:01]</a></p><details><summary><strong>ci:test:playwright - 82 out of 103 jobs PASSED</strong></summary><div><h4>21 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11595/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1078036/">playwright-compile/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/482269/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378933/">playwright-js-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971377/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968687/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1243520/"><strike>playwright-js-tomcat90-mysql57/4/0</strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485556/">playwright-js-tomcat90-mysql57/5/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971378/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012884/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378931/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442209/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1078034/"><strike>playwright-js-tomcat90-mysql57/10/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1018769/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378935/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012885/">playwright-js-tomcat90-mysql57/13/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1127558/"><strike>playwright-js-tomcat90-mysql57/14/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015600/">playwright-js-tomcat90-mysql57/15/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968685/"><strike>playwright-js-tomcat90-mysql57/16/0</strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485558/">playwright-js-tomcat90-mysql57/17/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/774732/">playwright-js-tomcat90-mysql57/18/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/709110/">playwright-js-tomcat90-mysql57/19/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1078038/">playwright-js-tomcat90-mysql57/20/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/482267/">playwright-js-tomcat90-mysql57/21/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971374/">playwright-js-tomcat90-mysql57/22/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971376/">playwright-js-tomcat90-mysql57/23/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/482272/">playwright-js-tomcat90-mysql57/24/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1127557/"><strike>playwright-js-tomcat90-mysql57/25/0</strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442208/">playwright-js-tomcat90-mysql57/26/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1243521/">playwright-js-tomcat90-mysql57/27/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439643/">playwright-js-tomcat90-mysql57/28/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1132244/">playwright-js-tomcat90-mysql57/29/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1115575/">playwright-js-tomcat90-mysql57/30/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/774734/">playwright-js-tomcat90-mysql57/31/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1115580/">playwright-js-tomcat90-mysql57/32/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1224954/">playwright-js-tomcat90-mysql57/33/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1224956/">playwright-js-tomcat90-mysql57/34/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/482271/">playwright-js-tomcat90-mysql57/35/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/709114/">playwright-js-tomcat90-mysql57/36/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1132245/">playwright-js-tomcat90-mysql57/37/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456545/">playwright-js-tomcat90-mysql57/38/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439642/">playwright-js-tomcat90-mysql57/39/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/951642/"><strike>playwright-js-tomcat90-mysql57/40/0</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378932/">playwright-js-tomcat90-mysql57/41/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1115574/"><strike>playwright-js-tomca [...]

2024-10-30 21:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11595/">test-portal-acceptance-pullrequest(master)#11595</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11595/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5531">liferay-commerce#5531</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/56511785">[master] ci:test:playwright - monaco-fabio &gt; liferay-commerce - PR#5531 - 2024-10-30[10:22:54]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>56511785<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/25098/">publish-testray-report#25098</a><br/></div></div>

2024-10-31 13:56 UTC, andrea-ale-sbarra approved these changes
LGTM.
Thank you!

2024-10-31 13:58 UTC, andrea-ale-sbarra commented
ci:forward

2024-10-31 13:58 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-31 13:58 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-10-31 13:59 UTC, closed without merging