LPD-36951 Use quantity selector
liferay-commerce/liferay-portal pull request #5545
Opened 2024-10-24 09:16 UTC by smottal

https://liferay.atlassian.net/browse/LPD-36951

2024-10-24 09:16 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-24 09:16 UTC, smottal commented
ci:test:sf

2024-10-24 09:25 UTC, gianmarcobrunialti requested changes
Just 1 minor thing.

2024-10-24 09:25 UTC, gianmarcobrunialti commented on modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/components/quantity_selector/InputQuantitySelector.js
> +		if (!value || value < min) {
Nesting not needed.

2024-10-24 09:25 UTC, gianmarcobrunialti commented on modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/components/quantity_selector/InputQuantitySelector.js
> +	value,
[NB]: arguments have become many, being local we could consider converting from separate function arguments to a single object.

2024-10-24 09:25 UTC, gianmarcobrunialti commented on modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/components/quantity_selector/ListQuantitySelector.js
> +				options={(allowEmptyValue ? [''] : [])
NB: 🥹

2024-10-24 09:33 UTC, smottal commented
ci:test:sf

2024-10-24 10:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/8184/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8184/jenkins-report.html">here</a>.</b></p>

2024-10-24 10:27 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ddeb14626d6563c2fd73d3c85c5baa5f1270f95d">ddeb14626d6563c2fd73d3c85c5baa5f1270f95d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/smottal/liferay-portal/tree/LPD-36949-3">LPD-36949-3</a><br/>Branch GIT ID: <a href="https://github.com/smottal/liferay-portal/commit/15089c5044b8998b9a581c3f64a378db2675e4e3">15089c5044b8998b9a581c3f64a378db2675e4e3</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/8184/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8184/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ?????? Running preflight checks...
     [exec] 
     [exec] ?????? Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ?????? Running TypeScript checks on modified files...
     [exec] ?????? A total of 8 CPUs were detected: launching tsc using 8 workers
     [exec] ??? Checked apps/commerce/commerce-order-content-web
     [exec]    src/main/resources/META-INF/resources/js/multishipping/OrderItemRow.tsx(15,8): error TS7016: Could not find a declaration file for module 'commerce-frontend-js'. '/opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/index.js' implicitly has an 'any' type.
     [exec] 
     [exec] 
     [exec] ?????? Running format checks on modified files...
     [exec] ??? CI checks failed.
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-10-24 10:27:14.475.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)</pre></details></html>

2024-10-24 10:31 UTC, smottal commented
ci:test:sf

2024-10-24 10:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/7298/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7298/jenkins-report.html">here</a>.</b></p>

2024-10-24 10:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/8184/">test-portal-source-format#8184</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8184/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5545">liferay-commerce#5545</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/50637275">[master] ci:test:sf - smottal &gt; liferay-commerce - PR#5545 - 2024-10-24[03:22:02]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>50637275<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4558/">publish-testray-report#4558</a><br/></div></div>

2024-10-24 10:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ddeb14626d6563c2fd73d3c85c5baa5f1270f95d">ddeb14626d6563c2fd73d3c85c5baa5f1270f95d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/smottal/liferay-portal/tree/LPD-36949-3">LPD-36949-3</a><br/>Branch GIT ID: <a href="https://github.com/smottal/liferay-portal/commit/f191a47ffda8024649283452d1b87cdd210bcd85">f191a47ffda8024649283452d1b87cdd210bcd85</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7298/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7298/jenkins-report.html">here</a>.</h5></details></html>

2024-10-24 10:37 UTC, smottal commented
ci:test:relevant

2024-10-24 10:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7298/">test-portal-source-format#7298</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7298/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5545">liferay-commerce#5545</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/50637293">[master] ci:test:sf - smottal &gt; liferay-commerce - PR#5545 - 2024-10-24[03:31:48]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>50637293<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/5239/">publish-testray-report#5239</a><br/></div></div>

2024-10-24 12:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12879/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12879/jenkins-report.html">here</a>.</b></p>

2024-10-24 16:30 UTC, smottal commented
ci:stop

2024-10-24 16:31 UTC, smottal commented
ci:test:relevant

2024-10-24 16:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 3 out of 3 jobs passed</h3><h3>:x: ci:test:relevant - 4 out of 5 jobs passed in 4 hours 27 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/947">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_12879</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ddeb14626d6563c2fd73d3c85c5baa5f1270f95d">ddeb14626d6563c2fd73d3c85c5baa5f1270f95d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ff9815fa7c6e0c17a7e10fd9f56ff6e4d93af28a">ff9815fa7c6e0c17a7e10fd9f56ff6e4d93af28a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/50688306">EE Development Acceptance (master) - 946 - 2024-10-24[02:44:51]</a></p><details><summary><strong>ci:test:stable - 3 out of 3 jobs PASSED</strong></summary><details><summary><strong>3 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 4 out of 5 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12879/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/479662/">central-requirements/0/0</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/431498/">js-unit/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/479663/">js-unit/1/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/964968/">modules-semantic-versioning/0/0</a></li></ul></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12879/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12879/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>4 Jobs Passed.<br/>1 Job Failed.</p></div><pre>[beanshell]     https://github-proxy-ujidqcdz2q-wl.a.run.app/repos/liferay-commerce/liferay-portal/statuses/f191a47ffda8024649283452d1b87cdd210bcd85
[beanshell] https://testray.liferay.com/o/graphql query: \{c \{routines (page: 1, pageSize: 1, filter: "id eq '590307'") \{items \{dateCreated dateModified id name routineToProjects \} page pageSize lastPage\}\}\} in 613 ms
[beanshell] https://testray.liferay.com/o/graphql query: \{c \{builds (page: 1, pageSize: 25, filter: "r_routineToBuilds_c_routineId eq '590307'", sort: "dateCreated:desc") \{items \{dateCreated dateModified description dueDate dueStatus \{key name\} githubCompareURLs gitHash id name productVersionToBuilds projectToBuilds routineToBuilds \} page pageSize lastPage\}\}\} in 798 ms
[beanshell] https://testray.liferay.com/o/graphql query: \{c \{projects (page: 1, pageSize: 1, filter: "id eq '35392'") \{items \{dateCreated dateModified description id name \} page pageSize lastPage\}\}\} in 407 ms
[beanshell] Executing commands: git merge-base --is-ancestor ddeb14626d6563c2fd73d3c85c5baa5f1270f95d HEAD
[beanshell] https://testray.liferay.com/o/graphql query: \{c \{caseResults (page: 1, pageSize: 5, filter: "r_buildToCaseResult_c_buildId eq '50751153'") \{items \{attachments buildToCaseResult caseToCaseResult componentToCaseResult dateCreated dateModified dueStatus \{ key name \} errors id startDate \} page pageSize lastPage\}\}\} in 675 ms
[beanshell] https://storage.cloud.google.com/testray-results/2024-10/test-1-40/test-portal-acceptance-upstream-dxp(master)/947/build-report.json.gz in 85 ms
[beanshell] Executing commands: git merge-base --is-ancestor ff9815fa7c6e0c17a7e10fd9f56ff6e4d93af28a HEAD
[beanshell] https://testray.liferay.com/o/graphql query: \{c \{caseResults (page: 1, pageSize: 5, filter: "r_buildToCaseResult_c_buildId eq '50688306'") \{items \{attachments buildToCaseResult caseToCaseResult componentToCaseResult dateCreated dateModified dueStatus \{ key name \} errors id startDate \} page pageSize lastPage\}\}\} in 574 ms
[beanshell] https://storage.cloud.google.com/testray-results/2024-10/test-1-40/test-portal-acceptance-upstream-dxp(master)/946/build-report.json.gz in 393 ms
[beanshell] Comparing with test results from https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/946 at SHA ff9815fa7c6e0c17a7e10fd9f56ff6e4d93af28a
[beanshell] 
[beanshell] Unique Failures:
[beanshell] 
[beanshell] Upstream Failures:
[beanshell] Collected 0 downstream failure messages</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-10-24 16:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12879/">test-portal-acceptance-pullrequest(master)#12879</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12879/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5545">liferay-commerce#5545</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/50815606">[master] ci:test:relevant - smottal &gt; liferay-commerce - PR#5545 - 2024-10-24[05:05:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>50815606<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28161/">publish-testray-report#28161</a><br/></div></div>

2024-10-24 21:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6886/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6886/jenkins-report.html">here</a>.</b></p>

2024-10-25 02:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 102 out of 105 jobs passed in 4 hours 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/682c54a9f50c5448a06cd562456c0efa6e2198b7">682c54a9f50c5448a06cd562456c0efa6e2198b7</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ff9815fa7c6e0c17a7e10fd9f56ff6e4d93af28a">ff9815fa7c6e0c17a7e10fd9f56ff6e4d93af28a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/50688306">EE Development Acceptance (master) - 946 - 2024-10-24[02:44:51]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 101 out of 105 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6886/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966084/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123755/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/432011/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/440362/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/386405/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123717/">js-unit/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1221715/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/386403/">modules-compile/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012132/">modules-compile/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/705933/">modules-compile/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/770974/">modules-compile/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015049/">modules-compile/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012130/">modules-compile/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015048/">modules-compile/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123756/">modules-compile/0/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012131/">modules-compile/0/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123759/">modules-compile/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/770976/">modules-compile/0/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123762/">modules-compile/0/11</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/386404/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968183/">modules-integration-mysql57/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015052/">modules-integration-mysql57/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1239486/">modules-integration-mysql57/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1012133/">modules-integration-mysql57/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031915/">modules-integration-mysql57/0/4</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1129308/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968184/">modules-integration-mysql57/0/6</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/966100/">modules-integration-mysql57/0/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/770978/">modules-integration-mysql57/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1221742/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968179/">modules-integration-mysql57/0/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968178/">modules-integration-mysql57/0/11</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123758/">modules-integration-mysql57/0/12</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1015047/">modules-integration-mysql57/0/13</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123757/">modules-integration-mysql57/0/14</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968181/">modules-integration-mysql57/0/15</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/968182/">modules-integration-mysql57/0/16</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031913/">modules-integration-mysql57/0/17</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1074494/">modules-integration-mysql57/0/18</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1129307/">modules-integration-mysql57/0/19</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1221743/">modules-integration-mysql57/0/20</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1031919/">modules-integration-mysql57/0/21</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1239487/">modules-integration-mysql57/0/22</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-p [...]

2024-10-25 02:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6886/">test-portal-acceptance-pullrequest(master)#6886</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6886/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5545">liferay-commerce#5545</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/51529120">[master] ci:test:relevant - smottal &gt; liferay-commerce - PR#5545 - 2024-10-24[14:50:02]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>51529120<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/15363/">publish-testray-report#15363</a><br/></div></div>

2024-10-25 07:02 UTC, smottal commented
ci:forward

2024-10-25 07:02 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-25 07:02 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-10-25 07:02 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-9.liferay.com/job/forward-pullrequest/740//consoleFull)

2024-10-25 07:03 UTC, closed without merging

2024-10-25 07:03 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/155554
[Console](https://test-1-9.liferay.com/job/forward-pullrequest/740//consoleFull)