LPD-35329 Add functional test for checkout with Multi Shipping
liferay-commerce/liferay-portal pull request #5559
Opened 2024-10-29 09:36 UTC by monaco-fabio

https://liferay.atlassian.net/browse/LPD-35329

2024-10-29 09:37 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-29 09:37 UTC, monaco-fabio commented
ci:test:sf

2024-10-29 09:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7414/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7414/jenkins-report.html">here</a>.</b></p>

2024-10-29 09:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cb5de877e640621412771e788397eed6d63fa549">cb5de877e640621412771e788397eed6d63fa549</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-35329">LPD-35329</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/61b8b51899f8aa470786b0fe4e0e5c3fa40b6bc9">61b8b51899f8aa470786b0fe4e0e5c3fa40b6bc9</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7414/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7414/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/commerce/commerce-checkout-web/src/main/resources/META-INF/resources/init.jsp expected:&lt;...e import="java.text.[]Format" %&gt;
     [java] 
     [java] &lt;%@ page...&gt; but was:&lt;...e import="java.text.[DateFormat" %&gt;&lt;%@
     [java] page import="java.text.]Format" %&gt;
     [java] 
     [java] &lt;%@ page...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:473)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 2:25.036 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-27/job/test-portal-source-format/7414//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20241029024135488.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20241029024135488.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1614464507.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null786065939
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 167ms
[junitreport] Deleting: /tmp/null786065939
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 10-29-2024 02:41:39:564 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2024-10-29 09:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7414/">test-portal-source-format#7414</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7414/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5559">liferay-commerce#5559</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/54636173">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5559 - 2024-10-29[02:37:15]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>54636173<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28238/">publish-testray-report#28238</a><br/></div></div>

2024-10-29 09:45 UTC, monaco-fabio commented
ci:test:sf

2024-10-29 09:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10469/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10469/jenkins-report.html">here</a>.</b></p>

2024-10-29 09:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cb5de877e640621412771e788397eed6d63fa549">cb5de877e640621412771e788397eed6d63fa549</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-35329">LPD-35329</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/147a3a0e1390b67205fb38e8f415c70b31bc729f">147a3a0e1390b67205fb38e8f415c70b31bc729f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10469/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10469/jenkins-report.html">here</a>.</h5></details></html>

2024-10-29 09:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10469/">test-portal-source-format#10469</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10469/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5559">liferay-commerce#5559</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/54636228">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5559 - 2024-10-29[02:45:44]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>54636228<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/39912/">publish-testray-report#39912</a><br/></div></div>

2024-10-29 09:56 UTC, monaco-fabio commented
ci:test:relevant

2024-10-29 09:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10351/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10351/jenkins-report.html">here</a>.</b></p>

2024-10-29 11:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 42 out of 46 jobs passed in 1 hour 31 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cb5de877e640621412771e788397eed6d63fa549">cb5de877e640621412771e788397eed6d63fa549</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f2d3fe5c3f6698a4bbb458e01d01bb43686d4246">f2d3fe5c3f6698a4bbb458e01d01bb43686d4246</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/54636290">EE Development Acceptance (master) - 957 - 2024-10-28[23:37:30]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 42 out of 46 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10351/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242350/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1017635/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1014552/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1017637/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1114544/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1126473/">js-unit/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1014548/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1017638/">modules-compile/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1114545/">modules-compile/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011741/">modules-compile/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1223945/">modules-compile/0/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/950659/">modules-compile/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011738/">modules-compile/0/5</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1076995/">modules-compile/0/6</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1034006/">modules-compile/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011740/">modules-compile/0/8</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/773762/">modules-compile/0/9</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011737/">modules-compile/0/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242362/">modules-compile/0/11</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1223944/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1114576/"><strike>modules-integration-mysql57/0/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/773760/">modules-integration-mysql57/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1223942/">modules-integration-mysql57/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1126480/">modules-integration-mysql57/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242359/">modules-integration-mysql57/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/773761/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1017636/">modules-integration-mysql57/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011775/"><strike>modules-integration-mysql57/0/7</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/773763/">modules-integration-mysql57/0/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708177/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242360/">modules-integration-mysql57/0/10</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1126481/">modules-integration-mysql57/0/11</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011739/">modules-integration-mysql57/0/12</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1223943/">modules-integration-mysql57/0/13</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242399/"><strike>modules-integration-mysql57/0/14</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708178/">modules-integration-mysql57/0/15</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1114546/">modules-integration-mysql57/0/16</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1076996/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242351/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1242361/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/970472/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/950657/">playwright-js-tomcat90-mysq [...]

2024-10-29 11:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10351/">test-portal-acceptance-pullrequest(master)#10351</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10351/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5559">liferay-commerce#5559</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/54728874">[master] ci:test:relevant - monaco-fabio &gt; liferay-commerce - PR#5559 - 2024-10-29[02:57:04]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>54728874<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/24633/">publish-testray-report#24633</a><br/></div></div>

2024-10-30 08:58 UTC, smottal requested changes

2024-10-30 08:58 UTC, smottal commented on modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/constants/CommerceCheckoutFDSNames.java
> +	public static final String DELIVERY_GROUP =
usually, in other places, we use the plural version (like in CommerceAccountFDSNames.java or CommerceAddressFDSNames.java)

2024-10-30 08:58 UTC, smottal commented on modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/display/context/DeliveryGroupDisplayContext.java
> +	public Date getDeliveryGroupDate(HttpServletRequest httpServletRequest) {
is it fine to have deliveryDate in the request and the method called getDelivery**Group**Date?

2024-10-30 08:58 UTC, smottal commented on modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/model/DeliveryGroup.java
> +		String addressSummary, long addressId, Date deliveryDate, String name) {
sort parameters

2024-10-30 08:58 UTC, smottal commented on modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/model/DeliveryGroup.java
> +		_addressId = addressId;
sort these

2024-10-30 08:58 UTC, smottal commented on modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/CommerceOrderUtil.java
> +		return deliveryGroups.size();
is not possible to do a dslquery to do a count(distinct deliveryGroup) from orderitem where order = XXX ?

2024-10-30 08:58 UTC, smottal commented on modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/CommerceOrderUtil.java
> +		return false;
and in case of dslquery here just check the the count is greater then 0

2024-10-30 08:58 UTC, smottal commented on modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/ShippingMethodCommerceCheckoutStep.java
> +
wy do we need to have this here and not inside the if (line 207)

2024-10-30 08:58 UTC, smottal commented on modules/apps/commerce/commerce-checkout-web/src/main/resources/META-INF/resources/view_commerce_checkout_delivery_group.jsp
> +			<span><%= region.getName() %></span>
I'm not sure but I think the region can remain null (and here we will have a NPE)

2024-10-30 08:58 UTC, smottal commented on modules/apps/commerce/commerce-checkout-web/src/main/resources/META-INF/resources/view_commerce_checkout_delivery_group.jsp
> +			<span><%= region.getName() %></span>
also I think we need to call the getName(locale) like we do for the country

2024-10-30 08:58 UTC, smottal commented on modules/test/playwright/pages/commerce/commerce-checkout-web/checkoutPage.ts
> +		this.iframeOkButton = page.getByLabel('close', {exact: true});
why we are calling it iframe**Ok**Button if the label is "close"? can we call it iframeCloseButton?

2024-10-30 08:58 UTC, smottal commented on modules/test/playwright/pages/commerce/commerce-checkout-web/checkoutPage.ts
> +		this.viewDeliveryGroupTable = page.getByLabel('view');
mmm... I don't think it's a table

2024-10-30 08:58 UTC, smottal commented on modules/test/playwright/tests/commerce/commerce-checkout-web/checkout.spec.ts
> +	);
is not possible to create the address and then do the postCart already with the delivery groups info? in this way we avoid a post + patch

2024-10-30 08:58 UTC, smottal commented on modules/test/playwright/tests/commerce/commerce-checkout-web/checkout.spec.ts
> +	await checkoutPage.viewDeliveryGroupTable.click();
add a new line before this

2024-10-30 08:58 UTC, smottal commented on modules/test/playwright/tests/commerce/commerce-checkout-web/checkout.spec.ts
> +	await expect(
add a new line before this

2024-10-30 08:58 UTC, smottal commented on modules/test/playwright/tests/commerce/commerce-checkout-web/checkout.spec.ts
> +	await checkoutPage.iframeOkButton.click();
add a new line before this

2024-10-30 09:31 UTC, luca-pellizzon commented
sent https://github.com/liferay-commerce/liferay-portal/pull/5564

2024-10-30 09:31 UTC, closed without merging