LPD-37883
liferay-commerce/liferay-portal pull request #5584
Opened 2024-11-04 17:27 UTC by andrea-ale-sbarra

https://liferay.atlassian.net/browse/LPD-37883

2024-11-04 17:27 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-11-04 17:27 UTC, andrea-ale-sbarra commented
ci:test:sf

2024-11-04 17:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10545/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10545/jenkins-report.html">here</a>.</b></p>

2024-11-04 17:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29046032b0c029e009060cf13ee2fbce9b6ef611">29046032b0c029e009060cf13ee2fbce9b6ef611</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/LPD-37883">LPD-37883</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/9e50278c01887a50a535249ffd958f6ec75ac16c">9e50278c01887a50a535249ffd958f6ec75ac16c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10545/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10545/jenkins-report.html">here</a>.</h5></details></html>

2024-11-04 17:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10545/">test-portal-source-format#10545</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10545/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5584">liferay-commerce#5584</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/59461124">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#5584 - 2024-11-04[09:29:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>59461124<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/40141/">publish-testray-report#40141</a><br/></div></div>

2024-11-05 09:28 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/spi/model/index/contributor/CPConfigurationEntryModelIndexerWriterContributor.java
> +	private final CPDefinitionLocalService _cpDefinitionLocalService;
CPDefinitionLocalService -> CPConfigurationEntryLocalService

2024-11-05 09:28 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/spi/model/index/contributor/CPConfigurationEntryModelIndexerWriterContributor.java
> +			(CPDefinition cpDefinition) -> batchIndexingActionable.addDocuments(
CPDefinition -> CPConfigurationEntry

2024-11-05 09:29 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/CPConfigurationEntryModelSearchConfigurator.java
> +	private CPDefinitionLocalService _cpDefinitionLocalService;
CPDefinitionLocalService -> CPConfigurationEntryLocalService

2024-11-07 16:51 UTC, andrea-ale-sbarra commented
ci:test:sf

2024-11-07 16:51 UTC, andrea-ale-sbarra commented
ci:test:relevant

2024-11-07 16:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10660/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10660/jenkins-report.html">here</a>.</b></p>

2024-11-07 16:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/6949/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6949/jenkins-report.html">here</a>.</b></p>

2024-11-07 16:56 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5021d89580a3c160ee272e800a8811fcb1c9352">a5021d89580a3c160ee272e800a8811fcb1c9352</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/LPD-37883">LPD-37883</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/88408564a47c60e0a2a2483598eb01672c34b6a1">88408564a47c60e0a2a2483598eb01672c34b6a1</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6949/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6949/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./modules/apps/commerce/commerce-product-api/src/main/java/com/liferay/commerce/product/exception/DuplicateCPConfigurationListException.java expected:&lt;...A-2.0.0-2023-06
     [java]  */
     [java] [
     [java] package com.liferay.commerce.product.exception;
     [java] 
     [java] import com.liferay.portal.kernel.exception.PortalException;
     [java] 
     [java] /**
     [java]  * @author Marco Leo
     [java]  */
     [java] public class DuplicateCPConfigurationListException extends PortalException \{
     [java] 
     [java]   public DuplicateCPConfigurationListException() \{
     [java]   \}
     [java] 
     [java]   public DuplicateCPConfigurationListException(String msg) \{
     [java]     super(msg);
     [java]   \}
     [java] 
     [java]   public DuplicateCPConfigurationListException(
     [java]     String msg, Throwable throwable) \{
     [java] ]
     [java]     super(msg, throwa...&gt; but was:&lt;...A-2.0.0-2023-06
     [java]  */
     [java] [package com.liferay.commerce.product.exception;
     [java] 
     [java] import com.liferay.portal.kernel.exception.PortalException;
     [java] 
     [java] /**
     [java]  * @author Marco Leo
     [java]  */
     [java] public class DuplicateCPConfigurationListException extends PortalException \{
     [java] 
     [java]   public DuplicateCPConfigurationListException() \{
     [java]   \}
     [java] 
     [java]   public DuplicateCPConfigurationListException(String msg) \{
     [java]     super(msg);
     [java]   \}
     [java] 
     [java]   public DuplicateCPConfigurationListException(String msg, Throwable throwable) \{]
     [java]     super(msg, throwa...&gt;
     [java] 2: ./modules/apps/commerce/commerce-product-api/src/main/java/com/liferay/commerce/product/exception/CPConfigurationListParentCPConfigurationListGroupIdException.java expected:&lt;...A-2.0.0-2023-06
     [java]  */
     [java] [
     [java] package com.liferay.commerce.product.exception;
     [java] 
     [java] import com.liferay.portal.kernel.exception.PortalException;
     [java] 
     [java] /**
     [java]  * @author Marco Leo
     [java]  */
     [java] public class CPConfigurationListParentCPConfigurationListGroupIdException
     [java]   extends PortalException \{
     [java] 
     [java]   public CPConfigurationListParentCPConfigurationListGroupIdException() \{
     [java]   \}
     [java] </pre></details></html>

2024-11-07 17:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6949/">test-portal-source-format#6949</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6949/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5584">liferay-commerce#5584</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/62791487">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#5584 - 2024-11-07[08:51:35]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>62791487<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/25388/">publish-testray-report#25388</a><br/></div></div>

2024-11-07 18:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 43 out of 46 jobs passed in 1 hour 49 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/993">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1297401_10660</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5021d89580a3c160ee272e800a8811fcb1c9352">a5021d89580a3c160ee272e800a8811fcb1c9352</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fb7e2292138e7b9d0309a2b503ce18541d891259">fb7e2292138e7b9d0309a2b503ce18541d891259</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/62739968">EE Development Acceptance (master) - 992 - 2024-11-07[04:41:47]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 43 out of 46 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10660/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485433/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390564/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/779086/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442097/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390566/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/381305/">js-unit/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459751/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/957623/">modules-compile/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459755/">modules-compile/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390567/">modules-compile/0/2</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/488769/">modules-compile/0/3</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/390565/">modules-compile/0/4</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/436164/">modules-compile/0/5</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442096/">modules-compile/0/6</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/488767/">modules-compile/0/7</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/488768/">modules-compile/0/8</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459752/">modules-compile/0/9</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/436163/">modules-compile/0/10</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459754/">modules-compile/0/11</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/459753/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1084159/">modules-integration-mysql57/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1084160/">modules-integration-mysql57/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1084158/">modules-integration-mysql57/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025443/"><strike>modules-integration-mysql57/0/3</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1063520/">modules-integration-mysql57/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/779085/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1063518/">modules-integration-mysql57/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1250376/">modules-integration-mysql57/0/7</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1137109/">modules-integration-mysql57/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025410/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1084162/">modules-integration-mysql57/0/10</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1084161/">modules-integration-mysql57/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025409/">modules-integration-mysql57/0/12</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025408/">modules-integration-mysql57/0/13</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025442/"><strike>modules-integration-mysql57/0/14</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025411/">modules-integration-mysql57/0/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1250377/">modules-integration-mysql57/0/16</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1019258/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1063516/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/37 [...]

2024-11-08 08:06 UTC, alessiorendina requested changes
@andrea-ale-sbarra LGTM overall, just a small changes and a question. Thank you!

2024-11-08 08:06 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPConfigurationListLocalServiceImpl.java
> +		return cpConfigurationListPersistence.findByG_MasterCPConfigurationList(
Can we change the finder name to `G_M` instead of `G_MasterCPConfigurationList`?

2024-11-08 08:06 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/spi/model/index/contributor/CPConfigurationEntryModelDocumentContributor.java
> +
Remove empty line

2024-11-08 08:06 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/spi/model/index/contributor/CPConfigurationEntryModelDocumentContributor.java
> +
Remove empty line

2024-11-08 08:06 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/spi/model/index/contributor/CPConfigurationEntryModelDocumentContributor.java
> +
Remove empty line

2024-11-08 09:34 UTC, andrea-ale-sbarra commented
ci:forward

2024-11-08 09:34 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-11-08 09:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11691/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11691/jenkins-report.html">here</a>.</b></p>

2024-11-08 09:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/8251/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8251/jenkins-report.html">here</a>.</b></p>

2024-11-08 09:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ea9e91dd1de379fdc9d2282b23d1b07d31afb02e">ea9e91dd1de379fdc9d2282b23d1b07d31afb02e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/tree/LPD-37883">LPD-37883</a><br/>Branch GIT ID: <a href="https://github.com/andrea-ale-sbarra/liferay-portal/commit/c156c622794b2b2b531ef69a1707ebee57ed4b11">c156c622794b2b2b531ef69a1707ebee57ed4b11</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/8251/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8251/jenkins-report.html">here</a>.</h5></details></html>

2024-11-08 09:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/8251/">test-portal-source-format#8251</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/8251/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5584">liferay-commerce#5584</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/63388768">[master] ci:test:sf - andrea-ale-sbarra &gt; liferay-commerce - PR#5584 - 2024-11-08[01:35:07]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>63388768<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4624/">publish-testray-report#4624</a><br/></div></div>

2024-11-08 11:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11691/">test-portal-acceptance-pullrequest(master)#11691</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11691/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5584">liferay-commerce#5584</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/63573355">[master] ci:test:relevant - andrea-ale-sbarra &gt; liferay-commerce - PR#5584 - 2024-11-08[01:35:01]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>63573355<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/25350/">publish-testray-report#25350</a><br/></div></div>

2024-11-08 14:16 UTC, andrea-ale-sbarra commented
ci:forward:force

2024-11-08 14:17 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-11-08 14:17 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-11-08 14:17 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1571//consoleFull)

2024-11-08 14:18 UTC, closed without merging

2024-11-08 14:18 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/156008
[Console](https://test-1-40.liferay.com/job/forward-pullrequest/1571//consoleFull)