LPD-39086 - Sort by Last Login Date appears to be sorting by Last Name
liferay-commerce/liferay-portal pull request #5587
Opened 2024-11-05 09:13 UTC by brbalazs

https://liferay.atlassian.net/browse/LPD-39086

2024-11-05 09:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-11-05 09:13 UTC, brbalazs commented
ci:test:sf

2024-11-05 09:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/7571/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7571/jenkins-report.html">here</a>.</b></p>

2024-11-05 09:18 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/52b71bc3c1114afaf74f3375139a83f21d56c3e0">52b71bc3c1114afaf74f3375139a83f21d56c3e0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brbalazs/liferay-portal/tree/LPD-39086">LPD-39086</a><br/>Branch GIT ID: <a href="https://github.com/brbalazs/liferay-portal/commit/8c20779a23bdaea8c3323a573cea1127e4297138">8c20779a23bdaea8c3323a573cea1127e4297138</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7571/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7571/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-kernel/src/com/liferay/portal/kernel/util/comparator/UserLastLoginDateComparator.java expected:&lt;...opyrightText: (c) 20[24] Liferay, Inc. https...&gt; but was:&lt;...opyrightText: (c) 20[00] Liferay, Inc. https...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:473)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 2:20.824 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-6/job/test-portal-source-format/7571//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20241105011823903.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20241105011823903.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1117255645.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1900768929
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 177ms
[junitreport] Deleting: /tmp/null1900768929
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 11-05-2024 01:18:29:266 PST
[stopwatch] [run.batch.test.tear.down: 0.001 sec]
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.</pre></details></html>

2024-11-05 09:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7571/">test-portal-source-format#7571</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7571/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5587">liferay-commerce#5587</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/59968725">[master] ci:test:sf - brbalazs &gt; liferay-commerce - PR#5587 - 2024-11-05[01:14:13]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>59968725<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/5312/">publish-testray-report#5312</a><br/></div></div>

2024-11-05 09:24 UTC, brbalazs commented
ci:test:sf

2024-11-05 09:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/9295/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9295/jenkins-report.html">here</a>.</b></p>

2024-11-05 09:42 UTC, smottal requested changes

2024-11-05 09:42 UTC, smottal commented on portal-kernel/src/com/liferay/portal/kernel/util/comparator/UserLastLoginDateComparator.java
> + * @author Brian Wing Shun Chan
mmm

2024-11-05 09:56 UTC, brbalazs commented
ci:test:sf

2024-11-05 09:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3701/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3701/jenkins-report.html">here</a>.</b></p>

2024-11-05 10:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/52b71bc3c1114afaf74f3375139a83f21d56c3e0">52b71bc3c1114afaf74f3375139a83f21d56c3e0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brbalazs/liferay-portal/tree/LPD-39086">LPD-39086</a><br/>Branch GIT ID: <a href="https://github.com/brbalazs/liferay-portal/commit/77bc8c0c82ffed6478b0272c2f3c21c661278c52">77bc8c0c82ffed6478b0272c2f3c21c661278c52</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3701/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3701/jenkins-report.html">here</a>.</h5></details></html>

2024-11-05 10:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3701/">test-portal-source-format#3701</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3701/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5587">liferay-commerce#5587</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/59974999">[master] ci:test:sf - brbalazs &gt; liferay-commerce - PR#5587 - 2024-11-05[01:57:00]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>59974999<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/15256/">publish-testray-report#15256</a><br/></div></div>

2024-11-05 10:18 UTC, brbalazs commented
ci:test:relevant

2024-11-05 10:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12979/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12979/jenkins-report.html">here</a>.</b></p>

2024-11-05 11:57 UTC, brbalazs commented
ci:stop

2024-11-05 11:59 UTC, brbalazs commented
ci:test:sf

2024-11-05 12:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12983/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12983/jenkins-report.html">here</a>.</b></p>

2024-11-05 12:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/6369/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6369/jenkins-report.html">here</a>.</b></p>

2024-11-05 12:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5e032e394aa5a9423586cecf372df569abc654e">a5e032e394aa5a9423586cecf372df569abc654e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brbalazs/liferay-portal/tree/LPD-39086">LPD-39086</a><br/>Branch GIT ID: <a href="https://github.com/brbalazs/liferay-portal/commit/41ac89c855b3ee6ae09c36e94480348ee2ac520e">41ac89c855b3ee6ae09c36e94480348ee2ac520e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6369/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6369/jenkins-report.html">here</a>.</h5></details></html>

2024-11-05 12:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 104 out of 139 jobs passed in 1 hour 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/52b71bc3c1114afaf74f3375139a83f21d56c3e0">52b71bc3c1114afaf74f3375139a83f21d56c3e0</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/52b71bc3c1114afaf74f3375139a83f21d56c3e0">52b71bc3c1114afaf74f3375139a83f21d56c3e0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/59989600">EE Development Acceptance (master) - 982 - 2024-11-04[23:04:11]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 104 out of 139 jobs PASSED</strong></summary><div><h4>35 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12979/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023303/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023312/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082551/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/713179/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038754/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120216/">js-unit/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082533/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023316/">modules-compile/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/713173/">modules-compile/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1229188/">modules-compile/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/955745/">modules-compile/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082542/">modules-compile/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038746/">modules-compile/0/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/955743/">modules-compile/0/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023313/">modules-compile/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023315/">modules-compile/0/8</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038747/">modules-compile/0/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/713174/">modules-compile/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023319/">modules-compile/0/11</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975135/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1229189/">modules-integration-mysql57/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038749/"><strike>modules-integration-mysql57/0/1</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082615/"><strike>modules-integration-mysql57/0/2</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023337/"><strike>modules-integration-mysql57/0/3</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1017727/"><strike>modules-integration-mysql57/0/4</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023318/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023317/">modules-integration-mysql57/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120294/"><strike>modules-integration-mysql57/0/7</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1229191/">modules-integration-mysql57/0/8</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082548/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082611/"><strike>modules-integration-mysql57/0/10</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1229255/"><strike>modules-integration-mysql57/0/11</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120228/">modules-integration-mysql57/0/12</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082541/">modules-integration-mysql57/0/13</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975130/">modules-integration-mysql57/0/14</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082544/">modules-integration-mysql57/0/15</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082545/">modules-integration-mysql57/0/16</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975132/">modules-integration-mysql57/0/17</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1017735/"><strike>modules-integration-mysql57/0/18</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082610/"><strike>modules-integration-mysql57/0/19</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1229195/">modules-integration-mysql57/0/20</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/713180/">modules-integration-mysql57/0/21</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-p [...]

2024-11-05 12:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6369/">test-portal-source-format#6369</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6369/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5587">liferay-commerce#5587</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/60038679">[master] ci:test:sf - brbalazs &gt; liferay-commerce - PR#5587 - 2024-11-05[03:59:13]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>60038679<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/24746/">publish-testray-report#24746</a><br/></div></div>

2024-11-05 16:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 23 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 108 out of 139 jobs passed in 4 hours 13 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/983">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_12983</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5e032e394aa5a9423586cecf372df569abc654e">a5e032e394aa5a9423586cecf372df569abc654e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/52b71bc3c1114afaf74f3375139a83f21d56c3e0">52b71bc3c1114afaf74f3375139a83f21d56c3e0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/59989600">EE Development Acceptance (master) - 982 - 2024-11-04[23:04:11]</a></p><details><summary><strong>ci:test:stable - 23 out of 24 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120316/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444190/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435452/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458725/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435451/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082638/">js-unit/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120317/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444194/">modules-compile/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487744/"><strike>modules-compile/0/1</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380571/">modules-compile/0/2</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444193/">modules-compile/0/3</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444192/">modules-compile/0/4</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487742/">modules-compile/0/5</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380569/">modules-compile/0/6</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444191/">modules-compile/0/7</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487743/">modules-compile/0/8</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380570/">modules-compile/0/9</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444195/">modules-compile/0/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975224/">modules-compile/0/11</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487746/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120324/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380568/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380572/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389800/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 108 out of 139 jobs PASSED</strong></summary><div><h4>31 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12983/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120316/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444190/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435452/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458725/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435451/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082638/">js-unit/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120317/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444194/">modules-compile/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487744/"><strike>modules-compile/0/1</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380571/">modules-compile/0/2</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444193/">modules-compile/0/3</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444192/">modules-compile/0/4</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487742/">modules-compile/0/5</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380569/">modules-compile/0/6</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444191/">modules-compi [...]

2024-11-05 16:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12983/">test-portal-acceptance-pullrequest(master)#12983</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12983/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5587">liferay-commerce#5587</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/60183217">[master] ci:test:relevant - brbalazs &gt; liferay-commerce - PR#5587 - 2024-11-05[03:59:59]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>60183217<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28380/">publish-testray-report#28380</a><br/></div></div>

2024-11-05 16:37 UTC, smottal commented
ci:test:relevant

2024-11-05 16:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12990/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12990/jenkins-report.html">here</a>.</b></p>

2024-11-05 19:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 108 out of 139 jobs passed in 2 hours 34 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/984">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_12990</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/018c46ee4f7af1eb39b9cf0ec93f43f92aabdb3a">018c46ee4f7af1eb39b9cf0ec93f43f92aabdb3a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5e032e394aa5a9423586cecf372df569abc654e">a5e032e394aa5a9423586cecf372df569abc654e</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/60334923">EE Development Acceptance (master) - 983 - 2024-11-05[04:42:43] - functional tests import fix - 2</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 108 out of 139 jobs PASSED</strong></summary><div><h4>31 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12990/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023573/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389855/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458806/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487822/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435494/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023574/">js-unit/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023576/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487820/">modules-compile/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038962/">modules-compile/0/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389856/">modules-compile/0/2</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380625/">modules-compile/0/3</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/441454/">modules-compile/0/4</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/380624/">modules-compile/0/5</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444260/">modules-compile/0/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/484503/">modules-compile/0/7</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444261/">modules-compile/0/8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/484502/">modules-compile/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120497/">modules-compile/0/10</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376981/">modules-compile/0/11</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/487821/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1132315/">modules-integration-mysql57/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/955982/"><strike>modules-integration-mysql57/0/1</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975435/"><strike>modules-integration-mysql57/0/2</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023622/"><strike>modules-integration-mysql57/0/3</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082895/"><strike>modules-integration-mysql57/0/4</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120499/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1229446/">modules-integration-mysql57/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1132385/"><strike>modules-integration-mysql57/0/7</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1132318/">modules-integration-mysql57/0/8</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/955984/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/777362/"><strike>modules-integration-mysql57/0/10</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1132381/"><strike>modules-integration-mysql57/0/11</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975365/">modules-integration-mysql57/0/12</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1120495/">modules-integration-mysql57/0/13</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/713408/">modules-integration-mysql57/0/14</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1023603/">modules-integration-mysql57/0/15</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1132313/">modules-integration-mysql57/0/16</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1082823/">modules-integration-mysql57/0/17</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971890/"><strike>modules-integration-mysql57/0/18</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstrea [...]

2024-11-05 19:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12990/">test-portal-acceptance-pullrequest(master)#12990</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12990/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5587">liferay-commerce#5587</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/60493199">[master] ci:test:relevant - brbalazs &gt; liferay-commerce - PR#5587 - 2024-11-05[08:37:49]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>60493199<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28393/">publish-testray-report#28393</a><br/></div></div>

2024-11-06 10:29 UTC, brbalazs commented
ci:report:60493199

2024-11-06 10:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>60493199</b>.</p><p>Job Link: <a href="https://test-1-40.liferay.com/job/generate-testray-csv/644/">generate-testray-csv</a></p>

2024-11-06 10:32 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>60493199</b>.</p><p>Job Link: <a href="https://test-1-40.liferay.com/job/generate-testray-csv/644/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-40.liferay.com/userContent/jobs/generate-testray-csv/builds/644/testray-results-60493199.csv">testray-results-60493199.csv</a></p>

2024-11-11 13:08 UTC, smottal commented
ci:forward:force

2024-11-11 13:08 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-11-11 13:09 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-9.liferay.com/job/forward-pullrequest/754//consoleFull)

2024-11-11 13:09 UTC, closed without merging

2024-11-11 13:09 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/156056
[Console](https://test-1-9.liferay.com/job/forward-pullrequest/754//consoleFull)