LPD-40361 - Gender Api
liferay-commerce/liferay-portal pull request #5605
Opened 2024-11-08 13:33 UTC by matyaswollner

https://liferay.atlassian.net/browse/LPD-40361

2024-11-08 13:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-11-08 13:33 UTC, matyaswollner commented
ci:test:sf

2024-11-08 13:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/6004/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/6004/jenkins-report.html">here</a>.</b></p>

2024-11-08 13:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/23b5dd3d3c53233fc9112dd71d55d8ce32887f69">23b5dd3d3c53233fc9112dd71d55d8ce32887f69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-40361">LPD-40361</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/e038c0c3e748ae558d15b46628a44668803f134f">e038c0c3e748ae558d15b46628a44668803f134f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/6004/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/6004/jenkins-report.html">here</a>.</h5></details></html>

2024-11-11 08:54 UTC, smottal requested changes
Good PR: just a rename

2024-11-11 08:54 UTC, smottal commented on modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/resource/v1_0/UserAccountResourceImpl.java
> +	private boolean _isMale(UserAccount.Gender gender, boolean male) {
can we call the boolean male -> boolean defaultValue ? (and in case you need to switch the two parameters to have them sorted)

2024-11-11 14:38 UTC, matyaswollner commented
ci:test:sf

2024-11-11 14:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6868/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6868/jenkins-report.html">here</a>.</b></p>

2024-11-11 14:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a4724f090d38bacdc946e8597abef29cbbbe1a20">a4724f090d38bacdc946e8597abef29cbbbe1a20</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/matyaswollner/liferay-portal/tree/LPD-40361">LPD-40361</a><br/>Branch GIT ID: <a href="https://github.com/matyaswollner/liferay-portal/commit/15d19c664d65444f9c739c98ace8cb36afb5a4a1">15d19c664d65444f9c739c98ace8cb36afb5a4a1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6868/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6868/jenkins-report.html">here</a>.</h5></details></html>

2024-11-11 14:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6868/">test-portal-source-format#6868</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6868/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5605">liferay-commerce#5605</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/65440933">[master] ci:test:sf - matyaswollner &gt; liferay-commerce - PR#5605 - 2024-11-11[06:38:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>65440933<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/25537/">publish-testray-report#25537</a><br/></div></div>

2024-11-11 14:53 UTC, matyaswollner commented
ci:test:relevant

2024-11-11 14:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11718/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11718/jenkins-report.html">here</a>.</b></p>

2024-11-11 19:57 UTC, smottal commented
ci:report:65673593

2024-11-11 20:50 UTC, smottal commented
ci:forward:force

2024-11-11 20:50 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-11-11 20:50 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-11-11 20:50 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-29.liferay.com/job/forward-pullrequest/1143//consoleFull)

2024-11-11 20:51 UTC, closed without merging

2024-11-11 20:51 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/156076
[Console](https://test-1-29.liferay.com/job/forward-pullrequest/1143//consoleFull)