LPD-39086 - Sort by Last Login Date appears to be sorting by Last Name
liferay-commerce/liferay-portal pull request #5616
Opened 2024-11-12 11:29 UTC by smottal

https://liferay.atlassian.net/browse/LPD-39086

Resent from: https://github.com/brianchandotcom/liferay-portal/pull/156056 to change the FeatureFlag annotation

2024-11-12 11:30 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-11-12 11:30 UTC, smottal commented
ci:test:sf

2024-11-12 11:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6879/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6879/jenkins-report.html">here</a>.</b></p>

2024-11-12 11:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fde9cf03e3d6c948d5345626a67f406d18eed3c0">fde9cf03e3d6c948d5345626a67f406d18eed3c0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/smottal/liferay-portal/tree/LPD-39086-2">LPD-39086-2</a><br/>Branch GIT ID: <a href="https://github.com/smottal/liferay-portal/commit/f03796e23a059ecef5a6e21a01453634efd66bd2">f03796e23a059ecef5a6e21a01453634efd66bd2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6879/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6879/jenkins-report.html">here</a>.</h5></details></html>

2024-11-12 11:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6879/">test-portal-source-format#6879</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6879/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5616">liferay-commerce#5616</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/66348477">[master] ci:test:sf - smottal &gt; liferay-commerce - PR#5616 - 2024-11-12[03:30:16]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>66348477<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/25575/">publish-testray-report#25575</a><br/></div></div>

2024-11-13 11:00 UTC, thiago-buarqque requested changes
Thanks @smottal, just a few comments

2024-11-13 11:00 UTC, thiago-buarqque commented on portal-test/src/com/liferay/portal/test/rule/FeatureFlagTestRule.java
There is a method called `_enableFeatureFlags`, since now a feature flag can be disabled, I'd change it to `_updateFeatureFlags`.

2024-11-13 11:00 UTC, thiago-buarqque commented on portal-test/src/com/liferay/portal/test/rule/FeatureFlagTestRule.java
> +					featureFlagKey, String.valueOf(featureFlags.enable())
Since now we are handling false values, you must add a test case in `FeatureFlagTestRuleTest`

2024-11-13 11:00 UTC, thiago-buarqque commented on modules/apps/user/user-test/src/testIntegration/java/com/liferay/user/service/test/UserLocalServiceTest.java
> +		String middleName = "middleName";
When creating a variable in which its value does not matter for the test case, use a random value. The idea is to only hard code values that matter for the test case. That makes easier to understand the test.

This isn't related to feature flag and you can ignore my comment if you want.

2024-11-14 11:36 UTC, brbalazs commented
@smottal unit test added and also done requested changes under PR: https://github.com/liferay/liferay-portal/pull/6117
I think, this one can be closed.

2024-11-14 16:28 UTC, closed without merging