LPD-39192 - getCountriesPage response does not match the localization selection of available languages configured on Instance Settings
liferay-commerce/liferay-portal pull request #5652
Opened 2024-11-21 18:00 UTC by victorcdp

2024-11-21 18:00 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-11-21 18:04 UTC, victorcdp commented
ci:test:sf

2024-11-21 18:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6754/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6754/jenkins-report.html">here</a>.</b></p>

2024-11-21 18:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/88f5c1e61324636dcb345e3358adef5e7589a5e8">88f5c1e61324636dcb345e3358adef5e7589a5e8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/victorcdp/liferay-portal/tree/LPD-39192">LPD-39192</a><br/>Branch GIT ID: <a href="https://github.com/victorcdp/liferay-portal/commit/2828329763b76264420038424b2b64efbabafa3c">2828329763b76264420038424b2b64efbabafa3c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6754/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6754/jenkins-report.html">here</a>.</h5></details></html>

2024-11-21 18:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6754/">test-portal-source-format#6754</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6754/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5652">liferay-commerce#5652</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/74403065">[master] ci:test:sf - victorcdp &gt; liferay-commerce - PR#5652 - 2024-11-21[10:05:18]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>74403065<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/25815/">publish-testray-report#25815</a><br/></div></div>

2024-11-25 10:57 UTC, smottal commented
Other place is on PostalAddressUtil where we have setAddressCountry_i18n that can use the new Util method. And we need a test like the others also for this

2024-11-25 11:14 UTC, smottal requested changes

2024-11-27 15:49 UTC, smottal commented
closing as resent here: https://github.com/liferay-commerce/liferay-portal/pull/5667

2024-11-27 15:49 UTC, closed without merging