LPD-41420 Headless changes for product configuration
liferay-commerce/liferay-portal pull request #5701
Opened 2024-12-09 20:02 UTC by dsitu

https://liferay.atlassian.net/browse/LPD-41420
This is the headless API part for product configuration

2024-12-09 20:02 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-12-09 20:02 UTC, dsitu commented
ci:test:sf

2024-12-09 20:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10888/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10888/jenkins-report.html">here</a>.</b></p>

2024-12-09 20:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-41420-2">LPD-41420-2</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/8b576a8c11679384ca6df48a3299db9a961ef0a4">8b576a8c11679384ca6df48a3299db9a961ef0a4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10888/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10888/jenkins-report.html">here</a>.</h5></details></html>

2024-12-09 20:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10888/">test-portal-source-format#10888</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10888/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5701">liferay-commerce#5701</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/87843411">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5701 - 2024-12-09[12:02:54]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>87843411<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/41340/">publish-testray-report#41340</a><br/></div></div>

2024-12-09 20:40 UTC, dsitu commented
ci:test:sf

2024-12-09 20:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-41420-2">LPD-41420-2</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/8eff2b1bc2d7b1bb793a3b49d88fa39de7c70b7a">8eff2b1bc2d7b1bb793a3b49d88fa39de7c70b7a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/6037/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/6037/jenkins-report.html">here</a>.</h5></details></html>

2024-12-09 20:44 UTC, dsitu commented
ci:test:relevant

2024-12-09 20:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19125/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19125/jenkins-report.html">here</a>.</b></p>

2024-12-09 21:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 16 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/87398872">EE Development Acceptance (master) - 1069 - 2024-12-09[00:38:54]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19125/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19125/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19125/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] &gt; Task :apps:commerce:commerce-product-service:compileJava FAILED
     [exec] &gt; Task :apps:commerce:commerce-inventory-service:jar
     [exec] &gt; Task :apps:commerce:commerce-inventory-service:autoUpdateXml SKIPPED
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-frontend-js:packageRunBuild
     [exec] ⌛ Legacy build (liferay-npm-scripts) took: 1.672 s
     [exec] 
     [exec] Using pre-existing NODE_ENV: "production"
     [exec] Received 0
     [exec] Done in 2.59s.
     [exec] 
     [exec] &gt; Task :apps:commerce:commerce-product-definitions-web:packageRunBuild
     [exec] yarn run v1.13.0
     [exec] warning package.json: No license field
     [exec] \$ node-scripts build
     [exec] ⌛ Esbuild for main took: 0.161 s
     [exec] ⌛ Sass for /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-definitions-web/src/main/resources/META-INF/resources/css/main.scss took: 0.123 s
     [exec] ⌛ Legacy build (liferay-npm-scripts) took: 1.054 s
     [exec] 
     [exec] Using pre-existing NODE_ENV: "production"
     [exec] Received 0
     [exec] Done in 1.97s.
     [exec] Gradle build finished at 2024-12-09 21:00:00.844.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-product-service:compileJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-product-service:compileJava'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec] 1527 actionable tasks: 1481 executed, 46 up-to-date
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)
     [exec]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-12-09 21:37 UTC, dsitu commented
ci:stop

2024-12-09 21:57 UTC, dsitu commented
ci:test:sf

2024-12-09 21:57 UTC, dsitu commented
ci:test:relevant

2024-12-09 21:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12200/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12200/jenkins-report.html">here</a>.</b></p>

2024-12-09 21:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/7122/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7122/jenkins-report.html">here</a>.</b></p>

2024-12-09 22:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-41420-2">LPD-41420-2</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/09ca2193204b7bd12b3c2e78ece4a439a9e42338">09ca2193204b7bd12b3c2e78ece4a439a9e42338</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7122/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7122/jenkins-report.html">here</a>.</h5></details></html>

2024-12-09 22:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7122/">test-portal-source-format#7122</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7122/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5701">liferay-commerce#5701</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/87889654">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5701 - 2024-12-09[13:57:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>87889654<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/25979/">publish-testray-report#25979</a><br/></div></div>

2024-12-09 22:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/87398872">EE Development Acceptance (master) - 1069 - 2024-12-09[00:38:54]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12200/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12200/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12200/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] &gt; Task :apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-impl:compileJava FAILED
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/OrderTypeResourceImpl.java:41: error: cannot find symbol
     [exec]       _cpConfigurationListRelService.getCPConfigurationListRel(id);
     [exec]                                     ^
     [exec]   symbol:   method getCPConfigurationListRel(java.lang.Long)
     [exec]   location: variable _cpConfigurationListRelService of type com.liferay.commerce.product.service.CPConfigurationListRelService
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/AccountGroupResourceImpl.java:41: error: cannot find symbol
     [exec]       _cpConfigurationListRelService.getCPConfigurationListRel(id);
     [exec]                                     ^
     [exec]   symbol:   method getCPConfigurationListRel(java.lang.Long)
     [exec]   location: variable _cpConfigurationListRelService of type com.liferay.commerce.product.service.CPConfigurationListRelService
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/AccountResourceImpl.java:40: error: cannot find symbol
     [exec]       _cpConfigurationListRelService.getCPConfigurationListRel(id);
     [exec]                                     ^
     [exec]   symbol:   method getCPConfigurationListRel(java.lang.Long)
     [exec]   location: variable _cpConfigurationListRelService of type com.liferay.commerce.product.service.CPConfigurationListRelService
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListAccountResourceImpl.java:75: error: no suitable method found for getCPConfigurationListRels(java.lang.String,long,int,int,&lt;nulltype&gt;)</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-12-09 22:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12200/">test-portal-acceptance-pullrequest(master)#12200</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12200/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5701">liferay-commerce#5701</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/87910270">[master] ci:test:relevant - dsitu &gt; liferay-commerce - PR#5701 - 2024-12-09[13:57:29]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>87910270<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26557/">publish-testray-report#26557</a><br/></div></div>

2024-12-10 00:00 UTC, dsitu commented
ci:test:sf

2024-12-10 00:00 UTC, dsitu commented
ci:test:relevant

2024-12-10 00:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/7047/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/7047/jenkins-report.html">here</a>.</b></p>

2024-12-10 00:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/dsitu/liferay-portal/tree/LPD-41420-2">LPD-41420-2</a><br/>Branch GIT ID: <a href="https://github.com/dsitu/liferay-portal/commit/75dc1dea70e1b42ab187e1a617589ecd316d9d2c">75dc1dea70e1b42ab187e1a617589ecd316d9d2c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/7047/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/7047/jenkins-report.html">here</a>.</h5></details></html>

2024-12-10 00:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/7047/">test-portal-source-format#7047</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/7047/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5701">liferay-commerce#5701</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/87956466">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5701 - 2024-12-09[16:00:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>87956466<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/26087/">publish-testray-report#26087</a><br/></div></div>

2024-12-10 01:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 38 out of 45 jobs passed in 1 hour 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/87398872">EE Development Acceptance (master) - 1069 - 2024-12-09[00:38:54]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 38 out of 45 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/12061/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/972341/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453942/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495305/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498618/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444735/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1140315/">js-unit/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/972342/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444736/">modules-compile/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495306/">modules-compile/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498619/">modules-compile/0/2</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/469230/">modules-compile/0/3</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498617/">modules-compile/0/4</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/469228/">modules-compile/0/5</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385311/">modules-compile/0/6</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498616/">modules-compile/0/7</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/469229/">modules-compile/0/8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495304/">modules-compile/0/9</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388918/">modules-compile/0/10</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453941/">modules-compile/0/11</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444734/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729260/">modules-integration-mysql57/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1140320/"><strike>modules-integration-mysql57/0/1</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986309/">modules-integration-mysql57/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1272537/"><strike>modules-integration-mysql57/0/3</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986312/">modules-integration-mysql57/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036903/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036904/"><strike>modules-integration-mysql57/0/6</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153908/">modules-integration-mysql57/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1036905/">modules-integration-mysql57/0/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/986313/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1102186/">modules-integration-mysql57/0/10</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729262/"><strike>modules-integration-mysql57/0/11</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1246762/"><strike>modules-integration-mysql57/0/12</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1246761/"><strike>modules-integration-mysql57/0/13</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729261/">modules-integration-mysql57/0/14</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153909/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1140316/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/398228/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449309/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385310/">playwright-js-tomcat90-mysql57/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449308/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>rest-builder<ul><li><a href="https://test-1-3 [...]

2024-12-10 01:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/12061/">test-portal-acceptance-pullrequest(master)#12061</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12061/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5701">liferay-commerce#5701</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/88031476">[master] ci:test:relevant - dsitu &gt; liferay-commerce - PR#5701 - 2024-12-09[16:01:08]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>88031476<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/25987/">publish-testray-report#25987</a><br/></div></div>

2024-12-11 13:52 UTC, andrea-ale-sbarra requested changes
@dsitu please have a look at my comments.
Thank you!

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListAccountResourceImpl.java
> +			pagination, totalItems);
please call the other method so that you don't repeat the logic + you can inline directly the service call in the Pagination constructor method call

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/dto/v1_0/converter/AccountDTOConverter.java
> +		else {
this doesn't look right to me, I'm not sure we need this, why do we have this? is this the eligibility pattern? Can't we just send the account info along with the payload of the ProductConfigurationListAccount?

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/dto/v1_0/converter/AccountDTOConverter.java
> +		else {
@luca-pellizzon can you please have a look at this too?

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListAccountResourceImpl.java
> +			cpConfigurationListRel.getCPConfigurationListRelId());
same here call the other post method

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListAccountResourceImpl.java
> +	}
you can inline using transformutil and remove this method

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/rest-openapi.yaml
> +    "/product-configuration-list-account-groups/{productConfigurationListAccountGroupId}/account-group":
also here I think we can send these 2 fields along with the other entity and remove this endpoint

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListAccountGroupResourceImpl.java
> +			_cpConfigurationListRelService.getCPConfigurationListRelsCount(
inline and call the other method so you don't repeat same code

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListAccountGroupResourceImpl.java
> +			_toProductConfigurationListAccountGroups(cpConfigurationListRels),
transformutil

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/rest-openapi.yaml
> +    "/product-configuration-list-channels/{productConfigurationListChannelId}/channel":
also this I think we can avoid this..

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ChannelResourceImpl.java
> +	public Channel getProductConfigurationListChannelChannel(Long id)
this I think can be removed as the other endpoints similar to this

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListChannelResourceImpl.java
> +	}
inline transformutil and call the other method to avoid repetition

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/rest-openapi.yaml
> +    "/product-configuration-list-order-types/{productConfigurationListOrderTypeId}/order-type":
same here

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/dto/v1_0/converter/OrderTypeDTOConverter.java
> +public class OrderTypeDTOConverter
this can be removed I believe

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/OrderTypeResourceImpl.java
> +public class OrderTypeResourceImpl extends BaseOrderTypeResourceImpl {
this I believe can be removed

2024-12-11 13:52 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListOrderTypeResourceImpl.java
> +
inline tranformutil call the other method

2024-12-11 22:14 UTC, dsitu commented
@andrea-ale-sbarra 
1. Removed endpoints
/product-configuration-list-accounts/{productConfigurationListAccountId}/account
/product-configuration-list-account-groups/{productConfigurationListAccountGroupId}/account-group
/product-configuration-list-channels/{productConfigurationListChannelId}/channel
/product-configuration-list-order-types/{productConfigurationListOrderTypeId}/order-type
2. Passing entities directly rather then using nestedFields
https://github.com/liferay-commerce/liferay-portal/pull/5701/commits/1010b2df4c39e8ae650b1595b72942cc568c5dc1#diff-5309c6df6ec0b06ce31e5910dc2bb69ca969466698476a8967360d021f1bfb7aR56-R63
https://github.com/liferay-commerce/liferay-portal/pull/5701/commits/16a319c5487b2513f9e0aa0ccebf64a5c9402b62#diff-08c40476130a81c7e8a38874e8bf9bca44b9f3be03734617955fb50628170d64R56-R68
https://github.com/liferay-commerce/liferay-portal/pull/5701/commits/ed099cce67c91ec5ff763e58aaa978f2b84f2f90#diff-c638fc83d2588f90d28fafa21637209c20921c0591db4206f67db3314fd96ed3R59-R71
https://github.com/liferay-commerce/liferay-portal/pull/5701/commits/628135bfc8029d8ae050ac25817e9cce20df667f#diff-e9c3dc38af0b32bca46519511bb6ad0cd108cea3223810c59972ed67842ddcf4R59-R67
3. Formatted code to use transform method and removed redundant logic.

2024-12-16 14:35 UTC, andrea-ale-sbarra requested changes
Overall looks good, I've suggested to make the ERC check first so that you can buy some space. Look at ConfigurationList and ConfigurationEntry endpoints for reference.

Thank you!

2024-12-16 14:35 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListAccountResourceImpl.java
> +			if (accountEntry == null) {
you can buy space by inverting this if, if you first check the erc branch you'll save and indented if

2024-12-16 14:35 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListAccountResourceImpl.java
> +			if (accountEntry == null) {
just saying because I fear Brian would ask to do this change.. :)

2024-12-16 14:35 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListAccountGroupResourceImpl.java
> +		if (Validator.isNull(
same here

2024-12-16 14:35 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListChannelResourceImpl.java
> +			if (commerceChannel == null) {
buy space

2024-12-16 14:35 UTC, andrea-ale-sbarra commented on modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductConfigurationListOrderTypeResourceImpl.java
> +			if (commerceOrderType == null) {
buy space

2024-12-16 18:46 UTC, dsitu commented
ci:test:sf

2024-12-16 18:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3988/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3988/jenkins-report.html">here</a>.</b></p>

2024-12-16 18:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3988/">test-portal-source-format#3988</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3988/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5701">liferay-commerce#5701</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/93150460">[master] ci:test:sf - dsitu &gt; liferay-commerce - PR#5701 - 2024-12-16[10:47:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>93150460<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/15681/">publish-testray-report#15681</a><br/></div></div>

2024-12-16 18:55 UTC, dsitu commented
ci:test:relevant

2024-12-16 18:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19266/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19266/jenkins-report.html">here</a>.</b></p>

2024-12-16 20:48 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 37 out of 45 jobs passed in 1 hour 50 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1085">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_19266</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e6a5c8935b0a32cc6a0cc803f39c0148cae921c9">e6a5c8935b0a32cc6a0cc803f39c0148cae921c9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/537e1ab42d119f8f2841389f66ad4684a372992a">537e1ab42d119f8f2841389f66ad4684a372992a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/92961119">EE Development Acceptance (master) - 1084 - 2024-12-16[04:38:35]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 37 out of 45 jobs PASSED</strong></summary><div><h4>8 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19266/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1276661/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1056220/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/732012/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039165/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/470998/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1276662/">js-unit/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1276665/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040085/">modules-compile/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/805323/">modules-compile/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1249688/">modules-compile/0/2</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/455473/">modules-compile/0/3</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/470997/">modules-compile/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1056222/">modules-compile/0/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975895/">modules-compile/0/6</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/470996/">modules-compile/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1046980/">modules-compile/0/8</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1156179/">modules-compile/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/805321/">modules-compile/0/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/996937/">modules-compile/0/11</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975896/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039163/">modules-integration-mysql57/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1154789/">modules-integration-mysql57/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1276782/"><strike>modules-integration-mysql57/0/2</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1056221/"><strike>modules-integration-mysql57/0/3</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039164/">modules-integration-mysql57/0/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1154790/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1105638/"><strike>modules-integration-mysql57/0/6</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1144014/">modules-integration-mysql57/0/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975947/"><strike>modules-integration-mysql57/0/8</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1056223/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1105639/"><strike>modules-integration-mysql57/0/10</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079976/">modules-integration-mysql57/0/11</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/805322/">modules-integration-mysql57/0/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1156178/">modules-integration-mysql57/0/13</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/996936/">modules-integration-mysql57/0/14</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1249687/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1276664/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497055/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/975894/">modules-unit_stable/0/0</a></li></ul></li><li>playwr [...]

2024-12-16 20:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19266/">test-portal-acceptance-pullrequest(master)#19266</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19266/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5701">liferay-commerce#5701</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/93225380">[master] ci:test:relevant - dsitu &gt; liferay-commerce - PR#5701 - 2024-12-16[10:56:13]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>93225380<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/41645/">publish-testray-report#41645</a><br/></div></div>

2024-12-16 21:21 UTC, dsitu commented
ci:forward:force

2024-12-16 21:21 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-12-16 21:22 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/1236//consoleFull)

2024-12-16 21:22 UTC, closed without merging

2024-12-16 21:22 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/157077
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/1236//consoleFull)