LPD-42552 Add check permission for fix a test that is failing
liferay-commerce/liferay-portal pull request #5720
Opened 2024-12-13 10:40 UTC by monaco-fabio

https://liferay.atlassian.net/browse/LPD-42552

2024-12-13 10:40 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-12-13 10:40 UTC, monaco-fabio commented
ci:test:sf

2024-12-13 10:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/7157/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7157/jenkins-report.html">here</a>.</b></p>

2024-12-13 10:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33b3b52351f51d533ca1d3355fc723a2f1dfb9f4">33b3b52351f51d533ca1d3355fc723a2f1dfb9f4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-42552">LPD-42552</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/18ce1b0e8e1f1132aeb5bb060b6bb05aca527921">18ce1b0e8e1f1132aeb5bb060b6bb05aca527921</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7157/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7157/jenkins-report.html">here</a>.</h5></details></html>

2024-12-13 10:44 UTC, monaco-fabio commented
ci:test:relevant

2024-12-13 10:45 UTC, monaco-fabio commented
ci:test:commerce-functional

2024-12-13 10:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19218/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19218/jenkins-report.html">here</a>.</b></p>

2024-12-13 10:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10808/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10808/jenkins-report.html">here</a>.</b></p>

2024-12-13 10:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7157/">test-portal-source-format#7157</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7157/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5720">liferay-commerce#5720</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/90984828">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5720 - 2024-12-13[02:40:26]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>90984828<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/26091/">publish-testray-report#26091</a><br/></div></div>

2024-12-13 11:07 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-asset-categories-navigation-web/src/main/java/com/liferay/commerce/product/asset/categories/navigation/web/internal/display/context/CPAssetCategoriesNavigationDisplayContext.java
> +		return null;
You need to cover the scenario in which vocabulary is null

2024-12-13 11:07 UTC, alessiorendina requested changes
@monaco-fabio please check my comment. Thank you!

2024-12-13 11:08 UTC, monaco-fabio commented
ci:stop

2024-12-13 11:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 0 out of 1 jobs passed in 23 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33b3b52351f51d533ca1d3355fc723a2f1dfb9f4">33b3b52351f51d533ca1d3355fc723a2f1dfb9f4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33b3b52351f51d533ca1d3355fc723a2f1dfb9f4">33b3b52351f51d533ca1d3355fc723a2f1dfb9f4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/90645729">EE Development Acceptance (master) - 1077 - 2024-12-12[12:36:57]</a></p><details><summary><strong>ci:test:commerce-functional - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10808/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10808/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10808/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-12-13 11:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33b3b52351f51d533ca1d3355fc723a2f1dfb9f4">33b3b52351f51d533ca1d3355fc723a2f1dfb9f4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33b3b52351f51d533ca1d3355fc723a2f1dfb9f4">33b3b52351f51d533ca1d3355fc723a2f1dfb9f4</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/90645729">EE Development Acceptance (master) - 1077 - 2024-12-12[12:36:57]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19218/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19218/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19218/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-12-13 11:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10808/">test-portal-acceptance-pullrequest(master)#10808</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10808/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5720">liferay-commerce#5720</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/91013829">[master] ci:test:commerce-functional - monaco-fabio &gt; liferay-commerce - PR#5720 - 2024-12-13[02:45:36]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>91013829<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/23957/">publish-testray-report#23957</a><br/></div></div>

2024-12-13 11:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19218/">test-portal-acceptance-pullrequest(master)#19218</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19218/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5720">liferay-commerce#5720</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/91027810">[master] ci:test:relevant - monaco-fabio &gt; liferay-commerce - PR#5720 - 2024-12-13[02:45:09]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>91027810<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/41532/">publish-testray-report#41532</a><br/></div></div>

2024-12-13 16:34 UTC, monaco-fabio commented
ci:test:sf

2024-12-13 16:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7666/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7666/jenkins-report.html">here</a>.</b></p>

2024-12-13 16:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66ea8bf815fa4ac8b619e4d598ac7c6c2614ed6c">66ea8bf815fa4ac8b619e4d598ac7c6c2614ed6c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/monaco-fabio/liferay-portal/tree/LPD-42552">LPD-42552</a><br/>Branch GIT ID: <a href="https://github.com/monaco-fabio/liferay-portal/commit/8776d3533491948fdc1d80e02b31e68570b8a1ee">8776d3533491948fdc1d80e02b31e68570b8a1ee</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7666/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7666/jenkins-report.html">here</a>.</h5></details></html>

2024-12-13 16:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7666/">test-portal-source-format#7666</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7666/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5720">liferay-commerce#5720</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/91373702">[master] ci:test:sf - monaco-fabio &gt; liferay-commerce - PR#5720 - 2024-12-13[08:35:06]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>91373702<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/29135/">publish-testray-report#29135</a><br/></div></div>

2024-12-13 16:43 UTC, monaco-fabio commented
ci:test:relevant

2024-12-13 16:44 UTC, monaco-fabio commented
ci:test:commerce-functional

2024-12-13 16:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19225/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19225/jenkins-report.html">here</a>.</b></p>

2024-12-13 16:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/7168/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7168/jenkins-report.html">here</a>.</b></p>

2024-12-13 18:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:x: ci:test:relevant - 38 out of 43 jobs passed in 1 hour 39 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1079">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_19225</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66ea8bf815fa4ac8b619e4d598ac7c6c2614ed6c">66ea8bf815fa4ac8b619e4d598ac7c6c2614ed6c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/adcc1b627a7d1c3276fe6d7f20ef2a1b8b0bd543">adcc1b627a7d1c3276fe6d7f20ef2a1b8b0bd543</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/91181864">EE Development Acceptance (master) - 1078 - 2024-12-13[04:36:07]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 38 out of 43 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19225/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104577/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/499918/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/445847/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385991/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/499922/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045870/">js-unit/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153733/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389827/">modules-compile/0/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385992/">modules-compile/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/499923/">modules-compile/0/2</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389826/">modules-compile/0/3</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389824/">modules-compile/0/4</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/499920/">modules-compile/0/5</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/445844/">modules-compile/0/6</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/499919/">modules-compile/0/7</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389825/">modules-compile/0/8</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/499921/">modules-compile/0/9</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/389823/">modules-compile/0/10</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/445846/">modules-compile/0/11</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385990/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1248854/"><strike>modules-integration-mysql57/0/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988156/">modules-integration-mysql57/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079138/">modules-integration-mysql57/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731218/"><strike>modules-integration-mysql57/0/3</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731219/">modules-integration-mysql57/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038359/">modules-integration-mysql57/0/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079141/"><strike>modules-integration-mysql57/0/6</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1248850/">modules-integration-mysql57/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045889/">modules-integration-mysql57/0/8</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804180/">modules-integration-mysql57/0/9</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974825/"><strike>modules-integration-mysql57/0/10</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155349/">modules-integration-mysql57/0/11</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988157/">modules-integration-mysql57/0/12</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153751/">modules-integration-mysql57/0/13</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079139/">modules-integration-mysql57/0/14</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1142899/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974807/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/445845/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/445843/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="h [...]

2024-12-13 18:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19225/">test-portal-acceptance-pullrequest(master)#19225</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19225/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5720">liferay-commerce#5720</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/91480842">[master] ci:test:relevant - monaco-fabio &gt; liferay-commerce - PR#5720 - 2024-12-13[08:44:00]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>91480842<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/41554/">publish-testray-report#41554</a><br/></div></div>

2024-12-13 19:33 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 157 out of 200 jobs passed in 2 hours 49 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1079">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1337401_7168</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/66ea8bf815fa4ac8b619e4d598ac7c6c2614ed6c">66ea8bf815fa4ac8b619e4d598ac7c6c2614ed6c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/adcc1b627a7d1c3276fe6d7f20ef2a1b8b0bd543">adcc1b627a7d1c3276fe6d7f20ef2a1b8b0bd543</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/91181864">EE Development Acceptance (master) - 1078 - 2024-12-13[04:36:07]</a></p><details><summary><strong>ci:test:commerce-functional - 157 out of 200 jobs PASSED</strong></summary><div><h4>43 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/7168/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055395/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731208/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995871/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038347/">functional-tomcat90-mysql57/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155338/">functional-tomcat90-mysql57/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995870/">functional-tomcat90-mysql57/0/5</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1248839/"><strike>functional-tomcat90-mysql57/0/6</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731207/">functional-tomcat90-mysql57/0/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974813/">functional-tomcat90-mysql57/0/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1142887/">functional-tomcat90-mysql57/0/9</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995877/">functional-tomcat90-mysql57/0/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079134/"><strike>functional-tomcat90-mysql57/0/11</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1248846/">functional-tomcat90-mysql57/0/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731214/">functional-tomcat90-mysql57/0/13</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1275405/">functional-tomcat90-mysql57/0/14</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1142894/">functional-tomcat90-mysql57/0/15</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/974820/">functional-tomcat90-mysql57/0/16</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155344/">functional-tomcat90-mysql57/0/17</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055401/">functional-tomcat90-mysql57/0/18</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045884/">functional-tomcat90-mysql57/0/19</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155340/"><strike>functional-tomcat90-mysql57/0/20</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045880/">functional-tomcat90-mysql57/0/21</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804171/">functional-tomcat90-mysql57/0/22</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038349/">functional-tomcat90-mysql57/0/23</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1275401/">functional-tomcat90-mysql57/0/24</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1142886/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153739/">functional-tomcat90-mysql57/1/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988145/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/995869/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055393/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1275396/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804166/"><strike>functional-tomcat90-mysql57/1/6</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039174/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/804167/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045876/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731212/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1038351/"><strike>functional-tomcat90-mysql57/1/11</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1275403/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079132/">functional-tomcat90-mysql57/1/13</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1155342/">functional-tomcat90-mysql57/1/14</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153744/">functional-tomcat90-mysql57/1/15</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/988150/">functional-tomcat90-mysq [...]

2024-12-13 19:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/7168/">test-portal-acceptance-pullrequest(master)#7168</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7168/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/5720">liferay-commerce#5720</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/91589824">[master] ci:test:commerce-functional - monaco-fabio &gt; liferay-commerce - PR#5720 - 2024-12-13[08:44:13]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>91589824<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/15695/">publish-testray-report#15695</a><br/></div></div>

2024-12-16 08:42 UTC, monaco-fabio commented
ci:report:91589824

2024-12-16 08:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>91480842</b>.</p><p>Job Link: <a href="https://test-1-28.liferay.com/job/generate-testray-csv/565/">generate-testray-csv</a></p>

2024-12-16 08:45 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>91480842</b>.</p><p>Job Link: <a href="https://test-1-28.liferay.com/job/generate-testray-csv/565/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-28.liferay.com/userContent/jobs/generate-testray-csv/builds/565/testray-results-91480842.csv">testray-results-91480842.csv</a></p>

2024-12-16 08:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>91589824</b>.</p><p>Job Link: <a href="https://test-1-29.liferay.com/job/generate-testray-csv/253/">generate-testray-csv</a></p>

2024-12-16 08:49 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>91589824</b>.</p><p>Job Link: <a href="https://test-1-29.liferay.com/job/generate-testray-csv/253/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-29.liferay.com/userContent/jobs/generate-testray-csv/builds/253/testray-results-91589824.csv">testray-results-91589824.csv</a></p>

2024-12-16 09:49 UTC, alessiorendina approved these changes

2024-12-16 09:50 UTC, alessiorendina commented
@monaco-fabio confirmed that failures are not related to the PR, thank you!

2024-12-16 09:50 UTC, alessiorendina commented
ci:forward:force

2024-12-16 09:50 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-12-16 09:50 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`
AND Skipping previously passed test suites:
- `ci:test:stable`

2024-12-16 09:50 UTC, liferay-continuous-integration commented
All required test suite(s) completed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/1234//consoleFull)

2024-12-16 09:51 UTC, closed without merging

2024-12-16 09:51 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/157047
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/1234//consoleFull)