COMMERCE-4433 Make CommerceContext extendable with custom CommerceContextFactory
liferay-commerce/liferay-portal pull request #708
Opened 2021-03-01 10:03 UTC by riccardo-alberti

2021-03-01 10:03 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-03-01 10:03 UTC, riccardo-alberti commented
ci:test:sf

2021-03-01 10:03 UTC, riccardo-alberti commented
ci:test:relevant

2021-03-01 10:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/3842/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-portal-source-format/builds/3842/jenkins-report.html">here</a>.</b></p>

2021-03-01 10:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9837c4d81f2de200ad2bcd7acc83578fb25e975c">9837c4d81f2de200ad2bcd7acc83578fb25e975c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/COMMERCE-4433_a">COMMERCE-4433_a</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/14019ffb38e91411cf1827df74a5ec87f642d861">14019ffb38e91411cf1827df74a5ec87f642d861</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/3842/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/3842/jenkins-report.html">here</a>.</h5></details></html>

2021-03-01 10:20 UTC, riccardo-alberti commented
ci:test:relevant

2021-03-01 10:20 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-7.liferay.com/job/test-portal-source-format/3842/">test-portal-source-format#3842</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/3842/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/708">liferay-commerce#708</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/96390.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#708 - 2021-03-01[02:04:01]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/16771/">publish-spira-report#16771</a><br />

2021-03-01 10:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/6786/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6786/jenkins-report.html">here</a>.</b></p>

2021-03-01 10:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7644/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7644/jenkins-report.html">here</a>.</b></p>

2021-03-01 11:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 41 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9837c4d81f2de200ad2bcd7acc83578fb25e975c">9837c4d81f2de200ad2bcd7acc83578fb25e975c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9837c4d81f2de200ad2bcd7acc83578fb25e975c">9837c4d81f2de200ad2bcd7acc83578fb25e975c</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1589">Acceptance Upstream DXP (master) #1589</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/6786/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6786/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/6786/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-impl:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductChannelResourceImpl.java:63: error: incompatible types: long cannot be converted to String
     [exec] 					contextCompany.getCompanyId(), externalReferenceCode);
     [exec] 					                           ^
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
     [exec] 1 error
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] &gt; Task :dxp:apps:sharepoint-soap:sharepoint-soap-repository:buildWSDLCompileCopy
     [exec] 
     [exec] &gt; Task :dxp:apps:segments:segments-experiment-web:packageRunBuild
     [exec] Bundling took 13s
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   1114
     [exec]   Files with errors: 857
     [exec]   Before size:       2099167
     [exec]   After size:        1609721
     [exec]   Delta:             489446
     [exec]   Elapsed:           3.74
     [exec] Received 0
     [exec] Done in 22.19s.
     [echo] Generating Jenkins report.
[beanshell] Jenkins reported generated in 392 ms
     [echo] Rsyncing Jenkins report.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20210301030654926
     [exec] 
     [exec] &gt; Task :dxp:apps:portal-workflow:portal-workflow-metrics-web:packageRunBuild
     [exec] Bundling took 1m
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/main.css
     [echo] Generating Jenkins report.
[beanshell] Jenkins reported generated in 34 ms
     [echo] Rsyncing Jenkins report.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20210301030755135
     [exec] Minification summary:
     [exec]   Files processed:   1683
     [exec]   Files with errors: 892</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-03-01 11:33 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 41 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9837c4d81f2de200ad2bcd7acc83578fb25e975c">9837c4d81f2de200ad2bcd7acc83578fb25e975c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9837c4d81f2de200ad2bcd7acc83578fb25e975c">9837c4d81f2de200ad2bcd7acc83578fb25e975c</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1589">Acceptance Upstream DXP (master) #1589</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7644/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7644/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7644/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-impl:compileJava FAILED
     [exec] 
     [exec] &gt; Task :dxp:apps:sharepoint-soap:sharepoint-soap-repository:buildWSDLCompileCopy
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] &gt; Task :dxp:apps:segments:segments-experiment-web:packageRunBuild
     [exec] Bundling took 15s
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   1114
     [exec]   Files with errors: 857
     [exec]   Before size:       2099167
     [exec]   After size:        1609721
     [exec]   Delta:             489446
     [exec]   Elapsed:           3.84
     [exec] Received 0
     [exec] Done in 24.66s.
     [echo] Generating Jenkins report.
[beanshell] Jenkins reported generated in 65 ms
     [echo] Rsyncing Jenkins report.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20210301033106700
     [exec] 
     [exec] &gt; Task :dxp:apps:portal-workflow:portal-workflow-metrics-web:packageRunBuild
     [exec] Bundling took 1m
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   1683
     [exec]   Files with errors: 892
     [exec]   Before size:       8586631
     [exec]   After size:        4168168
     [exec]   Delta:             4418463
     [exec]   Elapsed:           19.35
     [exec] Received 0
     [exec] Done in 99.55s.
     [exec] Gradle build finished at 2021-03-01 11:32:03.580.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-impl:compileJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-impl:compileJava'.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-03-01 13:23 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/6786/">test-portal-acceptance-pullrequest(master)#6786</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6786/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/708">liferay-commerce#708</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/96434.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#708 - 2021-03-01[02:27:46]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/16779/">publish-spira-report#16779</a><br />

2021-03-01 13:25 UTC, riccardo-alberti commented
ci:test:relevant

2021-03-01 13:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/4379/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4379/jenkins-report.html">here</a>.</b></p>

2021-03-01 14:03 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/7644/">test-portal-acceptance-pullrequest(master)#7644</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7644/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/708">liferay-commerce#708</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/96452.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#708 - 2021-03-01[02:52:01]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/16783/">publish-spira-report#16783</a><br />

2021-03-01 14:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 37 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9837c4d81f2de200ad2bcd7acc83578fb25e975c">9837c4d81f2de200ad2bcd7acc83578fb25e975c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9837c4d81f2de200ad2bcd7acc83578fb25e975c">9837c4d81f2de200ad2bcd7acc83578fb25e975c</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1589">Acceptance Upstream DXP (master) #1589</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/4379/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4379/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/4379/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-impl:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductChannelResourceImpl.java:63: error: incompatible types: long cannot be converted to String
     [exec] 					contextCompany.getCompanyId(), externalReferenceCode);
     [exec] 					                           ^
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
     [exec] 1 error
     [echo] Generating Jenkins report.
[beanshell] Jenkins reported generated in 122 ms
     [echo] Rsyncing Jenkins report.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20210301060810987
     [exec] 
     [exec] &gt; Task :dxp:apps:sharepoint-soap:sharepoint-soap-repository:buildWSDLGenerateLists
     [exec] Retrieving document at '/opt/dev/projects/github/liferay-portal/modules/dxp/apps/sharepoint-soap/sharepoint-soap-repository/wsdl/lists.wsdl'.
     [exec] 
     [exec] &gt; Task :dxp:apps:segments:segments-experiment-web:packageRunBuild
     [exec] Bundling took 17s
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   1114
     [exec]   Files with errors: 857
     [exec]   Before size:       2099167
     [exec]   After size:        1609721
     [exec]   Delta:             489446
     [exec]   Elapsed:           4.90
     [exec] Received 0
     [exec] Done in 29.75s.
     [exec] 
     [exec] &gt; Task :dxp:apps:portal-workflow:portal-workflow-metrics-web:packageRunBuild
     [exec] Bundling took 1m
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/main.css
     [echo] Generating Jenkins report.
[beanshell] Jenkins reported generated in 43 ms
     [echo] Rsyncing Jenkins report.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20210301060911334
     [exec] Minification summary:
     [exec]   Files processed:   1683</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-03-01 14:35 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/4379/">test-portal-acceptance-pullrequest(master)#4379</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4379/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/708">liferay-commerce#708</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/96463.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#708 - 2021-03-01[05:34:03]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/20638/">publish-spira-report#20638</a><br />

2021-03-01 16:00 UTC, riccardo-alberti commented
ci:test:relevant

2021-03-01 16:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/4351/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4351/jenkins-report.html">here</a>.</b></p>

2021-03-01 16:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 days 15 hours 31 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9837c4d81f2de200ad2bcd7acc83578fb25e975c">9837c4d81f2de200ad2bcd7acc83578fb25e975c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9837c4d81f2de200ad2bcd7acc83578fb25e975c">9837c4d81f2de200ad2bcd7acc83578fb25e975c</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1589">Acceptance Upstream DXP (master) #1589</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/4351/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4351/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/4351/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-impl:compileJava FAILED
     [exec] 
     [exec] &gt; Task :dxp:apps:segments:segments-experiment-web:packageRunBuild
     [exec] Bundling took 12s
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   1114
     [exec]   Files with errors: 857
     [exec]   Before size:       2099167
     [exec]   After size:        1609721
     [exec]   Delta:             489446
     [exec]   Elapsed:           3.76
     [exec] Received 0
     [exec] Done in 21.21s.
     [echo] Generating Jenkins report.
[beanshell] Jenkins reported generated in 73 ms
     [echo] Rsyncing Jenkins report.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20210303232946109
     [exec] 
     [exec] &gt; Task :dxp:apps:portal-workflow:portal-workflow-metrics-web:packageRunBuild
     [exec] Bundling took 1m
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   1683
     [exec]   Files with errors: 892
     [exec]   Before size:       8586631
     [exec]   After size:        4168168
     [exec]   Delta:             4418463
     [exec]   Elapsed:           18.99
     [exec] Received 0
     [exec] Done in 97.60s.
     [exec] Gradle build finished at 2021-03-04 07:30:18.818.
     [exec] 5767 actionable tasks: 5682 executed, 85 up-to-date
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-impl:compileJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-impl:compileJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:208)
     [exec] 	at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:263)</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-03-01 17:35 UTC, riccardo-alberti commented
ci:test:relevant

2021-03-01 17:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/6790/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6790/jenkins-report.html">here</a>.</b></p>

2021-03-01 17:42 UTC, dsitu approved these changes

2021-03-01 18:34 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/4351/">test-portal-acceptance-pullrequest(master)#4351</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4351/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/708">liferay-commerce#708</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/96571.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#708 - 2021-03-01[08:00:51]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/20666/">publish-spira-report#20666</a><br />

2021-03-01 20:50 UTC, dsitu requested changes

2021-03-01 20:50 UTC, dsitu commented on modules/apps/commerce/commerce-test-util/src/main/java/com/liferay/commerce/test/context/TestCommerceContext.java
> +package com.liferay.commerce.test.context;
```suggestion
package com.liferay.commerce.test.util.context;
```

2021-03-01 20:50 UTC, dsitu commented on modules/apps/commerce/commerce-test-util/src/main/java/com/liferay/commerce/test/context/TestCustomCommerceContext.java
> +package com.liferay.commerce.test.context;
```suggestion
package com.liferay.commerce.test.util.context;
```

2021-03-01 20:50 UTC, dsitu commented on modules/apps/commerce/commerce-test-util/src/main/java/com/liferay/commerce/test/context/TestCustomCommerceContextFactory.java
> +package com.liferay.commerce.test.context;
```suggestion
package com.liferay.commerce.test.util.context;
```

2021-03-01 20:50 UTC, dsitu commented on modules/apps/commerce/commerce-test-util/src/main/java/com/liferay/commerce/test/context/TestCustomCommerceContextHttp.java
> +package com.liferay.commerce.test.context;
```suggestion
package com.liferay.commerce.test.util.context;
```

2021-03-02 00:59 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/6790/">test-portal-acceptance-pullrequest(master)#6790</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6790/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/708">liferay-commerce#708</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/96755.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#708 - 2021-03-01[09:35:48]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/publish-spira-report/16651/">publish-spira-report#16651</a><br />

2021-03-02 08:09 UTC, riccardo-alberti commented
ci:test:sf

2021-03-02 08:09 UTC, riccardo-alberti commented
ci:test:relevant

2021-03-02 08:10 UTC, riccardo-alberti commented on modules/apps/commerce/commerce-test-util/src/main/java/com/liferay/commerce/test/context/TestCustomCommerceContextHttp.java
> +package com.liferay.commerce.test.context;
Done. Thanks

2021-03-02 08:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-source-format/6241/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-portal-source-format/builds/6241/jenkins-report.html">here</a>.</b></p>

2021-03-02 08:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e070ce0ffe54f493874dfd651ef7f7dcc179aad4">e070ce0ffe54f493874dfd651ef7f7dcc179aad4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/riccardo-alberti/liferay-portal/tree/COMMERCE-4433_a">COMMERCE-4433_a</a><br/>Branch GIT ID: <a href="https://github.com/riccardo-alberti/liferay-portal/commit/a1fb22dc7ae3e8f0938671b1d94e35f2ce9c570b">a1fb22dc7ae3e8f0938671b1d94e35f2ce9c570b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6241/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6241/jenkins-report.html">here</a>.</h5></details></html>

2021-03-02 08:51 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6241/">test-portal-source-format#6241</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6241/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/708">liferay-commerce#708</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/96963.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#708 - 2021-03-02[00:11:53]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/16887/">publish-spira-report#16887</a><br />

2021-03-02 10:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/5532/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5532/jenkins-report.html">here</a>.</b></p>

2021-03-02 16:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 20 out of 23 jobs passed in 6 hours 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e070ce0ffe54f493874dfd651ef7f7dcc179aad4">e070ce0ffe54f493874dfd651ef7f7dcc179aad4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e070ce0ffe54f493874dfd651ef7f7dcc179aad4">e070ce0ffe54f493874dfd651ef7f7dcc179aad4</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1595">Acceptance Upstream DXP (master) #1595</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320994/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461046/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/463978/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455425/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320995/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/463979/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320997/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464979/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464982/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 19 out of 23 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/5532/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464983/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/321000/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464981/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>19 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465732/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320998/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320994/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/465733/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461046/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/463978/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455423/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320999/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320996/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455425/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455424/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320995/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464980/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/463979/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320997/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/455426/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464979/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320993/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/464982/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5532/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at e070ce0ffe54f493874dfd651ef7f7dcc179aad4:</strong></summary><ol><li><div><h5><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullreque [...]

2021-03-02 16:45 UTC, riccardo-alberti commented
ci:forward

2021-03-02 16:45 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-03-02 16:45 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-03-02 16:47 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pullrequest to `brianchandotcom`.

2021-03-02 16:47 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/99397

2021-03-02 16:47 UTC, closed without merging

2021-03-02 17:04 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/5532/">test-portal-acceptance-pullrequest(master)#5532</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5532/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-commerce/liferay-portal/pull/708">liferay-commerce#708</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/97152.aspx">master - riccardo-alberti &gt; liferay-commerce - PR#708 - 2021-03-02[02:25:37]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/14000/">publish-spira-report#14000</a><br />