Commerce-5856
liferay-commerce/liferay-portal pull request #875
Opened 2021-03-31 02:13 UTC by RitaSilveira

2021-03-31 02:21 UTC, RitaSilveira commented
https://issues.liferay.com/browse/COMMERCE-5856; CC:@lorenzolapescara

2021-04-12 17:45 UTC, kristinonias commented
ci:test:sf

2021-04-12 17:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/5521/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-portal-source-format/builds/5521/jenkins-report.html">here</a>.</b></p>

2021-04-12 17:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9c27e5ff77f72ca30f234c06f42679ea7f6acb7c">9c27e5ff77f72ca30f234c06f42679ea7f6acb7c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RitaSilveira/liferay-portal/tree/Commerce-5856">Commerce-5856</a><br/>Branch GIT ID: <a href="https://github.com/RitaSilveira/liferay-portal/commit/436688c5d527ffd134fcfc4cd21f3fad1569b094">436688c5d527ffd134fcfc4cd21f3fad1569b094</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/5521/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/5521/jenkins-report.html">here</a>.</h5><pre><code>     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 2:08.587 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-18/job/test-portal-source-format/5521//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210412105144953.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210412105144953.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null744737054.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1161049253
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 242ms
[junitreport] Deleting: /tmp/null1161049253
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 04-12-2021 10:51:52:327 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] 
     [echo] Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
     [echo] Memory: 4k page, physical 32902016k(269720k free), swap 0k(0k free)</code></pre></details></html>

2021-04-12 17:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/5521/">test-portal-source-format#5521</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/5521/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/875">liferay-commerce#875</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1525123907">[master] ci:test:sf - RitaSilveira &gt; liferay-commerce - PR#875 - 2021-04-12[10:45:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/265/">publish-testray-report#265</a><br/></div></div>

2021-04-14 13:59 UTC, lorenzolapescara requested changes

2021-04-14 13:59 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductCard.testcase
>  	test AssertProductCardImageRedirectsToProductDetailsPage {
Please remove `@ignore = "true"`.

2021-04-14 13:59 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceFrontStore.path
> +</tr>
This locator is too specific, please rename it "PRODUCT_CARD_IMAGE" and try to identify and use a more reusable path(e.g. by using a variable).

2021-05-11 20:23 UTC, closed without merging