Automated Test - CommerceProductCard.testcase - combined PRs
liferay-commerce/liferay-portal pull request #890
Opened 2021-04-02 23:32 UTC by kristinonias

https://issues.liferay.com/browse/COMMERCE-5858
https://issues.liferay.com/browse/COMMERCE-5865
https://issues.liferay.com/browse/COMMERCE-5866
https://issues.liferay.com/browse/COMMERCE-5867
https://issues.liferay.com/browse/COMMERCE-5872
https://issues.liferay.com/browse/COMMERCE-5871
https://issues.liferay.com/browse/COMMERCE-5868

These should be ready for review.

cc: @lorenzolapescara

2021-04-02 23:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-04-05 15:26 UTC, kristinonias commented
ci:test:sf

2021-04-05 15:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/4855/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-portal-source-format/builds/4855/jenkins-report.html">here</a>.</b></p>

2021-04-05 15:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f8c2d81677d2d44fd0780d79f3b3557e8d55ba42">f8c2d81677d2d44fd0780d79f3b3557e8d55ba42</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kristinonias/liferay-portal/tree/COMMERCE-5858">COMMERCE-5858</a><br/>Branch GIT ID: <a href="https://github.com/kristinonias/liferay-portal/commit/4bc18c937da9ca4ca1f0644c64ab64a8afdaa4b3">4bc18c937da9ca4ca1f0644c64ab64a8afdaa4b3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/4855/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/4855/jenkins-report.html">here</a>.</h5></details></html>

2021-04-15 10:26 UTC, lorenzolapescara commented
Review started

2021-04-19 13:47 UTC, lorenzolapescara requested changes

2021-04-19 13:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +</tr>
This locator is too generic, please rename it to `PRODUCT_CARD_DEFAULT_IMAGE` and try to identify and use a unique and reusable path(e.g. by using a variable).

2021-04-19 13:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductCard.testcase
> +		AssertElementPresent(locator1 = "CommerceEntry#DEFAULT_PRODUCT_IMAGE");
As per comment above, please update `CommerceEntry#DEFAULT_PRODUCT_IMAGE` locator name.

2021-04-19 13:47 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductCard.testcase
> +		ApplicationsMenu.gotoSite(site = "Minium");
The test does not include these steps.

2021-04-28 22:52 UTC, closed without merging

2021-04-28 22:53 UTC, kristinonias commented
New PR [#1067](https://github.com/liferay-commerce/liferay-portal/pull/1067)