COMMERCE-6026
liferay-commerce/liferay-portal pull request #891
Opened 2021-04-05 18:05 UTC by IsaVV

2021-04-05 18:07 UTC, IsaVV commented
https://issues.liferay.com/browse/COMMERCE-6026, cc: @PietroBocale

2021-04-05 22:48 UTC, kristinonias commented
ci:test:sf

2021-04-05 22:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-24.liferay.com/job/test-portal-source-format/451/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-24.liferay.com//userContent/jobs/test-portal-source-format/builds/451/jenkins-report.html">here</a>.</b></p>

2021-04-05 22:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/17a03520500b06ba61c113af0ace535a602afdc8">17a03520500b06ba61c113af0ace535a602afdc8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/IsaVV/liferay-portal/tree/COMMERCE-6026">COMMERCE-6026</a><br/>Branch GIT ID: <a href="https://github.com/IsaVV/liferay-portal/commit/6811707da5534be4fded0d75e9fb5048cd70d204">6811707da5534be4fded0d75e9fb5048cd70d204</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-24.liferay.com/job/test-portal-source-format/451/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-24.liferay.com/userContent/jobs/test-portal-source-format/builds/451/jenkins-report.html">here</a>.</h5></details></html>

2021-04-15 23:43 UTC, brittneyq commented
Hi @IsaVV , please remove the **@ignore = true** in your test and please uncomment the `//CommerceConfiguration.commerceStoreFrontSetUp();` in setup. Thanks!

2021-04-16 17:21 UTC, IsaVV commented
@brittneyq fixed

2021-04-16 17:42 UTC, brittneyq commented
ci:test:sf

2021-04-16 17:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4608/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4608/jenkins-report.html">here</a>.</b></p>

2021-04-16 17:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a804a225365be702f88f6fe5d0ce1b310a2b4e1b">a804a225365be702f88f6fe5d0ce1b310a2b4e1b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/IsaVV/liferay-portal/tree/COMMERCE-6026">COMMERCE-6026</a><br/>Branch GIT ID: <a href="https://github.com/IsaVV/liferay-portal/commit/2ce6c99b6e5eae35b8bb11f87765c227962265ad">2ce6c99b6e5eae35b8bb11f87765c227962265ad</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4608/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4608/jenkins-report.html">here</a>.</h5></details></html>

2021-04-16 17:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4608/">test-portal-source-format#4608</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4608/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/891">liferay-commerce#891</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526497740">[master] ci:test:sf - IsaVV &gt; liferay-commerce - PR#891 - 2021-04-16[10:42:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/386/">publish-testray-report#386</a><br/></div></div>

2021-04-20 14:26 UTC, Pietro69 requested changes

2021-04-20 14:26 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductMedia.testcase
> +		Refresh();
Please remove the creation for the Master catalog because is already created when we do the reindex into the setUp (lines 15-20)

2021-04-20 19:37 UTC, IsaVV commented
fixed @Pietro69

2021-04-21 14:06 UTC, Pietro69 commented
Add the property `test.name.skip.portal.instance = "CPCommerceProductMedia#RemoveAnImage"`

2021-04-22 18:50 UTC, IsaVV commented
fixed

2021-04-22 19:04 UTC, pedro-michel commented
ci:test:sf

2021-04-22 19:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/5007/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-portal-source-format/builds/5007/jenkins-report.html">here</a>.</b></p>

2021-04-22 19:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9">03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/IsaVV/liferay-portal/tree/COMMERCE-6026">COMMERCE-6026</a><br/>Branch GIT ID: <a href="https://github.com/IsaVV/liferay-portal/commit/47c00f17288c0af7df62c39577c6d0d041cb45ab">47c00f17288c0af7df62c39577c6d0d041cb45ab</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5007/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5007/jenkins-report.html">here</a>.</h5></details></html>

2021-04-22 19:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5007/">test-portal-source-format#5007</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5007/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/891">liferay-commerce#891</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527872317">[master] ci:test:sf - IsaVV &gt; liferay-commerce - PR#891 - 2021-04-22[12:05:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/398/">publish-testray-report#398</a><br/></div></div>

2021-04-26 13:38 UTC, Pietro69 approved these changes

2021-04-26 13:38 UTC, Pietro69 commented
ci:test:commerce-functional

2021-04-26 14:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/4679/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4679/jenkins-report.html">here</a>.</b></p>

2021-04-28 15:06 UTC, Pietro69 commented
ci:forward

2021-04-28 15:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-28 15:06 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-04-28 15:07 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-21.liferay.com/job/forward-pullrequest/197//consoleFull)

2021-04-28 15:07 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101210
[Console](https://test-1-21.liferay.com/job/forward-pullrequest/197//consoleFull)

2021-04-28 15:07 UTC, closed without merging