COMMERCE-6318
liferay-commerce/liferay-portal pull request #900
Opened 2021-04-06 20:55 UTC by lucasperj

2021-04-06 20:57 UTC, lucasperj commented
https://issues.liferay.com/browse/COMMERCE-6318 ; cc: @lorenzolapescara

2021-04-06 21:53 UTC, kristinonias commented
ci:test:sf

2021-04-06 21:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/5511/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-source-format/builds/5511/jenkins-report.html">here</a>.</b></p>

2021-04-06 21:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7a0ca52f73c9537da5e4867a228d103eaa3264fe">7a0ca52f73c9537da5e4867a228d103eaa3264fe</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lucasperj/liferay-portal/tree/COMMERCE-6318">COMMERCE-6318</a><br/>Branch GIT ID: <a href="https://github.com/lucasperj/liferay-portal/commit/dce66cd9322677c75e0e03e0aa0da2ebbb805b03">dce66cd9322677c75e0e03e0aa0da2ebbb805b03</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/5511/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/5511/jenkins-report.html">here</a>.</h5></details></html>

2021-04-20 15:40 UTC, lorenzolapescara commented
Review started

2021-04-20 16:48 UTC, lorenzolapescara requested changes

2021-04-20 16:48 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductCard.testcase
> +			locator1 = "CommerceEntry#TABLE_LIST_TITLE");
```suggestion
		CommerceNavigator.gotoEntry(entryName = "U-Joint");
```

2021-04-22 20:44 UTC, pedro-michel commented
ci:test:sf

2021-04-22 20:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/2827/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-portal-source-format/builds/2827/jenkins-report.html">here</a>.</b></p>

2021-04-22 20:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9">03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lucasperj/liferay-portal/tree/COMMERCE-6318">COMMERCE-6318</a><br/>Branch GIT ID: <a href="https://github.com/lucasperj/liferay-portal/commit/94365af76b1e433cc2f00dbccb34a64c476cb766">94365af76b1e433cc2f00dbccb34a64c476cb766</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/2827/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/2827/jenkins-report.html">here</a>.</h5></details></html>

2021-04-22 20:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/2827/">test-portal-source-format#2827</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/2827/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/900">liferay-commerce#900</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527893130">[master] ci:test:sf - lucasperj &gt; liferay-commerce - PR#900 - 2021-04-22[13:44:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/371/">publish-testray-report#371</a><br/></div></div>

2021-04-26 13:40 UTC, lorenzolapescara approved these changes

2021-04-26 13:40 UTC, lorenzolapescara commented
ci:test:commerce-functional

2021-04-26 14:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7265/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7265/jenkins-report.html">here</a>.</b></p>

2021-04-26 16:28 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 2 out of 5 jobs passed in 2 hours 12 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1797">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1087401_7265</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2011a79507bc22f8141df273f04f5c319e61366">e2011a79507bc22f8141df273f04f5c319e61366</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c4dd4efe701b6e408384c72ed53a8b1df0d5aec0">c4dd4efe701b6e408384c72ed53a8b1df0d5aec0</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1796">Acceptance Upstream DXP (master) #1796</a></p><details><summary><strong>ci:test:commerce-functional - 2 out of 5 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7265/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/469751/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/441129/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/411791/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/411790/">test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7265/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/469751/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>18 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=18,label_exp=!master/469751//consoleText">AXIS_VARIABLE=18,label_exp=!master #469751</a><pre><code>run-ant-target:
[beanshell] The properties for 'functional-tomcat90-mysql57-jdk8/0/start.properties' cannot be found in /tmp/jenkins/test-1-16/test-portal-acceptance-pullrequest-batch(master)/18/469751/build-database.json
[beanshell] Executing commands: ssh test-1-16 date +%s
[beanshell] Created cache file in /tmp/jenkins-cached-files/-1471643765.txt
[beanshell] Created cache file in /tmp/jenkins-cached-files/-1471643765.txt

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:12833: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest-batch.xml:5: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-portal-acceptance-batch.xml:11: Please set the property 7265.</code></pre></div></li><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=22,label_exp=!master/469751//consoleText">AXIS_VARIABLE=22,label_exp=!master #469751</a><pre><code>run-ant-target:
[beanshell] The properties for 'functional-tomcat90-mysql57-jdk8/0/start.properties' cannot be found in /tmp/jenkins/test-1-16/test-portal-acceptance-pullrequest-batch(master)/22/469751/build-database.json
[beanshell] Executing commands: ssh test-1-16 date +%s
[beanshell] Created cache file in /tmp/jenkins-cached-files/-1040778120.txt
[beanshell] Created cache file in /tmp/jenkins-cached-files/-1040778120.txt

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:12833: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest-batch.xml:5: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-portal-acceptance-batch.xml:11: Please set the property 7265.</code></pre></div></li><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/469751//consoleText">AXIS_VARIABLE=1,label_exp=!master #469751</a><ol><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/469751//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CPCommerceChannels_AddShippingOptionFlatRate_">LocalFile.CPCommerceChannels#AddShippingOptionFlatRate</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-04/test-1-8/test-portal-acceptance-pullrequest(master)/7265/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.CPCommerceChannels_AddShippingOptionFlatRate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-04/test-1-8/test-portal-acceptance-pullrequest(master)/7265/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.CPCommerceChannels_AddShippingOptionFlatRate/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-04/test-1-8/test-portal-acceptance-pullrequest(master)/7265/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/469751//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CPCommerceChannels_AddShippingOptionVariableRate_">LocalFile.CPCommerceChannels#AddShippingOptionVariableRate</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-04/test-1-8/test-portal-acceptance-pullrequest(master)/7265/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.CPCommerceChannels_AddShippingOptionVariableRate/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-04/test-1-8/test-portal-acceptance-pullrequest(master)/7265/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.CPCommerceChannels_AddShippingOptionVariableRate/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-04/test-1-8/test-portal-acceptance-pullrequest(master)/7265/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/469751//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CPCommerceChannels_EditAuthorizePaymentMethod_">LocalFile.CPCommerceChannels#EditAuthorizePaymentMethod</a> - <a href="https://testray.liferay.com/reports/production/logs/2021-04/test-1-8/test-portal-acceptance-pullrequest(master)/7265/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.CPCommerceChannels_EditA [...]

2021-04-26 16:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7265/">test-portal-acceptance-pullrequest(master)#7265</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7265/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/900">liferay-commerce#900</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528596392">[master] ci:test:commerce-functional - lucasperj &gt; liferay-commerce - PR#900 - 2021-04-26[07:04:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/525/">publish-testray-report#525</a><br/></div></div>

2021-04-26 17:04 UTC, lorenzolapescara commented
ci:test:commerce-functional

2021-04-26 17:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/5738/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5738/jenkins-report.html">here</a>.</b></p>

2021-04-26 20:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 0 out of 5 jobs passed in 3 hours 46 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1798">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1187401_5738</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c4c731285388d615b0631d9b2d7ead8b2555c486">c4c731285388d615b0631d9b2d7ead8b2555c486</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/053984004354b73692dbc66c41ca271ab9cba057">053984004354b73692dbc66c41ca271ab9cba057</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1797">Acceptance Upstream DXP (master) #1797</a></p><details><summary><strong>ci:test:commerce-functional - 0 out of 5 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/5738/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328400/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460702/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/441155/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/432448/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5738/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460702/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>7 Tests Passed.<br/>14 Tests Failed.</p></div><ol><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/460702//consoleText">AXIS_VARIABLE=10,label_exp=!master #460702</a><pre><code>     [echo] 	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
     [echo] 	- locked &lt;0x00000006c20138f0&gt; (a java.lang.ref.Reference$Lock)
     [echo] 	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "main" #1 prio=5 os_prio=0 tid=0x00007f009400b800 nid=0x4f84 runnable [0x00007f009a481000]
     [echo]    java.lang.Thread.State: RUNNABLE
     [echo] 	at java.net.PlainSocketImpl.socketAccept(Native Method)
     [echo] 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
     [echo] 	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
     [echo] 	at java.net.ServerSocket.accept(ServerSocket.java:513)
     [echo] 	at org.apache.catalina.core.StandardServer.await(StandardServer.java:609)
     [echo] 	at org.apache.catalina.startup.Catalina.await(Catalina.java:864)
     [echo] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:810)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [echo] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [echo] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [echo] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
     [echo] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "VM Thread" os_prio=0 tid=0x00007f009409b000 nid=0x4f89 runnable 
     [echo] 
     [echo] "Gang worker#0 (Parallel GC Threads)" os_prio=0 tid=0x00007f009401c800 nid=0x4f85 runnable 
     [echo] 
     [echo] "Gang worker#1 (Parallel GC Threads)" os_prio=0 tid=0x00007f009401e800 nid=0x4f86 runnable 
     [echo] 
     [echo] "VM Periodic Task Thread" os_prio=0 tid=0x00007f0094223000 nid=0x4f9d waiting on condition 
     [echo] 
     [echo] JNI global references: 16644
      [get] Getting: http://test-1-19/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/460702//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210426123151494.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210426123151494.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2036559153.properties</code></pre></div></li><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/460702//consoleText">AXIS_VARIABLE=11,label_exp=!master #460702</a><pre><code> [parallel] 2021-04-26 18:54:22.317 INFO  [main][SystemCheckOSGiCommands:126] Spring Extender Unavailable Component Checker check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 6:13.540 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13178: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13536: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5634: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5831: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:397: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml doesn't exist
      [get] Getting: http://test-1-19/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/460702//c [...]

2021-04-26 20:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/5738/">test-portal-acceptance-pullrequest(master)#5738</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5738/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/900">liferay-commerce#900</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528621574">[master] ci:test:commerce-functional - lucasperj &gt; liferay-commerce - PR#900 - 2021-04-26[10:04:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/505/">publish-testray-report#505</a><br/></div></div>

2021-04-27 08:38 UTC, lorenzolapescara commented
ci:forward

2021-04-27 08:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-27 08:38 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-04-27 08:39 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-14.liferay.com/job/forward-pullrequest/228//consoleFull)

2021-04-27 08:39 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101134
[Console](https://test-1-14.liferay.com/job/forward-pullrequest/228//consoleFull)

2021-04-27 08:39 UTC, closed without merging