COMMERCE-5869
liferay-commerce/liferay-portal pull request #901
Opened 2021-04-06 21:32 UTC by PauloVAS

2021-04-06 21:34 UTC, PauloVAS commented
https://issues.liferay.com/browse/COMMERCE-5869, CC:@lorenzolapescara

2021-04-06 21:53 UTC, kristinonias commented
ci:test:sf

2021-04-06 21:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/5608/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-source-format/builds/5608/jenkins-report.html">here</a>.</b></p>

2021-04-06 21:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7a0ca52f73c9537da5e4867a228d103eaa3264fe">7a0ca52f73c9537da5e4867a228d103eaa3264fe</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/COMMERCE-5869">COMMERCE-5869</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/300d1250a0b078e4f1d32e9db940923c83725fb1">300d1250a0b078e4f1d32e9db940923c83725fb1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5608/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5608/jenkins-report.html">here</a>.</h5></details></html>

2021-04-15 23:37 UTC, brittneyq commented
Hi @PauloVAS, please uncomment your teardown and remove the **@ignore = true**. Thank you!

2021-04-16 16:39 UTC, PauloVAS commented
@brittneyq fixed.

2021-04-16 16:46 UTC, brittneyq commented
ci:test:sf

2021-04-16 16:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/2764/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com//userContent/jobs/test-portal-source-format/builds/2764/jenkins-report.html">here</a>.</b></p>

2021-04-16 16:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f6253db1cbd2802cf0ca60b90ef4615208134bdb">f6253db1cbd2802cf0ca60b90ef4615208134bdb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/COMMERCE-5869">COMMERCE-5869</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/b1491ba501752d62781babe420f3fc9f0e349f34">b1491ba501752d62781babe420f3fc9f0e349f34</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/2764/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/2764/jenkins-report.html">here</a>.</h5></details></html>

2021-04-16 16:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/2764/">test-portal-source-format#2764</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/2764/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/901">liferay-commerce#901</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526483886">[master] ci:test:sf - PauloVAS &gt; liferay-commerce - PR#901 - 2021-04-16[09:47:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/229/">publish-testray-report#229</a><br/></div></div>

2021-04-21 11:21 UTC, lorenzolapescara commented
Review started

2021-04-26 14:15 UTC, lorenzolapescara requested changes

2021-04-27 19:49 UTC, PauloVAS commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductCard.testcase
> +			locator1 = "CommerceEntry#SELECT_CHECKBOX");
@lorenzolapescara I tried to use only the "AssertChecked" function, but i was always getting the same error, so i decided to use "AssertChecked.assertCheckedNotVisible" and it worked 100%.

2021-04-27 19:50 UTC, PauloVAS commented
@lorenzolapescara fixed

2021-04-28 13:41 UTC, lorenzolapescara approved these changes

2021-04-28 13:41 UTC, lorenzolapescara commented
ci:test:sf

2021-04-28 13:41 UTC, lorenzolapescara commented
ci:test:commerce-functional

2021-04-28 13:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-source-format/6462/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-portal-source-format/builds/6462/jenkins-report.html">here</a>.</b></p>

2021-04-28 13:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest(master)/8100/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8100/jenkins-report.html">here</a>.</b></p>

2021-04-28 13:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/57e7fbc138485535fb62a9c888f6b158b3452e82">57e7fbc138485535fb62a9c888f6b158b3452e82</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/COMMERCE-5869">COMMERCE-5869</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/b4eed4210e8e19cc3c20675df127c4d38223fdd3">b4eed4210e8e19cc3c20675df127c4d38223fdd3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6462/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6462/jenkins-report.html">here</a>.</h5></details></html>

2021-04-28 13:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6462/">test-portal-source-format#6462</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6462/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/901">liferay-commerce#901</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529130273">[master] ci:test:sf - PauloVAS &gt; liferay-commerce - PR#901 - 2021-04-28[06:41:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-22.liferay.com/job/publish-testray-report/476/">publish-testray-report#476</a><br/></div></div>

2021-04-28 15:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 1 out of 5 jobs passed in 2 hours 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/57e7fbc138485535fb62a9c888f6b158b3452e82">57e7fbc138485535fb62a9c888f6b158b3452e82</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/57e7fbc138485535fb62a9c888f6b158b3452e82">57e7fbc138485535fb62a9c888f6b158b3452e82</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1808">Acceptance Upstream DXP (master) #1808</a></p><details><summary><strong>ci:test:commerce-functional - 1 out of 5 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest(master)/8100/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/383832/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460961/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/224889/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/224888/">test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8100/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/383832/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>19 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=23,label_exp=!master/383832//consoleText">AXIS_VARIABLE=23,label_exp=!master #383832</a><pre><code>[beanshell] Unable to delete because file does not exist /opt/dev/projects/github/liferay-jenkins-ee/testray/logs
[beanshell] Created cache file in /tmp/jenkins-cached-files/570904313.txt
[beanshell] Executing commands: git remote -v
[beanshell] Found git remotes: origin, upstream
[beanshell] Remote execution starting with 1 threads.
[beanshell] Executing commands: ssh -o NumberOfPasswordPrompts=0 test-1-9 'mkdir -p "/mnt/mfs-hdd1-10.0.10/jenkins/testray-results/production/logs/2021-04/test-1-22/test-portal-acceptance-pullrequest(master)/8100/functional-tomcat90-mysql57-jdk8/0/23"'
[beanshell] Average thread duration: 222ms
[beanshell] Busy slaves:0
[beanshell] Finished slaves:1
[beanshell] Target slaves:1
[beanshell] Total duration: 222
[beanshell] Remote execution completed in 223ms.
[beanshell] Executing commands: rsync -aqz --chmod=go=rx "/opt/dev/projects/github/liferay-jenkins-ee/testray/logs"/* "test-1-9::testray-results/production/logs/"
[beanshell] Uploaded https://testray.liferay.com/reports/production/logs/2021-04/test-1-22/test-portal-acceptance-pullrequest%28master%29/8100/functional-tomcat90-mysql57-jdk8/0/23/jenkins-console.txt.gz
[stopwatch] [run.current.job: 1:10.273 sec]
[beanshell] Created cache file in /tmp/jenkins-cached-files/570904313.txt

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:12794: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-portal-acceptance-batch.xml:195: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:9695: Sourced file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : Method Invocation gitWorkingDirectory.clean : at Line: 100 : in file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : gitWorkingDirectory .clean ( ) 

Target exception: java.lang.RuntimeException: Unable to clean Git repository
warning: failed to remove .gradle/caches/modules-2/files-2.1: Directory not empty
warning: failed to remove bundles/tomcat-9.0.43/webapps/ROOT: Directory not empty</code></pre></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=9,label_exp=!master/383832//consoleText">AXIS_VARIABLE=9,label_exp=!master #383832</a><pre><code>[beanshell] Uploaded https://testray.liferay.com/reports/production/logs/2021-04/test-1-22/test-portal-acceptance-pullrequest%28master%29/8100/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.SAML_AddUserInheritedRolesAsSAMLAttributeStatements/summary.html.gz
[beanshell] Uploaded https://testray.liferay.com/reports/production/logs/2021-04/test-1-22/test-portal-acceptance-pullrequest%28master%29/8100/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.SAML_AddUserInheritedRolesAsSAMLAttributeStatements/screenshots/screenshot1.jpg.gz
[beanshell] Uploaded https://testray.liferay.com/reports/production/logs/2021-04/test-1-22/test-portal-acceptance-pullrequest%28master%29/8100/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.SAML_AddUserInheritedRolesAsSAMLAttributeStatements/screenshots/after2.jpg.gz
[beanshell] Uploaded https://testray.liferay.com/reports/production/logs/2021-04/test-1-22/test-portal-acceptance-pullrequest%28master%29/8100/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.SAML_AddUserInheritedRolesAsSAMLAttributeStatements/screenshots/screenshot0.jpg.gz
[beanshell] Uploaded https://testray.liferay.com/reports/production/logs/2021-04/test-1-22/test-portal-acceptance-pullrequest%28master%29/8100/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.SAML_AddUserInheritedRolesAsSAMLAttributeStatements/screenshots/before2.jpg.gz
[stopwatch] [run.current.job: 51.302 sec]
[beanshell] Created cache file in /tmp/jenkins-cached-files/-1223694628.txt

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:12794: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-portal-acceptance-batch.xml:195: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:9695: Sourced file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : Method Invocation gitWorkingDirectory.clean : at Line: 100 : in file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : gitWorkingDirectory .clean ( ) 

Target exception: java.lang.RuntimeException: Unable to clean Git repository
fatal: Cannot lstat 'bundles/': No such file or directory</code></pre></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/383832//consoleText">AXIS_VARIABLE=1,label_exp=!master #383832</a><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/383832//testReport/com.liferay.poshi.runner/Po [...]

2021-04-28 15:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest(master)/8100/">test-portal-acceptance-pullrequest(master)#8100</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8100/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/901">liferay-commerce#901</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529204387">[master] ci:test:commerce-functional - PauloVAS &gt; liferay-commerce - PR#901 - 2021-04-28[06:41:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-22.liferay.com/job/publish-testray-report/482/">publish-testray-report#482</a><br/></div></div>

2021-04-28 16:06 UTC, lorenzolapescara commented
ci:forward

2021-04-28 16:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-28 16:06 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-04-28 16:06 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-17.liferay.com/job/forward-pullrequest/168//consoleFull)

2021-04-28 16:07 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101214
[Console](https://test-1-17.liferay.com/job/forward-pullrequest/168//consoleFull)

2021-04-28 16:07 UTC, closed without merging