COMMERCE-6086
liferay-commerce/liferay-portal pull request #903
Opened 2021-04-07 17:35 UTC by leilanyaragao

2021-04-07 17:37 UTC, leilanyaragao commented
https://issues.liferay.com/browse/COMMERCE-6086, cc: @PietroBocale

2021-04-08 15:01 UTC, kristinonias commented
ci:test:sf

2021-04-08 15:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/5330/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-source-format/builds/5330/jenkins-report.html">here</a>.</b></p>

2021-04-08 15:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/245d7f1752e0f05da0949b93ec60e181e0cde39c">245d7f1752e0f05da0949b93ec60e181e0cde39c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leilanyaragao/liferay-portal/tree/COMMERCE-6086">COMMERCE-6086</a><br/>Branch GIT ID: <a href="https://github.com/leilanyaragao/liferay-portal/commit/835572c3086b8a7676d5923f4a1ecb1ea1b35ed4">835572c3086b8a7676d5923f4a1ecb1ea1b35ed4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5330/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5330/jenkins-report.html">here</a>.</h5></details></html>

2021-04-08 15:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5330/">test-portal-source-format#5330</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5330/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/903">liferay-commerce#903</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1524203834">[master] ci:test:sf - leilanyaragao &gt; liferay-commerce - PR#903 - 2021-04-08[08:01:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/353/">publish-testray-report#353</a><br/></div></div>

2021-04-15 23:28 UTC, brittneyq commented
Hi @leilanyaragao , can you remove the **@ignore = true** in the test stub for your test? Thank you!

2021-04-16 21:53 UTC, kristinonias commented
ci:test:sf

2021-04-16 21:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/2881/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-source-format/builds/2881/jenkins-report.html">here</a>.</b></p>

2021-04-16 21:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9f375528c91b2c745e13b92a25b67de3595523a3">9f375528c91b2c745e13b92a25b67de3595523a3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leilanyaragao/liferay-portal/tree/COMMERCE-6086">COMMERCE-6086</a><br/>Branch GIT ID: <a href="https://github.com/leilanyaragao/liferay-portal/commit/f6b20a7b1a15a1cd1a0d07e1a222099246be7884">f6b20a7b1a15a1cd1a0d07e1a222099246be7884</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2881/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2881/jenkins-report.html">here</a>.</h5></details></html>

2021-04-16 21:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/2881/">test-portal-source-format#2881</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/2881/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/903">liferay-commerce#903</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526565445">[master] ci:test:sf - leilanyaragao &gt; liferay-commerce - PR#903 - 2021-04-16[14:53:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/316/">publish-testray-report#316</a><br/></div></div>

2021-04-21 15:39 UTC, Pietro69 requested changes

2021-04-21 15:39 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase
> +            key_checkboxName = "Test Channel");
It's possible to use Checkbox#ENABLE_CHECKBOX with key_checkboxName = "Test Channel"

2021-04-21 15:39 UTC, Pietro69 commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/Checkbox.path
> +</tr>
I think is possible to remove it

2021-04-21 15:39 UTC, Pietro69 commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/ToggleSwitch.path
> +</tr>
Please change this path and make it more reusable using variables

2021-04-21 15:39 UTC, Pietro69 commented
Please add the property `test.name.skip.portal.instance = "CPCommerceProductVisibility#AddAChannelFilter"`

2021-04-22 19:04 UTC, pedro-michel commented
ci:test:sf

2021-04-22 19:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/5610/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-source-format/builds/5610/jenkins-report.html">here</a>.</b></p>

2021-04-22 19:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9">03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leilanyaragao/liferay-portal/tree/COMMERCE-6086">COMMERCE-6086</a><br/>Branch GIT ID: <a href="https://github.com/leilanyaragao/liferay-portal/commit/e295a5dcc9c584ccdf8ec8ccb6c7099c67f31367">e295a5dcc9c584ccdf8ec8ccb6c7099c67f31367</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/5610/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/5610/jenkins-report.html">here</a>.</h5></details></html>

2021-04-23 12:52 UTC, Pietro69 commented
ci:test:commerce-functional

2021-04-23 12:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8108/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8108/jenkins-report.html">here</a>.</b></p>

2021-04-23 13:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 0 out of 1 jobs passed in 18 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9">03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9">03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1790">Acceptance Upstream DXP (master) #1790</a></p><details><summary><strong>ci:test:commerce-functional - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8108/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8108/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8108/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>POSHI Validation Failure<pre><code> [parallel] 1 errors in Poshi script syntax
 [parallel] 
 [parallel] Invalid Poshi Script syntax at:
 [parallel] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase:53
 [parallel]   43 |    test AddAccountGroupFilter \{
 [parallel]   44 |        property portal.acceptance = "false";
 [parallel]   45 |
 [parallel]   46 |        // TODO COMMERCE-6088 AddAccountGroupFilter
 [parallel]   47 |
 [parallel]   48 |    \}
 [parallel]   49 |
 [parallel]   50 |    @description = "This is a test for COMMERCE-6086. AddAChannelFilter"
 [parallel]   51 |    @priority = "3"
 [parallel]   52 |    test AddAChannelFilter \{
 [parallel] &gt; 53 |        test.name.skip.portal.instance = "CPCommerceProductVisibility#AddAChannelFilter"
 [parallel]   54 |        property portal.acceptance = "false";
 [parallel]   55 |
 [parallel]   56 |        CommerceNavigator.gotoPortlet(
 [parallel]   57 |            category = "Store Management",
 [parallel]   58 |            portlet = "Channels");
 [parallel]   59 |
 [parallel]   60 |        Click(locator1 = "Button#PLUS");
 [parallel]   61 |
 [parallel]   62 |        CommerceEntry.addNewChannelsEntry(
 [parallel]   63 |            channelCurrency = "US Dollar",
 [parallel] Retry creating a test class group in 5 seconds.
 [parallel] [functional-tomcat90-mysql57-jdk8] Started batch test class group at Apr 23, 2021 6:10:16 AM PDT
 [parallel] ant -f build-test.xml prepare-poshi-runner-properties
 [parallel] Buildfile: /opt/dev/projects/github/liferay-portal/build-test.xml
 [parallel]   [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
 [parallel]   [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
 [parallel]    [delete] Deleting: /opt/dev/projects/github/liferay-portal/null824277020.properties
 [parallel] 
 [parallel] prepare-poshi-runner-properties:
 [parallel] 
 [parallel] BUILD SUCCESSFUL
 [parallel] Total time: 0 seconds
 [parallel] Start reading Poshi files.
 [parallel] Directory /opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates/src/testFunctional does not exist.
 [parallel] 
 [parallel] 
 [parallel] 2 errors in Poshi script syntax
 [parallel] 
 [parallel] Invalid Poshi Script syntax at:
 [parallel] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase:53
 [parallel]   43 |    test AddAccountGroupFilter \{
 [parallel]   44 |        property portal.acceptance = "false";
 [parallel]   45 |
 [parallel]   46 |        // TODO COMMERCE-6088 AddAccountGroupFilter
 [parallel]   47 |
 [parallel]   48 |    \}
 [parallel]   49 |
 [parallel]   50 |    @description = "This is a test for COMMERCE-6086. AddAChannelFilter"
 [parallel]   51 |    @priority = "3"
 [parallel]   52 |    test AddAChannelFilter \{
 [parallel] &gt; 53 |        test.name.skip.portal.instance = "CPCommerceProductVisibility#AddAChannelFilter"
 [parallel]   54 |        property portal.acceptance = "false";
 [parallel]   55 |
 [parallel]   56 |        CommerceNavigator.gotoPortlet(
 [parallel]   57 |            category = "Store Management",
 [parallel]   58 |            portlet = "Channels");
 [parallel]   59 |
 [parallel]   60 |        Click(locator1 = "Button#PLUS");
 [parallel]   61 |
 [parallel]   62 |        CommerceEntry.addNewChannelsEntry(
 [parallel]   63 |            channelCurrency = "US Dollar",
 [parallel] 
 [parallel] 
 [parallel] Invalid Poshi Script syntax at:
 [parallel] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase:53
 [parallel]   43 |    test AddAccountGroupFilter \{
 [parallel]   44 |        property portal.acceptance = "false";
 [parallel]   45 |
 [parallel]   46 |        // TODO COMMERCE-6088 AddAccountGroupFilter
 [parallel]   47 |
 [parallel]   48 |    \}
 [parallel]   49 |
 [parallel]   50 |    @description = "This is a test for COMMERCE-6086. AddAChannelFilter"
 [parallel]   51 |    @priority = "3"
 [parallel]   52 |    test AddAChannelFilter \{
 [parallel] &gt; 53 |        test.name.skip.portal.instance = "CPCommerceProductVisibility#AddAChannelFilter"
 [parallel]   54 |        property portal.acceptance = "false";
 [parallel]   55 |
 [parallel]   56 |        CommerceNavigator.gotoPortlet(
 [parallel]   57 |            category = "Store Management",
 [parallel]   58 |            portlet = "Channels");
 [parallel]   59 |
 [parallel]   60 |        Click(locator1 = "Button#PLUS");
 [parallel]   61 |
 [parallel]   62 |        CommerceEntry.addNewChannelsEntry(
 [parallel]   63 |            channelCurrency = "US Dollar",
 [parallel] Retry creating a test class group in 5 seconds.
 [parallel] [functional-tomcat90-mysql57-jdk8] Started batch test class group at Apr 23, 2021 6:10:30 AM PDT
 [parallel] ant -f build-test.xml prepare-poshi-runner-properties
 [parallel] Buildfile: /opt/dev/projects/github/liferay-portal/build-test.xml
 [parallel]   [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
 [parallel]   [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
 [parallel]    [delete] Deleting: /opt/dev/projects/github/liferay-portal/null454340953.properties
 [parallel] 
 [parallel] prepare-poshi-runner-properties:
 [parallel] 
 [parallel] BUILD SUCCESSFUL
 [parallel] Total time: 0 seconds
 [parallel] Start reading Poshi files.
 [parallel] Directory /opt/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates/src/testFunctional does not exist.
 [parallel] 
 [parallel] 
 [parallel] 3 errors in Poshi script syntax
 [parallel] 
 [parallel] Invalid Poshi Script syntax at:
 [parallel] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase:53
 [parallel]   43 |    test AddAccountGroupFilter \{
 [parallel]   44 |        property portal.acceptance = "false";
 [parallel]   45 |
 [parallel]   46 |        // TODO COMMERCE-6088 AddAccountGroupFilter
 [parallel]   47 |
 [parallel]   48 |    \}
 [parallel]   49 |
 [parallel]   50 |    @descripti [...]

2021-04-26 14:27 UTC, Pietro69 requested changes

2021-04-26 14:27 UTC, Pietro69 commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/ToggleSwitch.path
> +    <td>//span[contains(@id,'${key_toggleSwitch}')]</td>
Please use this path `//h4[contains(.,"${key_name}")]//span[contains(@id,'toggle-switch')]`

2021-04-26 14:27 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase
> +			key_toggleSwitch = "ojma___toggle-switch",
Please use key_name = "Channels"

2021-04-26 19:25 UTC, pedro-michel commented
ci:test:sf

2021-04-26 19:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/5428/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-source-format/builds/5428/jenkins-report.html">here</a>.</b></p>

2021-04-26 19:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c4c731285388d615b0631d9b2d7ead8b2555c486">c4c731285388d615b0631d9b2d7ead8b2555c486</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leilanyaragao/liferay-portal/tree/COMMERCE-6086">COMMERCE-6086</a><br/>Branch GIT ID: <a href="https://github.com/leilanyaragao/liferay-portal/commit/924bab0e674a7989fe38386fb8a16512fefa67f9">924bab0e674a7989fe38386fb8a16512fefa67f9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5428/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5428/jenkins-report.html">here</a>.</h5></details></html>

2021-04-26 19:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5428/">test-portal-source-format#5428</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5428/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/903">liferay-commerce#903</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528612601">[master] ci:test:sf - leilanyaragao &gt; liferay-commerce - PR#903 - 2021-04-26[12:26:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/665/">publish-testray-report#665</a><br/></div></div>

2021-04-28 15:02 UTC, Pietro69 commented
ci:test:commerce-functional

2021-04-28 15:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/5758/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5758/jenkins-report.html">here</a>.</b></p>

2021-04-28 18:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 1 out of 5 jobs passed in 2 hours 57 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1809">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1187401_5758</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c551b24f138a765a4f18318e03953f4030650083">c551b24f138a765a4f18318e03953f4030650083</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/57e7fbc138485535fb62a9c888f6b158b3452e82">57e7fbc138485535fb62a9c888f6b158b3452e82</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1808">Acceptance Upstream DXP (master) #1808</a></p><details><summary><strong>ci:test:commerce-functional - 1 out of 5 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/5758/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/383847/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356021/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/224893/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/224892/">test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5758/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356021/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>7 Tests Passed.<br/>14 Tests Failed.</p></div><ol><li><div><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/356021//consoleText">AXIS_VARIABLE=10,label_exp=!master #356021</a><pre><code> [parallel] 2021-04-28 16:33:27.314 INFO  [main][SystemCheckOSGiCommands:126] Missing Component Scanner check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 7:11.199 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13207: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13565: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5645: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5842: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:397: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml doesn't exist
      [get] Getting: http://test-1-12/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/356021//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210428093334543.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210428093334543.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null225473399.properties</code></pre></div></li><li><div><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/356021//consoleText">AXIS_VARIABLE=11,label_exp=!master #356021</a><pre><code>     [echo] 	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
     [echo] 	- locked &lt;0x00000006c2029740&gt; (a java.lang.ref.Reference$Lock)
     [echo] 	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "main" #1 prio=5 os_prio=0 tid=0x00007f707400b800 nid=0x3850 runnable [0x00007f707a6c6000]
     [echo]    java.lang.Thread.State: RUNNABLE
     [echo] 	at java.net.PlainSocketImpl.socketAccept(Native Method)
     [echo] 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
     [echo] 	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
     [echo] 	at java.net.ServerSocket.accept(ServerSocket.java:513)
     [echo] 	at org.apache.catalina.core.StandardServer.await(StandardServer.java:609)
     [echo] 	at org.apache.catalina.startup.Catalina.await(Catalina.java:864)
     [echo] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:810)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [echo] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [echo] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [echo] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
     [echo] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "VM Thread" os_prio=0 tid=0x00007f707409b000 nid=0x3853 runnable 
     [echo] 
     [echo] "Gang worker#0 (Parallel GC Threads)" os_prio=0 tid=0x00007f707401c800 nid=0x3851 runnable 
     [echo] 
     [echo] "Gang worker#1 (Parallel GC Threads)" os_prio=0 tid=0x00007f707401e800 nid=0x3852 runnable 
     [echo] 
     [echo] "VM Periodic Task Thread" os_prio=0 tid=0x00007f707422d000 nid=0x3867 waiting on condition 
     [echo] 
     [echo] JNI global references: 16708
      [get] Getting: http://test-1-12/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11, [...]

2021-04-28 18:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/5758/">test-portal-acceptance-pullrequest(master)#5758</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5758/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/903">liferay-commerce#903</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529229979">[master] ci:test:commerce-functional - leilanyaragao &gt; liferay-commerce - PR#903 - 2021-04-28[08:03:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/550/">publish-testray-report#550</a><br/></div></div>

2021-04-29 14:52 UTC, Pietro69 commented
ci:test:commerce-functional

2021-04-29 15:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/8815/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8815/jenkins-report.html">here</a>.</b></p>

2021-04-29 18:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 0 out of 5 jobs passed in 2 hours 30 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1817">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1117401_8815</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/591fa6861af78c57a235d9d4c02a2aef53bbeb75">591fa6861af78c57a235d9d4c02a2aef53bbeb75</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f8aa3697ce0df564a38c8fae2516e86001402ed2">f8aa3697ce0df564a38c8fae2516e86001402ed2</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1816">Acceptance Upstream DXP (master) #1816</a></p><details><summary><strong>ci:test:commerce-functional - 0 out of 5 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/8815/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467643/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/412176/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461100/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461099/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8815/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/412176/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>10 Tests Passed.<br/>11 Tests Failed.</p></div><ol><li><div><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/412176//consoleText">AXIS_VARIABLE=12,label_exp=!master #412176</a><pre><code>  [waitfor] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._install(DirectoryWatcher.java:703) [bundleFile:?]
  [waitfor] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1001) [bundleFile:?]
  [waitfor] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:272) [bundleFile:?]
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 6:13.980 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13207: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13565: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5645: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5844: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:482: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/license.xml doesn't exist
      [get] Getting: http://test-1-21/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/412176//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210429094941737.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210429094941737.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1703150662.properties</code></pre></div></li><li><div><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13,label_exp=!master/412176//consoleText">AXIS_VARIABLE=13,label_exp=!master #412176</a><pre><code> [parallel] 2021-04-29 16:29:30.552 INFO  [main][SystemCheckOSGiCommands:126] Declarative Service Unsatisfied Component Checker check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 5:49.321 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13207: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13565: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5645: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5842: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:397: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml doesn't exist
      [get] Getting: http://test-1-21/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13,label_exp=!master/412176//console [...]

2021-04-29 18:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/8815/">test-portal-acceptance-pullrequest(master)#8815</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8815/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/903">liferay-commerce#903</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529509586">[master] ci:test:commerce-functional - leilanyaragao &gt; liferay-commerce - PR#903 - 2021-04-29[08:34:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/642/">publish-testray-report#642</a><br/></div></div>

2021-05-13 21:57 UTC, kristinonias commented
ci:test:commerce-functional

2021-05-13 22:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/4354/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4354/jenkins-report.html">here</a>.</b></p>

2021-05-14 00:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 0 out of 6 jobs passed in 2 hours 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6e25ad1e3cdcd4c6657caad6adef34ec3fbd64c6">6e25ad1e3cdcd4c6657caad6adef34ec3fbd64c6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6e25ad1e3cdcd4c6657caad6adef34ec3fbd64c6">6e25ad1e3cdcd4c6657caad6adef34ec3fbd64c6</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1863">Acceptance Upstream DXP (master) #1863</a></p><details><summary><strong>ci:test:commerce-functional - 0 out of 6 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/4354/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/472443/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/226779/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/471490/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/413594/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/471489/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4354/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/471490/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></h5><div><h6>Job Results:</h6><p>7 Tests Passed.<br/>16 Tests Failed.</p></div><ol><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/471490//consoleText">AXIS_VARIABLE=10,label_exp=!master #471490</a><pre><code>     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
     [echo] Unable to find commerce license file at /opt/dev/projects/github/liferay-portal/bundles/deploy/portal-commerce-license.xml or /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml.
[stopwatch] [run.batch.test.action: 7:15.468 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1626: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1630: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13485: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13843: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4308: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4389: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5818: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:6017: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:537: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/license.xml doesn't exist
      [get] Getting: http://test-1-11/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/471490//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210513160630287.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210513160630287.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null820122381.properties</code></pre></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/471490//consoleText">AXIS_VARIABLE=11,label_exp=!master #471490</a><pre><code>deploy-extra-apps:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null538210588.properties

prepare-log4j-ext-xml:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/bundles/poshi
[stopwatch] [run.batch.test.action: 1:47.428 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1626: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1630: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13396: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2715: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/deploy/portal-commerce-license.xml to copy.
      [get] Getting: http://test-1-11/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/471490//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210513160336178.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210513160336178.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1656052562.properties</code></pre></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/471490//consoleText">AXIS_VARIABLE=12,label_exp=!master #471490</a><pre><code>     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
     [echo] Unable to find commerce license file at /opt/dev/projects/github/liferay-portal/bundles/deploy/portal-commerce-license.xml or /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml.
[stopwatch] [run.batch.test.action: 7:28.101 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/l [...]

2021-05-14 00:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/4354/">test-portal-acceptance-pullrequest(master)#4354</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4354/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/903">liferay-commerce#903</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1532528872">[master] ci:test:commerce-functional - leilanyaragao &gt; liferay-commerce - PR#903 - 2021-05-13[15:03:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/738/">publish-testray-report#738</a><br/></div></div>

2021-05-14 20:51 UTC, kristinonias requested changes

2021-05-14 20:51 UTC, kristinonias commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase
> +			siteName = "Guest");
The test is failing at this Macro. Please fix and resend.

2021-05-18 21:27 UTC, p-albuquerque commented
New PR sent #1222

2021-05-18 21:51 UTC, closed without merging