Automated Test - COMMERCE-6085 | master
liferay-commerce/liferay-portal pull request #908
Opened 2021-04-07 22:32 UTC by brittneyq

https://issues.liferay.com/browse/COMMERCE-6085

cc: @pietro69

2021-04-07 22:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-04-07 22:32 UTC, brittneyq commented
ci:test:sf

2021-04-07 22:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4567/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4567/jenkins-report.html">here</a>.</b></p>

2021-04-07 22:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9c07f7bca2bbde25a8cbcf2c84b6b311fb60e0f7">9c07f7bca2bbde25a8cbcf2c84b6b311fb60e0f7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brittneyq/liferay-portal/tree/COMMERCE-6085">COMMERCE-6085</a><br/>Branch GIT ID: <a href="https://github.com/brittneyq/liferay-portal/commit/ead9fda11290afe9c05434631d86b352ac44c213">ead9fda11290afe9c05434631d86b352ac44c213</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4567/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4567/jenkins-report.html">here</a>.</h5></details></html>

2021-04-07 22:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4567/">test-portal-source-format#4567</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4567/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/908">liferay-commerce#908</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1524026972">[master] ci:test:sf - brittneyq &gt; liferay-commerce - PR#908 - 2021-04-07[15:34:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/267/">publish-testray-report#267</a><br/></div></div>

2021-04-12 21:56 UTC, brittneyq commented
ci:test:commerce-es7-remote

2021-04-12 22:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-es7-remote</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/4154/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4154/jenkins-report.html">here</a>.</b></p>

2021-04-12 22:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-es7-remote - 0 out of 1 jobs passed in 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bc9aa34a9c54739ae6bb4342cd3f11a79b549f75">bc9aa34a9c54739ae6bb4342cd3f11a79b549f75</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bc9aa34a9c54739ae6bb4342cd3f11a79b549f75">bc9aa34a9c54739ae6bb4342cd3f11a79b549f75</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1752">Acceptance Upstream DXP (master) #1752</a></p><details><summary><strong>ci:test:commerce-es7-remote - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/4154/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4154/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/4154/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [exec] &gt; Task :apps:layout:layout-admin-web:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:layout:layout-page-template-admin-api:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:layout:layout-page-template-service:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:layout:layout-prototype-api:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:layout:layout-seo-api:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/exportimport/data/handler/LayoutStagedModelDataHandler.java:929: error: local variables referenced from an inner class must be final or effectively final
     [exec] 										groupId, privateLayout,
     [exec] 										         ^
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
     [exec] 
     [exec] &gt; Task :apps:knowledge-base:knowledge-base-web:packageRunBuild
     [exec] Successfully compiled 3 files with Babel.
     [exec] Bundling took 2s
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/admin/css/common.css
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/admin/css/main.css
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/article/css/main.css
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/display/css/main.css
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/section/css/main.css
     [exec] Minification summary:
     [exec]   Files processed:   29
     [exec]   Files with errors: 0
     [exec]   Before size:       74055
     [exec]   After size:        32321
     [exec]   Delta:             41734
     [exec]   Elapsed:           0.66
     [exec] Received 0
     [exec] Done in 8.33s.
     [echo] Generating Jenkins report.
[beanshell] Jenkins reported generated in 87 ms
     [echo] Rsyncing Jenkins report.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20210412214853267
     [exec] 
     [exec] &gt; Task :apps:journal:journal-web:packageRunBuild
     [exec] Bundling took 32s
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/ddm_form.css</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2021-04-12 22:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest(master)/4154/">test-portal-acceptance-pullrequest(master)#4154</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4154/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-es7-remote<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/908">liferay-commerce#908</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1525184202">[master] ci:test:commerce-es7-remote - brittneyq &gt; liferay-commerce - PR#908 - 2021-04-12[15:29:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/218/">publish-testray-report#218</a><br/></div></div>

2021-04-21 14:56 UTC, Pietro69 requested changes

2021-04-21 14:56 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSubscriptions.testcase
> +		Click(locator1 = "CommerceEntry#PAYMENT_SUBSCRIPTION_TOGGLE");
For the locator i think is possible to use the macro Check.checkToggleSwitch with:
key_toggleSwitchLabel = "Payment Subscription"
locator1 = "ToggleSwitch#ANY_TOGGLE_SWITCH"

2021-04-21 14:56 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSubscriptions.testcase
> +		Click(locator1 = "CommerceEntry#DELIVERY_SUBSCRIPTION_TOGGLE");
For the locator i think is possible to use the macro Check.checkToggleSwitch with:
key_toggleSwitchLabel = "Delivery Subscription"
locator1 = "ToggleSwitch#ANY_TOGGLE_SWITCH"

2021-04-21 14:56 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +</tr>
I think is possible to remove it

2021-04-21 14:56 UTC, Pietro69 commented
Please add the property test.name.skip.portal.instance = "CPCommerceProductSubscriptions#UseSubscriptions"

2021-04-21 19:43 UTC, brittneyq commented
ci:test:sf

2021-04-21 19:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/3447/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-portal-source-format/builds/3447/jenkins-report.html">here</a>.</b></p>

2021-04-21 19:46 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c920b0efb66b7d02606b0cb90c22e0e47520fcb9">c920b0efb66b7d02606b0cb90c22e0e47520fcb9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brittneyq/liferay-portal/tree/COMMERCE-6085">COMMERCE-6085</a><br/>Branch GIT ID: <a href="https://github.com/brittneyq/liferay-portal/commit/11a0dbc04c838b3dc47d00c1df609b61b1885447">11a0dbc04c838b3dc47d00c1df609b61b1885447</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3447/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3447/jenkins-report.html">here</a>.</h5><pre><code>format-source-files:
[stopwatch] [run.batch.test.action: 1:09.307 sec]
     [echo] 
      [get] Getting: http://test-1-12/job/test-portal-source-format/3447//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210421124601426.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210421124601426.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1087921724.properties</code></pre></details></html>

2021-04-21 19:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3447/">test-portal-source-format#3447</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3447/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/908">liferay-commerce#908</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527609724">[master] ci:test:sf - brittneyq &gt; liferay-commerce - PR#908 - 2021-04-21[12:43:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/310/">publish-testray-report#310</a><br/></div></div>

2021-04-21 19:55 UTC, brittneyq commented
ci:test:sf

2021-04-21 19:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4632/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4632/jenkins-report.html">here</a>.</b></p>

2021-04-21 19:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c920b0efb66b7d02606b0cb90c22e0e47520fcb9">c920b0efb66b7d02606b0cb90c22e0e47520fcb9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/brittneyq/liferay-portal/tree/COMMERCE-6085">COMMERCE-6085</a><br/>Branch GIT ID: <a href="https://github.com/brittneyq/liferay-portal/commit/4ccec6a7e44a20bdfbb6f7f079e97fb6e95f04a7">4ccec6a7e44a20bdfbb6f7f079e97fb6e95f04a7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4632/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4632/jenkins-report.html">here</a>.</h5></details></html>

2021-04-21 19:58 UTC, brittneyq commented
fixed @Pietro69

2021-04-21 19:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4632/">test-portal-source-format#4632</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4632/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/908">liferay-commerce#908</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527609913">[master] ci:test:sf - brittneyq &gt; liferay-commerce - PR#908 - 2021-04-21[12:55:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/478/">publish-testray-report#478</a><br/></div></div>

2021-04-22 08:30 UTC, Pietro69 commented
ci:test:commerce-functional

2021-04-22 08:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/440/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/440/jenkins-report.html">here</a>.</b></p>

2021-04-22 11:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 2 out of 5 jobs passed in 2 hours 47 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9">03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9">03d7c8d68eb7d1074a41cb5a22d7938b62bdf6b9</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1790">Acceptance Upstream DXP (master) #1790</a></p><details><summary><strong>ci:test:commerce-functional - 2 out of 5 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/440/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/328076/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/459605/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/469533/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/469532/">test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/440/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/459605/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>7 Tests Passed.<br/>14 Tests Failed.</p></div><ol><li><div><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/459605//consoleText">AXIS_VARIABLE=10,label_exp=!master #459605</a><pre><code>     [echo] 	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
     [echo] 	- locked &lt;0x00000006c2020f78&gt; (a java.lang.ref.Reference$Lock)
     [echo] 	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "main" #1 prio=5 os_prio=0 tid=0x00007f249800b800 nid=0x45d8 runnable [0x00007f249f7e0000]
     [echo]    java.lang.Thread.State: RUNNABLE
     [echo] 	at java.net.PlainSocketImpl.socketAccept(Native Method)
     [echo] 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
     [echo] 	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
     [echo] 	at java.net.ServerSocket.accept(ServerSocket.java:513)
     [echo] 	at org.apache.catalina.core.StandardServer.await(StandardServer.java:609)
     [echo] 	at org.apache.catalina.startup.Catalina.await(Catalina.java:864)
     [echo] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:810)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [echo] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [echo] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [echo] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
     [echo] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "VM Thread" os_prio=0 tid=0x00007f249809b000 nid=0x45dc runnable 
     [echo] 
     [echo] "Gang worker#0 (Parallel GC Threads)" os_prio=0 tid=0x00007f249801c800 nid=0x45d9 runnable 
     [echo] 
     [echo] "Gang worker#1 (Parallel GC Threads)" os_prio=0 tid=0x00007f249801e800 nid=0x45da runnable 
     [echo] 
     [echo] "VM Periodic Task Thread" os_prio=0 tid=0x00007f2498228800 nid=0x45f1 waiting on condition 
     [echo] 
     [echo] JNI global references: 16503
      [get] Getting: http://test-1-5/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/459605//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210422035026344.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210422035026344.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null107658878.properties</code></pre></div></li><li><div><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/459605//consoleText">AXIS_VARIABLE=11,label_exp=!master #459605</a><pre><code> [parallel] 2021-04-22 10:27:58.553 INFO  [main][SystemCheckOSGiCommands:126] Declarative Service Unsatisfied Component Checker check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 7:01.098 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13157: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13515: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5634: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5831: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:397: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml doesn't exist
      [get] Getting: http://test-1-5/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/459605//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210422032809924.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210422032809924.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null539482441.properties</code></pre></div></li><li><div><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13,label_exp=!master/459605//consoleTex [...]

2021-04-22 11:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/440/">test-portal-acceptance-pullrequest(master)#440</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/440/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/908">liferay-commerce#908</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527786153">[master] ci:test:commerce-functional - brittneyq &gt; liferay-commerce - PR#908 - 2021-04-22[01:51:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/550/">publish-testray-report#550</a><br/></div></div>

2021-04-22 12:48 UTC, Pietro69 commented
ci:forward

2021-04-22 12:48 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-22 12:48 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-04-22 12:50 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-9.liferay.com/job/forward-pullrequest/168//consoleFull)

2021-04-22 12:50 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101013
[Console](https://test-1-9.liferay.com/job/forward-pullrequest/168//consoleFull)

2021-04-22 12:50 UTC, closed without merging