COMMERCE-6088
liferay-commerce/liferay-portal pull request #913
Opened 2021-04-08 18:05 UTC by fmarcio

2021-04-08 18:08 UTC, fmarcio commented
https://issues.liferay.com/browse/COMMERCE-6088, cc: @PietroBocale

2021-04-08 23:10 UTC, kristinonias commented
ci:test:sf

2021-04-08 23:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/5617/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-source-format/builds/5617/jenkins-report.html">here</a>.</b></p>

2021-04-08 23:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0e74f1451a6b6231a15cc772f665396c4eae1bae">0e74f1451a6b6231a15cc772f665396c4eae1bae</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/fmarcio/liferay-portal/tree/COMMERCE-6088">COMMERCE-6088</a><br/>Branch GIT ID: <a href="https://github.com/fmarcio/liferay-portal/commit/ec9ad8ec48b85f77291c8becc79191ae867b6414">ec9ad8ec48b85f77291c8becc79191ae867b6414</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5617/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5617/jenkins-report.html">here</a>.</h5></details></html>

2021-04-08 23:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5617/">test-portal-source-format#5617</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5617/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/913">liferay-commerce#913</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1524333145">[master] ci:test:sf - fmarcio &gt; liferay-commerce - PR#913 - 2021-04-08[16:10:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/211/">publish-testray-report#211</a><br/></div></div>

2021-04-16 22:08 UTC, kristinonias commented
ci:test:sf

2021-04-16 22:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/4610/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-source-format/builds/4610/jenkins-report.html">here</a>.</b></p>

2021-04-16 22:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9f375528c91b2c745e13b92a25b67de3595523a3">9f375528c91b2c745e13b92a25b67de3595523a3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/fmarcio/liferay-portal/tree/COMMERCE-6088">COMMERCE-6088</a><br/>Branch GIT ID: <a href="https://github.com/fmarcio/liferay-portal/commit/79e9b1f2d5e6e9cc1e8c9e53d22854f5e05f9202">79e9b1f2d5e6e9cc1e8c9e53d22854f5e05f9202</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4610/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4610/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: There should be a line break after ';': ./modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase 105 (SourceCheck:PoshiStylingCheck)
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:456)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:32.258 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-8/job/test-portal-source-format/4610//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210416151152088.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210416151152088.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1270291145.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1331043447
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 213ms
[junitreport] Deleting: /tmp/null1331043447
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 04-16-2021 15:11:58:214 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] 
     [echo] Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)</code></pre></details></html>

2021-04-16 22:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/4610/">test-portal-source-format#4610</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/4610/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/913">liferay-commerce#913</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526589427">[master] ci:test:sf - fmarcio &gt; liferay-commerce - PR#913 - 2021-04-16[15:09:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/390/">publish-testray-report#390</a><br/></div></div>

2021-04-19 15:28 UTC, kristinonias commented
@fmarcio 

This pull request has a formatting issue. Please fix and resend.

2021-04-20 19:27 UTC, kristinonias commented
ci:test:sf

2021-04-20 19:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/5682/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-source-format/builds/5682/jenkins-report.html">here</a>.</b></p>

2021-04-20 19:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/038a93283f5b35074444cecbba83560e830674eb">038a93283f5b35074444cecbba83560e830674eb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/fmarcio/liferay-portal/tree/COMMERCE-6088">COMMERCE-6088</a><br/>Branch GIT ID: <a href="https://github.com/fmarcio/liferay-portal/commit/e51b91af16a89b73ffeb569512a37d865b9429e1">e51b91af16a89b73ffeb569512a37d865b9429e1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5682/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5682/jenkins-report.html">here</a>.</h5></details></html>

2021-04-20 19:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5682/">test-portal-source-format#5682</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5682/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/913">liferay-commerce#913</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527330130">[master] ci:test:sf - fmarcio &gt; liferay-commerce - PR#913 - 2021-04-20[12:29:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/390/">publish-testray-report#390</a><br/></div></div>

2021-05-03 13:36 UTC, Pietro69 requested changes

2021-05-03 13:36 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase
> +			locator1 = "ToggleSwitch#SPECIFIC_TOGGLE_SWITCH");
I have requested changes to the locator in this PR: #903

2021-05-03 13:36 UTC, Pietro69 commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/ToggleSwitch.path
> +</tr>
I have requested changes to the locator in this PR: #903

2021-05-03 13:36 UTC, Pietro69 commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/Checkbox.path
> +</tr>
I have requested changes to the locator in this PR: #903

2021-05-03 13:36 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase
> +			locator1 = "Checkbox#ENABLE_CHECKBOX_SELECT_CHANNEL");
I have requested changes to the locator in this PR: #903

2021-05-03 13:36 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductVisibility.testcase
> +		Refresh();
Please remove the creation for the Master catalog because is already created when we do the reindex into the setUp (lines 15-20)

2021-05-03 13:36 UTC, Pietro69 commented
Please add the p`roperty test.name.skip.portal.instance = "CPCommerceProductVisibility#AddAccountGroupFilter"`

2021-05-04 15:35 UTC, closed without merging

2021-05-04 17:24 UTC, fmarcio commented
I had to create a new PR with the changes requested, https://github.com/liferay-commerce/liferay-portal/pull/1107 cc: @Pietro69