COMMERCE-6024
liferay-commerce/liferay-portal pull request #916
Opened 2021-04-08 20:07 UTC by rafaellajordao

2021-04-08 20:08 UTC, rafaellajordao commented
https://issues.liferay.com/browse/COMMERCE-6024, CC: @Pietrobocale

2021-04-08 23:10 UTC, kristinonias commented
ci:test:sf

2021-04-08 23:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/4935/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-portal-source-format/builds/4935/jenkins-report.html">here</a>.</b></p>

2021-04-08 23:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0e74f1451a6b6231a15cc772f665396c4eae1bae">0e74f1451a6b6231a15cc772f665396c4eae1bae</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/COMMERCE-6024">COMMERCE-6024</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/ea068e403d9f17c8e4b443b13f1d91662947bd6f">ea068e403d9f17c8e4b443b13f1d91662947bd6f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/4935/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/4935/jenkins-report.html">here</a>.</h5></details></html>

2021-04-08 23:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/4935/">test-portal-source-format#4935</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/4935/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/916">liferay-commerce#916</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1524333154">[master] ci:test:sf - rafaellajordao &gt; liferay-commerce - PR#916 - 2021-04-08[16:11:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/184/">publish-testray-report#184</a><br/></div></div>

2021-04-20 14:11 UTC, Pietro69 requested changes

2021-04-20 14:11 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +		Click(locator1 = "CommerceEntry#CLICK_OVERRIDE");
For the locator i think is possible to use the macro Check.checkToggleSwitch with:
key_toggleSwitchLabel = "Override Subscription Settings"
locator1 = "ToggleSwitch#ANY_TOGGLE_SWITCH"

2021-04-20 14:11 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +</tr>
I think is possible to remove it

2021-04-20 14:11 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +		Pause(locator1 = "3000");
Please remove this pause if is possible

2021-04-20 14:11 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +</tr>
I think is possible to remove it

2021-04-20 14:11 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +		AssertNotVisible(locator1 = "CommerceEntry#PAYMENT_SUBSCRIPTIONS");
For the locator i think is possible to use CommerceNavigation#ANY_ENTRY_NAME (//a[contains(.,'${key_entry}')]) with key_entry = Payment Subscription

2021-04-20 14:11 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +		AssertNotVisible(locator1 = "CommerceEntry#DELIVERY_SUBSCRIPTIONS");
For the locator i think is possible to use CommerceNavigation#ANY_ENTRY_NAME (//a[contains(.,'${key_entry}')]) with key_entry = Delivery Subscription

2021-04-21 14:05 UTC, Pietro69 commented
Add the property test.name.skip.portal.instance = "CPCommerceProductSKUs#AddASKUWithSubscriptions"

2021-04-21 15:22 UTC, Pietro69 requested changes

2021-04-21 15:22 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +        Click(locator1 = "CommerceEntry#CLICK_OVERRIDE");
I think is possible to use the macro Check.checkToggleSwitch with:
key_toggleSwitchLabel = "Override Subscription Settings"
locator1 = "ToggleSwitch#ANY_TOGGLE_SWITCH"

2021-04-21 15:22 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +        Click(locator1 = "CommerceEntry#CLICK_SUBSCRIPTIONS");
I think is possible to use the path CommerceNavigation#ANY_ENTRY_NAME with key_entry = "Subscriptions"

2021-04-21 15:22 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +</tr>
Please create a single path with a variable so that it can be used for both cases

2021-04-21 15:22 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +		AssertElementPresent.assertVisible(locator1 = "CommerceEntry#DELIVERY_SUBSCRIPTIONS");
Please create a single path with a variable so that it can be used for both cases

2021-04-21 15:23 UTC, Pietro69 requested changes

2021-04-21 15:23 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +		Click(locator1 = "CommerceEntry#CLICK_OVERRIDE");
For the locator i think is possible to use the macro Check.checkToggleSwitch with:
key_toggleSwitchLabel = "Override Subscription Settings"
locator1 = "ToggleSwitch#ANY_TOGGLE_SWITCH"

2021-04-21 15:26 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +		AssertNotVisible(locator1 = "CommerceEntry#DELIVERY_SUBSCRIPTIONS");
Please create a single path with a variable so that it can be used for both cases

2021-04-22 08:28 UTC, Pietro69 commented
Please add the property test.name.skip.portal.instance = "CPCommerceProductSKUs#AddASKUWithSubscriptions"

2021-04-23 21:52 UTC, kristinonias commented
ci:test:sf

2021-04-23 21:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-source-format/5766/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-source-format/builds/5766/jenkins-report.html">here</a>.</b></p>

2021-04-23 21:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fece321c64a487c51aad26831f6e32eab138b166">fece321c64a487c51aad26831f6e32eab138b166</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/COMMERCE-6024">COMMERCE-6024</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/45e702ddd37c487ffde302aa91979e64d1a0fc53">45e702ddd37c487ffde302aa91979e64d1a0fc53</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-source-format/5766/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/5766/jenkins-report.html">here</a>.</h5><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/rafaellajordao/liferay-portal/tree/COMMERCE-6024">rafaellajordao/COMMERCE-6024</a></strong><pre><code>Target exception: java.lang.RuntimeException: Unable to rebase rafaellajordao-916-COMMERCE-6024 to master
.git/rebase-apply/patch:118: trailing whitespace.
			
warning: 1 line adds whitespace errors.
error: Failed to merge in the changes.</code></pre></p></div></details></html>

2021-04-26 13:20 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +		// SearchAdministration.executeSearchActions(actionsDescription = "Reindex all search indexes.");
Please remove comments

2021-04-26 13:32 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +
Please remove this space

2021-04-26 17:22 UTC, rafaellajordao commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductSKUs.testcase
> +		// SearchAdministration.executeSearchActions(actionsDescription = "Reindex all search indexes.");
fixed

2021-04-26 18:04 UTC, pedro-michel commented
ci:test:sf

2021-04-26 18:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/5707/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-source-format/builds/5707/jenkins-report.html">here</a>.</b></p>

2021-04-26 18:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c4c731285388d615b0631d9b2d7ead8b2555c486">c4c731285388d615b0631d9b2d7ead8b2555c486</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/COMMERCE-6024">COMMERCE-6024</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/f02339aabd121dfeb5a235bca2e0e940db353206">f02339aabd121dfeb5a235bca2e0e940db353206</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5707/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5707/jenkins-report.html">here</a>.</h5></details></html>

2021-04-26 18:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/5707/">test-portal-source-format#5707</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/5707/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/916">liferay-commerce#916</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528608198">[master] ci:test:sf - rafaellajordao &gt; liferay-commerce - PR#916 - 2021-04-26[11:05:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/483/">publish-testray-report#483</a><br/></div></div>

2021-04-28 14:48 UTC, Pietro69 commented
ci:test:commerce-functional

2021-04-28 14:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7277/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7277/jenkins-report.html">here</a>.</b></p>

2021-04-28 16:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 1 out of 5 jobs passed in 2 hours 9 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1809">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1087401_7277</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c551b24f138a765a4f18318e03953f4030650083">c551b24f138a765a4f18318e03953f4030650083</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/57e7fbc138485535fb62a9c888f6b158b3452e82">57e7fbc138485535fb62a9c888f6b158b3452e82</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1808">Acceptance Upstream DXP (master) #1808</a></p><details><summary><strong>ci:test:commerce-functional - 1 out of 5 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7277/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460974/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460167/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/432721/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/432720/">test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7277/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/460167/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>7 Tests Passed.<br/>14 Tests Failed.</p></div><ol><li><div><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/460167//consoleText">AXIS_VARIABLE=10,label_exp=!master #460167</a><pre><code> [parallel] 2021-04-29 07:45:58.707 INFO  [main][SystemCheckOSGiCommands:126] Declarative Service Unsatisfied Component Checker check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 8:24.029 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13207: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13565: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5645: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5842: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:397: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml doesn't exist
      [get] Getting: http://test-1-5/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/460167//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210429244605242.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210429244605242.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1241526866.properties</code></pre></div></li><li><div><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/460167//consoleText">AXIS_VARIABLE=11,label_exp=!master #460167</a><pre><code>     [echo] 	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
     [echo] 	- locked &lt;0x00000006c2013780&gt; (a java.lang.ref.Reference$Lock)
     [echo] 	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "main" #1 prio=5 os_prio=0 tid=0x00007f4ca400b800 nid=0x5001 runnable [0x00007f4ca9f30000]
     [echo]    java.lang.Thread.State: RUNNABLE
     [echo] 	at java.net.PlainSocketImpl.socketAccept(Native Method)
     [echo] 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
     [echo] 	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
     [echo] 	at java.net.ServerSocket.accept(ServerSocket.java:513)
     [echo] 	at org.apache.catalina.core.StandardServer.await(StandardServer.java:609)
     [echo] 	at org.apache.catalina.startup.Catalina.await(Catalina.java:864)
     [echo] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:810)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [echo] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [echo] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [echo] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
     [echo] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "VM Thread" os_prio=0 tid=0x00007f4ca409b000 nid=0x5005 runnable 
     [echo] 
     [echo] "Gang worker#0 (Parallel GC Threads)" os_prio=0 tid=0x00007f4ca401c800 nid=0x5002 runnable 
     [echo] 
     [echo] "Gang worker#1 (Parallel GC Threads)" os_prio=0 tid=0x00007f4ca401e800 nid=0x5003 runnable 
     [echo] 
     [echo] "VM Periodic Task Thread" os_prio=0 tid=0x00007f4ca4239000 nid=0x5015 waiting on condition 
     [echo] 
     [echo] JNI global references: 16675
      [get] Getting: http://test-1-5/job/test-portal-acceptance-pullrequest-batch(master)/ [...]

2021-04-28 17:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7277/">test-portal-acceptance-pullrequest(master)#7277</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7277/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/916">liferay-commerce#916</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529214431">[master] ci:test:commerce-functional - rafaellajordao &gt; liferay-commerce - PR#916 - 2021-04-28[07:49:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/562/">publish-testray-report#562</a><br/></div></div>

2021-04-29 14:56 UTC, Pietro69 commented
ci:forward

2021-04-29 14:57 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-29 14:57 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-04-29 14:58 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-19.liferay.com/job/forward-pullrequest/177//consoleFull)

2021-04-29 14:58 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101260
[Console](https://test-1-19.liferay.com/job/forward-pullrequest/177//consoleFull)

2021-04-29 14:58 UTC, closed without merging