COMMERCE-5911
liferay-commerce/liferay-portal pull request #952
Opened 2021-04-14 18:54 UTC by JoMaAlves

2021-04-14 18:59 UTC, JoMaAlves commented
https://issues.liferay.com/browse/COMMERCE-5911 , cc: @lorenzolapescara

2021-04-15 22:30 UTC, brittneyq commented
ci:test:sf

2021-04-15 22:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/4894/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-portal-source-format/builds/4894/jenkins-report.html">here</a>.</b></p>

2021-04-15 22:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a7701997ce065011e14273683fa8a924e8a79432">a7701997ce065011e14273683fa8a924e8a79432</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JoMaAlves/liferay-portal/tree/COMMERCE-5911">COMMERCE-5911</a><br/>Branch GIT ID: <a href="https://github.com/JoMaAlves/liferay-portal/commit/d89cabb7a8cee7d03dea82ab5f6a52046fb824cd">d89cabb7a8cee7d03dea82ab5f6a52046fb824cd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/4894/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/4894/jenkins-report.html">here</a>.</h5></details></html>

2021-04-15 22:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-5.liferay.com/job/test-portal-source-format/4894/">test-portal-source-format#4894</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/4894/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/952">liferay-commerce#952</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526227690">[master] ci:test:sf - JoMaAlves &gt; liferay-commerce - PR#952 - 2021-04-15[15:30:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-5.liferay.com/job/publish-testray-report/230/">publish-testray-report#230</a><br/></div></div>

2021-04-27 15:25 UTC, lorenzolapescara commented
Review started.

2021-04-27 15:48 UTC, lorenzolapescara requested changes

2021-04-27 15:48 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +</tr>
Change requested to the same locator on #890.

2021-04-27 15:48 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase
> +			AssertElementPresent(locator1 = "CommerceEntry#ASSERT_MINI_COMPARE");
As for the comment above, please update `CommerceEntry#ASSERT_MINI_COMPARE` locator name.

2021-04-27 15:48 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +</tr>
Please rename this locator to `MINI_COMPARE_ITEM_ACTIVE_N` and move it to `CommerceFrontStore.path`.
```suggestion
<tr>
	<td>MINI_COMPARE_ITEM_ACTIVE_N</td>
	<td>//div[@class='mini-compare-item active'][${key_value}]//div[@class='mini-compare-thumbnail']</td>
	<td></td> 
</tr>
```

2021-04-27 15:48 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase
> +		CommerceNavigator.gotoMiniumSidebarItem(menuItem = "Catalog");
The test does not include these steps.

2021-04-27 17:15 UTC, JoMaAlves commented
Done!

2021-04-27 20:42 UTC, pedro-michel commented
ci:test:sf

2021-04-27 20:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/2809/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com//userContent/jobs/test-portal-source-format/builds/2809/jenkins-report.html">here</a>.</b></p>

2021-04-27 20:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e996e93d6a71fcf48965372ed5901a640766002d">e996e93d6a71fcf48965372ed5901a640766002d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JoMaAlves/liferay-portal/tree/COMMERCE-5911">COMMERCE-5911</a><br/>Branch GIT ID: <a href="https://github.com/JoMaAlves/liferay-portal/commit/2db2b434784304fac48e2b1728f33e1a92cb6623">2db2b434784304fac48e2b1728f33e1a92cb6623</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/2809/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/2809/jenkins-report.html">here</a>.</h5></details></html>

2021-04-27 20:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/2809/">test-portal-source-format#2809</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/2809/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/952">liferay-commerce#952</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528925551">[master] ci:test:sf - JoMaAlves &gt; liferay-commerce - PR#952 - 2021-04-27[13:43:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/373/">publish-testray-report#373</a><br/></div></div>

2021-04-28 13:28 UTC, lorenzolapescara requested changes

2021-04-28 13:28 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase
> +		}
```suggestion
		for (var value : list "1,2,3") {
			AssertElementPresent(
				key_value = "${value}",
				locator1 = "CommerceFrontStore#MINI_COMPARE_ITEM_ACTIVE_N");
		}
```

2021-04-28 18:32 UTC, JoMaAlves commented
Done!

2021-04-29 14:16 UTC, lorenzolapescara commented
Review started.

2021-04-29 14:20 UTC, lorenzolapescara requested changes

2021-04-29 14:20 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase
>  	test AssertComparisonItemsAreVisibleOnMiniCompare {
Please remove `@ignore = "true"` from the test.

2021-04-29 14:20 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +</tr>
Since this locator is already merged, to avoid conflicts, please remove it.

2021-04-29 16:44 UTC, JoMaAlves commented
Done!

2021-04-29 17:29 UTC, lorenzolapescara approved these changes

2021-04-29 17:29 UTC, lorenzolapescara commented
ci:test:sf

2021-04-29 17:29 UTC, lorenzolapescara commented
ci:test:commerce-functional

2021-04-29 17:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-24.liferay.com/job/test-portal-source-format/478/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-24.liferay.com//userContent/jobs/test-portal-source-format/builds/478/jenkins-report.html">here</a>.</b></p>

2021-04-29 17:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2a7be7ac355c0004797eda5ec475bfafc7362b6b">2a7be7ac355c0004797eda5ec475bfafc7362b6b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JoMaAlves/liferay-portal/tree/COMMERCE-5911">COMMERCE-5911</a><br/>Branch GIT ID: <a href="https://github.com/JoMaAlves/liferay-portal/commit/5b5e28885de2fd9e9f43d7d7ccf150a40e0863d0">5b5e28885de2fd9e9f43d7d7ccf150a40e0863d0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-24.liferay.com/job/test-portal-source-format/478/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-24.liferay.com/userContent/jobs/test-portal-source-format/builds/478/jenkins-report.html">here</a>.</h5></details></html>

2021-04-29 17:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-24.liferay.com/job/test-portal-source-format/478/">test-portal-source-format#478</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-24.liferay.com/userContent/jobs/test-portal-source-format/builds/478/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/952">liferay-commerce#952</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529505542">[master] ci:test:sf - JoMaAlves &gt; liferay-commerce - PR#952 - 2021-04-29[10:32:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-24.liferay.com/job/publish-testray-report/79/">publish-testray-report#79</a><br/></div></div>

2021-04-29 17:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/5868/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5868/jenkins-report.html">here</a>.</b></p>

2021-04-29 20:39 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 1 out of 5 jobs passed in 2 hours 42 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1821">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1137401_5868</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2a7be7ac355c0004797eda5ec475bfafc7362b6b">2a7be7ac355c0004797eda5ec475bfafc7362b6b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/318146d8babd408ff5f16b93b0e04428cbf3241f">318146d8babd408ff5f16b93b0e04428cbf3241f</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1818">Acceptance Upstream DXP (master) #1818</a></p><details><summary><strong>ci:test:commerce-functional - 1 out of 5 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/5868/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/412201/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356142/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/470138/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356141/">test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5868/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/356142/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>9 Tests Passed.<br/>11 Tests Failed.</p></div><ol><li><div><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/356142//consoleText">AXIS_VARIABLE=12,label_exp=!master #356142</a><pre><code>  [waitfor] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._install(DirectoryWatcher.java:703) [bundleFile:?]
  [waitfor] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1001) [bundleFile:?]
  [waitfor] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:272) [bundleFile:?]
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 5:15.315 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13207: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13565: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5645: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5844: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:482: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/license.xml doesn't exist
      [get] Getting: http://test-1-12/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/356142//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210429122359952.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210429122359952.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1793802562.properties</code></pre></div></li><li><div><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13,label_exp=!master/356142//consoleText">AXIS_VARIABLE=13,label_exp=!master #356142</a><pre><code> [parallel] 2021-04-29 19:23:53.044 INFO  [main][SystemCheckOSGiCommands:126] Spring Extender Unavailable Component Checker check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 7:07.292 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13207: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13565: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5645: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5842: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:397: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml doesn't exist
      [get] Getting: http://test-1-12/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_V [...]

2021-04-29 20:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/5868/">test-portal-acceptance-pullrequest(master)#5868</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5868/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/952">liferay-commerce#952</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529573087">[master] ci:test:commerce-functional - JoMaAlves &gt; liferay-commerce - PR#952 - 2021-04-29[10:57:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/584/">publish-testray-report#584</a><br/></div></div>

2021-04-29 20:46 UTC, lorenzolapescara commented
ci:forward

2021-04-29 20:46 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-29 20:46 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-04-29 20:46 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-19.liferay.com/job/forward-pullrequest/179//consoleFull)

2021-04-29 20:47 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101285
[Console](https://test-1-19.liferay.com/job/forward-pullrequest/179//consoleFull)

2021-05-04 16:46 UTC, brittneyq commented
ci:reopen

2021-05-04 17:02 UTC, brittneyq commented
ci:test:sf

2021-05-04 17:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/5340/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-source-format/builds/5340/jenkins-report.html">here</a>.</b></p>

2021-05-04 17:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/af58ea9ec030eaa16e3928456c5a3c46d86cc8c8">af58ea9ec030eaa16e3928456c5a3c46d86cc8c8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JoMaAlves/liferay-portal/tree/COMMERCE-5911">COMMERCE-5911</a><br/>Branch GIT ID: <a href="https://github.com/JoMaAlves/liferay-portal/commit/312bb352c2454483080367464e7cdf39fad33400">312bb352c2454483080367464e7cdf39fad33400</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/5340/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5340/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceCompare.testcase expected:&lt;...ding implementation
     [java] [
     [java] ]	\}
     [java] 
     [java] 	@description = ...&gt; but was:&lt;...ding implementation
     [java] []	\}
     [java] 
     [java] 	@description = ...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:456)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 1:17.415 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-16/job/test-portal-source-format/5340//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210504100520138.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210504100520138.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1750279520.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null666539506
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 204ms
[junitreport] Deleting: /tmp/null666539506
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 05-04-2021 10:05:26:324 PDT
[stopwatch] [run.batch.test.tear.down: 0.001 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] </code></pre></details></html>

2021-05-04 17:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-source-format/5340/">test-portal-source-format#5340</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5340/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/952">liferay-commerce#952</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530238333">[master] ci:test:sf - JoMaAlves &gt; liferay-commerce - PR#952 - 2021-05-04[10:02:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/541/">publish-testray-report#541</a><br/></div></div>

2021-05-04 17:19 UTC, brittneyq commented
ci:test:sf

2021-05-04 17:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/2917/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-portal-source-format/builds/2917/jenkins-report.html">here</a>.</b></p>

2021-05-04 17:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/af58ea9ec030eaa16e3928456c5a3c46d86cc8c8">af58ea9ec030eaa16e3928456c5a3c46d86cc8c8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JoMaAlves/liferay-portal/tree/COMMERCE-5911">COMMERCE-5911</a><br/>Branch GIT ID: <a href="https://github.com/JoMaAlves/liferay-portal/commit/40d259efccd7847800791de30a3ae480363ea6d4">40d259efccd7847800791de30a3ae480363ea6d4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/2917/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/2917/jenkins-report.html">here</a>.</h5></details></html>

2021-05-04 17:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/2917/">test-portal-source-format#2917</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/2917/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/952">liferay-commerce#952</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530241039">[master] ci:test:sf - JoMaAlves &gt; liferay-commerce - PR#952 - 2021-05-04[10:19:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/1573/">publish-testray-report#1573</a><br/></div></div>

2021-05-04 17:24 UTC, brittneyq commented
ci:forward

2021-05-04 17:24 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-04 17:24 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-05-04 17:25 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-5.liferay.com/job/forward-pullrequest/137//consoleFull)

2021-05-04 17:25 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101386
[Console](https://test-1-5.liferay.com/job/forward-pullrequest/137//consoleFull)

2021-05-04 17:25 UTC, closed without merging