COMMERCE-6030
liferay-commerce/liferay-portal pull request #957
Opened 2021-04-14 20:05 UTC by LucasAcacio

2021-04-14 20:07 UTC, LucasAcacio commented
https://issues.liferay.com/browse/COMMERCE-6030, cc: @PietroBocale

2021-04-15 10:23 UTC, Pietro69 requested changes

2021-04-15 10:23 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductMedia.testcase
> +			value1 = "Submit");
The Master catalog is already present because on line 20 into the setUp we have a reindex

2021-04-15 21:15 UTC, LucasAcacio commented
PR Uptated

2021-04-15 22:29 UTC, brittneyq commented
ci:test:sf

2021-04-15 22:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/4821/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-portal-source-format/builds/4821/jenkins-report.html">here</a>.</b></p>

2021-04-15 22:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a7701997ce065011e14273683fa8a924e8a79432">a7701997ce065011e14273683fa8a924e8a79432</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/LucasAcacio/liferay-portal/tree/COMMERCE-6030">COMMERCE-6030</a><br/>Branch GIT ID: <a href="https://github.com/LucasAcacio/liferay-portal/commit/be018769d4eb89a45e70ab8933151e34fb7c56d4">be018769d4eb89a45e70ab8933151e34fb7c56d4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/4821/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/4821/jenkins-report.html">here</a>.</h5></details></html>

2021-04-15 22:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/4821/">test-portal-source-format#4821</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/4821/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/957">liferay-commerce#957</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526227699">[master] ci:test:sf - LucasAcacio &gt; liferay-commerce - PR#957 - 2021-04-15[15:29:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/321/">publish-testray-report#321</a><br/></div></div>

2021-04-16 08:15 UTC, Pietro69 approved these changes

2021-04-16 08:32 UTC, andrea-ale-sbarra commented
ci:forward

2021-04-16 08:32 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-16 08:33 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-04-16 08:33 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-11.liferay.com/job/forward-pullrequest/203//consoleFull)

2021-04-16 08:33 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/100835
[Console](https://test-1-11.liferay.com/job/forward-pullrequest/203//consoleFull)

2021-04-16 08:33 UTC, closed without merging