COMMERCE-6264
liferay-commerce/liferay-portal pull request #958
Opened 2021-04-14 20:19 UTC by leticiachiu

2021-04-14 20:21 UTC, leticiachiu commented
https://issues.liferay.com/browse/COMMERCE-6264; cc: @AlessandroIovane

2021-04-15 16:29 UTC, kristinonias commented
ci:test:sf

2021-04-15 16:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/5562/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-source-format/builds/5562/jenkins-report.html">here</a>.</b></p>

2021-04-15 16:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33b9a74b842879484612dd215d771a7eaae1670e">33b9a74b842879484612dd215d771a7eaae1670e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leticiachiu/liferay-portal/tree/COMMERCE-6264">COMMERCE-6264</a><br/>Branch GIT ID: <a href="https://github.com/leticiachiu/liferay-portal/commit/b4ebee76c830d1e961a78549533ba9427b57c170">b4ebee76c830d1e961a78549533ba9427b57c170</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/5562/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/5562/jenkins-report.html">here</a>.</h5></details></html>

2021-04-15 16:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/5562/">test-portal-source-format#5562</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/5562/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/958">liferay-commerce#958</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526099969">[master] ci:test:sf - leticiachiu &gt; liferay-commerce - PR#958 - 2021-04-15[09:29:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/346/">publish-testray-report#346</a><br/></div></div>

2021-04-19 17:01 UTC, iovaneale commented
Starting review

2021-04-20 07:57 UTC, iovaneale requested changes

2021-04-20 07:57 UTC, iovaneale commented on modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceEntry.macro
> +		CommerceNavigator.gotoEntry(entryName = "${keyChannel}");
Please move this step outside of the macro. Thanks.

2021-04-20 20:16 UTC, leticiachiu commented
@iovaneale Fixed.

2021-04-21 08:14 UTC, iovaneale commented
ci:test:commerce-functional

2021-04-21 09:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8096/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8096/jenkins-report.html">here</a>.</b></p>

2021-04-21 11:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 1 out of 5 jobs passed in 2 hours 50 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/47aa84f3b08750630a6bb9caed8b22214f7e096a">47aa84f3b08750630a6bb9caed8b22214f7e096a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/47aa84f3b08750630a6bb9caed8b22214f7e096a">47aa84f3b08750630a6bb9caed8b22214f7e096a</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1785">Acceptance Upstream DXP (master) #1785</a></p><details><summary><strong>ci:test:commerce-functional - 1 out of 5 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8096/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7872/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/334499/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/355413/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/355412/">test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8096/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/334499/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>6 Tests Passed.<br/>14 Tests Failed.</p></div><ol><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/334499//consoleText">AXIS_VARIABLE=10,label_exp=!master #334499</a><pre><code> [parallel] 2021-04-21 10:09:49.055 INFO  [main][SystemCheckOSGiCommands:126] Missing Component Scanner check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 7:56.549 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13157: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13515: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5634: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5831: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:397: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml doesn't exist
      [get] Getting: http://test-1-15/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/334499//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210421031000673.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210421031000673.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1016483068.properties</code></pre></div></li><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/334499//consoleText">AXIS_VARIABLE=12,label_exp=!master #334499</a><pre><code> [parallel] 2021-04-21 10:24:11.250 INFO  [main][SystemCheckOSGiCommands:126] Declarative Service Unsatisfied Component Checker check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 6:28.843 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13157: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13515: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5634: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5831: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:397: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml doesn't exist
      [get] Getting: http://test-1-15/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/334499//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210421032420593.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210421032420593.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null347099460.properties</code></pre></div></li><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13,label_exp=!master/334499//consoleText">AXIS_VARIABLE=13,label_exp=!master #334499</a><pre><code>     [echo] 	at java.lang.ref.Reference.tryHandlePending(Re [...]

2021-04-21 11:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8096/">test-portal-acceptance-pullrequest(master)#8096</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8096/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/958">liferay-commerce#958</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527515071">[master] ci:test:commerce-functional - leticiachiu &gt; liferay-commerce - PR#958 - 2021-04-21[02:05:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/413/">publish-testray-report#413</a><br/></div></div>

2021-04-21 12:27 UTC, iovaneale commented
ci:forward

2021-04-21 12:27 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-21 12:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/4703/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-portal-source-format/builds/4703/jenkins-report.html">here</a>.</b></p>

2021-04-21 12:31 UTC, iovaneale commented
Forwarded since the failure are not related to the commits in this PR. The pushed test passed.

2021-04-21 12:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9e313bd504df559733dc6a37790bbd2cf2931baa">9e313bd504df559733dc6a37790bbd2cf2931baa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/leticiachiu/liferay-portal/tree/COMMERCE-6264">COMMERCE-6264</a><br/>Branch GIT ID: <a href="https://github.com/leticiachiu/liferay-portal/commit/0bff4ddcacae34a2e06430a444dc1187d4a45ccf">0bff4ddcacae34a2e06430a444dc1187d4a45ccf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/4703/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/4703/jenkins-report.html">here</a>.</h5></details></html>

2021-04-21 12:32 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-4.liferay.com/job/test-portal-source-format/4703//consoleFull)

2021-04-21 12:32 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/100973
[Console](https://test-1-4.liferay.com/job/test-portal-source-format/4703//consoleFull)

2021-04-21 12:32 UTC, closed without merging

2021-04-21 12:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-source-format/4703/">test-portal-source-format#4703</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/4703/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/958">liferay-commerce#958</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527518364">[master] ci:test:sf - leticiachiu &gt; liferay-commerce - PR#958 - 2021-04-21[05:27:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/768/">publish-testray-report#768</a><br/></div></div>

2021-04-21 12:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/9505/">test-portal-acceptance-pullrequest(master)#9505</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9505/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/958">liferay-commerce#958</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527518389">[master] ci:test:relevant - leticiachiu &gt; liferay-commerce - PR#958 - 2021-04-21[05:27:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/561/">publish-testray-report#561</a><br/></div></div>