COMMERCE-6064
liferay-commerce/liferay-portal pull request #970
Opened 2021-04-15 18:01 UTC by Jamersonze

2021-04-15 18:02 UTC, Jamersonze commented
https://issues.liferay.com/browse/COMMERCE-6064, cc: @PietroBocale

2021-04-15 21:13 UTC, kristinonias commented
ci:test:sf

2021-04-15 21:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/4053/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-portal-source-format/builds/4053/jenkins-report.html">here</a>.</b></p>

2021-04-15 21:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a7701997ce065011e14273683fa8a924e8a79432">a7701997ce065011e14273683fa8a924e8a79432</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Jamersonze/liferay-portal/tree/COMMERCE-6064">COMMERCE-6064</a><br/>Branch GIT ID: <a href="https://github.com/Jamersonze/liferay-portal/commit/379e3b5ad0f037ec838b03ece8a7aa8318d3b73b">379e3b5ad0f037ec838b03ece8a7aa8318d3b73b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/4053/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4053/jenkins-report.html">here</a>.</h5></details></html>

2021-04-15 21:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/4053/">test-portal-source-format#4053</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4053/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/970">liferay-commerce#970</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526210575">[master] ci:test:sf - Jamersonze &gt; liferay-commerce - PR#970 - 2021-04-15[14:24:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/349/">publish-testray-report#349</a><br/></div></div>

2021-04-16 13:34 UTC, Pietro69 commented
Review started

2021-04-16 15:07 UTC, Pietro69 requested changes

2021-04-16 15:07 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProductProductRelations.testcase
> +			key_orderValue = "1",
Please rename `key_orderValue` into `key_Value`

2021-04-16 18:44 UTC, Jamersonze commented
Fixed.

2021-04-16 23:53 UTC, kristinonias commented
ci:test:sf

2021-04-16 23:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/2767/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com//userContent/jobs/test-portal-source-format/builds/2767/jenkins-report.html">here</a>.</b></p>

2021-04-16 23:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9f375528c91b2c745e13b92a25b67de3595523a3">9f375528c91b2c745e13b92a25b67de3595523a3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Jamersonze/liferay-portal/tree/COMMERCE-6064">COMMERCE-6064</a><br/>Branch GIT ID: <a href="https://github.com/Jamersonze/liferay-portal/commit/c671440fbac181e6789db7ac03151615ead150d5">c671440fbac181e6789db7ac03151615ead150d5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/2767/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/2767/jenkins-report.html">here</a>.</h5></details></html>

2021-04-16 23:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/2767/">test-portal-source-format#2767</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/2767/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/970">liferay-commerce#970</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526642590">[master] ci:test:sf - Jamersonze &gt; liferay-commerce - PR#970 - 2021-04-16[16:53:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/234/">publish-testray-report#234</a><br/></div></div>

2021-04-19 13:42 UTC, Pietro69 approved these changes

2021-04-19 13:43 UTC, Pietro69 commented
ci:forward

2021-04-19 13:43 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-19 13:43 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-04-19 13:44 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-2.liferay.com/job/forward-pullrequest/59//consoleFull)

2021-04-19 13:44 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/100892
[Console](https://test-1-2.liferay.com/job/forward-pullrequest/59//consoleFull)

2021-04-19 13:44 UTC, closed without merging