COMMERCE-6157
liferay-commerce/liferay-portal pull request #971
Opened 2021-04-15 18:27 UTC by julioribeiiro

2021-04-15 18:29 UTC, julioribeiiro commented
https://issues.liferay.com/browse/COMMERCE-6157, cc: @lorenzolapescara

2021-04-15 19:16 UTC, kristinonias commented
ci:test:sf

2021-04-15 19:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/5382/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-source-format/builds/5382/jenkins-report.html">here</a>.</b></p>

2021-04-15 19:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3d663fd53ab189bbb75895b1d255efa5eec28de8">3d663fd53ab189bbb75895b1d255efa5eec28de8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/julioribeiiro/liferay-portal/tree/COMMERCE-6157">COMMERCE-6157</a><br/>Branch GIT ID: <a href="https://github.com/julioribeiiro/liferay-portal/commit/f0fec852549189af649bf2c84e5822a1f13cfff2">f0fec852549189af649bf2c84e5822a1f13cfff2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5382/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5382/jenkins-report.html">here</a>.</h5></details></html>

2021-04-15 19:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/5382/">test-portal-source-format#5382</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/5382/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/971">liferay-commerce#971</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526136944">[master] ci:test:sf - julioribeiiro &gt; liferay-commerce - PR#971 - 2021-04-15[12:17:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/493/">publish-testray-report#493</a><br/></div></div>

2021-04-28 15:18 UTC, lorenzolapescara commented
Review started.

2021-04-28 15:44 UTC, lorenzolapescara requested changes

2021-04-28 15:44 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductCard.testcase
> +		ApplicationsMenu.gotoSite(site = "Minium");
The test does not include these steps.

2021-04-28 15:44 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceAccelerators.path
> +</tr>
This locator is too complex, please try to find and use a path that identifies just the promo price in a product card. Also, please move this locator to `CommerceFrontStore.path`.
```suggestion
<tr>
	<td>PRODUCT_CARD_PROMO_PRICE</td>
	<td>//p[@title='${key_productName}']//following-sibling::p[@class='card-text']//span[contains(@class,'price-value-promo')]</td>
	<td></td>
</tr>
```

2021-04-28 15:44 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductCard.testcase
> +			locator1 = "CommerceAccelerators#PRODUCT_DETAILS_VALUE_INACTIVE_PROMO_PRICE");
As for the comment above, please update `CommerceAccelerators#PRODUCT_DETAILS_VALUE_INACTIVE_PROMO_PRICE` locator name.

2021-04-28 15:44 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductCard.testcase
> +
Add another `AssertElementPresent` that checks for the barred list price on a product card on this line. A new locator that identifies the inactive price on a product card is needed.

2021-04-30 20:12 UTC, pedro-michel commented
ci:test:sf

2021-04-30 20:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/5659/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-source-format/builds/5659/jenkins-report.html">here</a>.</b></p>

2021-04-30 20:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/648105cf63932af9173a603bb43e553b7d7793df">648105cf63932af9173a603bb43e553b7d7793df</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/julioribeiiro/liferay-portal/tree/COMMERCE-6157">COMMERCE-6157</a><br/>Branch GIT ID: <a href="https://github.com/julioribeiiro/liferay-portal/commit/86f417ce0952d4f3ebdf9a5ae4fb25be7102027b">86f417ce0952d4f3ebdf9a5ae4fb25be7102027b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/5659/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/5659/jenkins-report.html">here</a>.</h5></details></html>

2021-04-30 20:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/5659/">test-portal-source-format#5659</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/5659/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/971">liferay-commerce#971</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1529830566">[master] ci:test:sf - julioribeiiro &gt; liferay-commerce - PR#971 - 2021-04-30[13:13:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/658/">publish-testray-report#658</a><br/></div></div>

2021-05-05 17:33 UTC, pedro-michel commented
ci:test:sf

2021-05-05 17:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/4146/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-portal-source-format/builds/4146/jenkins-report.html">here</a>.</b></p>

2021-05-05 17:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cf70710751a2813aaa61f88bd8df1060ca857620">cf70710751a2813aaa61f88bd8df1060ca857620</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/julioribeiiro/liferay-portal/tree/COMMERCE-6157">COMMERCE-6157</a><br/>Branch GIT ID: <a href="https://github.com/julioribeiiro/liferay-portal/commit/9699807353bc008c9ff09cdafe70878a0eeeda0a">9699807353bc008c9ff09cdafe70878a0eeeda0a</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/4146/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4146/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre><code>     [exec] 1 errors in Poshi file reading
     [exec] 
     [exec] Unable to read: /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceFrontStore.path
     [exec] Unable to parse Poshi file: /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceFrontStore.path
     [exec] 
     [exec] 
     [exec] Exception in thread "main" java.lang.Exception
     [exec] 	at com.liferay.poshi.core.PoshiContext._throwExceptions(PoshiContext.java:1399)
     [exec] 	at com.liferay.poshi.core.PoshiContext.readFiles(PoshiContext.java:541)
     [exec] 	at com.liferay.poshi.core.PoshiContext.readFiles(PoshiContext.java:470)
     [exec] 	at com.liferay.poshi.core.PoshiValidation.main(PoshiValidation.java:54)
     [exec] 
     [exec] &gt; Task :validatePoshi FAILED</code></pre></p></div></details></html>

2021-05-05 17:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/4146/">test-portal-source-format#4146</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/4146/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/971">liferay-commerce#971</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530548279">[master] ci:test:sf - julioribeiiro &gt; liferay-commerce - PR#971 - 2021-05-05[10:33:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/622/">publish-testray-report#622</a><br/></div></div>

2021-05-05 18:03 UTC, pedro-michel commented
ci:test:sf

2021-05-05 18:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-portal-source-format/6484/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-portal-source-format/builds/6484/jenkins-report.html">here</a>.</b></p>

2021-05-05 18:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e419a88bd3eaf17b8fd149acb1f7adcf0fc0636f">e419a88bd3eaf17b8fd149acb1f7adcf0fc0636f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/julioribeiiro/liferay-portal/tree/COMMERCE-6157">COMMERCE-6157</a><br/>Branch GIT ID: <a href="https://github.com/julioribeiiro/liferay-portal/commit/34e59f286ac1e82b311ea47fc9d5530f906f06b2">34e59f286ac1e82b311ea47fc9d5530f906f06b2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6484/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6484/jenkins-report.html">here</a>.</h5></details></html>

2021-05-05 18:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6484/">test-portal-source-format#6484</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6484/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/971">liferay-commerce#971</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1530553852">[master] ci:test:sf - julioribeiiro &gt; liferay-commerce - PR#971 - 2021-05-05[11:03:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-22.liferay.com/job/publish-testray-report/531/">publish-testray-report#531</a><br/></div></div>

2021-05-06 22:37 UTC, kristinonias commented
@julioribeiiro 

This pull request has conflicting files. Please fix and resend.

2021-05-07 17:05 UTC, julioribeiiro commented
fixed

2021-05-07 17:09 UTC, julioribeiiro commented
fixed

2021-05-11 17:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ffd0befc13449e6c0863104e000f812b8ceee005">ffd0befc13449e6c0863104e000f812b8ceee005</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/julioribeiiro/liferay-portal/tree/COMMERCE-6157">COMMERCE-6157</a><br/>Branch GIT ID: <a href="https://github.com/julioribeiiro/liferay-portal/commit/6328f760986f42d99c2d533aae2e0717f2aaaae7">6328f760986f42d99c2d533aae2e0717f2aaaae7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/4820/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/4820/jenkins-report.html">here</a>.</h5></details></html>

2021-05-13 08:29 UTC, iovaneale commented
ci:test:commerce-functional

2021-05-13 08:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/117/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/117/jenkins-report.html">here</a>.</b></p>

2021-05-18 07:04 UTC, nikki-pru commented
ci:test:commerce-functional

2021-05-18 07:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7412/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7412/jenkins-report.html">here</a>.</b></p>

2021-05-18 09:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 1 out of 7 jobs passed in 2 hours 50 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/1875">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1087401_7412</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2525abbf42901829bc1f03a70f5fd85f7c4d0bd8">2525abbf42901829bc1f03a70f5fd85f7c4d0bd8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cae1e2b6bf6354639a4bfb0ad40b1929a674b683">cae1e2b6bf6354639a4bfb0ad40b1929a674b683</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1873">Acceptance Upstream DXP (master) #1873</a></p><details><summary><strong>ci:test:commerce-functional - 1 out of 7 jobs PASSED</strong></summary><div><h4>6 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7412/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/469285/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10150/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/385857/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/472894/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/469284/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/330144/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li></ul></details></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7412/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/385857/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></h5><div><h6>Job Results:</h6><p>10 Tests Passed.<br/>13 Tests Failed.</p></div><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/385857//consoleText">AXIS_VARIABLE=12,label_exp=!master #385857</a><pre><code>  [waitfor] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._install(DirectoryWatcher.java:703) [bundleFile:?]
  [waitfor] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1001) [bundleFile:?]
  [waitfor] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:272) [bundleFile:?]
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 6:20.412 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1626: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1630: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13437: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13795: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4308: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4389: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5826: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:6025: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:537: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/license.xml doesn't exist
      [get] Getting: http://test-1-9/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/385857//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210518014402455.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210518014402455.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null612890173.properties</code></pre></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13,label_exp=!master/385857//consoleText">AXIS_VARIABLE=13,label_exp=!master #385857</a><pre><code>     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
     [echo] Unable to find commerce license file at /opt/dev/projects/github/liferay-portal/bundles/deploy/portal-commerce-license.xml or /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml.
[stopwatch] [run.batch.test.action: 6:25.161 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1626: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1630: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13437: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13795: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4308: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4389: The following error occurred while executing this line:
     [echo] [...]

2021-05-18 09:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(master)/7412/">test-portal-acceptance-pullrequest(master)#7412</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7412/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/971">liferay-commerce#971</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1533324291">[master] ci:test:commerce-functional - julioribeiiro &gt; liferay-commerce - PR#971 - 2021-05-18[00:05:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/871/">publish-testray-report#871</a><br/></div></div>

2021-05-18 13:47 UTC, iovaneale commented
ci:forward

2021-05-18 13:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-05-18 13:47 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-05-18 13:48 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-19.liferay.com/job/forward-pullrequest/195//consoleFull)

2021-05-18 13:48 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101946
[Console](https://test-1-19.liferay.com/job/forward-pullrequest/195//consoleFull)

2021-05-18 13:48 UTC, closed without merging