COMMERCE-6020
liferay-commerce/liferay-portal pull request #972
Opened 2021-04-15 18:28 UTC by AfonsoHSantos

2021-04-15 18:44 UTC, kristinonias commented
ci:test:sf

2021-04-15 18:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/5690/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-portal-source-format/builds/5690/jenkins-report.html">here</a>.</b></p>

2021-04-15 18:48 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3d663fd53ab189bbb75895b1d255efa5eec28de8">3d663fd53ab189bbb75895b1d255efa5eec28de8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/COMMERCE-6020">COMMERCE-6020</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/cd16399c8fcf33bbca97b86e105bb2a5be5b4a51">cd16399c8fcf33bbca97b86e105bb2a5be5b4a51</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/5690/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/5690/jenkins-report.html">here</a>.</h5></details></html>

2021-04-15 18:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/5690/">test-portal-source-format#5690</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/5690/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/972">liferay-commerce#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526134673">[master] ci:test:sf - AfonsoHSantos &gt; liferay-commerce - PR#972 - 2021-04-15[11:44:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/417/">publish-testray-report#417</a><br/></div></div>

2021-04-16 10:29 UTC, Pietro69 requested changes

2021-04-16 10:29 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProducts.testcase
> +
Is missing the Alert.viewSuccessMessage() (Step 17 into the ticket)

2021-04-16 10:29 UTC, Pietro69 commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommerceProducts.testcase
> +		Alert.viewSuccessMessage();
The test does not include these steps

2021-04-16 16:57 UTC, Pietro69 approved these changes

2021-04-16 17:02 UTC, Pietro69 commented
ci:test:sf

2021-04-16 17:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/5568/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-source-format/builds/5568/jenkins-report.html">here</a>.</b></p>

2021-04-16 17:03 UTC, Pietro69 commented
ci:test:relevant

2021-04-16 17:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f6253db1cbd2802cf0ca60b90ef4615208134bdb">f6253db1cbd2802cf0ca60b90ef4615208134bdb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/COMMERCE-6020">COMMERCE-6020</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/5f60b6316683b3a049002a6da2da9b399764a397">5f60b6316683b3a049002a6da2da9b399764a397</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/5568/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/5568/jenkins-report.html">here</a>.</h5></details></html>

2021-04-16 17:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/5568/">test-portal-source-format#5568</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/5568/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/972">liferay-commerce#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526485454">[master] ci:test:sf - AfonsoHSantos &gt; liferay-commerce - PR#972 - 2021-04-16[10:02:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/371/">publish-testray-report#371</a><br/></div></div>

2021-04-16 17:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/8718/">test-portal-acceptance-pullrequest(master)#8718</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8718/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/972">liferay-commerce#972</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526486415">[master] ci:test:relevant - AfonsoHSantos &gt; liferay-commerce - PR#972 - 2021-04-16[10:03:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/372/">publish-testray-report#372</a><br/></div></div>

2021-04-19 14:07 UTC, Pietro69 commented
ci:forward

2021-04-19 14:07 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-19 14:07 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-04-19 14:08 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-8.liferay.com/job/forward-pullrequest/189//consoleFull)

2021-04-19 14:08 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/100894
[Console](https://test-1-8.liferay.com/job/forward-pullrequest/189//consoleFull)

2021-04-19 14:08 UTC, closed without merging