COMMERCE-5857
liferay-commerce/liferay-portal pull request #983
Opened 2021-04-16 19:15 UTC by AfonsoHSantos

2021-04-16 19:17 UTC, AfonsoHSantos commented
https://issues.liferay.com/browse/COMMERCE-5857, cc: @lorenzolapescara

2021-04-16 19:21 UTC, kristinonias commented
ci:test:sf

2021-04-16 19:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/2795/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-portal-source-format/builds/2795/jenkins-report.html">here</a>.</b></p>

2021-04-16 19:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a804a225365be702f88f6fe5d0ce1b310a2b4e1b">a804a225365be702f88f6fe5d0ce1b310a2b4e1b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/COMMERCE-5857">COMMERCE-5857</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/419adb1898bfc16bab48294a71da653429371ddf">419adb1898bfc16bab48294a71da653429371ddf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/2795/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/2795/jenkins-report.html">here</a>.</h5></details></html>

2021-04-16 19:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/2795/">test-portal-source-format#2795</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/2795/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/983">liferay-commerce#983</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1526525414">[master] ci:test:sf - AfonsoHSantos &gt; liferay-commerce - PR#983 - 2021-04-16[12:22:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/277/">publish-testray-report#277</a><br/></div></div>

2021-04-20 20:12 UTC, pedro-michel commented
ci:test:sf

2021-04-20 20:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/3441/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-portal-source-format/builds/3441/jenkins-report.html">here</a>.</b></p>

2021-04-20 20:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c095d83e59e09f7f1e439efaba10a01a7b2e8785">c095d83e59e09f7f1e439efaba10a01a7b2e8785</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/COMMERCE-5857">COMMERCE-5857</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/2edc5906c9a7239cc1fd6e3daf4aa11502c8a0e9">2edc5906c9a7239cc1fd6e3daf4aa11502c8a0e9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3441/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3441/jenkins-report.html">here</a>.</h5></details></html>

2021-04-20 20:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/3441/">test-portal-source-format#3441</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/3441/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/983">liferay-commerce#983</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1527348038">[master] ci:test:sf - AfonsoHSantos &gt; liferay-commerce - PR#983 - 2021-04-20[13:13:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/294/">publish-testray-report#294</a><br/></div></div>

2021-04-26 15:43 UTC, lorenzolapescara commented
Review started

2021-04-26 15:45 UTC, lorenzolapescara requested changes

2021-04-26 15:45 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/paths/CommerceEntry.path
> +</tr>
Please rename this locator to `PRODUCT_CARD_CUSTOM_IMAGE`.
```suggestion
<tr>
	<td>PRODUCT_CARD_CUSTOM_IMAGE</td>
	<td>//span[contains(text(),'${key_itemName}')]/../../../../../../..//div[contains(@class,'product-card')]//div[contains(@style,'${key_itemImage}')]</td>
	<td></td>
</tr>
```

2021-04-26 15:45 UTC, lorenzolapescara commented on modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommerceProductCard.testcase
> +			locator1 = "CommerceEntry#ASSERT_IMAGE_IS_SET");
As for the comment above, please update `CommerceEntry#ASSERT_IMAGE_IS_SET` locator name.

2021-04-26 16:47 UTC, AfonsoHSantos commented
@lorenzolapescara fixed!

2021-04-26 17:25 UTC, lorenzolapescara approved these changes

2021-04-26 17:26 UTC, lorenzolapescara commented
ci:test:commerce-functional

2021-04-26 18:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>commerce-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8120/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8120/jenkins-report.html">here</a>.</b></p>

2021-04-26 22:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:commerce-functional - 1 out of 5 jobs passed in 3 hours 57 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c4c731285388d615b0631d9b2d7ead8b2555c486">c4c731285388d615b0631d9b2d7ead8b2555c486</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c4c731285388d615b0631d9b2d7ead8b2555c486">c4c731285388d615b0631d9b2d7ead8b2555c486</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1798">Acceptance Upstream DXP (master) #1798</a></p><details><summary><strong>ci:test:commerce-functional - 1 out of 5 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8120/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/334891/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/383548/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/385264/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/385265/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li></ul></details></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8120/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/383548/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>7 Tests Passed.<br/>14 Tests Failed.</p></div><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/383548//consoleText">AXIS_VARIABLE=10,label_exp=!master #383548</a><pre><code>     [echo] 	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
     [echo] 	- locked &lt;0x00000006c2020f78&gt; (a java.lang.ref.Reference$Lock)
     [echo] 	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "main" #1 prio=5 os_prio=0 tid=0x00007fedb000b800 nid=0x5022 runnable [0x00007fedb8b05000]
     [echo]    java.lang.Thread.State: RUNNABLE
     [echo] 	at java.net.PlainSocketImpl.socketAccept(Native Method)
     [echo] 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
     [echo] 	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
     [echo] 	at java.net.ServerSocket.accept(ServerSocket.java:513)
     [echo] 	at org.apache.catalina.core.StandardServer.await(StandardServer.java:609)
     [echo] 	at org.apache.catalina.startup.Catalina.await(Catalina.java:864)
     [echo] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:810)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [echo] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [echo] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [echo] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [echo] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
     [echo] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
     [echo] 
     [echo]    Locked ownable synchronizers:
     [echo] 	- None
     [echo] 
     [echo] "VM Thread" os_prio=0 tid=0x00007fedb009b000 nid=0x5027 runnable 
     [echo] 
     [echo] "Gang worker#0 (Parallel GC Threads)" os_prio=0 tid=0x00007fedb001c800 nid=0x5023 runnable 
     [echo] 
     [echo] "Gang worker#1 (Parallel GC Threads)" os_prio=0 tid=0x00007fedb001e800 nid=0x5024 runnable 
     [echo] 
     [echo] "VM Periodic Task Thread" os_prio=0 tid=0x00007fedb022d000 nid=0x5037 waiting on condition 
     [echo] 
     [echo] JNI global references: 16788
      [get] Getting: http://test-1-9/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10,label_exp=!master/383548//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210426142232585.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210426142232585.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1805847993.properties</code></pre></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/383548//consoleText">AXIS_VARIABLE=11,label_exp=!master #383548</a><pre><code> [parallel] 2021-04-26 21:02:44.183 INFO  [main][SystemCheckOSGiCommands:126] Spring Extender Unavailable Component Checker check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
     [echo] http://localhost:8080/web/guest has loaded
[stopwatch] [run.batch.test.action: 5:35.677 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1606: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1610: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:62: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13178: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13536: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4236: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:4317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5634: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:5831: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:397: /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/portal-commerce-license.xml doesn't exist
      [get] Getting: http://test-1-9/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/383548//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210426140252173.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210426140252173.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null820331630.properties</code></pre></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13,l [...]

2021-04-26 22:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest(master)/8120/">test-portal-acceptance-pullrequest(master)#8120</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8120/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>commerce-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/983">liferay-commerce#983</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528640734">[master] ci:test:commerce-functional - AfonsoHSantos &gt; liferay-commerce - PR#983 - 2021-04-26[11:03:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/476/">publish-testray-report#476</a><br/></div></div>

2021-04-27 08:38 UTC, lorenzolapescara commented
ci:forward

2021-04-27 08:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-04-27 08:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-24.liferay.com/job/test-portal-source-format/472/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-24.liferay.com//userContent/jobs/test-portal-source-format/builds/472/jenkins-report.html">here</a>.</b></p>

2021-04-27 08:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4b4ff53717645e7bf4c4b373b5cb5d218fb1207a">4b4ff53717645e7bf4c4b373b5cb5d218fb1207a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/COMMERCE-5857">COMMERCE-5857</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/cb2073d01b44ab7763ce6123481a25fe45599336">cb2073d01b44ab7763ce6123481a25fe45599336</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-24.liferay.com/job/test-portal-source-format/472/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-24.liferay.com/userContent/jobs/test-portal-source-format/builds/472/jenkins-report.html">here</a>.</h5></details></html>

2021-04-27 08:53 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-24.liferay.com/job/test-portal-source-format/472//consoleFull)

2021-04-27 08:53 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101135
[Console](https://test-1-24.liferay.com/job/test-portal-source-format/472//consoleFull)

2021-04-27 08:54 UTC, closed without merging

2021-04-27 08:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-24.liferay.com/job/test-portal-source-format/472/">test-portal-source-format#472</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-24.liferay.com/userContent/jobs/test-portal-source-format/builds/472/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/983">liferay-commerce#983</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528746731">[master] ci:test:sf - AfonsoHSantos &gt; liferay-commerce - PR#983 - 2021-04-27[01:50:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-24.liferay.com/job/publish-testray-report/65/">publish-testray-report#65</a><br/></div></div>

2021-04-27 12:40 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest(master)/659//consoleFull)

2021-04-27 12:40 UTC, liferay-continuous-integration commented
Closed pull request will not be forwarded.

2021-04-27 12:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-24.liferay.com/job/test-portal-acceptance-pullrequest(master)/659/">test-portal-acceptance-pullrequest(master)#659</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-24.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/659/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-commerce/liferay-portal/pull/983">liferay-commerce#983</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528770987">[master] ci:test:relevant - AfonsoHSantos &gt; liferay-commerce - PR#983 - 2021-04-27[05:39:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-24.liferay.com/job/publish-testray-report/67/">publish-testray-report#67</a><br/></div></div>